{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-99j13","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp","text":"Notice","kind":"typeIdentifier"},{"text":".Type = Notice.self, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"callback","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp","text":"Notice","kind":"typeIdentifier"},{"text":") -> ()) -> ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","text":"SwiftKey","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Notice","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd","preciseIdentifier":"c:@N@SwiftUsd","text":"SwiftUsd","kind":"typeIdentifier"},{"text":".","kind":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/SwiftUsd\/TfNoticeProtocol","preciseIdentifier":"s:So8SwiftUsdO7OpenUSDE16TfNoticeProtocolP","text":"TfNoticeProtocol","kind":"typeIdentifier"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"Registration of interest in a notice class ","type":"text"},{"code":"N","type":"codeVoice"},{"text":" automatically registers interest in all classes derived from ","type":"text"},{"code":"N","type":"codeVoice"},{"text":". When a notice of appropriate type is received, the ","type":"text"},{"code":"callback","type":"codeVoice"},{"text":" is called with the notice.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"To reverse the registration, call ","type":"text"},{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0","type":"reference"},{"text":" on the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","type":"reference"},{"text":" object returned by this call.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"This form of registration listens for a notice globally. Prefer listening to a notice from a particular sender whenever possible (see overloads).","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Additionally, all forms of registration can also support dynamically downcasting notice types in the callback (see overloads)."}],"type":"paragraph"}],"kind":"content"}],"seeAlsoSections":[{"title":"Type Methods","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-8j5mu","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-6we16","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-2cm0u","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-7toj3","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-17h9z","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-2xoh5","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-7ycue","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-9e095"],"anchor":"Type-Methods","generated":true}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice"]]},"abstract":[{"type":"text","text":"Register a listener as being interested in a TfNotice, regardless of sender."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:)-99j13"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"Register(_:_:)","extendedModule":"C++","modules":[{"relatedModules":["C++"],"name":"OpenUSD"}],"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":">(","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp","text":"Notice","kind":"typeIdentifier"},{"text":".Type, (","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp","text":"Notice","kind":"typeIdentifier"},{"text":") -> ()) -> ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","text":"SwiftKey","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Type Method","externalID":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ"},"references":{"doc://SwiftUsd/documentation/OpenUSD/Revoke-31sr0":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Revoke"}],"kind":"symbol","title":"Revoke(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Revoke","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}],"role":"symbol","abstract":[],"url":"\/documentation\/openusd\/revoke-31sr0"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr":{"role":"symbol","url":"\/documentation\/openusd\/c++\/pxr","title":"pxr","navigatorTitle":[{"text":"pxr","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr","abstract":[],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:)-2cm0u":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Register"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Notice"},{"kind":"text","text":">("},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp","text":"Notice"},{"kind":"text","text":".Type, ("},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp","text":"Notice"},{"kind":"text","text":", "},{"kind":"keyword","text":"borrowing"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV","text":"NoticeCaster"},{"kind":"text","text":") -> ()) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","text":"SwiftKey"}],"title":"Register(_:_:)","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:)-2cm0u","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-2cm0u","abstract":[{"type":"text","text":"Register a listener as being interested in a TfNotice, regardless of sender."}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice":{"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TfNotice"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","kind":"identifier","text":"TfNotice"}],"title":"pxr.TfNotice","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD":{"url":"\/documentation\/openusd","kind":"symbol","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-8j5mu":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Register"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Notice"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"Sender"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"Sender","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyxYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Notice","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyxYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"kind":"text","text":".Type, ("},{"kind":"typeIdentifier","text":"Notice","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyxYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"kind":"text","text":") -> ()) -> "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SwiftKey","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-8j5mu","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-8j5mu","title":"Register(_:_:_:)","role":"symbol","abstract":[{"type":"text","text":"Register a listener as being interested in a TfNotice from a particular sender."}]},"doc://SwiftUsd/documentation/OpenUSD/Revoke-2xoh5":{"abstract":[],"title":"Revoke(_:)","type":"topic","url":"\/documentation\/openusd\/revoke-2xoh5","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Revoke"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","kind":"typeIdentifier","text":"TfNotice"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S0_","kind":"typeIdentifier","text":"SwiftKeys"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-2xoh5","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Revoke"}]},"doc://SwiftUsd/documentation/OpenUSD/RevokeAndWait-7ycue":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"RevokeAndWait"}],"kind":"symbol","title":"RevokeAndWait(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-7ycue","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"RevokeAndWait","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SwiftKey","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"url":"\/documentation\/openusd\/revokeandwait-7ycue"},"doc://SwiftUsd/documentation/OpenUSD/SwiftKey":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","kind":"symbol","title":"class SwiftKey","url":"\/documentation\/openusd\/swiftkey","navigatorTitle":[{"text":"SwiftKey","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SwiftKey","kind":"identifier"}],"abstract":[{"text":"A key representing a listener registered from either Swift or C++","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-6we16":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Register"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Notice"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"Sender"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"Sender","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Notice","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"kind":"text","text":".Type, ("},{"kind":"typeIdentifier","text":"Notice","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Sender","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"kind":"text","text":") -> ()) -> "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SwiftKey","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-6we16","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-6we16","title":"Register(_:_:_:)","role":"symbol","abstract":[{"text":"Register a listener as being interested in a TfNotice from a particular sender.","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/RevokeAndWait-9e095":{"role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RevokeAndWait","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S0_","text":"SwiftKeys","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-9e095","navigatorTitle":[{"kind":"identifier","text":"RevokeAndWait"}],"title":"RevokeAndWait(_:)","abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/revokeandwait-9e095"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:)-99j13":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Register"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Notice"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"Notice","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"kind":"text","text":".Type, ("},{"kind":"typeIdentifier","text":"Notice","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"kind":"text","text":") -> ()) -> "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SwiftKey","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-99j13","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:)-99j13","kind":"symbol","title":"Register(_:_:)","type":"topic","abstract":[{"text":"Register a listener as being interested in a TfNotice, regardless of sender.","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/C++":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++","url":"\/documentation\/openusd\/c++","type":"topic","title":"C++","role":"collection"},"doc://SwiftUsd/documentation/OpenUSD/C++/SwiftUsd/TfNoticeProtocol":{"kind":"symbol","navigatorTitle":[{"text":"TfNoticeProtocol","kind":"identifier"}],"role":"symbol","url":"\/documentation\/openusd\/c++\/swiftusd\/tfnoticeprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TfNoticeProtocol","kind":"identifier"}],"title":"SwiftUsd.TfNoticeProtocol","abstract":[{"text":"Protocol representing ","type":"text"},{"code":"pxr::TfNotice","type":"codeVoice"},{"text":" subclasses.","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/SwiftUsd\/TfNoticeProtocol","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd":{"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd","abstract":[],"fragments":[{"text":"SwiftUsd","kind":"identifier"}],"url":"\/documentation\/openusd\/swiftusd","title":"SwiftUsd","kind":"symbol","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-17h9z":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Register"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Notice"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"Sender"},{"kind":"text","text":">("},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp","text":"Sender"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice"},{"kind":"text","text":".Type, ("},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp","text":"Sender"},{"kind":"text","text":", "},{"kind":"keyword","text":"borrowing"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV","text":"NoticeCaster"},{"kind":"text","text":") -> ()) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","text":"SwiftKey"}],"title":"Register(_:_:_:)","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-17h9z","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-17h9z","abstract":[{"text":"Register a listener as being interested in a TfNotice from a particular sender.","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-7toj3":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Register"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Notice"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"Sender"},{"kind":"text","text":">("},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp","text":"Sender"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice"},{"kind":"text","text":".Type, ("},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice"},{"kind":"text","text":", "},{"kind":"keyword","text":"borrowing"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV","text":"NoticeCaster"},{"kind":"text","text":") -> ()) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","text":"SwiftKey"}],"title":"Register(_:_:_:)","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-7toj3","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-7toj3","abstract":[{"type":"text","text":"Register a listener as being interested in a TfNotice from a particular sender."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"Revoke","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/title"},{"op":"replace","value":[{"text":"Revoke","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/fragments"},{"op":"replace","value":[{"text":"Revoke","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/navigatorTitle"},{"op":"replace","value":"Revoke","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-2xoh5\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Revoke"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-2xoh5\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Revoke"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-2xoh5\/navigatorTitle"},{"op":"replace","value":"RevokeAndWait","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-7ycue\/title"},{"op":"replace","value":[{"text":"RevokeAndWait","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-7ycue\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"RevokeAndWait"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-7ycue\/navigatorTitle"},{"op":"replace","value":"SwiftKey","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/title"},{"op":"replace","value":[{"text":"SwiftKey","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/fragments"},{"op":"replace","value":[{"text":"SwiftKey","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/navigatorTitle"},{"op":"replace","value":"RevokeAndWait","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-9e095\/title"},{"op":"replace","value":[{"text":"RevokeAndWait","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-9e095\/fragments"},{"op":"replace","value":[{"text":"RevokeAndWait","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-9e095\/navigatorTitle"},{"op":"replace","value":"SwiftUsd","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SwiftUsd"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/fragments"},{"op":"add","value":[{"kind":"identifier","text":"SwiftUsd"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/navigatorTitle"}]}]}