{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/get_shared"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper"]]},"metadata":{"modules":[{"name":"OpenUSD"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get_shared","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"std","kind":"identifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"std::shared_ptr","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr"},{"text":"<","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"HioImage","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HioImage"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"get_shared","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","title":"get_shared()","symbolKind":"method","externalID":"c:@N@Overlay@S@HioImageWrapper@F@get_shared#1"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get_shared","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"std","preciseIdentifier":"c:@N@std","kind":"identifier"},{"text":".","kind":"text"},{"text":"std::shared_ptr","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"HioImage","preciseIdentifier":"c:@N@pxr@S@HioImage","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/get_shared"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/get_shared"]}],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"kind":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","type":"topic","role":"symbol","fragments":[{"text":"Overlay","kind":"identifier"}],"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/get_shared":{"type":"topic","abstract":[],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/get_shared","navigatorTitle":[{"kind":"identifier","text":"get_shared"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get_shared"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"std::shared_ptr","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr"},{"kind":"text","text":"<"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"HioImage","preciseIdentifier":"c:@N@pxr@S@HioImage","kind":"typeIdentifier"},{"text":">","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/get_shared","title":"get_shared()","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","url":"\/documentation\/openusd","kind":"symbol","role":"collection","title":"OpenUSD","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"role":"symbol","url":"\/documentation\/openusd\/overlay\/hioimagewrapper","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","navigatorTitle":[{"kind":"identifier","text":"HioImageWrapper"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HioImageWrapper"}],"title":"class HioImageWrapper","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"get_shared","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"get_shared","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"get_shared"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"preciseIdentifier":"c:@N@std","kind":"identifier","text":"std"},{"kind":"text","text":"::"},{"preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr","kind":"typeIdentifier","text":"std::shared_ptr"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"::"},{"preciseIdentifier":"c:@N@pxr@S@HioImage","kind":"typeIdentifier","text":"HioImage"},{"kind":"text","text":"> "},{"kind":"identifier","text":"get_shared"},{"kind":"text","text":"() "},{"kind":"keyword","text":"const"},{"kind":"text","text":";"}],"platforms":["macOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"Overlay","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"value":"get_shared","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1get_shared\/title"},{"value":[{"text":"get_shared","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1get_shared\/fragments"},{"value":[{"text":"get_shared","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1get_shared\/navigatorTitle"},{"value":"HioImageWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title"},{"value":[{"text":"HioImageWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments"},{"value":[{"text":"HioImageWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle"}]}]}