{"metadata":{"symbolKind":"method","modules":[{"name":"OpenUSD"}],"role":"symbol","externalID":"c:@N@Overlay@S@HioImageWrapper@F@GetNumMipLevels#1","roleHeading":"Instance Method","title":"GetNumMipLevels()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetNumMipLevels","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:I","text":"CInt","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"GetNumMipLevels","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetNumMipLevels"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"CInt","preciseIdentifier":"c:I"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/getnummiplevels"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/getnummiplevels"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetNumMipLevels","interfaceLanguage":"swift"},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/GetNumMipLevels":{"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/getnummiplevels","type":"topic","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetNumMipLevels","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetNumMipLevels"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:I","kind":"typeIdentifier","text":"CInt"}],"navigatorTitle":[{"kind":"identifier","text":"GetNumMipLevels"}],"kind":"symbol","title":"GetNumMipLevels()"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"kind":"identifier","text":"Overlay"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","title":"Overlay","type":"topic","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HioImageWrapper","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","url":"\/documentation\/openusd\/overlay\/hioimagewrapper","role":"symbol","type":"topic","navigatorTitle":[{"text":"HioImageWrapper","kind":"identifier"}],"title":"class HioImageWrapper"},"doc://SwiftUsd/documentation/OpenUSD":{"role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","abstract":[],"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"GetNumMipLevels"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GetNumMipLevels","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GetNumMipLevels","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"int","kind":"typeIdentifier","preciseIdentifier":"c:I"},{"text":" ","kind":"text"},{"text":"GetNumMipLevels","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GetNumMipLevels","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetNumMipLevels\/title"},{"value":[{"kind":"identifier","text":"GetNumMipLevels"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetNumMipLevels\/fragments"},{"value":[{"kind":"identifier","text":"GetNumMipLevels"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetNumMipLevels\/navigatorTitle"},{"value":"Overlay","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"value":[{"kind":"identifier","text":"Overlay"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"value":[{"kind":"identifier","text":"Overlay"}],"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"value":"HioImageWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title"},{"value":[{"kind":"identifier","text":"HioImageWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments"},{"value":[{"kind":"identifier","text":"HioImageWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}