{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper"]]},"metadata":{"title":"GetSamplerMetadata(_:_:)","externalID":"c:@N@Overlay@S@HioImageWrapper@F@GetSamplerMetadata#$@N@pxr@E@HioAddressDimension#*$@N@pxr@E@HioAddressMode#1","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"GetSamplerMetadata"}],"modules":[{"name":"OpenUSD"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetSamplerMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"HioAddressDimension","preciseIdentifier":"c:@N@pxr@E@HioAddressDimension","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"HioAddressMode","preciseIdentifier":"c:@N@pxr@E@HioAddressMode","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/getsamplermetadata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/getsamplermetadata"]}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetSamplerMetadata","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetSamplerMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dim"},{"kind":"text","text":": "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HioAddressDimension","preciseIdentifier":"c:@N@pxr@E@HioAddressDimension"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"param"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HioAddressMode","preciseIdentifier":"c:@N@pxr@E@HioAddressMode"},{"kind":"text","text":">"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"c:b"}],"platforms":["macOS"],"languages":["swift"]}]}],"sections":[],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/GetSamplerMetadata":{"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GetSamplerMetadata"}],"kind":"symbol","title":"GetSamplerMetadata(_:_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetSamplerMetadata","type":"topic","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/getsamplermetadata","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetSamplerMetadata"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@E@HioAddressDimension","kind":"typeIdentifier","text":"HioAddressDimension"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@E@HioAddressMode","kind":"typeIdentifier","text":"HioAddressMode"},{"kind":"text","text":">"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:b","kind":"typeIdentifier","text":"Bool"}]},"doc://SwiftUsd/documentation/OpenUSD":{"role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","abstract":[],"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HioImageWrapper","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","url":"\/documentation\/openusd\/overlay\/hioimagewrapper","role":"symbol","type":"topic","navigatorTitle":[{"text":"HioImageWrapper","kind":"identifier"}],"title":"class HioImageWrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"kind":"identifier","text":"Overlay"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","title":"Overlay","type":"topic","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/overlay"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"GetSamplerMetadata","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"GetSamplerMetadata"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"GetSamplerMetadata","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"typeIdentifier","text":"bool","preciseIdentifier":"c:b"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetSamplerMetadata"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","text":"HioAddressDimension","preciseIdentifier":"c:@N@pxr@E@HioAddressDimension"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dim"},{"kind":"text","text":", "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@E@HioAddressMode","text":"HioAddressMode"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"param"},{"kind":"text","text":") "},{"kind":"keyword","text":"const"},{"kind":"text","text":";"}],"platforms":["macOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"GetSamplerMetadata","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetSamplerMetadata\/title"},{"op":"replace","value":[{"text":"GetSamplerMetadata","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetSamplerMetadata\/fragments"},{"op":"replace","value":[{"text":"GetSamplerMetadata","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetSamplerMetadata\/navigatorTitle"},{"op":"replace","value":"HioImageWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title"},{"op":"replace","value":[{"text":"HioImageWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments"},{"op":"replace","value":[{"text":"HioImageWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"}]}]}