{"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation\/OriginLowerLeft","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation\/OriginUpperLeft"],"anchor":"Enumeration-Cases"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/imageoriginlocation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/imageoriginlocation"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageOriginLocation","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageOriginLocation"}],"symbolKind":"enum","modules":[{"name":"OpenUSD"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageOriginLocation"}],"externalID":"c:@N@Overlay@S@HioImageWrapper@E@ImageOriginLocation","title":"ImageOriginLocation"},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/ImageOriginLocation/OriginUpperLeft":{"role":"symbol","navigatorTitle":[{"text":"OriginUpperLeft","kind":"identifier"}],"type":"topic","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/imageoriginlocation\/originupperleft","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OriginUpperLeft","kind":"identifier"}],"title":"OriginUpperLeft","kind":"symbol","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation\/OriginUpperLeft"},"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","url":"\/documentation\/openusd","kind":"symbol","role":"collection","title":"OpenUSD","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/ImageOriginLocation/OriginLowerLeft":{"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/imageoriginlocation\/originlowerleft","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation\/OriginLowerLeft","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"OriginLowerLeft"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OriginLowerLeft"}],"title":"OriginLowerLeft"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/ImageOriginLocation":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageOriginLocation","kind":"identifier"}],"navigatorTitle":[{"text":"ImageOriginLocation","kind":"identifier"}],"kind":"symbol","title":"ImageOriginLocation","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/imageoriginlocation"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"kind":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","type":"topic","role":"symbol","fragments":[{"text":"Overlay","kind":"identifier"}],"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"role":"symbol","url":"\/documentation\/openusd\/overlay\/hioimagewrapper","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","navigatorTitle":[{"kind":"identifier","text":"HioImageWrapper"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HioImageWrapper"}],"title":"class HioImageWrapper","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ImageOriginLocation","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ImageOriginLocation","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ImageOriginLocation"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation\/OriginLowerLeft","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation\/OriginUpperLeft"],"anchor":"Enumeration-Cases","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageOriginLocation"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:i","kind":"typeIdentifier","text":"unsigned int"},{"kind":"text","text":";"}],"platforms":["macOS"]}]},"op":"replace"},{"op":"replace","value":"OriginUpperLeft","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation~1OriginUpperLeft\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OriginUpperLeft"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation~1OriginUpperLeft\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OriginUpperLeft"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation~1OriginUpperLeft\/navigatorTitle"},{"op":"replace","value":"OriginLowerLeft","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation~1OriginLowerLeft\/title"},{"op":"replace","value":[{"text":"OriginLowerLeft","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation~1OriginLowerLeft\/fragments"},{"op":"replace","value":[{"text":"OriginLowerLeft","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation~1OriginLowerLeft\/navigatorTitle"},{"op":"replace","value":"ImageOriginLocation","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation\/title"},{"op":"replace","value":[{"text":"ImageOriginLocation","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation\/fragments"},{"op":"replace","value":[{"text":"ImageOriginLocation","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation\/navigatorTitle"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"op":"replace","value":"HioImageWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title"},{"op":"replace","value":[{"text":"HioImageWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments"},{"op":"replace","value":[{"text":"HioImageWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}