{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/OpenForReading"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"title":"OpenForReading(_:_:_:_:_:)","role":"symbol","roleHeading":"Static Method","externalID":"c:@N@Overlay@S@HioImageWrapper@F@OpenForReading#&1$@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C#I#I#$@N@Overlay@S@HioImageWrapper@E@SourceColorSpace#b#S","navigatorTitle":[{"text":"OpenForReading","kind":"identifier"}],"modules":[{"name":"OpenUSD"}],"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenForReading","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@std","text":"std","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C","text":"string","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:I","text":"CInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:I","text":"CInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@N@Overlay@S@HioImageWrapper@E@SourceColorSpace","text":"SourceColorSpace","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:b","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@Overlay@S@HioImageWrapper","text":"HioImageWrapper","kind":"typeIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenForReading","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"filename","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"std","preciseIdentifier":"c:@N@std","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C","text":"string","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"subimage","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:I","text":"CInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"mip","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CInt","preciseIdentifier":"c:I","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sourceColorSpace","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SourceColorSpace","preciseIdentifier":"c:@N@Overlay@S@HioImageWrapper@E@SourceColorSpace","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/SourceColorSpace","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"suppressErrors","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"HioImageWrapper","preciseIdentifier":"c:@N@Overlay@S@HioImageWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","kind":"typeIdentifier"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper"]]},"variants":[{"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/openforreading"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/openforreading"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://SwiftUsd/documentation/OpenUSD":{"role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","abstract":[],"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/SourceColorSpace":{"title":"SourceColorSpace","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/sourcecolorspace","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/SourceColorSpace","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceColorSpace","kind":"identifier"}],"navigatorTitle":[{"text":"SourceColorSpace","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HioImageWrapper","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","url":"\/documentation\/openusd\/overlay\/hioimagewrapper","role":"symbol","type":"topic","navigatorTitle":[{"text":"HioImageWrapper","kind":"identifier"}],"title":"class HioImageWrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/OpenForReading":{"kind":"symbol","navigatorTitle":[{"text":"OpenForReading","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenForReading"},{"kind":"text","text":"("},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"string","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"CInt","preciseIdentifier":"c:I"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"CInt","preciseIdentifier":"c:I"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"SourceColorSpace","preciseIdentifier":"c:@N@Overlay@S@HioImageWrapper@E@SourceColorSpace"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"c:b"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@S@HioImageWrapper","text":"HioImageWrapper"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/OpenForReading","title":"OpenForReading(_:_:_:_:_:)","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/openforreading"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"kind":"identifier","text":"Overlay"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","title":"Overlay","type":"topic","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/overlay"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Static Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OpenForReading","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OpenForReading"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"OpenForReading","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HioImageWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@S@HioImageWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper"},{"text":" ","kind":"text"},{"text":"OpenForReading","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"std","kind":"identifier","preciseIdentifier":"c:@N@std"},{"text":"::","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"kind":"text","text":" & "},{"kind":"internalParam","text":"filename"},{"kind":"text","text":", "},{"preciseIdentifier":"c:I","kind":"typeIdentifier","text":"int"},{"kind":"text","text":" "},{"kind":"internalParam","text":"subimage"},{"kind":"text","text":", "},{"preciseIdentifier":"c:I","kind":"typeIdentifier","text":"int"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mip"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@S@HioImageWrapper@E@SourceColorSpace","text":"SourceColorSpace","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/SourceColorSpace"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sourceColorSpace"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:b","text":"bool"},{"kind":"text","text":" "},{"kind":"internalParam","text":"suppressErrors"},{"kind":"text","text":");"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SourceColorSpace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1SourceColorSpace\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SourceColorSpace"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1SourceColorSpace\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SourceColorSpace"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1SourceColorSpace\/navigatorTitle"},{"op":"replace","value":"HioImageWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title"},{"op":"replace","value":[{"text":"HioImageWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HioImageWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle"},{"op":"replace","value":"OpenForReading","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1OpenForReading\/title"},{"op":"replace","value":[{"text":"OpenForReading","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1OpenForReading\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OpenForReading"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1OpenForReading\/navigatorTitle"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"}]}]}