{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Dynamically casts ","type":"text"},{"code":"self","type":"codeVoice"},{"text":" to the argument type.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/c++\/pxr\/glfdrawtarget\/as(_:)"]}],"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","externalID":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolPACE2asyqd__Sgqd__mAbCEADRd__9_SelfTypeQyd__Rsd__lF::SYNTHESIZED::c:@N@pxr@S@GlfDrawTarget","modules":[{"name":"OpenUSD"}],"extendedModule":"OpenUSD","title":"as(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"`as`"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolPACE2asyqd__Sgqd__mAbCEADRd__9_SelfTypeQyd__Rsd__lF1TL_qd__mfp"},{"kind":"text","text":".Type) -> "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolPACE2asyqd__Sgqd__mAbCEADRd__9_SelfTypeQyd__Rsd__lF1TL_qd__mfp"},{"kind":"text","text":"?"}]},"kind":"symbol","identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GlfDrawTarget\/as(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`as`","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"t","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolPACE2asyqd__Sgqd__mAbCEADRd__9_SelfTypeQyd__Rsd__lF1TL_qd__mfp"},{"kind":"text","text":".Type = T.self) -> "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolPACE2asyqd__Sgqd__mAbCEADRd__9_SelfTypeQyd__Rsd__lF1TL_qd__mfp"},{"kind":"text","text":"? "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","kind":"typeIdentifier","text":"Overlay","preciseIdentifier":"c:@N@Overlay"},{"kind":"text","text":"."},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfRefBaseProtocol","kind":"typeIdentifier","text":"_TfRefBaseProtocol","preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolP"},{"text":", ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":" == ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"_SelfType","preciseIdentifier":"s:So7OverlayO7OpenUSDE30_SwiftUsdReferenceTypeProtocolP05_SelfG0Qa","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"In Swift 6.0, the built-in ","type":"text"},{"type":"codeVoice","code":"as\/as?\/as!"},{"text":" operators don’t work properly on foreign reference types.","type":"text"},{"text":" ","type":"text"},{"text":"Instead, use this function to conditionally cast between subclasses of ","type":"text"},{"type":"codeVoice","code":"pxr::TfRefBase"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GlfDrawTarget"]]},"references":{"doc://SwiftUsd/documentation/OpenUSD":{"url":"\/documentation\/openusd","kind":"symbol","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD"},"doc://SwiftUsd/documentation/OpenUSD/C++":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++","url":"\/documentation\/openusd\/c++","type":"topic","title":"C++","role":"collection"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GlfDrawTarget":{"url":"\/documentation\/openusd\/c++\/pxr\/glfdrawtarget","type":"topic","role":"symbol","navigatorTitle":[{"text":"GlfDrawTarget","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@GlfDrawTarget","text":"GlfDrawTarget","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GlfDrawTarget","abstract":[],"title":"pxr.GlfDrawTarget"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"fragments":[{"text":"Overlay","kind":"identifier"}],"role":"symbol","title":"Overlay","type":"topic","url":"\/documentation\/openusd\/overlay","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GlfDrawTarget/as(_:)":{"role":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GlfDrawTarget\/as(_:)","kind":"symbol","abstract":[{"text":"Dynamically casts ","type":"text"},{"code":"self","type":"codeVoice"},{"text":" to the argument type.","type":"text"}],"url":"\/documentation\/openusd\/c++\/pxr\/glfdrawtarget\/as(_:)","title":"as(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`as`","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolPACE2asyqd__Sgqd__mAbCEADRd__9_SelfTypeQyd__Rsd__lF1TL_qd__mfp","text":"T","kind":"typeIdentifier"},{"text":".Type) -> ","kind":"text"},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolPACE2asyqd__Sgqd__mAbCEADRd__9_SelfTypeQyd__Rsd__lF1TL_qd__mfp","text":"T","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/_TfRefBaseProtocol":{"kind":"symbol","abstract":[{"text":"Protocol representing ","type":"text"},{"type":"codeVoice","code":"pxr::TfRefBase"},{"text":" subclasses. Don’t use this unless you know what you’re doing","type":"text"}],"type":"topic","title":"Overlay._TfRefBaseProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_TfRefBaseProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"_TfRefBaseProtocol","kind":"identifier"}],"url":"\/documentation\/openusd\/c++\/overlay\/_tfrefbaseprotocol","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfRefBaseProtocol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr":{"role":"symbol","url":"\/documentation\/openusd\/c++\/pxr","title":"pxr","navigatorTitle":[{"text":"pxr","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"kind":"identifier","text":"Overlay"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"text":"Overlay","kind":"identifier"}],"op":"add"}],"traits":[{"interfaceLanguage":"occ"}]}]}