{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateGraphicsPipeline"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pipeDesc"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@HgiGraphicsPipelineDesc","kind":"typeIdentifier","text":"HgiGraphicsPipelineDesc"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiGraphicsPipeline","kind":"typeIdentifier","text":"HgiGraphicsPipelineHandle"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateGraphicsPipeline","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","modules":[{"name":"OpenUSD"}],"navigatorTitle":[{"text":"CreateGraphicsPipeline","kind":"identifier"}],"fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateGraphicsPipeline","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@HgiGraphicsPipelineDesc","text":"HgiGraphicsPipelineDesc","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiGraphicsPipeline","text":"HgiGraphicsPipelineHandle","kind":"typeIdentifier"}],"title":"CreateGraphicsPipeline(_:)","symbolKind":"method","externalID":"c:@N@Overlay@S@HgiWrapper@F@CreateGraphicsPipeline#&1$@N@pxr@S@HgiGraphicsPipelineDesc#","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper"]]},"sections":[],"variants":[{"paths":["\/documentation\/openusd\/overlay\/hgiwrapper\/creategraphicspipeline"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/hgiwrapper\/creategraphicspipeline"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","type":"topic","url":"\/documentation\/openusd\/overlay\/hgiwrapper","role":"symbol","kind":"symbol","title":"class HgiWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HgiWrapper"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"HgiWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreateGraphicsPipeline":{"kind":"symbol","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateGraphicsPipeline","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@HgiGraphicsPipelineDesc","text":"HgiGraphicsPipelineDesc","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiGraphicsPipeline","text":"HgiGraphicsPipelineHandle","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"CreateGraphicsPipeline","kind":"identifier"}],"title":"CreateGraphicsPipeline(_:)","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/creategraphicspipeline","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateGraphicsPipeline","abstract":[],"type":"topic","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"type":"topic","kind":"symbol","url":"\/documentation\/openusd\/overlay","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"fragments":[{"kind":"identifier","text":"Overlay"}],"title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"CreateGraphicsPipeline","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"CreateGraphicsPipeline","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"CreateGraphicsPipeline","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":"::","kind":"text"},{"text":"HgiGraphicsPipelineHandle","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiGraphicsPipeline","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"CreateGraphicsPipeline","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":"::","kind":"text"},{"text":"HgiGraphicsPipelineDesc","preciseIdentifier":"c:@N@pxr@S@HgiGraphicsPipelineDesc","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"pipeDesc","kind":"internalParam"},{"text":");","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"HgiWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/title"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/fragments","op":"replace","value":[{"text":"HgiWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"HgiWrapper"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateGraphicsPipeline\/title","op":"replace","value":"CreateGraphicsPipeline"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateGraphicsPipeline\/fragments","op":"replace","value":[{"kind":"identifier","text":"CreateGraphicsPipeline"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateGraphicsPipeline\/navigatorTitle","op":"replace","value":[{"text":"CreateGraphicsPipeline","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace","value":"Overlay"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace","value":[{"kind":"identifier","text":"Overlay"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add","value":[{"text":"Overlay","kind":"identifier"}]}]}]}