{"metadata":{"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"OpenUSD"}],"externalID":"c:@N@Overlay@S@HgiWrapper@F@CreateTextureView#&1$@N@pxr@S@HgiTextureViewDesc#","role":"symbol","navigatorTitle":[{"text":"CreateTextureView","kind":"identifier"}],"title":"CreateTextureView(_:)","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateTextureView"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiTextureViewDesc","text":"HgiTextureViewDesc"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"HgiTextureViewHandle","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiTextureView","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateTextureView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"desc","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@HgiTextureViewDesc","kind":"typeIdentifier","text":"HgiTextureViewDesc"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiTextureView","kind":"typeIdentifier","text":"HgiTextureViewHandle"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hgiwrapper\/createtextureview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hgiwrapper\/createtextureview"]}],"sections":[],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateTextureView","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"fragments":[{"text":"Overlay","kind":"identifier"}],"role":"symbol","title":"Overlay","type":"topic","url":"\/documentation\/openusd\/overlay","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreateTextureView":{"kind":"symbol","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/createtextureview","type":"topic","abstract":[],"title":"CreateTextureView(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateTextureView","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateTextureView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"HgiTextureViewDesc","preciseIdentifier":"c:@N@pxr@S@HgiTextureViewDesc","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"HgiTextureViewHandle","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiTextureView","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"CreateTextureView"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"url":"\/documentation\/openusd","kind":"symbol","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HgiWrapper"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HgiWrapper"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper","title":"class HgiWrapper","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"CreateTextureView","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"CreateTextureView"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CreateTextureView"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","text":"HgiTextureViewHandle","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiTextureView"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateTextureView"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","text":"HgiTextureViewDesc","preciseIdentifier":"c:@N@pxr@S@HgiTextureViewDesc"},{"kind":"text","text":" & "},{"kind":"internalParam","text":"desc"},{"kind":"text","text":");"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"op":"replace","value":"CreateTextureView","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateTextureView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CreateTextureView"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateTextureView\/fragments"},{"op":"replace","value":[{"text":"CreateTextureView","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateTextureView\/navigatorTitle"},{"op":"replace","value":"HgiWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HgiWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/fragments"},{"op":"replace","value":[{"text":"HgiWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}