{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"DestroyBuffer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"bufHandle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HgiBufferHandle","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiBuffer"},{"kind":"text","text":">"},{"kind":"text","text":")"}]}]}],"kind":"symbol","metadata":{"roleHeading":"Instance Method","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DestroyBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"HgiBufferHandle","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiBuffer"},{"text":">","kind":"text"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"DestroyBuffer","kind":"identifier"}],"externalID":"c:@N@Overlay@S@HgiWrapper@F@DestroyBuffer#*$@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiBuffer#","title":"DestroyBuffer(_:)","modules":[{"name":"OpenUSD"}],"role":"symbol","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyBuffer"},"variants":[{"paths":["\/documentation\/openusd\/overlay\/hgiwrapper\/destroybuffer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/hgiwrapper\/destroybuffer"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/DestroyBuffer":{"type":"topic","navigatorTitle":[{"text":"DestroyBuffer","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyBuffer","title":"DestroyBuffer(_:)","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"DestroyBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiBuffer","text":"HgiBufferHandle","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/destroybuffer","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","type":"topic","url":"\/documentation\/openusd\/overlay\/hgiwrapper","role":"symbol","kind":"symbol","title":"class HgiWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HgiWrapper"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"HgiWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"type":"topic","kind":"symbol","url":"\/documentation\/openusd\/overlay","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"fragments":[{"kind":"identifier","text":"Overlay"}],"title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DestroyBuffer","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DestroyBuffer"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"DestroyBuffer","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" "},{"kind":"identifier","text":"DestroyBuffer"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiBuffer","text":"HgiBufferHandle"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"bufHandle"},{"kind":"text","text":");"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DestroyBuffer","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyBuffer\/title"},{"value":[{"text":"DestroyBuffer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyBuffer\/fragments"},{"value":[{"text":"DestroyBuffer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyBuffer\/navigatorTitle"},{"value":"HgiWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/title"},{"value":[{"text":"HgiWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/fragments"},{"value":[{"kind":"identifier","text":"HgiWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/navigatorTitle"},{"value":"Overlay","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"}]}]}