{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdZipFileIteratorWrapper"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"zipFile","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"UsdZipFile","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdZipFile"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"iter","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"UsdZipFile","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdZipFile"},{"text":".","kind":"text"},{"text":"Iterator","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdZipFile@S@Iterator"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"UsdZipFileIteratorWrapper","kind":"typeIdentifier"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/usdzipfileiteratorwrapper\/usdzipfileiteratorwrapper-770q2"]}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdZipFileIteratorWrapper\/UsdZipFileIteratorWrapper-770q2","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"roleHeading":"Initializer","externalID":"c:@N@Overlay@S@UsdZipFileIteratorWrapper@F@UsdZipFileIteratorWrapper#$@N@pxr@S@UsdZipFile#$@N@pxr@S@UsdZipFile@S@Iterator#","title":"init(_:_:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdZipFile","text":"UsdZipFile"},{"kind":"text","text":", "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdZipFile","text":"UsdZipFile"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdZipFile@S@Iterator","text":"Iterator"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"UsdZipFileIteratorWrapper"}],"navigatorTitle":[{"text":"UsdZipFileIteratorWrapper","kind":"identifier"}],"symbolKind":"init","modules":[{"name":"OpenUSD"}]},"kind":"symbol","references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdZipFileIteratorWrapper/UsdZipFileIteratorWrapper-770q2":{"type":"topic","abstract":[],"kind":"symbol","title":"init(_:_:)","url":"\/documentation\/openusd\/overlay\/usdzipfileiteratorwrapper\/usdzipfileiteratorwrapper-770q2","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdZipFileIteratorWrapper\/UsdZipFileIteratorWrapper-770q2","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"UsdZipFile","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdZipFile"},{"text":", ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"UsdZipFile","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdZipFile"},{"text":".","kind":"text"},{"text":"Iterator","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdZipFile@S@Iterator"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"UsdZipFileIteratorWrapper","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"UsdZipFileIteratorWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdZipFileIteratorWrapper":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdZipFileIteratorWrapper","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdZipFileIteratorWrapper","navigatorTitle":[{"text":"UsdZipFileIteratorWrapper","kind":"identifier"}],"title":"struct UsdZipFileIteratorWrapper","abstract":[],"url":"\/documentation\/openusd\/overlay\/usdzipfileiteratorwrapper","type":"topic","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"url":"\/documentation\/openusd\/overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol","title":"Overlay","type":"topic","kind":"symbol","fragments":[{"text":"Overlay","kind":"identifier"}],"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","kind":"symbol","abstract":[],"url":"\/documentation\/openusd","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace"},{"value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace"},{"value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add"}]}]}