{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd"]]},"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"TakeReturnValueFromSwift","kind":"identifier"}],"externalID":"c:@N@SwiftUsd@FT@>1#TTakeReturnValueFromSwift#*^type-parameter-0-0:::DataType#t0.0#","modules":[{"name":"OpenUSD"}],"role":"symbol","title":"TakeReturnValueFromSwift","symbolKind":"func","roleHeading":"Function Template","fragments":[{"text":"TakeReturnValueFromSwift","kind":"identifier"}]},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/TakeReturnValueFromSwift","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/swiftusd\/takereturnvaluefromswift"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"template","kind":"keyword"},{"text":" <","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmartPointer","kind":"genericParameter"},{"text":"> ","kind":"text"},{"text":"SmartPointer","preciseIdentifier":"c:t0.0","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"TakeReturnValueFromSwift","kind":"identifier"},{"text":"(","kind":"text"},{"text":"typename SmartPointer::DataType","preciseIdentifier":"c:^type-parameter-0-0:::DataType","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"x","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this function to create a "},{"code":"pxr::TfRefPtr<T>","type":"codeVoice"},{"type":"text","text":" or "},{"code":"pxr::TfWeakPtr<T>","type":"codeVoice"},{"type":"text","text":" from a raw pointer returned from calling a Swift function in C++. Make sure that "},{"code":"SwiftUsd::TakeReturnValueFromSwift(SmartPointer::DataType*)","type":"codeVoice"},{"type":"text","text":" is called on the return value from Swift, even if the result of "},{"code":"SwiftUsd::TakeReturnValueFromSwift(SmartPointer::DataType*)","type":"codeVoice"},{"type":"text","text":" isn’t used."}]},{"type":"codeListing","syntax":"swift","code":["\/\/ foo.swift","import OpenUSD","public func returnStageByRawPointer() -> pxr.UsdStage { ... }"]},{"type":"codeListing","syntax":"c++","code":["\/\/ foo.mm","#include \"MyTarget-Swift.h\"","#include \"swiftUsd\/swiftUsd.h\"","#include \"pxr\/usd\/usd\/stage.h\"","","void takeRawPointerFromSwift() {","    pxr::UsdStageRefPtr stage = SwiftUsd::TakeReturnValueFromSwift<pxr::UsdStageRefPtr>(MyTarget::returnStageByRawPointer());","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxInteropMemorySafety"},{"type":"text","text":" for more information."}]}],"kind":"content"}],"references":{"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd":{"url":"\/documentation\/openusd\/swiftusd","fragments":[{"text":"SwiftUsd","kind":"identifier"}],"title":"SwiftUsd","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd","role":"symbol","kind":"symbol","type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/SwiftCxxInteropMemorySafety":{"title":"Swift-Cxx Interop and Memory Safety","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxInteropMemorySafety","abstract":[{"type":"text","text":"Learn how to avoid unsafe memory management issues when using Swift-Cxx interop"}],"url":"\/documentation\/swiftusd\/swiftcxxinteropmemorysafety","role":"article","kind":"article"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd/TakeReturnValueFromSwift":{"role":"symbol","type":"topic","title":"TakeReturnValueFromSwift","fragments":[{"kind":"identifier","text":"TakeReturnValueFromSwift"}],"kind":"symbol","url":"\/documentation\/openusd\/swiftusd\/takereturnvaluefromswift","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/TakeReturnValueFromSwift"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","abstract":[],"url":"\/documentation\/openusd","kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SwiftUsd","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/title"},{"op":"replace","value":[{"text":"SwiftUsd","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/fragments"},{"op":"add","value":[{"text":"SwiftUsd","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/navigatorTitle"}]}]}