{"metadata":{"navigatorTitle":[{"text":"TakeFunctionParameterFromSwift","kind":"identifier"}],"externalID":"c:@N@SwiftUsd@FT@>1#TTakeFunctionParameterFromSwift#*^type-parameter-0-0:::DataType#t0.0#","role":"symbol","modules":[{"name":"OpenUSD"}],"symbolKind":"func","title":"TakeFunctionParameterFromSwift","roleHeading":"Function Template","fragments":[{"kind":"identifier","text":"TakeFunctionParameterFromSwift"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/TakeFunctionParameterFromSwift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/swiftusd\/takefunctionparameterfromswift"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"template"},{"kind":"text","text":" <"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"genericParameter","text":"SmartPointer"},{"kind":"text","text":"> "},{"kind":"typeIdentifier","text":"SmartPointer","preciseIdentifier":"c:t0.0"},{"kind":"text","text":" "},{"kind":"identifier","text":"TakeFunctionParameterFromSwift"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"typename SmartPointer::DataType","preciseIdentifier":"c:^type-parameter-0-0:::DataType"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"x"},{"kind":"text","text":");"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"Discussion"},{"inlineContent":[{"type":"text","text":"Use this function to create a "},{"code":"pxr::TfRefPtr<T>","type":"codeVoice"},{"type":"text","text":" or "},{"code":"pxr::TfWeakPtr<T>","type":"codeVoice"},{"type":"text","text":" from a raw pointer passed into a C++ function called by Swift. Make sure that "},{"code":"SwiftUsd::TakeFunctionParameterFromSwift(SmartPointer::DataType*)","type":"codeVoice"},{"type":"text","text":" is called on the return value from Swift, even if the result of "},{"code":"SwiftUsd::TakeFunctionParameterFromSwift(SmartPointer::DataType*)","type":"codeVoice"},{"type":"text","text":" isn’t used."}],"type":"paragraph"},{"code":["\/\/ foo.hpp","#include \"swiftUsd\/swiftUsd.h\"","#include \"pxr\/usd\/usd\/stage.h\"","void useRawPointerPassedBySwift(pxr::UsdStage* _Nonnull _stage);"],"type":"codeListing","syntax":"c++"},{"code":["\/\/ foo.mm","#include \"foo.hpp\"","","void useRawPointerPassedBySwift(pxr::UsdStage* _Nonnull _stage) {","    pxr::UsdStageRefPtr stage = SwiftUsd::TakeFunctionParameterFromSwift<pxr::UsdStageRefPtr>(_stage);","}"],"type":"codeListing","syntax":"c++"},{"inlineContent":[{"text":"See ","type":"text"},{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxInteropMemorySafety","isActive":true},{"text":" for more information.","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd"]]},"references":{"doc://SwiftUsd/documentation/SwiftUsd/SwiftCxxInteropMemorySafety":{"kind":"article","type":"topic","role":"article","url":"\/documentation\/swiftusd\/swiftcxxinteropmemorysafety","title":"Swift-Cxx Interop and Memory Safety","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxInteropMemorySafety","abstract":[{"text":"Learn how to avoid unsafe memory management issues when using Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","type":"topic","url":"\/documentation\/openusd","abstract":[],"role":"collection"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd":{"title":"SwiftUsd","abstract":[],"url":"\/documentation\/openusd\/swiftusd","fragments":[{"text":"SwiftUsd","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd","kind":"symbol","role":"symbol","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd/TakeFunctionParameterFromSwift":{"abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"TakeFunctionParameterFromSwift"}],"type":"topic","url":"\/documentation\/openusd\/swiftusd\/takefunctionparameterfromswift","title":"TakeFunctionParameterFromSwift","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/TakeFunctionParameterFromSwift"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SwiftUsd","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SwiftUsd"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/fragments"},{"op":"add","value":[{"text":"SwiftUsd","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}