{"variants":[{"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper\/arresolverwrapper-3q8zx"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper\/arresolverwrapper-3q8zx"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/ArResolverWrapper-3q8zx"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"unowned","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArResolver","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArResolver"},{"text":">","kind":"text"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"ArResolverWrapper","kind":"typeIdentifier"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"ArResolverWrapper"}],"role":"symbol","title":"init(_:)","externalID":"c:@N@Overlay@S@ArResolverWrapper@F@ArResolverWrapper#*$@N@pxr@S@ArResolver#","modules":[{"name":"OpenUSD"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ArResolver","preciseIdentifier":"c:@N@pxr@S@ArResolver"},{"kind":"text","text":">"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"ArResolverWrapper"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","abstract":[],"url":"\/documentation\/openusd","kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/ArResolverWrapper-3q8zx":{"title":"init(_:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArResolver","text":"ArResolver"},{"kind":"text","text":">"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"ArResolverWrapper"}],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/arresolverwrapper-3q8zx","type":"topic","navigatorTitle":[{"text":"ArResolverWrapper","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/ArResolverWrapper-3q8zx"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper":{"url":"\/documentation\/openusd\/overlay\/arresolverwrapper","title":"class ArResolverWrapper","navigatorTitle":[{"kind":"identifier","text":"ArResolverWrapper"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArResolverWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"text":"Overlay","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","title":"Overlay","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Constructor","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ArResolverWrapper","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ArResolverWrapper","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ArResolverWrapper"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ArResolverWrapper"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","text":"ArResolver","preciseIdentifier":"c:@N@pxr@S@ArResolver"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"unowned"},{"kind":"text","text":");"}],"platforms":["macOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ArResolverWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1ArResolverWrapper-3q8zx\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ArResolverWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1ArResolverWrapper-3q8zx\/fragments"},{"op":"replace","value":[{"text":"ArResolverWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1ArResolverWrapper-3q8zx\/navigatorTitle"},{"op":"replace","value":"ArResolverWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ArResolverWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/fragments"},{"op":"replace","value":[{"text":"ArResolverWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/navigatorTitle"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"}]}]}