{"sections":[],"metadata":{"modules":[{"name":"OpenUSD"}],"externalID":"c:@N@Overlay@S@ArResolverWrapper@F@BeginCacheScope#*$@N@pxr@S@VtValue#","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","title":"BeginCacheScope(_:)","navigatorTitle":[{"kind":"identifier","text":"BeginCacheScope"}],"fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BeginCacheScope","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"VtValue","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@VtValue"},{"text":">","kind":"text"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BeginCacheScope"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cacheScopeData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@VtValue","kind":"typeIdentifier","text":"VtValue"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"platforms":["macOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/BeginCacheScope"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper\/begincachescope"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper\/begincachescope"]}],"references":{"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","type":"topic","url":"\/documentation\/openusd","abstract":[],"role":"collection"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"role":"symbol","url":"\/documentation\/openusd\/overlay","fragments":[{"kind":"identifier","text":"Overlay"}],"kind":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","type":"topic","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/BeginCacheScope":{"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/BeginCacheScope","title":"BeginCacheScope(_:)","navigatorTitle":[{"kind":"identifier","text":"BeginCacheScope"}],"type":"topic","url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/begincachescope","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BeginCacheScope"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@VtValue","text":"VtValue"},{"kind":"text","text":">"},{"kind":"text","text":")"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper":{"navigatorTitle":[{"kind":"identifier","text":"ArResolverWrapper"}],"abstract":[],"type":"topic","role":"symbol","title":"class ArResolverWrapper","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArResolverWrapper"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","url":"\/documentation\/openusd\/overlay\/arresolverwrapper"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"BeginCacheScope","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"BeginCacheScope"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"BeginCacheScope","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"BeginCacheScope","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":"::","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@VtValue","text":"VtValue","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"cacheScopeData","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["macOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"kind":"identifier","text":"Overlay"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"kind":"identifier","text":"Overlay"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1BeginCacheScope\/title","value":"BeginCacheScope"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1BeginCacheScope\/fragments","value":[{"text":"BeginCacheScope","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1BeginCacheScope\/navigatorTitle","value":[{"text":"BeginCacheScope","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/title","value":"ArResolverWrapper"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/fragments","value":[{"kind":"identifier","text":"ArResolverWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/navigatorTitle","value":[{"text":"ArResolverWrapper","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}