{"metadata":{"title":"CreateContextFromString(_:)","symbolKind":"method","role":"symbol","externalID":"c:@N@Overlay@S@ArResolverWrapper@F@CreateContextFromString#&1$@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C#1","navigatorTitle":[{"text":"CreateContextFromString","kind":"identifier"}],"modules":[{"name":"OpenUSD"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateContextFromString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","kind":"identifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArResolverContext","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArResolverContext"}]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateContextFromString-59xki"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateContextFromString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"contextStr"},{"kind":"text","text":": "},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"string","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArResolverContext","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArResolverContext"}],"platforms":["macOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper\/createcontextfromstring-59xki"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper\/createcontextfromstring-59xki"]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"type":"topic","url":"\/documentation\/openusd\/overlay","fragments":[{"kind":"identifier","text":"Overlay"}],"title":"Overlay"},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","title":"OpenUSD","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","type":"topic","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArResolverWrapper"}],"navigatorTitle":[{"kind":"identifier","text":"ArResolverWrapper"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/openusd\/overlay\/arresolverwrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","title":"class ArResolverWrapper","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/CreateContextFromString-59xki":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CreateContextFromString"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateContextFromString-59xki","abstract":[],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/createcontextfromstring-59xki","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateContextFromString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","kind":"identifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArResolverContext","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArResolverContext"}],"title":"CreateContextFromString(_:)","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"CreateContextFromString"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"CreateContextFromString","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CreateContextFromString"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":"::","kind":"text"},{"text":"ArResolverContext","preciseIdentifier":"c:@N@pxr@S@ArResolverContext","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"CreateContextFromString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"std","preciseIdentifier":"c:@N@std","kind":"identifier"},{"text":"::","kind":"text"},{"text":"string","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"contextStr","kind":"internalParam"},{"text":") ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"kind":"identifier","text":"Overlay"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"text":"Overlay","kind":"identifier"}],"op":"add"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/title","value":"ArResolverWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/fragments","value":[{"kind":"identifier","text":"ArResolverWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"ArResolverWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateContextFromString-59xki\/title","value":"CreateContextFromString","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateContextFromString-59xki\/fragments","value":[{"kind":"identifier","text":"CreateContextFromString"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateContextFromString-59xki\/navigatorTitle","value":[{"kind":"identifier","text":"CreateContextFromString"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}