{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/OpenAssetForWrite","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper\/openassetforwrite"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper\/openassetforwrite"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"OpenUSD"}],"title":"OpenAssetForWrite(_:_:)","navigatorTitle":[{"kind":"identifier","text":"OpenAssetForWrite"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenAssetForWrite"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ArResolvedPath","preciseIdentifier":"c:@N@pxr@S@ArResolvedPath"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"WriteMode","preciseIdentifier":"c:@N@Overlay@S@ArResolverWrapper@E@WriteMode"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"std::shared_ptr","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ArWritableAsset","preciseIdentifier":"c:@N@pxr@S@ArWritableAsset"},{"kind":"text","text":">"}],"role":"symbol","symbolKind":"method","externalID":"c:@N@Overlay@S@ArResolverWrapper@F@OpenAssetForWrite#&1$@N@pxr@S@ArResolvedPath#$@N@Overlay@S@ArResolverWrapper@E@WriteMode#1","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenAssetForWrite","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"resolvedPath","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArResolvedPath","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArResolvedPath"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"writeMode","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/WriteMode","text":"WriteMode","kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@S@ArResolverWrapper@E@WriteMode"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"std","kind":"identifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"std::shared_ptr","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr"},{"text":"<","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArWritableAsset","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArWritableAsset"},{"text":">","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/WriteMode":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/WriteMode","url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/writemode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WriteMode"}],"abstract":[],"type":"topic","kind":"symbol","title":"WriteMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WriteMode"}]},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","type":"topic","url":"\/documentation\/openusd","abstract":[],"role":"collection"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"role":"symbol","url":"\/documentation\/openusd\/overlay","fragments":[{"kind":"identifier","text":"Overlay"}],"kind":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","type":"topic","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper":{"navigatorTitle":[{"kind":"identifier","text":"ArResolverWrapper"}],"abstract":[],"type":"topic","role":"symbol","title":"class ArResolverWrapper","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArResolverWrapper"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","url":"\/documentation\/openusd\/overlay\/arresolverwrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/OpenAssetForWrite":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"OpenAssetForWrite","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/OpenAssetForWrite","type":"topic","kind":"symbol","title":"OpenAssetForWrite(_:_:)","url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/openassetforwrite","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenAssetForWrite"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ArResolvedPath","preciseIdentifier":"c:@N@pxr@S@ArResolvedPath"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"WriteMode","preciseIdentifier":"c:@N@Overlay@S@ArResolverWrapper@E@WriteMode"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"std","kind":"identifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"std::shared_ptr","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr"},{"text":"<","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArWritableAsset","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArWritableAsset"},{"text":">","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"OpenAssetForWrite","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"OpenAssetForWrite","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"OpenAssetForWrite","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"preciseIdentifier":"c:@N@std","text":"std","kind":"identifier"},{"text":"::","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr","text":"std::shared_ptr","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":"::","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@ArWritableAsset","text":"ArWritableAsset","kind":"typeIdentifier"},{"text":"> ","kind":"text"},{"text":"OpenAssetForWrite","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":"::","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@ArResolvedPath","text":"ArResolvedPath","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"resolvedPath","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@N@Overlay@S@ArResolverWrapper@E@WriteMode","text":"WriteMode","kind":"typeIdentifier","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/WriteMode"},{"text":" ","kind":"text"},{"text":"writeMode","kind":"internalParam"},{"text":") ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"WriteMode","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode\/title","op":"replace"},{"value":[{"text":"WriteMode","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode\/fragments","op":"replace"},{"value":[{"text":"WriteMode","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode\/navigatorTitle","op":"replace"},{"value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace"},{"value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace"},{"value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add"},{"value":"ArResolverWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/title","op":"replace"},{"value":[{"text":"ArResolverWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/fragments","op":"replace"},{"value":[{"text":"ArResolverWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/navigatorTitle","op":"replace"},{"value":"OpenAssetForWrite","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1OpenAssetForWrite\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OpenAssetForWrite"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1OpenAssetForWrite\/fragments","op":"replace"},{"value":[{"text":"OpenAssetForWrite","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1OpenAssetForWrite\/navigatorTitle","op":"replace"}]}]}