{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Enumeration","title":"WriteMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WriteMode"}],"navigatorTitle":[{"kind":"identifier","text":"WriteMode"}],"symbolKind":"enum","role":"symbol","modules":[{"name":"OpenUSD"}],"externalID":"c:@N@Overlay@S@ArResolverWrapper@E@WriteMode"},"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/WriteMode\/Replace","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/WriteMode\/Update"],"anchor":"Enumeration-Cases"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper"]]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WriteMode"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper\/writemode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper\/writemode"]}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/WriteMode","interfaceLanguage":"swift"},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper":{"type":"topic","url":"\/documentation\/openusd\/overlay\/arresolverwrapper","navigatorTitle":[{"kind":"identifier","text":"ArResolverWrapper"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArResolverWrapper"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","kind":"symbol","title":"class ArResolverWrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"kind":"identifier","text":"Overlay"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","title":"Overlay","type":"topic","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/WriteMode/Update":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/WriteMode\/Update","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Update"}],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/writemode\/update","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"Update"}],"title":"Update","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/WriteMode":{"title":"WriteMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WriteMode"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"WriteMode"}],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/writemode","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/WriteMode"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/WriteMode/Replace":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Replace","kind":"identifier"}],"role":"symbol","url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/writemode\/replace","type":"topic","title":"Replace","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/WriteMode\/Replace","abstract":[],"navigatorTitle":[{"text":"Replace","kind":"identifier"}],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","abstract":[],"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"WriteMode","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"WriteMode","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"WriteMode","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/WriteMode\/Replace","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/WriteMode\/Update"],"anchor":"Enumeration-Cases"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WriteMode"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:I","text":"int"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ArResolverWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/title"},{"op":"replace","value":[{"text":"ArResolverWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/fragments"},{"op":"replace","value":[{"text":"ArResolverWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/navigatorTitle"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"op":"replace","value":"Update","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode~1Update\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Update"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode~1Update\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Update"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode~1Update\/navigatorTitle"},{"op":"replace","value":"WriteMode","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"WriteMode"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode\/fragments"},{"op":"replace","value":[{"text":"WriteMode","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode\/navigatorTitle"},{"op":"replace","value":"Replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode~1Replace\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Replace"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode~1Replace\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Replace"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode~1Replace\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}