{"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","interfaceLanguage":"swift"},"topicSections":[{"title":"Essentials","anchor":"Essentials","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Capabilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DifferencesInSwift","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CurrentLimitations"]},{"title":"Wrapped symbol documentation","abstract":[{"text":"In Swift, some parts of the OpenUSD API aren’t directly available. This Swift Package re-exposes a subset of the API, documented here. (See ","type":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CurrentLimitations","type":"reference","isActive":true},{"text":" for more information.)","type":"text"}],"anchor":"Wrapped-symbol-documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedEnums","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedFunctions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedOperators"]},{"title":"New symbol documentation","abstract":[{"type":"text","text":"This Swift package adds new functions\/types to make OpenUSD more natural to use in Swift."}],"anchor":"New-symbol-documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"]},{"title":"Protocol conformances","abstract":[{"text":"This Swift Package provides a number of protocol conformances to make OpenUSD more natural to use in Swift.","type":"text"}],"anchor":"Protocol-conformances","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Equatable","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Comparable","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Hashable","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CustomStringConvertible","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Sendable","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Codable"]},{"title":"Working with foreign reference types","anchor":"Working-with-foreign-reference-types","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WhatIsAForeignReferenceType","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ForeignReferenceTypesAndSmartPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CastingBetweenForeignReferenceTypes"]},{"title":"Using SwiftUsd from C++","anchor":"Using-SwiftUsd-from-C++","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStartedInCPlusPlus","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxInteropMemorySafety","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxMacros"]},{"title":"Technical details","anchor":"Technical-details","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DetectingOpenUSDFeatureFlags","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/BuildingLocally","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangesToOpenUSD"]},{"title":"Deprecated","anchor":"Deprecated","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DeprecatedSymbols"]},{"title":"About this repo","anchor":"About-this-repo","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangeLog","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UpgradeChecklist","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ReleaseChecklist","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Miscellaneous"]},{"title":"Classes","generated":true,"anchor":"Classes","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey"]},{"title":"Operators","generated":true,"anchor":"Operators","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/!==(_:_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/===(_:_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-2xoh5","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-7ycue","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-9e095"],"generated":true,"anchor":"Type-Methods"},{"title":"Enumerations","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd"],"generated":true,"anchor":"Enumerations"},{"title":"Extended Modules","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift"],"generated":true,"anchor":"Extended-Modules"}],"sections":[],"metadata":{"modules":[{"name":"OpenUSD"}],"externalID":"OpenUSD","role":"collection","roleHeading":"Framework","title":"OpenUSD","symbolKind":"module"},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","level":2,"anchor":"Overview","text":"Overview"},{"inlineContent":[{"text":"This repo modifies Pixar’s ","type":"text"},{"identifier":"https:\/\/openusd.org\/release\/index.html","isActive":true,"type":"reference"},{"text":" to enable Swift-Cxx interoperability, letting developers use the OpenUSD C++ API directly from Swift, distributed as a Swift package.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The documentation in this repo goes over differences when using OpenUSD in Swift. The full C++ documentation for OpenUSD can be found "},{"identifier":"https:\/\/openusd.org\/release\/api\/index.html","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/openusd"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[[]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd_PXR_ENABLE_DRACO_SUPPORT":{"role":"symbol","title":"SwiftUsd_PXR_ENABLE_DRACO_SUPPORT","abstract":[],"url":"\/documentation\/openusd\/swiftusd_pxr_enable_draco_support","kind":"symbol","fragments":[{"kind":"identifier","text":"SwiftUsd_PXR_ENABLE_DRACO_SUPPORT"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_DRACO_SUPPORT"},"doc://SwiftUsd/documentation/SwiftUsd/Hashable":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Hashable","role":"article","url":"\/documentation\/swiftusd\/hashable","kind":"article","abstract":[],"title":"Hashable protocol conformances","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/SwiftKey":{"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","abstract":[{"text":"A key representing a listener registered from either Swift or C++","type":"text"}],"url":"\/documentation\/openusd\/swiftkey","navigatorTitle":[{"kind":"identifier","text":"SwiftKey"}],"role":"symbol","title":"class SwiftKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwiftKey"}]},"doc://SwiftUsd/documentation/OpenUSD/Revoke-2xoh5":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-2xoh5","role":"symbol","url":"\/documentation\/openusd\/revoke-2xoh5","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Revoke","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S0_","kind":"typeIdentifier","text":"SwiftKeys"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"text":"Revoke","kind":"identifier"}],"title":"Revoke(_:)","abstract":[],"type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/ChangesToOpenUSD":{"kind":"article","title":"Changes to OpenUSD","url":"\/documentation\/swiftusd\/changestoopenusd","type":"topic","abstract":[{"text":"Learn about the changes this Swift Package makes to OpenUSD","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangesToOpenUSD","role":"article"},"doc://SwiftUsd/documentation/SwiftUsd/Sendable":{"url":"\/documentation\/swiftusd\/sendable","type":"topic","abstract":[],"role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Sendable","title":"Sendable protocol conformances","kind":"article"},"doc://SwiftUsd/documentation/SwiftUsd/WrappedTypes":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","type":"topic","title":"Wrapped types","url":"\/documentation\/swiftusd\/wrappedtypes","abstract":[],"kind":"article","role":"collectionGroup"},"doc://SwiftUsd/documentation/SwiftUsd/OngoingWork":{"url":"\/documentation\/swiftusd\/ongoingwork","abstract":[{"type":"text","text":"In-progress and future tasks for improving OpenUSD in Swift"}],"kind":"article","role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork","type":"topic","title":"Ongoing Work"},"doc://SwiftUsd/documentation/OpenUSD/RevokeAndWait-7ycue":{"url":"\/documentation\/openusd\/revokeandwait-7ycue","type":"topic","navigatorTitle":[{"text":"RevokeAndWait","kind":"identifier"}],"abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RevokeAndWait","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:b","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-7ycue","title":"RevokeAndWait(_:)","kind":"symbol"},"doc://SwiftUsd/documentation/SwiftUsd/UsingEditContexts":{"type":"topic","url":"\/documentation\/swiftusd\/usingeditcontexts","title":"Using edit contexts","role":"collectionGroup","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","abstract":[{"type":"text","text":"Using "},{"code":"pxr.UsdEditContext","type":"codeVoice"},{"type":"text","text":" in Swift"}],"kind":"article"},"doc://SwiftUsd/documentation/SwiftUsd/CreatingPointers":{"type":"topic","title":"Creating pointers","url":"\/documentation\/swiftusd\/creatingpointers","role":"collectionGroup","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","abstract":[{"type":"text","text":"Creating "},{"type":"codeVoice","code":"pxr.TfRefPtr"},{"type":"text","text":" and "},{"type":"codeVoice","code":"pxr.TfWeakPtr"},{"type":"text","text":" in Swift"}],"kind":"article"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd_PXR_ENABLE_OPENIMAGEIO_SUPPORT":{"type":"topic","title":"SwiftUsd_PXR_ENABLE_OPENIMAGEIO_SUPPORT","url":"\/documentation\/openusd\/swiftusd_pxr_enable_openimageio_support","role":"symbol","fragments":[{"text":"SwiftUsd_PXR_ENABLE_OPENIMAGEIO_SUPPORT","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_OPENIMAGEIO_SUPPORT","abstract":[],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd_PXR_ENABLE_PYTHON_SUPPORT":{"abstract":[],"fragments":[{"text":"SwiftUsd_PXR_ENABLE_PYTHON_SUPPORT","kind":"identifier"}],"type":"topic","url":"\/documentation\/openusd\/swiftusd_pxr_enable_python_support","kind":"symbol","role":"symbol","title":"SwiftUsd_PXR_ENABLE_PYTHON_SUPPORT","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_PYTHON_SUPPORT"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd_PXR_ENABLE_PTEX_SUPPORT":{"type":"topic","title":"SwiftUsd_PXR_ENABLE_PTEX_SUPPORT","url":"\/documentation\/openusd\/swiftusd_pxr_enable_ptex_support","role":"symbol","fragments":[{"kind":"identifier","text":"SwiftUsd_PXR_ENABLE_PTEX_SUPPORT"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_PTEX_SUPPORT","abstract":[],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/SWIFT_UNAVAILABLE":{"abstract":[],"url":"\/documentation\/openusd\/swift_unavailable","role":"symbol","fragments":[{"kind":"identifier","text":"SWIFT_UNAVAILABLE"}],"title":"SWIFT_UNAVAILABLE","kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SWIFT_UNAVAILABLE"},"doc://SwiftUsd/documentation/OpenUSD/RevokeAndWait-9e095":{"type":"topic","title":"RevokeAndWait(_:)","url":"\/documentation\/openusd\/revokeandwait-9e095","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RevokeAndWait","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SwiftKeys","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S0_"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-9e095","navigatorTitle":[{"text":"RevokeAndWait","kind":"identifier"}],"abstract":[],"kind":"symbol"},"https://openusd.org/release/api/index.html":{"url":"https:\/\/openusd.org\/release\/api\/index.html","type":"link","titleInlineContent":[{"text":"here","type":"text"}],"identifier":"https:\/\/openusd.org\/release\/api\/index.html","title":"here"},"doc://SwiftUsd/documentation/SwiftUsd/ConvenientExtensions":{"url":"\/documentation\/swiftusd\/convenientextensions","role":"collectionGroup","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","title":"Convenient extensions","type":"topic","kind":"article","abstract":[{"type":"text","text":"Extensions that make OpenUSD nicer to use in Swift"}]},"doc://SwiftUsd/documentation/SwiftUsd/WrappedFunctions":{"abstract":[],"type":"topic","role":"collectionGroup","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedFunctions","title":"Wrapped functions","url":"\/documentation\/swiftusd\/wrappedfunctions"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd_PXR_ENABLE_USD_IMAGING_SUPPORT":{"kind":"symbol","abstract":[],"url":"\/documentation\/openusd\/swiftusd_pxr_enable_usd_imaging_support","role":"symbol","fragments":[{"text":"SwiftUsd_PXR_ENABLE_USD_IMAGING_SUPPORT","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_USD_IMAGING_SUPPORT","type":"topic","title":"SwiftUsd_PXR_ENABLE_USD_IMAGING_SUPPORT"},"doc://SwiftUsd/documentation/SwiftUsd/CurrentLimitations":{"abstract":[{"text":"Learn about the current limitations of OpenUSD in Swift","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CurrentLimitations","kind":"article","url":"\/documentation\/swiftusd\/currentlimitations","type":"topic","title":"Current Limitations","role":"article"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd_PXR_ENABLE_MATERIALX_SUPPORT":{"abstract":[],"url":"\/documentation\/openusd\/swiftusd_pxr_enable_materialx_support","type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_MATERIALX_SUPPORT","title":"SwiftUsd_PXR_ENABLE_MATERIALX_SUPPORT","role":"symbol","fragments":[{"text":"SwiftUsd_PXR_ENABLE_MATERIALX_SUPPORT","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd_PXR_ENABLE_OPENCOLORIO_SUPPORT":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_OPENCOLORIO_SUPPORT","kind":"symbol","url":"\/documentation\/openusd\/swiftusd_pxr_enable_opencolorio_support","type":"topic","title":"SwiftUsd_PXR_ENABLE_OPENCOLORIO_SUPPORT","role":"symbol","fragments":[{"text":"SwiftUsd_PXR_ENABLE_OPENCOLORIO_SUPPORT","kind":"identifier"}]},"doc://SwiftUsd/documentation/SwiftUsd/SwiftCxxInteropMemorySafety":{"kind":"article","abstract":[{"type":"text","text":"Learn how to avoid unsafe memory management issues when using Swift-Cxx interop"}],"role":"article","title":"Swift-Cxx Interop and Memory Safety","type":"topic","url":"\/documentation\/swiftusd\/swiftcxxinteropmemorysafety","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxInteropMemorySafety"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfNotice":{"abstract":[{"text":"Learn how to use the TfNotice notification subsystem in Swift","type":"text"}],"url":"\/documentation\/swiftusd\/workingwithtfnotice","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","kind":"article","title":"Working with TfNotice","role":"article"},"doc://SwiftUsd/documentation/OpenUSD/SWIFT_UNAVAILABLE_MESSAGE":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SWIFT_UNAVAILABLE_MESSAGE","abstract":[],"role":"symbol","title":"SWIFT_UNAVAILABLE_MESSAGE","type":"topic","fragments":[{"kind":"identifier","text":"SWIFT_UNAVAILABLE_MESSAGE"}],"url":"\/documentation\/openusd\/swift_unavailable_message","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd","kind":"symbol","url":"\/documentation\/openusd\/swiftusd","type":"topic","title":"SwiftUsd","role":"symbol","fragments":[{"text":"SwiftUsd","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++":{"abstract":[],"role":"collection","url":"\/documentation\/openusd\/c++","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++","type":"topic","kind":"symbol","title":"C++"},"doc://SwiftUsd/documentation/SwiftUsd/GettingStarted":{"abstract":[{"text":"Adding SwiftUsd to your project or package","type":"text"}],"url":"\/documentation\/swiftusd\/gettingstarted","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted","kind":"article","title":"Getting Started with OpenUSD","role":"article"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd_PXR_ENABLE_EMBREE_SUPPORT":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_EMBREE_SUPPORT","kind":"symbol","type":"topic","url":"\/documentation\/openusd\/swiftusd_pxr_enable_embree_support","title":"SwiftUsd_PXR_ENABLE_EMBREE_SUPPORT","role":"symbol","fragments":[{"kind":"identifier","text":"SwiftUsd_PXR_ENABLE_EMBREE_SUPPORT"}]},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd_PXR_ENABLE_PRMAN_SUPPORT":{"abstract":[],"url":"\/documentation\/openusd\/swiftusd_pxr_enable_prman_support","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_PRMAN_SUPPORT","kind":"symbol","title":"SwiftUsd_PXR_ENABLE_PRMAN_SUPPORT","role":"symbol","fragments":[{"text":"SwiftUsd_PXR_ENABLE_PRMAN_SUPPORT","kind":"identifier"}]},"doc://SwiftUsd/documentation/SwiftUsd/DetectingOpenUSDFeatureFlags":{"abstract":[{"type":"text","text":"Learn how to detect OpenUSD feature flags"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DetectingOpenUSDFeatureFlags","kind":"article","type":"topic","url":"\/documentation\/swiftusd\/detectingopenusdfeatureflags","title":"Detecting OpenUSD feature flags","role":"article"},"doc://SwiftUsd/documentation/SwiftUsd/WrappedEnums":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedEnums","url":"\/documentation\/swiftusd\/wrappedenums","type":"topic","kind":"article","title":"Wrapped enums","role":"article"},"doc://SwiftUsd/documentation/SwiftUsd/CheckingForValidity":{"abstract":[{"text":"Checking for ","type":"text"},{"code":"IsValid()","type":"codeVoice"},{"text":" and null pointers in Swift","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","kind":"article","type":"topic","url":"\/documentation\/swiftusd\/checkingforvalidity","title":"Checking for validity","role":"article"},"https://openusd.org/release/index.html":{"identifier":"https:\/\/openusd.org\/release\/index.html","titleInlineContent":[{"type":"text","text":"OpenUSD"}],"url":"https:\/\/openusd.org\/release\/index.html","title":"OpenUSD","type":"link"},"doc://SwiftUsd/documentation/OpenUSD/Revoke-31sr0":{"abstract":[],"url":"\/documentation\/openusd\/revoke-31sr0","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0","kind":"symbol","title":"Revoke(_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Revoke","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","text":"SwiftKey","kind":"typeIdentifier"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"c:b"}],"navigatorTitle":[{"text":"Revoke","kind":"identifier"}]},"doc://SwiftUsd/documentation/SwiftUsd/CheatSheet":{"title":"Cheat sheet","abstract":[{"text":"Tips for advanced users modifying this repo","type":"text"}],"kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet","url":"\/documentation\/swiftusd\/cheatsheet","role":"article","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd_PXR_ENABLE_IMAGING_SUPPORT":{"abstract":[],"title":"SwiftUsd_PXR_ENABLE_IMAGING_SUPPORT","fragments":[{"text":"SwiftUsd_PXR_ENABLE_IMAGING_SUPPORT","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_IMAGING_SUPPORT","role":"symbol","type":"topic","url":"\/documentation\/openusd\/swiftusd_pxr_enable_imaging_support"},"doc://SwiftUsd/documentation/SwiftUsd/CastingBetweenForeignReferenceTypes":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CastingBetweenForeignReferenceTypes","url":"\/documentation\/swiftusd\/castingbetweenforeignreferencetypes","kind":"article","type":"topic","title":"Casting between Foreign Reference Types","role":"article","abstract":[{"text":"Learn about casting with Foreign Reference Types","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"title":"Overlay","type":"topic","fragments":[{"kind":"identifier","text":"Overlay"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/Swift":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift","abstract":[],"url":"\/documentation\/openusd\/swift","title":"Swift","kind":"symbol","type":"topic","role":"collection"},"doc://SwiftUsd/documentation/SwiftUsd/Miscellaneous":{"abstract":[{"type":"text","text":"Miscellaneous details about this repo"}],"role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Miscellaneous","type":"topic","kind":"article","title":"Miscellaneous","url":"\/documentation\/swiftusd\/miscellaneous"},"doc://SwiftUsd/documentation/SwiftUsd/ForeignReferenceTypesAndSmartPointers":{"abstract":[{"text":"Learn about ","type":"text"},{"code":"pxr::TfRefPtr","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"pxr::TfWeakPtr","type":"codeVoice"},{"text":" in Swift","type":"text"}],"url":"\/documentation\/swiftusd\/foreignreferencetypesandsmartpointers","kind":"article","type":"topic","title":"Foreign Reference Types and Smart Pointers","role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ForeignReferenceTypesAndSmartPointers"},"doc://SwiftUsd/documentation/SwiftUsd/ReleaseChecklist":{"abstract":[{"text":"Checklist for releasing new versions of SwiftUsd","type":"text"}],"role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ReleaseChecklist","type":"topic","kind":"article","title":"Release Checklist","url":"\/documentation\/swiftusd\/releasechecklist"},"doc://SwiftUsd/documentation/SwiftUsd/DeprecatedSymbols":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DeprecatedSymbols","url":"\/documentation\/swiftusd\/deprecatedsymbols","kind":"article","type":"topic","title":"Deprecated","role":"article","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd_PXR_ENABLE_IMAGEIO_SUPPORT":{"abstract":[],"url":"\/documentation\/openusd\/swiftusd_pxr_enable_imageio_support","kind":"symbol","type":"topic","fragments":[{"text":"SwiftUsd_PXR_ENABLE_IMAGEIO_SUPPORT","kind":"identifier"}],"title":"SwiftUsd_PXR_ENABLE_IMAGEIO_SUPPORT","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_IMAGEIO_SUPPORT"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd_PXR_ENABLE_OPENVDB_SUPPORT":{"fragments":[{"kind":"identifier","text":"SwiftUsd_PXR_ENABLE_OPENVDB_SUPPORT"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_OPENVDB_SUPPORT","title":"SwiftUsd_PXR_ENABLE_OPENVDB_SUPPORT","kind":"symbol","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/openusd\/swiftusd_pxr_enable_openvdb_support"},"doc://SwiftUsd/documentation/OpenUSD/===(_:_:)":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/===(_:_:)","url":"\/documentation\/openusd\/===(_:_:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"==="},{"kind":"text","text":" "},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3eeeoiySbxSg_ACtSo7OverlayOAAE30_SwiftUsdReferenceTypeProtocolRzlF1TL_xmfp","text":"T"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3eeeoiySbxSg_ACtSo7OverlayOAAE30_SwiftUsdReferenceTypeProtocolRzlF1TL_xmfp","text":"T"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"===(_:_:)","role":"symbol","abstract":[]},"doc://SwiftUsd/documentation/SwiftUsd/Equatable":{"title":"Equatable protocol conformances","url":"\/documentation\/swiftusd\/equatable","abstract":[],"role":"article","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Equatable","type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/WhatIsAForeignReferenceType":{"title":"What is a Foreign Reference Type?","url":"\/documentation\/swiftusd\/whatisaforeignreferencetype","abstract":[{"text":"Learn about foreign reference types and how to use them","type":"text"}],"role":"article","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WhatIsAForeignReferenceType","type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/Capabilities":{"title":"Capabilities","url":"\/documentation\/swiftusd\/capabilities","abstract":[{"text":"Learn about the current capabilities of OpenUSD in Swift","type":"text"}],"role":"article","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Capabilities","type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/WrappedOperators":{"title":"Wrapped operators","url":"\/documentation\/swiftusd\/wrappedoperators","abstract":[],"role":"collectionGroup","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedOperators","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/!==(_:_:)":{"title":"!==(_:_:)","url":"\/documentation\/openusd\/!==(_:_:)","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!==","kind":"identifier"},{"text":" ","kind":"text"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3neeoiySbxSg_ACtSo7OverlayOAAE30_SwiftUsdReferenceTypeProtocolRzlF1TL_xmfp"},{"text":"?, ","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3neeoiySbxSg_ACtSo7OverlayOAAE30_SwiftUsdReferenceTypeProtocolRzlF1TL_xmfp"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/!==(_:_:)","type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/GettingStartedInCPlusPlus":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStartedInCPlusPlus","abstract":[{"type":"text","text":"Using SwiftUsd from C++"}],"role":"article","title":"Getting Started In C++","type":"topic","url":"\/documentation\/swiftusd\/gettingstartedincplusplus","kind":"article"},"doc://SwiftUsd/documentation/SwiftUsd/TypeConversion":{"role":"collectionGroup","title":"Type conversion","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion","type":"topic","url":"\/documentation\/swiftusd\/typeconversion","abstract":[],"kind":"article"},"doc://SwiftUsd/documentation/SwiftUsd/Codable":{"role":"article","title":"Codable protocol conformances","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Codable","type":"topic","url":"\/documentation\/swiftusd\/codable","abstract":[],"kind":"article"},"doc://SwiftUsd/documentation/SwiftUsd/BuildingLocally":{"kind":"article","title":"Building locally","url":"\/documentation\/swiftusd\/buildinglocally","type":"topic","abstract":[{"text":"Learn how to use SwiftUsd with local\/existing OpenUSD binaries","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/BuildingLocally","role":"article"},"doc://SwiftUsd/documentation/SwiftUsd/DereferencingPointers":{"role":"collectionGroup","title":"Dereferencing pointers","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","type":"topic","url":"\/documentation\/swiftusd\/dereferencingpointers","abstract":[{"text":"Safely dereferencing ","type":"text"},{"type":"codeVoice","code":"pxr.TfRefPtr"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"pxr.TfWeakPtr"},{"text":" in Swift","type":"text"}],"kind":"article"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfDiagnosticFacilities":{"role":"collectionGroup","title":"Working with Tf Diagnostic Facilities","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","type":"topic","url":"\/documentation\/swiftusd\/workingwithtfdiagnosticfacilities","abstract":[{"type":"text","text":"Learn how to use the Tf diagnostic facilities in Swift"}],"kind":"article"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","abstract":[],"type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/DifferencesInSwift":{"role":"article","title":"Differences in Swift","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DifferencesInSwift","type":"topic","url":"\/documentation\/swiftusd\/differencesinswift","abstract":[{"type":"text","text":"Learn how the OpenUSD API is different in Swift"}],"kind":"article"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfErrorMark":{"role":"article","title":"Working with TfErrorMark","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","type":"topic","url":"\/documentation\/swiftusd\/workingwithtferrormark","abstract":[{"type":"text","text":"Learn how to use TfErrorMark in Swift"}],"kind":"article"},"doc://SwiftUsd/documentation/SwiftUsd/CustomStringConvertible":{"role":"article","title":"CustomStringConvertible protocol conformances","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CustomStringConvertible","type":"topic","url":"\/documentation\/swiftusd\/customstringconvertible","abstract":[],"kind":"article"},"doc://SwiftUsd/documentation/SwiftUsd/Comparable":{"role":"article","title":"Comparable protocol conformances","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Comparable","type":"topic","url":"\/documentation\/swiftusd\/comparable","kind":"article","abstract":[]},"doc://SwiftUsd/documentation/SwiftUsd/SwiftCxxMacros":{"role":"article","title":"Swift-Cxx Macros","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxMacros","type":"topic","url":"\/documentation\/swiftusd\/swiftcxxmacros","abstract":[{"type":"text","text":"Learn about useful Swift-Cxx macros for writing C++ code used by Swift"}],"kind":"article"},"doc://SwiftUsd/documentation/SwiftUsd/ChangeLog":{"abstract":[{"text":"Changes to SwiftUsd","type":"text"}],"role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangeLog","type":"topic","kind":"article","title":"Change Log","url":"\/documentation\/swiftusd\/changelog"},"doc://SwiftUsd/documentation/SwiftUsd/UpgradeChecklist":{"abstract":[{"text":"Checklist for upgrading SwiftUsd to be based on a new OpenUSD version","type":"text"}],"role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UpgradeChecklist","type":"topic","kind":"article","title":"Upgrade Checklist","url":"\/documentation\/swiftusd\/upgradechecklist"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd_PXR_ENABLE_ALEMBIC_SUPPORT":{"role":"symbol","title":"SwiftUsd_PXR_ENABLE_ALEMBIC_SUPPORT","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_ALEMBIC_SUPPORT","type":"topic","url":"\/documentation\/openusd\/swiftusd_pxr_enable_alembic_support","fragments":[{"kind":"identifier","text":"SwiftUsd_PXR_ENABLE_ALEMBIC_SUPPORT"}],"kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Capabilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DifferencesInSwift","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CurrentLimitations"],"anchor":"Essentials","title":"Essentials"},{"abstract":[{"text":"In Swift, some parts of the OpenUSD API aren’t directly available. This Swift Package re-exposes a subset of the API, documented here. (See ","type":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CurrentLimitations","isActive":true,"type":"reference"},{"text":" for more information.)","type":"text"}],"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedEnums","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedFunctions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedOperators"],"anchor":"Wrapped-symbol-documentation","title":"Wrapped symbol documentation"},{"abstract":[{"text":"This Swift package adds new functions\/types to make OpenUSD more natural to use in Swift.","type":"text"}],"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"],"anchor":"New-symbol-documentation","title":"New symbol documentation"},{"abstract":[{"type":"text","text":"This Swift Package provides a number of protocol conformances to make OpenUSD more natural to use in Swift."}],"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Equatable","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Comparable","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Hashable","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CustomStringConvertible","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Sendable","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Codable"],"anchor":"Protocol-conformances","title":"Protocol conformances"},{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WhatIsAForeignReferenceType","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ForeignReferenceTypesAndSmartPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CastingBetweenForeignReferenceTypes"],"anchor":"Working-with-foreign-reference-types","title":"Working with foreign reference types"},{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStartedInCPlusPlus","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxInteropMemorySafety","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxMacros"],"anchor":"Using-SwiftUsd-from-C++","title":"Using SwiftUsd from C++"},{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DetectingOpenUSDFeatureFlags","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/BuildingLocally","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangesToOpenUSD"],"anchor":"Technical-details","title":"Technical details"},{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DeprecatedSymbols"],"anchor":"Deprecated","title":"Deprecated"},{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangeLog","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UpgradeChecklist","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ReleaseChecklist","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Miscellaneous"],"anchor":"About-this-repo","title":"About this repo"},{"anchor":"Namespaces","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd"],"generated":true,"title":"Namespaces"},{"anchor":"Classes","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey"],"generated":true,"title":"Classes"},{"anchor":"Macros","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SWIFT_UNAVAILABLE","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SWIFT_UNAVAILABLE_MESSAGE","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_ALEMBIC_SUPPORT","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_DRACO_SUPPORT","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_EMBREE_SUPPORT","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_IMAGEIO_SUPPORT","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_IMAGING_SUPPORT","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_MATERIALX_SUPPORT","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_OPENCOLORIO_SUPPORT","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_OPENIMAGEIO_SUPPORT","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_OPENVDB_SUPPORT","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_PRMAN_SUPPORT","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_PTEX_SUPPORT","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_PYTHON_SUPPORT","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd_PXR_ENABLE_USD_IMAGING_SUPPORT"],"title":"Macros","generated":true},{"anchor":"Type-Methods","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-2xoh5","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-7ycue","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-9e095"],"title":"Type Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"SwiftKey","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/title"},{"value":[{"text":"SwiftKey","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/fragments"},{"value":[{"kind":"identifier","text":"SwiftKey"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/navigatorTitle"},{"value":"Revoke","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-2xoh5\/title"},{"value":[{"text":"Revoke","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-2xoh5\/fragments"},{"value":[{"kind":"identifier","text":"Revoke"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-2xoh5\/navigatorTitle"},{"value":"RevokeAndWait","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-7ycue\/title"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-7ycue\/fragments","value":[{"text":"RevokeAndWait","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-7ycue\/navigatorTitle","value":[{"text":"RevokeAndWait","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-9e095\/title","value":"RevokeAndWait"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-9e095\/fragments","value":[{"kind":"identifier","text":"RevokeAndWait"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-9e095\/navigatorTitle","value":[{"kind":"identifier","text":"RevokeAndWait"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/title","value":"SwiftUsd"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/fragments","value":[{"kind":"identifier","text":"SwiftUsd"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/navigatorTitle","value":[{"text":"SwiftUsd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/title","value":"Revoke"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/fragments","value":[{"text":"Revoke","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"Revoke"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/navigatorTitle"},{"value":"Overlay","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"value":[{"kind":"identifier","text":"Overlay"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"}]}]}