{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/openusd\/c++\/overlay\/sdflayer"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","text":"Overlay"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@N@SdfLayer","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfLayer","text":"SdfLayer"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/SdfLayer"},"kind":"symbol","topicSections":[{"generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/SdfLayer\/IsMuted(_:)"],"title":"Type Methods"}],"metadata":{"symbolKind":"extension","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@Overlay","text":"Overlay","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@Overlay@N@SdfLayer","text":"SdfLayer","kind":"identifier"}],"title":"Overlay.SdfLayer","navigatorTitle":[{"kind":"identifier","text":"SdfLayer"}],"extendedModule":"C++","role":"symbol","externalID":"s:e:s:So7OverlayO8SdfLayerO7OpenUSDE7IsMutedySbSo3stdO3__1O0088basic_stringCCharstd__1char_traitsCCharstd__1allocatorCChar_cyHBywaEDexaCidvdFCgAayGjzaaVFZ","modules":[{"relatedModules":["C++"],"name":"OpenUSD"}],"roleHeading":"Extended Enumeration"},"sections":[],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"type":"topic","url":"\/documentation\/openusd\/overlay","fragments":[{"kind":"identifier","text":"Overlay"}],"title":"Overlay"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/SdfLayer/IsMuted(_:)":{"deprecated":true,"title":"IsMuted(_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsMuted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","kind":"typeIdentifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@string"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/SdfLayer\/IsMuted(_:)","role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/c++\/overlay\/sdflayer\/ismuted(_:)"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay":{"type":"topic","title":"Overlay","role":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"Overlay","preciseIdentifier":"c:@N@Overlay"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Overlay"}],"url":"\/documentation\/openusd\/c++\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/SdfLayer":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/SdfLayer","title":"Overlay.SdfLayer","url":"\/documentation\/openusd\/c++\/overlay\/sdflayer","kind":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@Overlay","kind":"identifier","text":"Overlay"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@Overlay@N@SdfLayer","kind":"identifier","text":"SdfLayer"}],"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SdfLayer"}]},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","title":"OpenUSD","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","type":"topic","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/C++":{"abstract":[],"type":"topic","url":"\/documentation\/openusd\/c++","role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++","title":"C++","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/SdfLayer":{"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/overlay\/sdflayer","type":"topic","fragments":[{"text":"SdfLayer","kind":"identifier"}],"abstract":[],"title":"SdfLayer","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfLayer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"kind":"identifier","text":"Overlay"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"kind":"identifier","text":"Overlay"}]}]}]}