{"topicSections":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/UsdPrimTypeInfoWrapper\/Equatable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","text":"Overlay","preciseIdentifier":"c:@N@Overlay"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","text":"UsdPrimTypeInfoWrapper","preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper"}]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/SwiftUsd\/s8CopyableP","doc:\/\/SwiftUsd\/SQ"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"kind":"symbol","metadata":{"title":"Overlay.UsdPrimTypeInfoWrapper","role":"symbol","roleHeading":"Extended Structure","navigatorTitle":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"extendedModule":"C++","externalID":"s:e:c:@N@Overlay@S@UsdPrimTypeInfoWrappers:SQ","modules":[{"name":"OpenUSD","relatedModules":["C++"]}],"symbolKind":"extension","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Overlay","preciseIdentifier":"c:@N@Overlay","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/UsdPrimTypeInfoWrapper"},"sections":[],"variants":[{"paths":["\/documentation\/openusd\/c++\/overlay\/usdprimtypeinfowrapper"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","type":"topic","url":"\/documentation\/openusd","abstract":[],"role":"collection"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"role":"symbol","url":"\/documentation\/openusd\/overlay","fragments":[{"kind":"identifier","text":"Overlay"}],"kind":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","type":"topic","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper","type":"topic","kind":"symbol","title":"struct UsdPrimTypeInfoWrapper","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper"},"doc://SwiftUsd/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/SwiftUsd\/SQ","type":"unresolvable"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/UsdPrimTypeInfoWrapper/Equatable-Implementations":{"url":"\/documentation\/openusd\/c++\/overlay\/usdprimtypeinfowrapper\/equatable-implementations","kind":"article","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/UsdPrimTypeInfoWrapper\/Equatable-Implementations"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/openusd\/c++\/overlay","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"Overlay","preciseIdentifier":"c:@N@Overlay"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Overlay"}],"title":"Overlay"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/UsdPrimTypeInfoWrapper":{"role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/openusd\/c++\/overlay\/usdprimtypeinfowrapper","title":"Overlay.UsdPrimTypeInfoWrapper","navigatorTitle":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@N@Overlay","text":"Overlay"},{"kind":"text","text":"."},{"kind":"identifier","preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper","text":"UsdPrimTypeInfoWrapper"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/UsdPrimTypeInfoWrapper"},"doc://SwiftUsd/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/SwiftUsd\/s8CopyableP","type":"unresolvable"},"doc://SwiftUsd/documentation/OpenUSD/C++":{"kind":"symbol","url":"\/documentation\/openusd\/c++","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++","abstract":[],"title":"C++","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace"},{"value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace"},{"value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add"},{"value":"UsdPrimTypeInfoWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/title","op":"replace"},{"value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/fragments","op":"replace"},{"value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/navigatorTitle","op":"replace"}]}]}