{"metadata":{"roleHeading":"Instance Method","externalID":"c:@N@Overlay@S@HgiWrapper@F@CreateGraphicsCmds#&1$@N@pxr@S@HgiGraphicsCmdsDesc#","symbolKind":"method","navigatorTitle":[{"text":"CreateGraphicsCmds","kind":"identifier"}],"role":"symbol","title":"CreateGraphicsCmds(_:)","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateGraphicsCmds","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@HgiGraphicsCmdsDesc","text":"HgiGraphicsCmdsDesc","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@S@unique_ptr>#$@N@pxr@S@HgiGraphicsCmds#$@N@std@N@__1@S@default_delete>#S0_","text":"HgiGraphicsCmdsUniquePtr","kind":"typeIdentifier"}],"modules":[{"name":"OpenUSD"}]},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateGraphicsCmds"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hgiwrapper\/creategraphicscmds"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hgiwrapper\/creategraphicscmds"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateGraphicsCmds","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"desc"},{"kind":"text","text":": "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HgiGraphicsCmdsDesc","preciseIdentifier":"c:@N@pxr@S@HgiGraphicsCmdsDesc"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@std@N@__1@S@unique_ptr>#$@N@pxr@S@HgiGraphicsCmds#$@N@std@N@__1@S@default_delete>#S0_","kind":"typeIdentifier","text":"HgiGraphicsCmdsUniquePtr"}],"platforms":["macOS"]}],"kind":"declarations"}],"references":{"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","abstract":[],"url":"\/documentation\/openusd","kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"text":"Overlay","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","title":"Overlay","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HgiWrapper"}],"title":"class HgiWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","url":"\/documentation\/openusd\/overlay\/hgiwrapper","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HgiWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreateGraphicsCmds":{"abstract":[],"type":"topic","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/creategraphicscmds","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateGraphicsCmds","title":"CreateGraphicsCmds(_:)","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateGraphicsCmds","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@HgiGraphicsCmdsDesc","text":"HgiGraphicsCmdsDesc","kind":"typeIdentifier"},{"text":")","kind":"text"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@std@N@__1@S@unique_ptr>#$@N@pxr@S@HgiGraphicsCmds#$@N@std@N@__1@S@default_delete>#S0_","kind":"typeIdentifier","text":"HgiGraphicsCmdsUniquePtr"}],"navigatorTitle":[{"text":"CreateGraphicsCmds","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"CreateGraphicsCmds"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CreateGraphicsCmds"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"CreateGraphicsCmds","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@unique_ptr>#$@N@pxr@S@HgiGraphicsCmds#$@N@std@N@__1@S@default_delete>#S0_","text":"HgiGraphicsCmdsUniquePtr"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateGraphicsCmds"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiGraphicsCmdsDesc","text":"HgiGraphicsCmdsDesc"},{"kind":"text","text":" & "},{"kind":"internalParam","text":"desc"},{"kind":"text","text":");"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"kind":"identifier","text":"Overlay"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"kind":"identifier","text":"Overlay"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/title","value":"HgiWrapper"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/fragments","value":[{"text":"HgiWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/navigatorTitle","value":[{"text":"HgiWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateGraphicsCmds\/title","value":"CreateGraphicsCmds"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateGraphicsCmds\/fragments","value":[{"text":"CreateGraphicsCmds","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateGraphicsCmds\/navigatorTitle","value":[{"kind":"identifier","text":"CreateGraphicsCmds"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}