{"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper"]]},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"OpenUSD"}],"role":"symbol","externalID":"c:@N@Overlay@S@HgiWrapper@F@CreateBlitCmds#","navigatorTitle":[{"text":"CreateBlitCmds","kind":"identifier"}],"title":"CreateBlitCmds()","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateBlitCmds","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Overlay","kind":"identifier","preciseIdentifier":"c:@N@Overlay"},{"text":".","kind":"text"},{"text":"HgiBlitCmds_SharedPtr","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@shared_ptr>#$@N@pxr@S@HgiBlitCmds"}],"symbolKind":"method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateBlitCmds"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@N@Overlay","text":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay"},{"kind":"text","text":"."},{"text":"HgiBlitCmds_SharedPtr","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@shared_ptr>#$@N@pxr@S@HgiBlitCmds"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateBlitCmds","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/openusd\/overlay\/hgiwrapper\/createblitcmds"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/hgiwrapper\/createblitcmds"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"kind":"identifier","text":"Overlay"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","title":"Overlay","type":"topic","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","type":"topic","role":"symbol","navigatorTitle":[{"text":"HgiWrapper","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiWrapper","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper","abstract":[],"kind":"symbol","title":"class HgiWrapper"},"doc://SwiftUsd/documentation/OpenUSD":{"role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","abstract":[],"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreateBlitCmds":{"title":"CreateBlitCmds()","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/createblitcmds","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateBlitCmds","kind":"symbol","navigatorTitle":[{"text":"CreateBlitCmds","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateBlitCmds"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@Overlay","kind":"identifier","text":"Overlay"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@std@N@__1@S@shared_ptr>#$@N@pxr@S@HgiBlitCmds","text":"HgiBlitCmds_SharedPtr","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"CreateBlitCmds","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"CreateBlitCmds"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"CreateBlitCmds","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"preciseIdentifier":"c:@N@Overlay","text":"Overlay","kind":"identifier","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay"},{"text":"::","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@S@shared_ptr>#$@N@pxr@S@HgiBlitCmds","text":"HgiBlitCmds_SharedPtr","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"CreateBlitCmds","kind":"identifier"},{"text":"();","kind":"text"}],"platforms":["macOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace","value":"Overlay"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace","value":[{"text":"Overlay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add","value":[{"kind":"identifier","text":"Overlay"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/title","op":"replace","value":"HgiWrapper"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/fragments","op":"replace","value":[{"text":"HgiWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/navigatorTitle","op":"replace","value":[{"text":"HgiWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateBlitCmds\/title","op":"replace","value":"CreateBlitCmds"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateBlitCmds\/fragments","op":"replace","value":[{"kind":"identifier","text":"CreateBlitCmds"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateBlitCmds\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CreateBlitCmds"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}