{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DestroyResourceBindings","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"resHandle","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"HgiResourceBindingsHandle","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiResourceBindings"},{"text":">","kind":"text"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"DestroyResourceBindings"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HgiResourceBindingsHandle","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiResourceBindings"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@N@Overlay@S@HgiWrapper@F@DestroyResourceBindings#*$@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiResourceBindings#","roleHeading":"Instance Method","title":"DestroyResourceBindings(_:)","role":"symbol","modules":[{"name":"OpenUSD"}],"navigatorTitle":[{"kind":"identifier","text":"DestroyResourceBindings"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyResourceBindings"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hgiwrapper\/destroyresourcebindings"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hgiwrapper\/destroyresourcebindings"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper"]]},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/DestroyResourceBindings":{"role":"symbol","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"DestroyResourceBindings"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HgiResourceBindingsHandle","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiResourceBindings"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"DestroyResourceBindings","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyResourceBindings","type":"topic","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/destroyresourcebindings","kind":"symbol","title":"DestroyResourceBindings(_:)"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiWrapper","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","type":"topic","title":"class HgiWrapper","navigatorTitle":[{"text":"HgiWrapper","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper"},"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","url":"\/documentation\/openusd","kind":"symbol","role":"collection","title":"OpenUSD","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"kind":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","type":"topic","role":"symbol","fragments":[{"text":"Overlay","kind":"identifier"}],"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"DestroyResourceBindings","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DestroyResourceBindings"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DestroyResourceBindings"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" "},{"kind":"identifier","text":"DestroyResourceBindings"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"::"},{"preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiResourceBindings","kind":"typeIdentifier","text":"HgiResourceBindingsHandle"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"resHandle"},{"kind":"text","text":");"}],"platforms":["macOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyResourceBindings\/title","op":"replace","value":"DestroyResourceBindings"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyResourceBindings\/fragments","op":"replace","value":[{"kind":"identifier","text":"DestroyResourceBindings"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyResourceBindings\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DestroyResourceBindings"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/title","op":"replace","value":"HgiWrapper"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/fragments","op":"replace","value":[{"text":"HgiWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"HgiWrapper"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace","value":"Overlay"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace","value":[{"text":"Overlay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add","value":[{"text":"Overlay","kind":"identifier"}]}]}]}