{"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation\/OriginLowerLeft","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","modules":[{"name":"OpenUSD"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OriginLowerLeft"}],"title":"OriginLowerLeft","externalID":"c:@N@Overlay@S@HioImageWrapper@E@ImageOriginLocation@OriginLowerLeft","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"OriginLowerLeft"}],"roleHeading":"Enumeration Case"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation"]]},"sections":[],"variants":[{"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/imageoriginlocation\/originlowerleft"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/imageoriginlocation\/originlowerleft"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OriginLowerLeft","kind":"identifier"}]}]}],"references":{"doc://SwiftUsd/documentation/OpenUSD":{"role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","abstract":[],"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/ImageOriginLocation/OriginLowerLeft":{"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/imageoriginlocation\/originlowerleft","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OriginLowerLeft"}],"navigatorTitle":[{"kind":"identifier","text":"OriginLowerLeft"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation\/OriginLowerLeft","title":"OriginLowerLeft","role":"symbol","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/ImageOriginLocation":{"kind":"symbol","title":"ImageOriginLocation","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation","type":"topic","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/imageoriginlocation","role":"symbol","navigatorTitle":[{"text":"ImageOriginLocation","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageOriginLocation","kind":"identifier"}],"abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"kind":"identifier","text":"Overlay"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","title":"Overlay","type":"topic","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HioImageWrapper","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","url":"\/documentation\/openusd\/overlay\/hioimagewrapper","role":"symbol","type":"topic","navigatorTitle":[{"text":"HioImageWrapper","kind":"identifier"}],"title":"class HioImageWrapper"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"OriginLowerLeft"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"OriginLowerLeft"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"OriginLowerLeft","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"OriginLowerLeft"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"OriginLowerLeft","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation~1OriginLowerLeft\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OriginLowerLeft"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation~1OriginLowerLeft\/fragments","op":"replace"},{"value":[{"text":"OriginLowerLeft","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation~1OriginLowerLeft\/navigatorTitle","op":"replace"},{"value":"ImageOriginLocation","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation\/title","op":"replace"},{"value":[{"text":"ImageOriginLocation","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation\/fragments","op":"replace"},{"value":[{"text":"ImageOriginLocation","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation\/navigatorTitle","op":"replace"},{"value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace"},{"value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add"},{"value":"HioImageWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title","op":"replace"},{"value":[{"kind":"identifier","text":"HioImageWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments","op":"replace"},{"value":[{"text":"HioImageWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}