{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation"]]},"kind":"symbol","metadata":{"roleHeading":"Enumeration Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OriginUpperLeft"}],"role":"symbol","modules":[{"name":"OpenUSD"}],"navigatorTitle":[{"kind":"identifier","text":"OriginUpperLeft"}],"externalID":"c:@N@Overlay@S@HioImageWrapper@E@ImageOriginLocation@OriginUpperLeft","symbolKind":"case","title":"OriginUpperLeft"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OriginUpperLeft","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation\/OriginUpperLeft","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/imageoriginlocation\/originupperleft"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/imageoriginlocation\/originupperleft"]}],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"kind":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","type":"topic","role":"symbol","fragments":[{"text":"Overlay","kind":"identifier"}],"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"role":"symbol","url":"\/documentation\/openusd\/overlay\/hioimagewrapper","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","navigatorTitle":[{"kind":"identifier","text":"HioImageWrapper"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HioImageWrapper"}],"title":"class HioImageWrapper","abstract":[],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/ImageOriginLocation/OriginUpperLeft":{"role":"symbol","navigatorTitle":[{"text":"OriginUpperLeft","kind":"identifier"}],"type":"topic","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/imageoriginlocation\/originupperleft","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OriginUpperLeft","kind":"identifier"}],"title":"OriginUpperLeft","kind":"symbol","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation\/OriginUpperLeft"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/ImageOriginLocation":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageOriginLocation","kind":"identifier"}],"navigatorTitle":[{"text":"ImageOriginLocation","kind":"identifier"}],"kind":"symbol","title":"ImageOriginLocation","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/imageoriginlocation"},"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","url":"\/documentation\/openusd","kind":"symbol","role":"collection","title":"OpenUSD","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OriginUpperLeft","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OriginUpperLeft","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"OriginUpperLeft","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"OriginUpperLeft","kind":"identifier"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"kind":"identifier","text":"Overlay"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"kind":"identifier","text":"Overlay"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title","value":"HioImageWrapper"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments","value":[{"text":"HioImageWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"HioImageWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation~1OriginUpperLeft\/title","value":"OriginUpperLeft"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation~1OriginUpperLeft\/fragments","value":[{"kind":"identifier","text":"OriginUpperLeft"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation~1OriginUpperLeft\/navigatorTitle","value":[{"text":"OriginUpperLeft","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation\/title","value":"ImageOriginLocation"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation\/fragments","value":[{"kind":"identifier","text":"ImageOriginLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation\/navigatorTitle","value":[{"text":"ImageOriginLocation","kind":"identifier"}]}]}]}