{"abstract":[{"text":"Learn how to use SwiftUsd with local\/existing OpenUSD binaries","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftusd\/buildinglocally"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/swiftusd\/buildinglocally"]}],"metadata":{"role":"article","title":"Building locally","roleHeading":"Article","modules":[{"name":"OpenUSD"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"seeAlsoSections":[{"generated":true,"anchor":"Technical-details","title":"Technical details","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DetectingOpenUSDFeatureFlags","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangesToOpenUSD"]}],"kind":"article","primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"Overview","type":"heading"},{"inlineContent":[{"type":"text","text":"SwiftUsd comes with pre-built OpenUSD binaries that make it easy to start using SwiftUsd without additional setup. To do so, follow the instructions in "},{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted","isActive":true},{"type":"text","text":" to add SwiftUsd as a remote package dependency to an Xcode project or Swift Package. However, if you want to use SwiftUsd with different Usd feature flags or on other platforms\/architectures, you can build OpenUSD to your specifications, and then create a Swift Package that lets you use your OpenUSD build in Swift."}],"type":"paragraph"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"Clone SwiftUsd","type":"text"}],"type":"paragraph"}]}]},{"syntax":"zsh","type":"codeListing","code":["git clone git@github.com:apple\/SwiftUsd.git ~\/SwiftUsd"]},{"start":2,"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Clone OpenUSD v25.08"}],"type":"paragraph"}]}]},{"syntax":"zsh","type":"codeListing","code":["git clone https:\/\/github.com\/PixarAnimationStudios\/OpenUSD.git ~\/SwiftUsd\/openusd-source","cd ~\/SwiftUsd\/openusd-source","git checkout v25.08"]},{"start":3,"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Apply ","type":"text"},{"type":"codeVoice","code":"openusd-source.patch"},{"text":" to it","type":"text"}]}]}]},{"syntax":"zsh","type":"codeListing","code":["cd ~\/SwiftUsd\/openusd-source","patch -p1 -i ~\/SwiftUsd\/openusd-patch.patch"]},{"start":4,"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Build OpenUSD for one more more platforms with feature flags of your choosing. These are the feature flags that SwiftUsd is built with by default:","type":"text"}]}]}]},{"syntax":"zsh","type":"codeListing","code":["cd ~\/SwiftUsd\/openusd-source","python3 build_scripts\/build_usd.py \\","    --embree \\","    --imageio \\","    --alembic \\","    --openvdb \\","    --no-python \\","    --ignore-homebrew \\","    --build-target native \\","    ~\/SwiftUsd\/openusd-builds\/macOS","","cd ~\/SwiftUsd\/openusd-source","python3 build_scripts\/build_usd.py \\","    --imageio \\","    --alembic \\","    --no-python \\","    --ignore-homebrew \\","    --build-target iOS \\","    ~\/SwiftUsd\/openusd-builds\/iOS"]},{"content":[{"inlineContent":[{"type":"text","text":"Custom feature flags are experimental, and may have some restrictions. For example, building with Python will not work on Apple platforms, building with additional plugins may not work for app-bundlable packages, and packaging multiple Usd builds with incompatible feature flags may not work."}],"type":"paragraph"}],"name":"Note","type":"aside","style":"note"},{"start":5,"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Run "},{"type":"codeVoice","code":"scripts\/make-swift-package.zsh"},{"type":"text","text":". Use the "},{"type":"codeVoice","code":"--generated-package-dir"},{"type":"text","text":" flag to create the custom SwiftUsd package at a specific location (defaults to the SwiftUsd repo cloned from git). Note: if making the swift package in place with the following command, remove "},{"type":"codeVoice","code":"swift-package"},{"type":"text","text":" before running "},{"type":"codeVoice","code":"make-swift-package"},{"type":"text","text":"."}],"type":"paragraph"}]}]},{"syntax":"zsh","type":"codeListing","code":["cd ~\/SwiftUsd",".\/scripts\/make-swift-package.zsh openusd-builds\/iOS openusd-builds\/macOS"]}]}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/BuildingLocally","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","type":"topic","url":"\/documentation\/openusd","abstract":[],"role":"collection"},"doc://SwiftUsd/documentation/SwiftUsd/DetectingOpenUSDFeatureFlags":{"kind":"article","url":"\/documentation\/swiftusd\/detectingopenusdfeatureflags","title":"Detecting OpenUSD feature flags","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DetectingOpenUSDFeatureFlags","abstract":[{"type":"text","text":"Learn how to detect OpenUSD feature flags"}],"type":"topic","role":"article"},"doc://SwiftUsd/documentation/SwiftUsd/ChangesToOpenUSD":{"kind":"article","role":"article","title":"Changes to OpenUSD","url":"\/documentation\/swiftusd\/changestoopenusd","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangesToOpenUSD","abstract":[{"text":"Learn about the changes this Swift Package makes to OpenUSD","type":"text"}],"type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/GettingStarted":{"abstract":[{"text":"Adding SwiftUsd to your project or package","type":"text"}],"role":"article","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted","url":"\/documentation\/swiftusd\/gettingstarted","title":"Getting Started with OpenUSD","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"generated":true,"title":"Technical details","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DetectingOpenUSDFeatureFlags","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangesToOpenUSD"],"anchor":"Technical-details"}],"path":"\/seeAlsoSections","op":"replace"}]}]}