{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftusd\/capabilities"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/swiftusd\/capabilities"]}],"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Capabilities","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Learn about the current capabilities of OpenUSD in Swift","type":"text"}],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"OpenUSD in Swift is currently evolving and may change in the future. Here are some key features currently supported:"}]},{"type":"heading","text":"Reference types in Swift","anchor":"Reference-types-in-Swift","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"UsdStage and SdfLayer are imported as classes in Swift and behave like classes written in Swift. When Swift passes a raw pointer to UsdStage or SdfLayer, Swift automatically increments or decrements the underlying reference count as needed, allowing Swift or C++ to influence the lifetime of the same UsdStage or SdfLayer."}]},{"type":"codeListing","syntax":"swift","code":["func makeTempStage() -> pxr.UsdStage {","    return Overlay.Dereference(pxr.UsdStage.CreateNew(\"\/tmp\/myStage.usda\", .LoadAll))","}","","func defineXform(_ stage: pxr.UsdStage, _ path: pxr.SdfPath) {","    stage.DefinePrim(path, .UsdGeomTokens.Xform)","}","","let stage = makeTempStage()","defineXform(stage, \"\/hello\")","let layer = Overlay.Dereference(stage.GetRootLayer())","layer.Save(false)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WhatIsAForeignReferenceType"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ForeignReferenceTypesAndSmartPointers"},{"type":"text","text":" for more information."}]},{"type":"aside","style":"warning","content":[{"inlineContent":[{"type":"text","text":"When working in Swift, do not use "},{"type":"codeVoice","code":"TfRefPtr.pointee"},{"type":"text","text":" or "},{"type":"codeVoice","code":"TfWeakPtr.pointee"},{"type":"text","text":" to dereference Pixar’s smart pointers, as the "},{"type":"codeVoice","code":"pointee"},{"type":"text","text":" property is unsafe. Use "},{"type":"codeVoice","code":"Overlay.Dereference(_:TfRefPtr)"},{"type":"text","text":" and "},{"type":"codeVoice","code":"Overlay.Dereference(_:TfWeakPtr)"},{"type":"text","text":" instead."}],"type":"paragraph"}],"name":"Warning"},{"type":"heading","text":"Swift protocol conformances","anchor":"Swift-protocol-conformances","level":3},{"type":"paragraph","inlineContent":[{"text":"Many OpenUSD types conform to one or more of the following protocols:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"code":"Equatable","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"Hashable","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"Identifiable","type":"codeVoice"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"CustomStringConvertible"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"ExpressibleByStringLiteral"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"ExpressibleByArrayLiteral"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Sequence"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"Sendable"}],"type":"paragraph"}]}]},{"type":"codeListing","syntax":"swift","code":["let token: pxr.TfToken = \"my custom token\" \/\/ TfToken conforms to ExpressibleByStringLiteral","var prims: Set<pxr.UsdPrim> = Set<pxr.UsdPrim>() \/\/ UsdPrim conforms to Hashable","let numbers: pxr.VtIntArray = [1, 2, 3] \/\/ VtIntArray conforms to ExpressibleByArrayLiteral"]},{"type":"heading","text":"TfNotice support","anchor":"TfNotice-support","level":3},{"type":"paragraph","inlineContent":[{"text":"Swift code can register for ","type":"text"},{"code":"TfNotice","type":"codeVoice"},{"text":" callbacks by using ","type":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-99j13","isActive":true,"overridingTitleInlineContent":[{"code":"pxr.TfNotice.Register","type":"codeVoice"}],"overridingTitle":"pxr.TfNotice.Register","type":"reference"},{"text":".","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["class StageWatcher {","    var stage: pxr.UsdStage","    var key: pxr.TfNotice.SwiftKey","","    init(stage: pxr.UsdStage) {","        self.stage = stage","","        key = pxr.TfNotice.Register(stage, pxr.UsdNotice.ObjectsChanged.self) { notice in","            print(\"Resynced: \\(notice.GetResyncedPaths())\")","            print(\"Changed info only: \\(notice.GetChangedInfoOnlyPaths())\")","        }","    }","    deinit {","        pxr.TfNotice.Revoke(key)","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For more information, see "},{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","isActive":true},{"type":"text","text":"."}]},{"type":"heading","text":"More details","anchor":"More-details","level":3},{"type":"paragraph","inlineContent":[{"text":"For details about supported features, see ","type":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DifferencesInSwift","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]}],"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DifferencesInSwift","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CurrentLimitations"],"anchor":"Essentials","generated":true}],"metadata":{"modules":[{"name":"OpenUSD"}],"role":"article","title":"Capabilities","roleHeading":"Article"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"references":{"doc://SwiftUsd/documentation/SwiftUsd/CurrentLimitations":{"abstract":[{"type":"text","text":"Learn about the current limitations of OpenUSD in Swift"}],"role":"article","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CurrentLimitations","url":"\/documentation\/swiftusd\/currentlimitations","title":"Current Limitations","type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/WhatIsAForeignReferenceType":{"kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WhatIsAForeignReferenceType","url":"\/documentation\/swiftusd\/whatisaforeignreferencetype","abstract":[{"text":"Learn about foreign reference types and how to use them","type":"text"}],"title":"What is a Foreign Reference Type?","type":"topic","role":"article"},"doc://SwiftUsd/documentation/SwiftUsd/GettingStarted":{"abstract":[{"text":"Adding SwiftUsd to your project or package","type":"text"}],"role":"article","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted","url":"\/documentation\/swiftusd\/gettingstarted","title":"Getting Started with OpenUSD","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:)-99j13":{"type":"topic","abstract":[{"text":"Register a listener as being interested in a TfNotice, regardless of sender.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:)-99j13","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-99j13","kind":"symbol","title":"Register(_:_:)"},"doc://SwiftUsd/documentation/SwiftUsd/DifferencesInSwift":{"role":"article","title":"Differences in Swift","url":"\/documentation\/swiftusd\/differencesinswift","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DifferencesInSwift","abstract":[{"text":"Learn how the OpenUSD API is different in Swift","type":"text"}],"type":"topic","kind":"article"},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","type":"topic","url":"\/documentation\/openusd","abstract":[],"role":"collection"},"doc://SwiftUsd/documentation/SwiftUsd/ForeignReferenceTypesAndSmartPointers":{"abstract":[{"text":"Learn about ","type":"text"},{"code":"pxr::TfRefPtr","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"pxr::TfWeakPtr","type":"codeVoice"},{"text":" in Swift","type":"text"}],"type":"topic","title":"Foreign Reference Types and Smart Pointers","role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ForeignReferenceTypesAndSmartPointers","kind":"article","url":"\/documentation\/swiftusd\/foreignreferencetypesandsmartpointers"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfNotice":{"type":"topic","url":"\/documentation\/swiftusd\/workingwithtfnotice","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","role":"article","abstract":[{"type":"text","text":"Learn how to use the TfNotice notification subsystem in Swift"}],"kind":"article","title":"Working with TfNotice"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DifferencesInSwift","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CurrentLimitations"],"title":"Essentials","anchor":"Essentials","generated":true}],"op":"replace","path":"\/seeAlsoSections"}]}]}