{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Changes to SwiftUsd"}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangeLog","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftusd\/changelog"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/swiftusd\/changelog"]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"kind":"article","metadata":{"title":"Change Log","roleHeading":"Article","role":"article","modules":[{"name":"OpenUSD"}]},"seeAlsoSections":[{"title":"About this repo","generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UpgradeChecklist","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ReleaseChecklist","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Miscellaneous"],"anchor":"About-this-repo"}],"primaryContentSections":[{"content":[{"text":"5.1.0","level":3,"anchor":"510","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Released 2025-08-27, based on OpenUSD v25.08","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"text":"Exposed some libWork APIs to Swift (see ","type":"text"},{"overridingTitle":"Using libWork","isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingLibWork","overridingTitleInlineContent":[{"type":"text","text":"Using libWork"}]},{"text":")","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Changed dylib bundling to pick up OpenEXR again for default macOS and iOS packages"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Cherry pick a commit from the OpenUSD dev branch to fix a memory footprint regression with UsdImagingGLEngine on macOS"}]}]}],"type":"unorderedList"},{"text":"5.0.2","level":3,"anchor":"502","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Released 2025-08-11, based on OpenUSD v25.08","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Fixed deployment error when using Xcode 26 beta 5 to target iOS devices"}]}]}],"type":"unorderedList"},{"text":"5.0.1","level":3,"anchor":"501","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Released 2025-08-07, based on OpenUSD v25.08","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Fixed compiler errors when using Xcode 26 beta 5 (17A5295f)"}]}]}],"type":"unorderedList"},{"text":"5.0.0","level":3,"anchor":"500","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Released 2025-08-06, based on OpenUSD v25.08","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Move from OpenUSD v25.05.01 to v25.08"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Added ImageIO to default macOS and iOS packages, and removed OpenImageIO from default macOS package"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Added OpenVDB to default macOS package"}],"type":"paragraph"}]}],"type":"unorderedList"},{"text":"4.1.1","level":3,"anchor":"411","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Released 2025-07-28, based on OpenUSD v25.05.01","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Moved to final repo URLs for public release"}]}]}],"type":"unorderedList"},{"text":"4.1.0","level":3,"anchor":"410","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Released 2025-07-18, based on OpenUSD v25.05.01","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added Alembic to default macOS and iOS packages"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Restructured make-swift-package, added clearer command line options"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Added better documentation for wrapped types"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Changed source\/generated\/StaticTokens to use ","type":"text"},{"code":"extern const* const","type":"codeVoice"},{"text":" variables for better Swift Concurrency safety","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"text":"4.0.0","level":3,"anchor":"400","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Released 2025-06-20, based on OpenUSD v25.05.01","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added ArResolverWrapper, UsdZipFileIteratorWrapper, UsdAppUtilsFrameRecorderWrapper"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Added Codable support for many Gf types, VtArray specializations, and a handful of other types","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Added UsdUtilsTimeCodeRange and GfMultiInterval conformances to Sequence and Codable","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Added Swift ","type":"text"},{"code":"pointee","type":"codeVoice"},{"text":" properties for SdfFooSpecHandle specializations","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added CustomStringConvertible implementation for TfErrorMarkWrapper.ErrorSequence"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Added ","type":"text"},{"code":"template <typename T> pxr::TfEnum Overlay::formTfEnum(T t)","type":"codeVoice"},{"text":" for Swift","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added more const-ref-returning wrapper methods"}]}]},{"content":[{"inlineContent":[{"text":"Added LICENSE.txt","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Fixed UsdTimeCode Codable implementation for PreTime values","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Improve HgiWrapper, HgiMetalWrapper"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Internal cleanup\/tidying","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Allowed codegen for types previously blocked by compiler bugs"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Simplified patch to ","type":"text"},{"code":"pxr\/base\/tf\/notice.h","type":"codeVoice"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Removed patch modifications for reading back depth from Hydra"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Removed UsdView, UsdTransportBar, and source\/SwiftUI","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Removed UsdZipFileWriterWrapper. Usd pxr.UsdZipFileWriter instead","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Remove support for old-style framework includes, i.e. ","type":"text"},{"type":"codeVoice","code":"#include <OpenUSD\/pxr\/usd\/usd\/stage.h>"},{"text":". Use ","type":"text"},{"type":"codeVoice","code":"#include \"pxr\/usd\/usd\/stage.h\""},{"text":" instead.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Removed dead deprecated code"}]}]}],"type":"unorderedList"},{"text":"3.0.1","level":3,"anchor":"301","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Released 2025-05-28, based on OpenUSD v25.05.01"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added OpenImageIO to default macOS package"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added warning about dylibs with non-relocatable dependencies to makes-swift-package"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Blocked pxr\/imaging\/hdEmbree headers from the modulemap for now"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Neatened changes to pxr\/usd\/usdMtlx\/utils.cpp"}]}]}],"type":"unorderedList"},{"text":"3.0.0","level":3,"anchor":"300","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Released 2025-05-20, based on OpenUSD v25.05.01"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Increased minimum supported Swift compiler version to Swift 6.1","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Added importing of non-movable "},{"code":"pxr::TfSingleton<T>","type":"codeVoice"},{"type":"text","text":" specializations as immortal reference types"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added support for dereferencing and checking validity of "},{"code":"pxr::TfRefPtr<const T>","type":"codeVoice"},{"type":"text","text":" and "},{"code":"pxr::TfWeakPtr<const T>","type":"codeVoice"},{"type":"text","text":" specializations"}]}]},{"content":[{"inlineContent":[{"text":"Upgraded the Embree Hydra Render Delegate to embree4","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Used new Swift 6.1 features to shrink the patch to OpenUSD","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"text":"2.1.1","level":3,"anchor":"211","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Released 2025-04-02, based on OpenUSD v25.02a"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Added the Embree Hydra Render Delegate to the macOS default Swift Package. (Note: Embree is not available on iOS)","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Fixed some documentation typos"}]}]}],"type":"unorderedList"},{"text":"2.1.0","level":3,"anchor":"210","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Released 2025-03-26, based on OpenUSD v25.02a"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Added ","type":"text"},{"code":"Overlay.withTfErrorMark(_:)","type":"codeVoice"},{"text":" to expose ","type":"text"},{"code":"pxr::TfErrorMark","type":"codeVoice"},{"text":" to Swift","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Added "},{"type":"codeVoice","code":"TF_ERROR"},{"type":"text","text":", "},{"type":"codeVoice","code":"#TF_VERIFY"},{"type":"text","text":", and others to expose Tf diagnostic functions\/macros to Swift"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Switched to ast-answerer for exposing TfStaticData token types (e.g. pxr::UsdGeomTokens->Cube)","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Added std::size_t fix from ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/PixarAnimationStudios\/OpenUSD\/pull\/3535"},{"text":" for prerelease compilers","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added std.string initializer from TfToken"}]}]}],"type":"unorderedList"},{"text":"2.0.1","level":3,"anchor":"201","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Released 2025-03-05, based on OpenUSD v25.02a"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Moved from OpenUSD v25.02 to OpenUSD v25.02a"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added back "},{"type":"codeVoice","code":"#include \"pxr\/pxr.h\""},{"type":"text","text":" includes. "},{"type":"codeVoice","code":"#include <OpenUSD\/pxr\/pxr.h>"},{"type":"text","text":" includes are still supported, but will be removed in a future release."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Rewrote "},{"type":"codeVoice","code":"scripts\/make-swift-package"},{"type":"text","text":" in Swift. Now has experimental support for Linux, non-app-bundled SwiftUsd packages, and multiple Usd feature flags"}]}]},{"content":[{"inlineContent":[{"text":"Simplified workaround for ","type":"text"},{"identifier":"rdar:\/\/117091104","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Added "},{"identifier":"https:\/\/github.com\/PixarAnimationStudios\/OpenUSD\/pull\/3553","isActive":true,"type":"reference"}],"type":"paragraph"}]}],"type":"unorderedList"},{"text":"2.0.0","level":3,"anchor":"200","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Released 2025-01-27, based on OpenUSD v25.02"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Move from OpenUSD v24.11 to OpenUSD v25.02"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Two small source-breaking changes to types ("},{"type":"codeVoice","code":"Overlay::SdfSubLayerProxyIteratorWrapper"},{"type":"text","text":", "},{"type":"codeVoice","code":"pxr.SdfPath.AbsoluteRootPath()"},{"type":"text","text":")"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Hide "},{"type":"codeVoice","code":"pxr.TfRefPtr<T>.pointee"},{"type":"text","text":" and "},{"type":"codeVoice","code":"pxr.TfWeakPtr<T>.pointee"},{"type":"text","text":" completely from Swift"}]}]}],"type":"unorderedList"},{"text":"1.2.0","level":3,"anchor":"120","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Released 2025-01-22, based on OpenUSD v24.11"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Exposed the "},{"code":"pxr.TfNotice.Register","type":"codeVoice"},{"type":"text","text":" notification subsystem to Swift"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Added "},{"type":"codeVoice","code":"protocol SwiftUsd.TfNoticeProtocol"},{"type":"text","text":" and conformed all types deriving from "},{"type":"codeVoice","code":"pxr::TfNotice"},{"type":"text","text":" to it"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Added ","type":"text"},{"code":"pxr::TfNotice::SwiftKey","type":"codeVoice"},{"text":", ","type":"text"},{"code":"pxr::TfNotice::SwiftKeys","type":"codeVoice"},{"text":" types for revoking Swift\/C++ listeners","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added "},{"type":"codeVoice","code":"pxr.TfNotice.NoticeCaster"},{"type":"text","text":" for conditionally downcasting notices during a "},{"type":"codeVoice","code":"pxr.TfNotice.Register"},{"type":"text","text":" callback"}]}]},{"content":[{"inlineContent":[{"text":"Marked types nested under ","type":"text"},{"code":"pxr::UsdNotice","type":"codeVoice"},{"text":" with ","type":"text"},{"code":"SWIFT_SELF_CONTAINED","type":"codeVoice"},{"text":" and wrapped their const-ref accessors","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"text":"1.1.0","level":3,"anchor":"110","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Released 2024-12-19, based on OpenUSD v24.11"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Added importing all ","type":"text"},{"code":"pxr::TfRefBase","type":"codeVoice"},{"text":" subclasses as ","type":"text"},{"code":"SWIFT_SHARED_REFERENCE","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added C++ API for safely moving raw pointers of "},{"code":"SWIFT_SHARED_REFERENCE","type":"codeVoice"},{"type":"text","text":" types across the Swift-Cxx language boundary"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added C++ umbrella header "},{"code":"<OpenUSD\/swiftUsd\/swiftUsd.h>","type":"codeVoice"},{"type":"text","text":" for API added by SwiftUsd usable in C++"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added casting between "},{"type":"codeVoice","code":"pxr::TfRefBase"},{"type":"text","text":" subclasses via "},{"type":"codeVoice","code":"as"},{"type":"text","text":" protocol method"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added "},{"code":"Bool.init(_:)","type":"codeVoice"},{"type":"text","text":" initializer for all "},{"code":"pxr::TfRefPtr<T>","type":"codeVoice"},{"type":"text","text":" and "},{"code":"pxr::TfWeakPtr<T>","type":"codeVoice"},{"type":"text","text":" specializations"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Applied "},{"identifier":"https:\/\/github.com\/PixarAnimationStudios\/OpenUSD\/pull\/3434","type":"reference","isActive":true},{"type":"text","text":" to allow building on newer Clangs"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Added workaround for ","type":"text"},{"isActive":true,"identifier":"rdar:\/\/140940883","type":"reference"}]}]}],"type":"unorderedList"},{"text":"1.0.1","level":3,"anchor":"101","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Released 2024-10-31, based on OpenUSD v24.11"}]},{"items":[{"content":[{"inlineContent":[{"text":"Add missing non-mutating function ","type":"text"},{"code":"pxr.UsdReferences.ClearReferences()","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Make "},{"code":"Overlay.SdfLayer.TraversalFunction","type":"codeVoice"},{"type":"text","text":" take its value by const-ref to work around "},{"identifier":"rdar:\/\/134358343","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Add ","type":"text"},{"code":"source\/SwiftOverlay\/__SwiftUsdBuildSettingsCheck.h","type":"codeVoice"},{"text":" to catch incorrect build settings","type":"text"}]}]}],"type":"unorderedList"},{"text":"1.0.0","level":3,"anchor":"100","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Released 2024-10-29, based on OpenUSD v24.11"}]},{"items":[{"content":[{"inlineContent":[{"text":"Move from OpenUSD v24.08 to OpenUSD v24.11","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Simplified openusd-patch.patch","type":"text"}]}]}],"type":"unorderedList"},{"text":"0.0.3","level":3,"anchor":"003","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Released 2024-10-23, based on OpenUSD v24.08","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Add documentation","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add Swift 6.1-compatible workaround for "},{"identifier":"rdar:\/\/136691907","type":"reference","isActive":true}]}]}],"type":"unorderedList"},{"text":"0.0.2","level":3,"anchor":"002","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Released 2024-10-21, based on OpenUSD v24.08"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Update code generation for C++ types imported as ~Copyable values"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Simplified openusd-patch.patch","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"text":"0.0.1","level":3,"anchor":"001","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Released 2024-10-07, based on OpenUSD v24.08"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Initial release","type":"text"}]}]}],"type":"unorderedList"}],"kind":"content"}],"sections":[],"references":{"rdar://134358343":{"url":"rdar:\/\/134358343","identifier":"rdar:\/\/134358343","title":"rdar:\/\/134358343: Second call to SdfLayer.Traverse function causes Sdf_PathNodeHandleImpl use-after-free","type":"link","titleInlineContent":[{"text":"rdar:\/\/134358343: Second call to SdfLayer.Traverse function causes Sdf_PathNodeHandleImpl use-after-free","type":"text"}]},"doc://SwiftUsd/documentation/SwiftUsd/CheatSheet":{"title":"Cheat sheet","kind":"article","url":"\/documentation\/swiftusd\/cheatsheet","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet","role":"article","abstract":[{"text":"Tips for advanced users modifying this repo","type":"text"}]},"https://github.com/PixarAnimationStudios/OpenUSD/pull/3553":{"url":"https:\/\/github.com\/PixarAnimationStudios\/OpenUSD\/pull\/3553","type":"link","title":"https:\/\/github.com\/PixarAnimationStudios\/OpenUSD\/pull\/3553","titleInlineContent":[{"text":"https:\/\/github.com\/PixarAnimationStudios\/OpenUSD\/pull\/3553","type":"text"}],"identifier":"https:\/\/github.com\/PixarAnimationStudios\/OpenUSD\/pull\/3553"},"doc://SwiftUsd/documentation/SwiftUsd/OngoingWork":{"abstract":[{"type":"text","text":"In-progress and future tasks for improving OpenUSD in Swift"}],"kind":"article","title":"Ongoing Work","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork","role":"article","url":"\/documentation\/swiftusd\/ongoingwork"},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","type":"topic","url":"\/documentation\/openusd","abstract":[],"role":"collection"},"doc://SwiftUsd/documentation/SwiftUsd/UsingLibWork":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingLibWork","kind":"article","url":"\/documentation\/swiftusd\/usinglibwork","role":"article","type":"topic","abstract":[{"type":"text","text":"Learn how to use the "},{"type":"codeVoice","code":"pxr::Work"},{"type":"text","text":" library for multithreading in Swift"}],"title":"Using libWork"},"doc://SwiftUsd/documentation/SwiftUsd/ReleaseChecklist":{"abstract":[{"type":"text","text":"Checklist for releasing new versions of SwiftUsd"}],"kind":"article","title":"Release Checklist","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ReleaseChecklist","role":"article","url":"\/documentation\/swiftusd\/releasechecklist"},"https://github.com/PixarAnimationStudios/OpenUSD/pull/3434":{"url":"https:\/\/github.com\/PixarAnimationStudios\/OpenUSD\/pull\/3434","identifier":"https:\/\/github.com\/PixarAnimationStudios\/OpenUSD\/pull\/3434","title":"https:\/\/github.com\/PixarAnimationStudios\/OpenUSD\/pull\/3434","type":"link","titleInlineContent":[{"text":"https:\/\/github.com\/PixarAnimationStudios\/OpenUSD\/pull\/3434","type":"text"}]},"https://github.com/PixarAnimationStudios/OpenUSD/pull/3535":{"url":"https:\/\/github.com\/PixarAnimationStudios\/OpenUSD\/pull\/3535","type":"link","title":"https:\/\/github.com\/PixarAnimationStudios\/OpenUSD\/pull\/3535","titleInlineContent":[{"text":"https:\/\/github.com\/PixarAnimationStudios\/OpenUSD\/pull\/3535","type":"text"}],"identifier":"https:\/\/github.com\/PixarAnimationStudios\/OpenUSD\/pull\/3535"},"doc://SwiftUsd/documentation/SwiftUsd/Miscellaneous":{"kind":"article","title":"Miscellaneous","type":"topic","abstract":[{"type":"text","text":"Miscellaneous details about this repo"}],"role":"article","url":"\/documentation\/swiftusd\/miscellaneous","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Miscellaneous"},"rdar://140940883":{"url":"rdar:\/\/140940883","identifier":"rdar:\/\/140940883","title":"rdar:\/\/140940883: Swift calling Swift subscript across module boundary in Release accesses uninitialized memory (C++ interop)","type":"link","titleInlineContent":[{"text":"rdar:\/\/140940883: Swift calling Swift subscript across module boundary in Release accesses uninitialized memory (C++ interop)","type":"text"}]},"doc://SwiftUsd/documentation/SwiftUsd/UpgradeChecklist":{"kind":"article","title":"Upgrade Checklist","type":"topic","abstract":[{"type":"text","text":"Checklist for upgrading SwiftUsd to be based on a new OpenUSD version"}],"role":"article","url":"\/documentation\/swiftusd\/upgradechecklist","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UpgradeChecklist"},"rdar://136691907":{"url":"rdar:\/\/136691907","type":"link","title":"rdar:\/\/136691907: Linker error in Release because std::__1::__voidify and C++ inline functions are missing","titleInlineContent":[{"text":"rdar:\/\/136691907: Linker error in Release because std::__1::__voidify and C++ inline functions are missing","type":"text"}],"identifier":"rdar:\/\/136691907"},"rdar://117091104":{"url":"rdar:\/\/117091104","identifier":"rdar:\/\/117091104","title":"rdar:\/\/117091104: Swift overspecializes templates, causing an error that C++ avoids (Usd v23.11rc-1)","type":"link","titleInlineContent":[{"text":"rdar:\/\/117091104: Swift overspecializes templates, causing an error that C++ avoids (Usd v23.11rc-1)","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"anchor":"About-this-repo","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UpgradeChecklist","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ReleaseChecklist","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Miscellaneous"],"title":"About this repo","generated":true}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}