{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"kind":"article","abstract":[{"text":"Tips for advanced users modifying this repo","type":"text"}],"variants":[{"paths":["\/documentation\/swiftusd\/cheatsheet"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/cheatsheet"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"OpenUSD"}],"role":"article","roleHeading":"Article","title":"Cheat sheet"},"seeAlsoSections":[{"title":"About this repo","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangeLog","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UpgradeChecklist","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ReleaseChecklist","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Miscellaneous"],"anchor":"About-this-repo","generated":true}],"primaryContentSections":[{"content":[{"type":"heading","anchor":"Overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"This page contains some useful Terminal commands for working on this repo. If you’re just trying to use OpenUSD in Swift, the information here won’t be helpful. Most users should ignore this page.","type":"text"}]},{"type":"heading","anchor":"Documentation","text":"Documentation","level":3},{"type":"paragraph","inlineContent":[{"code":"swift package generate-documentation","type":"codeVoice"},{"text":" runs into issues with SwiftUsd. (See ","type":"text"},{"identifier":"https:\/\/github.com\/swiftlang\/swift-docc-plugin\/issues\/80","isActive":true,"type":"reference"},{"text":".) Instead, ","type":"text"},{"code":"SwiftUsd","type":"codeVoice"},{"text":" provides its own workflow for building, previewing, and publishing documentation.","type":"text"}]},{"type":"heading","anchor":"Building-documentation","text":"Building documentation","level":4},{"type":"paragraph","inlineContent":[{"type":"text","text":"To build the DocC symbol graphs, run:"}]},{"code":["cd ~\/SwiftUsd","swift run --package-path scripts\/docc build-documentation"],"type":"codeListing","syntax":"zsh"},{"inlineContent":[{"type":"text","text":"This will take several minutes, and create a "},{"type":"codeVoice","code":"Package.resolved"},{"type":"text","text":" file, a "},{"type":"codeVoice","code":".build"},{"type":"text","text":" directory, and a "},{"type":"codeVoice","code":".symbol-graphs"},{"type":"text","text":" directory."}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Note, even if ","type":"text"},{"code":"swift package generate-documentation","type":"codeVoice"},{"text":" starts working, using ","type":"text"},{"code":"scripts\/docc build-documentation","type":"codeVoice"},{"text":" is still the recommended approach, because it also manipulates the symbol graphs to look nicer for Swift-Cxx interop (e.g. hiding the long Pixar internal namespace, hiding C++ DocC workarounds) in addition to symlinking generated markdown files into the documentation catalog.","type":"text"}]}],"style":"note","name":"Note","type":"aside"},{"text":"Previewing documentation","anchor":"Previewing-documentation","type":"heading","level":4},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Prerequisite: You already ran ","type":"text"},{"type":"codeVoice","code":"build-documentation"},{"type":"text","text":"."},{"type":"text","text":"\n"},{"type":"text","text":"To preview the DocC documentation locally, run:"}]}]}]},{"code":["cd ~\/SwiftUsd","swift run --package-path scripts\/docc preview-documentation"],"syntax":"zsh","type":"codeListing"},{"inlineContent":[{"type":"text","text":"This script will automatically open a window in your web browser viewing the locally hosted documentation. You can modify the markdown files in the documentation catalog and the preview will automatically update. (You may need to refresh the page, and the updating may take a few seconds.)"}],"type":"paragraph"},{"text":"Publishing documentation","anchor":"Publishing-documentation","type":"heading","level":4},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Prerequisite: You already ran "},{"type":"codeVoice","code":"build-documentation"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Prerequisite: You already ran "},{"code":"preview-documentation","type":"codeVoice"},{"type":"text","text":" and there were no documentation warnings or errors."},{"type":"text","text":"\n"},{"type":"text","text":"To update the published documentation, run:"}],"type":"paragraph"}]}]},{"code":["cd ~\/SwiftUsd","swift run --package-path scripts\/docc update-documentation"],"syntax":"zsh","type":"codeListing"},{"inlineContent":[{"text":"This script will update the ","type":"text"},{"type":"codeVoice","code":"SwiftUsd.doccarchive"},{"text":" that is viewable locally in Xcode, as well as the ","type":"text"},{"type":"codeVoice","code":"docs"},{"text":" directory that powers the online documentation hosted at ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/apple.github.io\/SwiftUsd\/documentation\/openusd\/"},{"text":".","type":"text"}],"type":"paragraph"},{"text":"Patches","anchor":"Patches","type":"heading","level":3},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Prerequisite: "},{"type":"codeVoice","code":"~\/OpenUSD"},{"type":"text","text":" is an unmodified version of OpenUSD."}]}]},{"content":[{"inlineContent":[{"text":"Prerequisite: You’ve already cloned OpenUSD to ","type":"text"},{"code":"SwiftUsd\/openusd-source","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}]},{"anchor":"Generating-a-new-patch","type":"heading","level":4,"text":"Generating a new patch"},{"type":"codeListing","code":["cd ~\/SwiftUsd\/openusd-source","diff -Nura \\","    --exclude .git --exclude '*.orig' \\","    --exclude .DS_Store --exclude '*.pyc' \\","    ~\/OpenUSD . > ~\/Desktop\/wip.patch"],"syntax":"zsh"},{"anchor":"Viewing-the-list-of-files-changed-from-OpenUSD","type":"heading","level":4,"text":"Viewing the list of files changed from OpenUSD"},{"type":"codeListing","code":["cd ~\/SwiftUsd\/openusd-source","diff -Nqra \\","    --exclude .git --exclude '*.orig' \\","    --exclude .DS_Store --exclude '*.pyc' \\","    ~\/OpenUSD ."],"syntax":"zsh"},{"anchor":"Comparing-the-differences-between-an-old-patch-and-a-new-patch","type":"heading","level":4,"text":"Comparing the differences between an old patch and a new patch"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Prerequisite: You generated a new patch at "},{"type":"codeVoice","code":"~\/Desktop\/wip.patch"}]}]}]},{"type":"codeListing","code":["diff -ua \\","    -I '^(diff |\\+\\+\\+ |--- |@@ |\\ | )' \\","    ~\/SwiftUsd\/openusd-patch.patch ~\/Desktop\/wip.patch"],"syntax":"zsh"},{"anchor":"Reviewing-commit-changes","type":"heading","level":3,"text":"Reviewing commit changes"},{"type":"codeListing","code":["git status \":(exclude)docs\/*\" \":(exclude)SwiftUsd.doccarchive\/*\" \":(exclude)swift-package\/XCFrameworks\/*.xcframework\/Info.plist\"","git diff \":(exclude)docs\/*\" \":(exclude)SwiftUsd.doccarchive\/*\" \":(exclude)swift-package\/XCFrameworks\/*.xcframework\/Info.plist\""],"syntax":"zsh"},{"anchor":"Grep","type":"heading","level":3,"text":"Grep"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Grepping for text in the entire package will likely pull up useless matches from various hidden directories and build artifacts. To get more relevant matches, use something like this:"}]},{"type":"codeListing","code":["grep SEARCHPATTERN -r scripts source SwiftUsd.docc Package.swift --exclude-dir={.docc-build,.build}"],"syntax":"zsh"}],"kind":"content"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://SwiftUsd/documentation/SwiftUsd/ChangeLog":{"type":"topic","abstract":[{"text":"Changes to SwiftUsd","type":"text"}],"kind":"article","url":"\/documentation\/swiftusd\/changelog","role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangeLog","title":"Change Log"},"doc://SwiftUsd/documentation/SwiftUsd/UpgradeChecklist":{"role":"article","kind":"article","type":"topic","url":"\/documentation\/swiftusd\/upgradechecklist","abstract":[{"text":"Checklist for upgrading SwiftUsd to be based on a new OpenUSD version","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UpgradeChecklist","title":"Upgrade Checklist"},"doc://SwiftUsd/documentation/SwiftUsd/ReleaseChecklist":{"kind":"article","url":"\/documentation\/swiftusd\/releasechecklist","role":"article","type":"topic","abstract":[{"type":"text","text":"Checklist for releasing new versions of SwiftUsd"}],"title":"Release Checklist","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ReleaseChecklist"},"doc://SwiftUsd/documentation/SwiftUsd/Miscellaneous":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Miscellaneous","url":"\/documentation\/swiftusd\/miscellaneous","type":"topic","abstract":[{"text":"Miscellaneous details about this repo","type":"text"}],"title":"Miscellaneous","role":"article","kind":"article"},"doc://SwiftUsd/documentation/SwiftUsd/OngoingWork":{"title":"Ongoing Work","abstract":[{"type":"text","text":"In-progress and future tasks for improving OpenUSD in Swift"}],"kind":"article","url":"\/documentation\/swiftusd\/ongoingwork","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork","type":"topic","role":"article"},"https://apple.github.io/SwiftUsd/documentation/openusd/":{"type":"link","title":"https:\/\/apple.github.io\/SwiftUsd\/documentation\/openusd\/","titleInlineContent":[{"type":"text","text":"https:\/\/apple.github.io\/SwiftUsd\/documentation\/openusd\/"}],"identifier":"https:\/\/apple.github.io\/SwiftUsd\/documentation\/openusd\/","url":"https:\/\/apple.github.io\/SwiftUsd\/documentation\/openusd\/"},"https://github.com/swiftlang/swift-docc-plugin/issues/80":{"identifier":"https:\/\/github.com\/swiftlang\/swift-docc-plugin\/issues\/80","title":"here","type":"link","titleInlineContent":[{"type":"text","text":"here"}],"url":"https:\/\/github.com\/swiftlang\/swift-docc-plugin\/issues\/80"},"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","url":"\/documentation\/openusd","kind":"symbol","role":"collection","title":"OpenUSD","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"anchor":"About-this-repo","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangeLog","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UpgradeChecklist","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ReleaseChecklist","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Miscellaneous"],"generated":true,"title":"About this repo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}