{"metadata":{"title":"Codable protocol conformances","modules":[{"name":"OpenUSD"}],"role":"article","roleHeading":"Article"},"variants":[{"paths":["\/documentation\/swiftusd\/codable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/codable"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"These types conform to "},{"type":"codeVoice","code":"Codable"},{"type":"text","text":" in Swift."}],"type":"paragraph"},{"anchor":"Tf-types","text":"Tf types","type":"heading","level":3},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfToken"}]}]}]},{"anchor":"Gf-types","text":"Gf types","type":"heading","level":3},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfBBox3d","isActive":true}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfCamera","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfCamera\/Projection","type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfColor","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfColorSpace"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfDualQuatd","type":"reference","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfDualQuatf"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfDualQuath"}]}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfFrustum"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfFrustum\/ProjectionType","type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/pxr_half\/half"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfInterval"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfLine","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfLine2d","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfLineSeg","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix2d"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix2f","isActive":true,"type":"reference"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix3d","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix3f"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix4d","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix4f"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMultiInterval","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfPlane","type":"reference","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfQuatd","isActive":true}]}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfQuaternion"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfQuatf"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfQuath","type":"reference"}]}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfRange1d","type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfRange1f","isActive":true,"type":"reference"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfRange2d","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfRange2f","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfRange3d","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfRange3f","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfRay"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfRect2i"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfRotation","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfSize2","type":"reference","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfSize3","type":"reference"}]}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfTransform"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec2d","type":"reference"}]}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec2f"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec2h"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec2i","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec3d"}]}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec3f"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec3h","type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec3i"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec4d","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec4f"}]}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec4h"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec4i","isActive":true,"type":"reference"}]}]}]},{"text":"VtArray specializations","anchor":"VtArray-specializations","type":"heading","level":3},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfDualQuatd_","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfDualQuatf_","type":"reference"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfDualQuath_","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.pxr_half.half_","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfInterval_"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfMatrix2d_","isActive":true}]}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfMatrix2f_","type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfMatrix3d_"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfMatrix3f_"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfMatrix4d_","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfMatrix4f_"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfQuatd_","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfQuaternion_","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfQuatf_","type":"reference","isActive":true}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfQuath_","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfRange1d_"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfRange1f_"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfRange2d_","type":"reference","isActive":true}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfRange2f_","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfRange3d_","isActive":true}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfRange3f_","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfRect2i_"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec2d_","type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec2f_","isActive":true,"type":"reference"}]}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec2h_"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec2i_","type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec3d_"}]}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec3f_","type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec3h_","type":"reference","isActive":true}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec3i_","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec4d_","type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec4f_","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec4h_"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec4i_","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.TfToken_"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CBool_","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CChar_"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CDouble_","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CFloat_"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CLongLong_","type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CInt_"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CShort_","type":"reference","isActive":true}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_std.__1.basic_string_CChar,_std.__1.char_traits_CChar_,_std.__1.allocator_CChar___","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CUnsignedLongLong_"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CUnsignedChar_","type":"reference"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CUnsignedInt_","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CUnsignedShort_","type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.SdfAssetPath_","isActive":true,"type":"reference"}],"type":"paragraph"}]}]},{"text":"Ar types","anchor":"Ar-types","type":"heading","level":3},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/ArTimestamp","type":"reference","isActive":true}],"type":"paragraph"}]}]},{"text":"Sdf types","anchor":"Sdf-types","type":"heading","level":3},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/SdfAssetPath","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/SdfPath","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/SdfTimeCode"}]}]}]},{"text":"Usd types","anchor":"Usd-types","type":"heading","level":3},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdTimeCode"}],"type":"paragraph"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Codable"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"seeAlsoSections":[{"title":"Protocol conformances","anchor":"Protocol-conformances","generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Equatable","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Comparable","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Hashable","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CustomStringConvertible","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Sendable"]}],"references":{"doc://SwiftUsd/documentation/SwiftUsd/Sendable":{"url":"\/documentation\/swiftusd\/sendable","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Sendable","type":"topic","role":"article","title":"Sendable protocol conformances","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/ArTimestamp":{"title":"pxr.ArTimestamp","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/ArTimestamp","navigatorTitle":[{"text":"ArTimestamp","kind":"identifier"}],"kind":"symbol","abstract":[],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"ArTimestamp","kind":"identifier","preciseIdentifier":"c:@N@pxr@S@ArTimestamp"}],"url":"\/documentation\/openusd\/c++\/pxr\/artimestamp","role":"symbol","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfVec4i":{"url":"\/documentation\/openusd\/c++\/pxr\/gfvec4i","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec4i","navigatorTitle":[{"text":"GfVec4i","kind":"identifier"}],"type":"topic","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@GfVec4i","text":"GfVec4i","kind":"identifier"}],"role":"symbol","title":"pxr.GfVec4i","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfRange2f":{"type":"topic","navigatorTitle":[{"text":"GfRange2f","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfRange2f","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"GfRange2f","kind":"identifier","preciseIdentifier":"c:@N@pxr@S@GfRange2f"}],"url":"\/documentation\/openusd\/c++\/pxr\/gfrange2f","title":"pxr.GfRange2f"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfRotation":{"navigatorTitle":[{"kind":"identifier","text":"GfRotation"}],"url":"\/documentation\/openusd\/c++\/pxr\/gfrotation","kind":"symbol","title":"pxr.GfRotation","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"identifier","text":"GfRotation","preciseIdentifier":"c:@N@pxr@S@GfRotation"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfRotation"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfDualQuatd_":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.GfDualQuatd>"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfDualQuatd_","kind":"symbol","title":"pxr.VtArray<pxr.GfDualQuatd>","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@VtDualQuatdArray","text":"VtDualQuatdArray"}],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfdualquatd_","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfDualQuath_":{"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@VtDualQuathArray","text":"VtDualQuathArray"}],"navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.GfDualQuath>"}],"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfdualquath_","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfDualQuath_","title":"pxr.VtArray<pxr.GfDualQuath>"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfVec4d":{"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GfVec4d"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec4d","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@GfVec4d","kind":"identifier","text":"GfVec4d"}],"kind":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/gfvec4d","title":"pxr.GfVec4d","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfFrustum/ProjectionType":{"type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/gffrustum\/projectiontype","kind":"symbol","abstract":[],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier"},{"text":".","kind":"text"},{"text":"GfFrustum","preciseIdentifier":"c:@N@pxr@S@GfFrustum","kind":"identifier"},{"text":".","kind":"text"},{"kind":"identifier","text":"ProjectionType","preciseIdentifier":"c:@N@pxr@S@GfFrustum@E@ProjectionType"}],"title":"pxr.GfFrustum.ProjectionType","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfFrustum\/ProjectionType","navigatorTitle":[{"kind":"identifier","text":"ProjectionType"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfBBox3d":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfBBox3d","abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/gfbbox3d","role":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@GfBBox3d","kind":"identifier","text":"GfBBox3d"}],"navigatorTitle":[{"kind":"identifier","text":"GfBBox3d"}],"title":"pxr.GfBBox3d","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfPlane":{"title":"pxr.GfPlane","abstract":[],"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@GfPlane","kind":"identifier","text":"GfPlane"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfPlane","navigatorTitle":[{"kind":"identifier","text":"GfPlane"}],"kind":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/gfplane","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/SdfAssetPath":{"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"SdfAssetPath","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/SdfAssetPath","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"SdfAssetPath","kind":"identifier","preciseIdentifier":"c:@N@pxr@S@SdfAssetPath"}],"title":"pxr.SdfAssetPath","type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/sdfassetpath","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfMultiInterval":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMultiInterval","kind":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/gfmultiinterval","type":"topic","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@GfMultiInterval","kind":"identifier","text":"GfMultiInterval"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GfMultiInterval"}],"role":"symbol","title":"pxr.GfMultiInterval"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfDualQuatf_":{"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfdualquatf_","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfDualQuatf_","navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.GfDualQuatf>"}],"type":"topic","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"VtDualQuatfArray","preciseIdentifier":"c:@N@pxr@VtDualQuatfArray"}],"role":"symbol","title":"pxr.VtArray<pxr.GfDualQuatf>","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfMatrix2f":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GfMatrix2f"}],"abstract":[],"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@GfMatrix2f","kind":"identifier","text":"GfMatrix2f"}],"role":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/gfmatrix2f","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix2f","type":"topic","title":"pxr.GfMatrix2f"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfRange1f_":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfRange1f_","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@VtRange1fArray","text":"VtRange1fArray"}],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfrange1f_","role":"symbol","abstract":[],"title":"pxr.VtArray<pxr.GfRange1f>","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.GfRange1f>"}],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfVec4f":{"url":"\/documentation\/openusd\/c++\/pxr\/gfvec4f","role":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@GfVec4f","kind":"identifier","text":"GfVec4f"}],"navigatorTitle":[{"kind":"identifier","text":"GfVec4f"}],"kind":"symbol","type":"topic","title":"pxr.GfVec4f","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec4f"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.TfToken_":{"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.TfToken_","navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.TfToken>"}],"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"VtTokenArray","preciseIdentifier":"c:@N@pxr@VtTokenArray"}],"title":"pxr.VtArray<pxr.TfToken>","role":"symbol","abstract":[],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.tftoken_"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_CBool_":{"role":"symbol","abstract":[],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_cbool_","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CBool_","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"VtBoolArray","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@VtBoolArray"}],"navigatorTitle":[{"text":"VtArray<CBool>","kind":"identifier"}],"kind":"symbol","title":"pxr.VtArray<CBool>","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/SdfTimeCode":{"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/SdfTimeCode","type":"topic","abstract":[],"title":"pxr.SdfTimeCode","url":"\/documentation\/openusd\/c++\/pxr\/sdftimecode","navigatorTitle":[{"kind":"identifier","text":"SdfTimeCode"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"identifier","text":"SdfTimeCode","preciseIdentifier":"c:@N@pxr@S@SdfTimeCode"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfMatrix3d":{"title":"pxr.GfMatrix3d","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"identifier","preciseIdentifier":"c:@N@pxr@S@GfMatrix3d","text":"GfMatrix3d"}],"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GfMatrix3d"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix3d","url":"\/documentation\/openusd\/c++\/pxr\/gfmatrix3d","type":"topic","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_CDouble_":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CDouble_","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"VtArray<CDouble>"}],"title":"pxr.VtArray<CDouble>","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@VtDoubleArray","kind":"typeIdentifier","text":"VtDoubleArray"}],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_cdouble_"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfVec4f_":{"type":"topic","role":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfvec4f_","title":"pxr.VtArray<pxr.GfVec4f>","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec4f_","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"VtVec4fArray","preciseIdentifier":"c:@N@pxr@VtVec4fArray","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"VtArray<pxr.GfVec4f>","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfVec4d_":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"VtVec4dArray","preciseIdentifier":"c:@N@pxr@VtVec4dArray"}],"navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.GfVec4d>"}],"abstract":[],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfvec4d_","title":"pxr.VtArray<pxr.GfVec4d>","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec4d_"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfDualQuath":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfDualQuath","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"GfDualQuath","kind":"identifier"}],"url":"\/documentation\/openusd\/c++\/pxr\/gfdualquath","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@GfDualQuath","text":"GfDualQuath","kind":"identifier"}],"title":"pxr.GfDualQuath","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfQuath":{"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@GfQuath","kind":"identifier","text":"GfQuath"}],"title":"pxr.GfQuath","type":"topic","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfQuath","abstract":[],"url":"\/documentation\/openusd\/c++\/pxr\/gfquath","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GfQuath"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfVec3i":{"kind":"symbol","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/gfvec3i","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec3i","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"identifier","preciseIdentifier":"c:@N@pxr@S@GfVec3i","text":"GfVec3i"}],"title":"pxr.GfVec3i","navigatorTitle":[{"kind":"identifier","text":"GfVec3i"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfRange2d_":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.GfRange2d>"}],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfrange2d_","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@VtRange2dArray","text":"VtRange2dArray"}],"title":"pxr.VtArray<pxr.GfRange2d>","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfRange2d_","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfRect2i_":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfRect2i_","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.GfRect2i>"}],"abstract":[],"kind":"symbol","title":"pxr.VtArray<pxr.GfRect2i>","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfrect2i_","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"VtRect2iArray","preciseIdentifier":"c:@N@pxr@VtRect2iArray"}],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfVec2h":{"title":"pxr.GfVec2h","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@GfVec2h","text":"GfVec2h","kind":"identifier"}],"role":"symbol","abstract":[],"navigatorTitle":[{"text":"GfVec2h","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec2h","type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/gfvec2h","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfLine":{"abstract":[],"url":"\/documentation\/openusd\/c++\/pxr\/gfline","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfLine","type":"topic","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"identifier","text":"GfLine","preciseIdentifier":"c:@N@pxr@S@GfLine"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GfLine"}],"title":"pxr.GfLine"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfVec2f":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec2f","navigatorTitle":[{"text":"GfVec2f","kind":"identifier"}],"url":"\/documentation\/openusd\/c++\/pxr\/gfvec2f","kind":"symbol","type":"topic","title":"pxr.GfVec2f","role":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@GfVec2f","text":"GfVec2f","kind":"identifier"}],"abstract":[]},"doc://SwiftUsd/documentation/SwiftUsd/CustomStringConvertible":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CustomStringConvertible","url":"\/documentation\/swiftusd\/customstringconvertible","kind":"article","abstract":[],"role":"article","type":"topic","title":"CustomStringConvertible protocol conformances"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfLine2d":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfLine2d","title":"pxr.GfLine2d","url":"\/documentation\/openusd\/c++\/pxr\/gfline2d","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"identifier","text":"GfLine2d","preciseIdentifier":"c:@N@pxr@S@GfLine2d"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GfLine2d"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfRange3d_":{"type":"topic","abstract":[],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"VtRange3dArray","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@VtRange3dArray"}],"kind":"symbol","title":"pxr.VtArray<pxr.GfRange3d>","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfRange3d_","navigatorTitle":[{"text":"VtArray<pxr.GfRange3d>","kind":"identifier"}],"role":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfrange3d_"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfVec3d_":{"kind":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"VtVec3dArray","preciseIdentifier":"c:@N@pxr@VtVec3dArray"}],"type":"topic","abstract":[],"role":"symbol","title":"pxr.VtArray<pxr.GfVec3d>","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec3d_","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfvec3d_","navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.GfVec3d>"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfInterval":{"url":"\/documentation\/openusd\/c++\/pxr\/gfinterval","type":"topic","title":"pxr.GfInterval","navigatorTitle":[{"kind":"identifier","text":"GfInterval"}],"role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@GfInterval","kind":"identifier","text":"GfInterval"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfInterval"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfRay":{"kind":"symbol","type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/gfray","role":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"GfRay","kind":"identifier","preciseIdentifier":"c:@N@pxr@S@GfRay"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfRay","title":"pxr.GfRay","navigatorTitle":[{"text":"GfRay","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfRange3f":{"title":"pxr.GfRange3f","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"GfRange3f","kind":"identifier","preciseIdentifier":"c:@N@pxr@S@GfRange3f"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfRange3f","role":"symbol","type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/gfrange3f","abstract":[],"navigatorTitle":[{"text":"GfRange3f","kind":"identifier"}],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfCamera":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfCamera","abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/gfcamera","title":"pxr.GfCamera","navigatorTitle":[{"text":"GfCamera","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@GfCamera","text":"GfCamera","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfVec3d":{"role":"symbol","title":"pxr.GfVec3d","abstract":[],"url":"\/documentation\/openusd\/c++\/pxr\/gfvec3d","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec3d","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"identifier","preciseIdentifier":"c:@N@pxr@S@GfVec3d","text":"GfVec3d"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GfVec3d"}],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfVec2h_":{"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfvec2h_","navigatorTitle":[{"text":"VtArray<pxr.GfVec2h>","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"VtVec2hArray","preciseIdentifier":"c:@N@pxr@VtVec2hArray","kind":"typeIdentifier"}],"abstract":[],"kind":"symbol","title":"pxr.VtArray<pxr.GfVec2h>","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec2h_"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfMatrix2f_":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfMatrix2f_","title":"pxr.VtArray<pxr.GfMatrix2f>","navigatorTitle":[{"text":"VtArray<pxr.GfMatrix2f>","kind":"identifier"}],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfmatrix2f_","role":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@VtMatrix2fArray","text":"VtMatrix2fArray","kind":"typeIdentifier"}],"abstract":[],"kind":"symbol","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfQuatf_":{"role":"symbol","type":"topic","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"VtQuatfArray","preciseIdentifier":"c:@N@pxr@VtQuatfArray","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"VtArray<pxr.GfQuatf>","kind":"identifier"}],"title":"pxr.VtArray<pxr.GfQuatf>","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfquatf_","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfQuatf_","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_CShort_":{"title":"pxr.VtArray<CShort>","type":"topic","kind":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"VtShortArray","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@VtShortArray"}],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_cshort_","role":"symbol","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CShort_","navigatorTitle":[{"text":"VtArray<CShort>","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfQuatf":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfQuatf","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"GfQuatf","kind":"identifier","preciseIdentifier":"c:@N@pxr@S@GfQuatf"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"GfQuatf","kind":"identifier"}],"url":"\/documentation\/openusd\/c++\/pxr\/gfquatf","role":"symbol","title":"pxr.GfQuatf"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfFrustum":{"url":"\/documentation\/openusd\/c++\/pxr\/gffrustum","abstract":[],"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"identifier","text":"GfFrustum","preciseIdentifier":"c:@N@pxr@S@GfFrustum"}],"navigatorTitle":[{"kind":"identifier","text":"GfFrustum"}],"kind":"symbol","title":"pxr.GfFrustum","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfFrustum","type":"topic","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfRange1f":{"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@GfRange1f","kind":"identifier","text":"GfRange1f"}],"title":"pxr.GfRange1f","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/gfrange1f","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfRange1f","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GfRange1f"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfVec3f":{"navigatorTitle":[{"kind":"identifier","text":"GfVec3f"}],"abstract":[],"role":"symbol","type":"topic","title":"pxr.GfVec3f","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec3f","url":"\/documentation\/openusd\/c++\/pxr\/gfvec3f","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"identifier","preciseIdentifier":"c:@N@pxr@S@GfVec3f","text":"GfVec3f"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfLineSeg":{"url":"\/documentation\/openusd\/c++\/pxr\/gflineseg","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfLineSeg","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier"},{"text":".","kind":"text"},{"text":"GfLineSeg","preciseIdentifier":"c:@N@pxr@S@GfLineSeg","kind":"identifier"}],"kind":"symbol","type":"topic","title":"pxr.GfLineSeg","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GfLineSeg"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfMatrix2d":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix2d","url":"\/documentation\/openusd\/c++\/pxr\/gfmatrix2d","kind":"symbol","abstract":[],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@GfMatrix2d","text":"GfMatrix2d","kind":"identifier"}],"type":"topic","title":"pxr.GfMatrix2d","role":"symbol","navigatorTitle":[{"text":"GfMatrix2d","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfMatrix2d_":{"title":"pxr.VtArray<pxr.GfMatrix2d>","navigatorTitle":[{"text":"VtArray<pxr.GfMatrix2d>","kind":"identifier"}],"type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfmatrix2d_","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfMatrix2d_","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"VtMatrix2dArray","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@VtMatrix2dArray"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfQuaternion":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfQuaternion","role":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"identifier","preciseIdentifier":"c:@N@pxr@S@GfQuaternion","text":"GfQuaternion"}],"kind":"symbol","abstract":[],"url":"\/documentation\/openusd\/c++\/pxr\/gfquaternion","navigatorTitle":[{"kind":"identifier","text":"GfQuaternion"}],"title":"pxr.GfQuaternion"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfRange3d":{"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/openusd\/c++\/pxr\/gfrange3d","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfRange3d","title":"pxr.GfRange3d","type":"topic","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier"},{"text":".","kind":"text"},{"text":"GfRange3d","preciseIdentifier":"c:@N@pxr@S@GfRange3d","kind":"identifier"}],"navigatorTitle":[{"text":"GfRange3d","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfRect2i":{"navigatorTitle":[{"text":"GfRect2i","kind":"identifier"}],"role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"GfRect2i","kind":"identifier","preciseIdentifier":"c:@N@pxr@S@GfRect2i"}],"url":"\/documentation\/openusd\/c++\/pxr\/gfrect2i","title":"pxr.GfRect2i","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfRect2i","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfVec3h_":{"abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec3h_","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"VtVec3hArray","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@VtVec3hArray"}],"navigatorTitle":[{"text":"VtArray<pxr.GfVec3h>","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfvec3h_","title":"pxr.VtArray<pxr.GfVec3h>"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfRange1d":{"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@GfRange1d","kind":"identifier","text":"GfRange1d"}],"type":"topic","title":"pxr.GfRange1d","kind":"symbol","abstract":[],"url":"\/documentation\/openusd\/c++\/pxr\/gfrange1d","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfRange1d","navigatorTitle":[{"kind":"identifier","text":"GfRange1d"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_CUnsignedLongLong_":{"kind":"symbol","role":"symbol","title":"pxr.VtArray<CUnsignedLongLong>","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CUnsignedLongLong_","navigatorTitle":[{"text":"VtArray<CUnsignedLongLong>","kind":"identifier"}],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_cunsignedlonglong_","abstract":[],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"VtUInt64Array","preciseIdentifier":"c:@N@pxr@VtUInt64Array","kind":"typeIdentifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/UsdTimeCode":{"navigatorTitle":[{"text":"UsdTimeCode","kind":"identifier"}],"type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/usdtimecode","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdTimeCode","title":"pxr.UsdTimeCode","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@UsdTimeCode","text":"UsdTimeCode","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfVec4h":{"role":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"GfVec4h","kind":"identifier","preciseIdentifier":"c:@N@pxr@S@GfVec4h"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec4h","navigatorTitle":[{"text":"GfVec4h","kind":"identifier"}],"url":"\/documentation\/openusd\/c++\/pxr\/gfvec4h","title":"pxr.GfVec4h"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfMatrix3f_":{"title":"pxr.VtArray<pxr.GfMatrix3f>","kind":"symbol","type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfmatrix3f_","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfMatrix3f_","role":"symbol","navigatorTitle":[{"text":"VtArray<pxr.GfMatrix3f>","kind":"identifier"}],"abstract":[],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@VtMatrix3fArray","text":"VtMatrix3fArray","kind":"typeIdentifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfMatrix4f_":{"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfmatrix4f_","title":"pxr.VtArray<pxr.GfMatrix4f>","type":"topic","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"VtMatrix4fArray","preciseIdentifier":"c:@N@pxr@VtMatrix4fArray"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.GfMatrix4f>"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfMatrix4f_","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_CUnsignedInt_":{"navigatorTitle":[{"kind":"identifier","text":"VtArray<CUnsignedInt>"}],"title":"pxr.VtArray<CUnsignedInt>","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_cunsignedint_","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CUnsignedInt_","kind":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"VtUIntArray","preciseIdentifier":"c:@N@pxr@VtUIntArray"}],"type":"topic","abstract":[],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_CLongLong_":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"VtArray<CLongLong>"}],"title":"pxr.VtArray<CLongLong>","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CLongLong_","role":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@VtInt64Array","kind":"typeIdentifier","text":"VtInt64Array"}],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_clonglong_"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfSize3":{"role":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"GfSize3","kind":"identifier","preciseIdentifier":"c:@N@pxr@S@GfSize3"}],"type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/gfsize3","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfSize3","navigatorTitle":[{"text":"GfSize3","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"pxr.GfSize3"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfTransform":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfTransform","role":"symbol","title":"pxr.GfTransform","type":"topic","kind":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/gftransform","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@GfTransform","text":"GfTransform","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"GfTransform","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfMatrix3d_":{"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfmatrix3d_","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfMatrix3d_","abstract":[],"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@VtMatrix3dArray","kind":"typeIdentifier","text":"VtMatrix3dArray"}],"type":"topic","role":"symbol","title":"pxr.VtArray<pxr.GfMatrix3d>","navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.GfMatrix3d>"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfDualQuatd":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfDualQuatd","url":"\/documentation\/openusd\/c++\/pxr\/gfdualquatd","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GfDualQuatd"}],"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"identifier","preciseIdentifier":"c:@N@pxr@S@GfDualQuatd","text":"GfDualQuatd"}],"abstract":[],"role":"symbol","type":"topic","title":"pxr.GfDualQuatd"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_CFloat_":{"abstract":[],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_cfloat_","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@VtFloatArray","kind":"typeIdentifier","text":"VtFloatArray"}],"navigatorTitle":[{"kind":"identifier","text":"VtArray<CFloat>"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CFloat_","kind":"symbol","title":"pxr.VtArray<CFloat>","type":"topic","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfVec2i":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec2i","navigatorTitle":[{"text":"GfVec2i","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/gfvec2i","abstract":[],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@GfVec2i","text":"GfVec2i","kind":"identifier"}],"title":"pxr.GfVec2i","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_CChar_":{"abstract":[],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"VtCharArray","preciseIdentifier":"c:@N@pxr@VtCharArray","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"VtArray<CChar>","kind":"identifier"}],"role":"symbol","title":"pxr.VtArray<CChar>","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CChar_","type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_cchar_"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfColorSpace":{"url":"\/documentation\/openusd\/c++\/pxr\/gfcolorspace","role":"symbol","title":"pxr.GfColorSpace","kind":"symbol","navigatorTitle":[{"text":"GfColorSpace","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfColorSpace","abstract":[],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@GfColorSpace","text":"GfColorSpace","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfQuatd":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"GfQuatd","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier"},{"text":".","kind":"text"},{"text":"GfQuatd","preciseIdentifier":"c:@N@pxr@S@GfQuatd","kind":"identifier"}],"role":"symbol","title":"pxr.GfQuatd","url":"\/documentation\/openusd\/c++\/pxr\/gfquatd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfQuatd"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfVec2d":{"type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/gfvec2d","title":"pxr.GfVec2d","abstract":[],"navigatorTitle":[{"text":"GfVec2d","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec2d","role":"symbol","kind":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@GfVec2d","text":"GfVec2d","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfVec3h":{"url":"\/documentation\/openusd\/c++\/pxr\/gfvec3h","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfVec3h","kind":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"GfVec3h","kind":"identifier","preciseIdentifier":"c:@N@pxr@S@GfVec3h"}],"abstract":[],"role":"symbol","type":"topic","title":"pxr.GfVec3h","navigatorTitle":[{"text":"GfVec3h","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_CUnsignedShort_":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"VtUShortArray","preciseIdentifier":"c:@N@pxr@VtUShortArray"}],"title":"pxr.VtArray<CUnsignedShort>","navigatorTitle":[{"kind":"identifier","text":"VtArray<CUnsignedShort>"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CUnsignedShort_","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_cunsignedshort_","role":"symbol","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfVec4i_":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec4i_","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@VtVec4iArray","kind":"typeIdentifier","text":"VtVec4iArray"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.GfVec4i>"}],"title":"pxr.VtArray<pxr.GfVec4i>","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfvec4i_","kind":"symbol","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfSize2":{"role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"GfSize2","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfSize2","title":"pxr.GfSize2","type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/gfsize2","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"GfSize2","kind":"identifier","preciseIdentifier":"c:@N@pxr@S@GfSize2"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfToken":{"title":"pxr.TfToken","type":"topic","kind":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/tftoken","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfToken","navigatorTitle":[{"kind":"identifier","text":"TfToken"}],"role":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"identifier","text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfVec3f_":{"type":"topic","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@VtVec3fArray","text":"VtVec3fArray","kind":"typeIdentifier"}],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfvec3f_","navigatorTitle":[{"text":"VtArray<pxr.GfVec3f>","kind":"identifier"}],"kind":"symbol","title":"pxr.VtArray<pxr.GfVec3f>","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec3f_","abstract":[],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfRange3f_":{"title":"pxr.VtArray<pxr.GfRange3f>","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfRange3f_","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfrange3f_","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.GfRange3f>"}],"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"VtRange3fArray","preciseIdentifier":"c:@N@pxr@VtRange3fArray"}],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfRange2f_":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"VtArray<pxr.GfRange2f>","kind":"identifier"}],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@VtRange2fArray","text":"VtRange2fArray","kind":"typeIdentifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfRange2f_","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfrange2f_","title":"pxr.VtArray<pxr.GfRange2f>","type":"topic","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.SdfAssetPath_":{"role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.SdfAssetPath_","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Overlay","kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay"},{"text":".","kind":"text"},{"text":"SdfAssetPath_VtArray","kind":"typeIdentifier","preciseIdentifier":"c:Typedefs.h@N@Overlay@T@SdfAssetPath_VtArray"}],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.sdfassetpath_","navigatorTitle":[{"text":"VtArray<pxr.SdfAssetPath>","kind":"identifier"}],"kind":"symbol","title":"pxr.VtArray<pxr.SdfAssetPath>"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfVec4h_":{"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfvec4h_","navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.GfVec4h>"}],"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"VtVec4hArray","preciseIdentifier":"c:@N@pxr@VtVec4hArray"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec4h_","type":"topic","abstract":[],"role":"symbol","title":"pxr.VtArray<pxr.GfVec4h>","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfQuath_":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfQuath_","navigatorTitle":[{"text":"VtArray<pxr.GfQuath>","kind":"identifier"}],"role":"symbol","title":"pxr.VtArray<pxr.GfQuath>","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfquath_","kind":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@VtQuathArray","text":"VtQuathArray","kind":"typeIdentifier"}],"abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfColor":{"navigatorTitle":[{"kind":"identifier","text":"GfColor"}],"abstract":[],"url":"\/documentation\/openusd\/c++\/pxr\/gfcolor","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfColor","title":"pxr.GfColor","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"identifier","text":"GfColor","preciseIdentifier":"c:@N@pxr@S@GfColor"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/SdfPath":{"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/SdfPath","title":"pxr.SdfPath","role":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"identifier","text":"SdfPath","preciseIdentifier":"c:@N@pxr@S@SdfPath"}],"url":"\/documentation\/openusd\/c++\/pxr\/sdfpath","navigatorTitle":[{"kind":"identifier","text":"SdfPath"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfVec2f_":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.GfVec2f>"}],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfvec2f_","role":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@VtVec2fArray","kind":"typeIdentifier","text":"VtVec2fArray"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec2f_","title":"pxr.VtArray<pxr.GfVec2f>","abstract":[],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfVec2i_":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec2i_","kind":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@VtVec2iArray","text":"VtVec2iArray"}],"abstract":[],"role":"symbol","title":"pxr.VtArray<pxr.GfVec2i>","type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfvec2i_","navigatorTitle":[{"text":"VtArray<pxr.GfVec2i>","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_CInt_":{"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"VtIntArray","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@VtIntArray"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CInt_","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_cint_","title":"pxr.VtArray<CInt>","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"VtArray<CInt>","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfDualQuatf":{"title":"pxr.GfDualQuatf","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier"},{"text":".","kind":"text"},{"text":"GfDualQuatf","preciseIdentifier":"c:@N@pxr@S@GfDualQuatf","kind":"identifier"}],"navigatorTitle":[{"text":"GfDualQuatf","kind":"identifier"}],"url":"\/documentation\/openusd\/c++\/pxr\/gfdualquatf","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfDualQuatf","abstract":[],"kind":"symbol","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfCamera/Projection":{"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"identifier","text":"GfCamera","preciseIdentifier":"c:@N@pxr@S@GfCamera"},{"kind":"text","text":"."},{"kind":"identifier","text":"Projection","preciseIdentifier":"c:@N@pxr@S@GfCamera@E@Projection"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfCamera\/Projection","title":"pxr.GfCamera.Projection","url":"\/documentation\/openusd\/c++\/pxr\/gfcamera\/projection","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Projection"}],"type":"topic","role":"symbol","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfMatrix4f":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix4f","abstract":[],"title":"pxr.GfMatrix4f","type":"topic","kind":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@GfMatrix4f","text":"GfMatrix4f","kind":"identifier"}],"navigatorTitle":[{"text":"GfMatrix4f","kind":"identifier"}],"role":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/gfmatrix4f"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfMatrix4d":{"abstract":[],"title":"pxr.GfMatrix4d","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix4d","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GfMatrix4d"}],"url":"\/documentation\/openusd\/c++\/pxr\/gfmatrix4d","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"identifier","preciseIdentifier":"c:@N@pxr@S@GfMatrix4d","text":"GfMatrix4d"}],"type":"topic","kind":"symbol"},"doc://SwiftUsd/documentation/SwiftUsd/Comparable":{"title":"Comparable protocol conformances","url":"\/documentation\/swiftusd\/comparable","abstract":[],"type":"topic","role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Comparable","kind":"article"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.pxr_half.half_":{"abstract":[],"role":"symbol","title":"pxr.VtArray<pxr.pxr_half.half>","kind":"symbol","type":"topic","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"VtHalfArray","preciseIdentifier":"c:@N@pxr@VtHalfArray","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"VtArray<pxr.pxr_half.half>","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.pxr_half.half_","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.pxr_half.half_"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_std.__1.basic_string_CChar,_std.__1.char_traits_CChar_,_std.__1.allocator_CChar___":{"role":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@VtStringArray","text":"VtStringArray"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_std.__1.basic_string_CChar,_std.__1.char_traits_CChar_,_std.__1.allocator_CChar___","title":"pxr.VtArray<std.__1.basic_string<CChar, std.__1.char_traits<CChar>, std.__1.allocator<CChar>>>","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"VtArray<std.__1.basic_string<CChar, std.__1.char_traits<CChar>, std.__1.allocator<CChar>>>"}],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_std.__1.basic_string_cchar,_std.__1.char_traits_cchar_,_std.__1.allocator_cchar___","kind":"symbol","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/pxr_half/half":{"title":"pxr.pxr_half.half","abstract":[],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/pxr_half\/half","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@N@pxr_half","kind":"identifier","text":"pxr_half"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@N@pxr_half@S@half","kind":"identifier","text":"half"}],"navigatorTitle":[{"kind":"identifier","text":"half"}],"type":"topic","kind":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/pxr_half\/half"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_CUnsignedChar_":{"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"VtUCharArray","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@VtUCharArray"}],"type":"topic","navigatorTitle":[{"text":"VtArray<CUnsignedChar>","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_CUnsignedChar_","kind":"symbol","role":"symbol","title":"pxr.VtArray<CUnsignedChar>","abstract":[],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_cunsignedchar_"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfRange1d_":{"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.GfRange1d>"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfRange1d_","type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfrange1d_","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@VtRange1dArray","kind":"typeIdentifier","text":"VtRange1dArray"}],"title":"pxr.VtArray<pxr.GfRange1d>"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfRange2d":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfRange2d","title":"pxr.GfRange2d","abstract":[],"url":"\/documentation\/openusd\/c++\/pxr\/gfrange2d","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@GfRange2d","text":"GfRange2d","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"GfRange2d","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfQuatd_":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.GfQuatd>"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfQuatd_","abstract":[],"title":"pxr.VtArray<pxr.GfQuatd>","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfquatd_","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@VtQuatdArray","text":"VtQuatdArray"}]},"doc://SwiftUsd/documentation/SwiftUsd/Equatable":{"title":"Equatable protocol conformances","url":"\/documentation\/swiftusd\/equatable","abstract":[],"type":"topic","role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Equatable","kind":"article"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfVec3i_":{"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfvec3i_","kind":"symbol","title":"pxr.VtArray<pxr.GfVec3i>","type":"topic","abstract":[],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"VtVec3iArray","preciseIdentifier":"c:@N@pxr@VtVec3iArray","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"VtArray<pxr.GfVec3i>","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec3i_"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfMatrix3f":{"title":"pxr.GfMatrix3f","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@GfMatrix3f","text":"GfMatrix3f","kind":"identifier"}],"url":"\/documentation\/openusd\/c++\/pxr\/gfmatrix3f","navigatorTitle":[{"text":"GfMatrix3f","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix3f","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfVec2d_":{"abstract":[],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"VtVec2dArray","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@VtVec2dArray"}],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfvec2d_","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfVec2d_","role":"symbol","navigatorTitle":[{"text":"VtArray<pxr.GfVec2d>","kind":"identifier"}],"kind":"symbol","type":"topic","title":"pxr.VtArray<pxr.GfVec2d>"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfInterval_":{"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@VtIntervalArray","text":"VtIntervalArray","kind":"typeIdentifier"}],"title":"pxr.VtArray<pxr.GfInterval>","abstract":[],"type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfinterval_","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfInterval_","kind":"symbol","navigatorTitle":[{"text":"VtArray<pxr.GfInterval>","kind":"identifier"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfQuaternion_":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfQuaternion_","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@VtQuaternionArray","text":"VtQuaternionArray"}],"title":"pxr.VtArray<pxr.GfQuaternion>","navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.GfQuaternion>"}],"abstract":[],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfquaternion_"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/VtArray_pxr.GfMatrix4d_":{"navigatorTitle":[{"kind":"identifier","text":"VtArray<pxr.GfMatrix4d>"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/VtArray_pxr.GfMatrix4d_","abstract":[],"title":"pxr.VtArray<pxr.GfMatrix4d>","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@VtMatrix4dArray","text":"VtMatrix4dArray"}],"url":"\/documentation\/openusd\/c++\/pxr\/vtarray_pxr.gfmatrix4d_"},"doc://SwiftUsd/documentation/OpenUSD":{"role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","abstract":[],"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol"},"doc://SwiftUsd/documentation/SwiftUsd/Hashable":{"type":"topic","role":"article","url":"\/documentation\/swiftusd\/hashable","kind":"article","title":"Hashable protocol conformances","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Hashable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"anchor":"Protocol-conformances","title":"Protocol conformances","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Equatable","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Comparable","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Hashable","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CustomStringConvertible","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Sendable"],"generated":true}],"path":"\/seeAlsoSections","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}