{"abstract":[{"text":"Extensions that make OpenUSD nicer to use in Swift","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftusd\/convenientextensions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/swiftusd\/convenientextensions"]}],"topicSections":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/SdfLayer\/ExportToString()"],"title":"SdfLayer","anchor":"SdfLayer"},{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdStage\/ExportToString(addSourceFileComment:)"],"title":"UsdStage","anchor":"UsdStage"},{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdPrimRange\/withIterator()","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/UsdPrimRangeIteratedSequence"],"title":"UsdPrimRange","anchor":"UsdPrimRange"},{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix4d\/MakeTranslate(_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix4d\/MakeRotate(_:)"],"title":"GfMatrix","anchor":"GfMatrix"}],"kind":"article","hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"metadata":{"modules":[{"name":"OpenUSD"}],"title":"Convenient extensions","roleHeading":"API Collection","role":"collectionGroup"},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"],"anchor":"New-symbol-documentation","title":"New symbol documentation","generated":true}],"references":{"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfNotice":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","role":"article","kind":"article","title":"Working with TfNotice","type":"topic","url":"\/documentation\/swiftusd\/workingwithtfnotice","abstract":[{"type":"text","text":"Learn how to use the TfNotice notification subsystem in Swift"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/SdfLayer/ExportToString()":{"url":"\/documentation\/openusd\/c++\/pxr\/sdflayer\/exporttostring()","title":"ExportToString()","abstract":[{"text":"Wrapper for ","type":"text"},{"code":"pxr.SdfLayer.ExportToString()","type":"codeVoice"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/SdfLayer\/ExportToString()","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExportToString","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","abstract":[],"url":"\/documentation\/openusd","kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD"},"doc://SwiftUsd/documentation/SwiftUsd/UsingEditContexts":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","title":"Using edit contexts","abstract":[{"text":"Using ","type":"text"},{"code":"pxr.UsdEditContext","type":"codeVoice"},{"text":" in Swift","type":"text"}],"role":"collectionGroup","url":"\/documentation\/swiftusd\/usingeditcontexts","kind":"article"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfMatrix4d/MakeRotate(_:)":{"type":"topic","title":"MakeRotate(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MakeRotate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"GfRotation","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@GfRotation"},{"text":") -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"GfMatrix4d","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@GfMatrix4d"}],"abstract":[{"text":"Wrapper for ","type":"text"},{"code":"pxr.GfMatrix().SetRotate(r)","type":"codeVoice"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix4d\/MakeRotate(_:)","kind":"symbol","role":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/gfmatrix4d\/makerotate(_:)"},"doc://SwiftUsd/documentation/SwiftUsd/CheckingForValidity":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","role":"article","kind":"article","title":"Checking for validity","type":"topic","abstract":[{"type":"text","text":"Checking for "},{"code":"IsValid()","type":"codeVoice"},{"type":"text","text":" and null pointers in Swift"}],"url":"\/documentation\/swiftusd\/checkingforvalidity"},"doc://SwiftUsd/documentation/SwiftUsd/DereferencingPointers":{"title":"Dereferencing pointers","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","abstract":[{"type":"text","text":"Safely dereferencing "},{"type":"codeVoice","code":"pxr.TfRefPtr"},{"type":"text","text":" and "},{"type":"codeVoice","code":"pxr.TfWeakPtr"},{"type":"text","text":" in Swift"}],"type":"topic","role":"collectionGroup","url":"\/documentation\/swiftusd\/dereferencingpointers"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfMatrix4d/MakeTranslate(_:)":{"title":"MakeTranslate(_:)","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix4d\/MakeTranslate(_:)","abstract":[{"text":"Wrapper for ","type":"text"},{"code":"pxr.GfMatrix().SetTranslate(v)","type":"codeVoice"}],"url":"\/documentation\/openusd\/c++\/pxr\/gfmatrix4d\/maketranslate(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MakeTranslate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"GfVec3d","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@GfVec3d"},{"text":") -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"GfMatrix4d","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@GfMatrix4d"}],"type":"topic","role":"symbol"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfDiagnosticFacilities":{"role":"collectionGroup","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","title":"Working with Tf Diagnostic Facilities","kind":"article","abstract":[{"text":"Learn how to use the Tf diagnostic facilities in Swift","type":"text"}],"type":"topic","url":"\/documentation\/swiftusd\/workingwithtfdiagnosticfacilities"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/UsdPrimRange/withIterator()":{"url":"\/documentation\/openusd\/c++\/pxr\/usdprimrange\/withiterator()","role":"symbol","abstract":[{"text":"Returns an iterator that exposes the ","type":"text"},{"code":"isPostVisit","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"pruneChildren()","type":"codeVoice"},{"text":" properties for a ","type":"text"},{"code":"UsdPrimRange","type":"codeVoice"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withIterator"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@N@Overlay","kind":"typeIdentifier","text":"Overlay"},{"kind":"text","text":"."},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE28UsdPrimRangeIteratedSequenceV","kind":"typeIdentifier","text":"UsdPrimRangeIteratedSequence"}],"title":"withIterator()","type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdPrimRange\/withIterator()"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/UsdStage/ExportToString(addSourceFileComment:)":{"abstract":[{"text":"Wrapper for ","type":"text"},{"code":"pxr.UsdStage.ExportToString()","type":"codeVoice"}],"role":"symbol","title":"ExportToString(addSourceFileComment:)","url":"\/documentation\/openusd\/c++\/pxr\/usdstage\/exporttostring(addsourcefilecomment:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExportToString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"addSourceFileComment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdStage\/ExportToString(addSourceFileComment:)"},"doc://SwiftUsd/documentation/SwiftUsd/CreatingPointers":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","url":"\/documentation\/swiftusd\/creatingpointers","type":"topic","kind":"article","role":"collectionGroup","title":"Creating pointers","abstract":[{"type":"text","text":"Creating "},{"type":"codeVoice","code":"pxr.TfRefPtr"},{"type":"text","text":" and "},{"type":"codeVoice","code":"pxr.TfWeakPtr"},{"type":"text","text":" in Swift"}]},"doc://SwiftUsd/documentation/SwiftUsd/TypeConversion":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion","kind":"article","url":"\/documentation\/swiftusd\/typeconversion","abstract":[],"type":"topic","title":"Type conversion","role":"collectionGroup"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/UsdPrimRangeIteratedSequence":{"abstract":[{"text":"A wrapper for ","type":"text"},{"type":"codeVoice","code":"pxr.UsdPrimRange.iterator"},{"text":" that exposes the ","type":"text"},{"type":"codeVoice","code":"IsPostVisit()"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"PruneChildren()"},{"text":" methods for a ","type":"text"},{"type":"codeVoice","code":"UsdPrimRange"}],"title":"Overlay.UsdPrimRangeIteratedSequence","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/UsdPrimRangeIteratedSequence","role":"symbol","navigatorTitle":[{"text":"UsdPrimRangeIteratedSequence","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openusd\/c++\/overlay\/usdprimrangeiteratedsequence","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdPrimRangeIteratedSequence","kind":"identifier"}],"type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfErrorMark":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","type":"topic","url":"\/documentation\/swiftusd\/workingwithtferrormark","title":"Working with TfErrorMark","kind":"article","abstract":[{"type":"text","text":"Learn how to use TfErrorMark in Swift"}],"role":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":[{"title":"New symbol documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"],"generated":true,"anchor":"New-symbol-documentation"}],"op":"replace"}]}]}