{"abstract":[{"text":"Creating ","type":"text"},{"code":"pxr.TfRefPtr","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"pxr.TfWeakPtr","type":"codeVoice"},{"text":" in Swift","type":"text"}],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"text":"In Swift, it’s recommended to hold a ","type":"text"},{"code":"pxr.UsdStage","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"pxr.SdfLayer","type":"codeVoice"},{"text":" directly. However, when calling into the OpenUSD API, it may be necessary to convert the directly held reference type into a smart pointer.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This Swift Package provides "},{"overridingTitle":"Overlay.TfRefPtr(_:)","isActive":true,"type":"reference","overridingTitleInlineContent":[{"type":"codeVoice","code":"Overlay.TfRefPtr(_:)"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfRefPtr(_:)-7quy3"},{"type":"text","text":" and "},{"overridingTitle":"Overlay.TfWeakPtr(_:)","isActive":true,"type":"reference","overridingTitleInlineContent":[{"code":"Overlay.TfWeakPtr(_:)","type":"codeVoice"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfWeakPtr(_:)-8de9g"},{"type":"text","text":" for that purpose."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For more information, see "},{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WhatIsAForeignReferenceType","isActive":true,"type":"reference"},{"type":"text","text":" and "},{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ForeignReferenceTypesAndSmartPointers","isActive":true,"type":"reference"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftusd\/creatingpointers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/swiftusd\/creatingpointers"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","interfaceLanguage":"swift"},"kind":"article","hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"topicSections":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfRefPtr(_:)-7quy3","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfRefPtr(_:)-v2wi","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfRefPtr(_:)-4647l","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfWeakPtr(_:)-8de9g","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfWeakPtr(_:)-1gjl1","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfWeakPtr(_:)-69u6l"],"anchor":"Topics","abstract":[{"text":"In Swift, these functions live under ","type":"text"},{"code":"Overlay","type":"codeVoice"},{"text":".","type":"text"}]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingLibWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"],"title":"New symbol documentation","anchor":"New-symbol-documentation"}],"metadata":{"roleHeading":"API Collection","modules":[{"name":"OpenUSD"}],"title":"Creating pointers","role":"collectionGroup"},"references":{"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/TfRefPtr(_:)-7quy3":{"role":"symbol","abstract":[{"text":"Wraps the argument in a ","type":"text"},{"code":"pxr::TfRefPtr<T>","type":"codeVoice"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfRefPtr(_:)-7quy3","kind":"symbol","title":"TfRefPtr(_:)","url":"\/documentation\/openusd\/c++\/overlay\/tfrefptr(_:)-7quy3","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TfRefPtr","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE8TfRefPtry01_deF4TypeQzxSgAbCE01_dE12BaseProtocolRzlFZ1TL_xmfp"},{"text":"?) -> ","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE8TfRefPtry01_deF4TypeQzxSgAbCE01_dE12BaseProtocolRzlFZ1TL_xmfp"},{"text":".","kind":"text"},{"text":"_TfRefPtrType","kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolP01_dE7PtrTypeQa"}],"type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/UsingLibWork":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingLibWork","kind":"article","url":"\/documentation\/swiftusd\/usinglibwork","role":"article","type":"topic","abstract":[{"type":"text","text":"Learn how to use the "},{"type":"codeVoice","code":"pxr::Work"},{"type":"text","text":" library for multithreading in Swift"}],"title":"Using libWork"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/TfRefPtr(_:)-4647l":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TfRefPtr","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE8TfRefPtry01_D12WeakBaseType_01_defI0AbCE01_deH8ProtocolPQZxAbCE01_dgfJ0RzAbCEAgERpzlFZ1TL_xmfp","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE8TfRefPtry01_D12WeakBaseType_01_defI0AbCE01_deH8ProtocolPQZxAbCE01_dgfJ0RzAbCEAgERpzlFZ1TL_xmfp","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"_TfWeakBaseType","preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfWeakPtrProtocolP01_dE8BaseTypeQa","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"_TfRefPtrType","preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolP01_dE7PtrTypeQa","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfRefPtr(_:)-4647l","abstract":[{"type":"text","text":"Converts a "},{"type":"codeVoice","code":"pxr::TfWeakPtr<T>"},{"type":"text","text":" into a "},{"type":"codeVoice","code":"pxr::TfRefPtr<T>"}],"kind":"symbol","title":"TfRefPtr(_:)","type":"topic","url":"\/documentation\/openusd\/c++\/overlay\/tfrefptr(_:)-4647l"},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","type":"topic","url":"\/documentation\/openusd","abstract":[],"role":"collection"},"doc://SwiftUsd/documentation/SwiftUsd/WhatIsAForeignReferenceType":{"kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WhatIsAForeignReferenceType","url":"\/documentation\/swiftusd\/whatisaforeignreferencetype","abstract":[{"text":"Learn about foreign reference types and how to use them","type":"text"}],"title":"What is a Foreign Reference Type?","type":"topic","role":"article"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/TfWeakPtr(_:)-69u6l":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfWeakPtr(_:)-69u6l","abstract":[{"text":"Converts a ","type":"text"},{"code":"pxr::TfRefPtr<T>","type":"codeVoice"},{"text":" into a ","type":"text"},{"code":"pxr::TfWeakPtr<T>","type":"codeVoice"}],"role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TfWeakPtr","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE9TfWeakPtry01_D11RefBaseType_01_defI0AbCE01_deH8ProtocolPQZxAbCE01_dgfJ0RzAbCEAgERpzlFZ1TL_xmfp"},{"text":") -> ","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE9TfWeakPtry01_D11RefBaseType_01_defI0AbCE01_deH8ProtocolPQZxAbCE01_dgfJ0RzAbCEAgERpzlFZ1TL_xmfp"},{"text":".","kind":"text"},{"text":"_TfRefBaseType","kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE17_TfRefPtrProtocolP01_dE8BaseTypeQa"},{"text":".","kind":"text"},{"text":"_TfWeakPtrType","kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE19_TfWeakBaseProtocolP01_dE7PtrTypeQa"}],"url":"\/documentation\/openusd\/c++\/overlay\/tfweakptr(_:)-69u6l","title":"TfWeakPtr(_:)","type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfErrorMark":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","title":"Working with TfErrorMark","url":"\/documentation\/swiftusd\/workingwithtferrormark","role":"article","type":"topic","kind":"article","abstract":[{"type":"text","text":"Learn how to use TfErrorMark in Swift"}]},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfNotice":{"type":"topic","url":"\/documentation\/swiftusd\/workingwithtfnotice","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","role":"article","abstract":[{"type":"text","text":"Learn how to use the TfNotice notification subsystem in Swift"}],"kind":"article","title":"Working with TfNotice"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/TfWeakPtr(_:)-8de9g":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/openusd\/c++\/overlay\/tfweakptr(_:)-8de9g","title":"TfWeakPtr(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfWeakPtr(_:)-8de9g","abstract":[{"text":"Wraps the argument in a ","type":"text"},{"type":"codeVoice","code":"pxr::TfWeakPtr<T>"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TfWeakPtr","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE9TfWeakPtry01_deF4TypeQzxSgAbCE01_dE12BaseProtocolRzlFZ1TL_xmfp"},{"text":"?) -> ","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE9TfWeakPtry01_deF4TypeQzxSgAbCE01_dE12BaseProtocolRzlFZ1TL_xmfp"},{"text":".","kind":"text"},{"text":"_TfWeakPtrType","kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE19_TfWeakBaseProtocolP01_dE7PtrTypeQa"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/TfWeakPtr(_:)-1gjl1":{"role":"symbol","abstract":[{"text":"Wraps the argument in a ","type":"text"},{"code":"pxr::TfWeakPtr<T>","type":"codeVoice"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfWeakPtr(_:)-1gjl1","kind":"symbol","title":"TfWeakPtr(_:)","url":"\/documentation\/openusd\/c++\/overlay\/tfweakptr(_:)-1gjl1","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TfWeakPtr","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE9TfWeakPtryx01_dE8BaseTypeQzSgAbCE01_deF8ProtocolRzlFZ1TL_xmfp"},{"text":".","kind":"text"},{"text":"_TfWeakBaseType","kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfWeakPtrProtocolP01_dE8BaseTypeQa"},{"text":"?) -> ","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE9TfWeakPtryx01_dE8BaseTypeQzSgAbCE01_deF8ProtocolRzlFZ1TL_xmfp"}],"type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/ForeignReferenceTypesAndSmartPointers":{"abstract":[{"text":"Learn about ","type":"text"},{"code":"pxr::TfRefPtr","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"pxr::TfWeakPtr","type":"codeVoice"},{"text":" in Swift","type":"text"}],"type":"topic","title":"Foreign Reference Types and Smart Pointers","role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ForeignReferenceTypesAndSmartPointers","kind":"article","url":"\/documentation\/swiftusd\/foreignreferencetypesandsmartpointers"},"doc://SwiftUsd/documentation/SwiftUsd/DereferencingPointers":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","kind":"article","abstract":[{"text":"Safely dereferencing ","type":"text"},{"code":"pxr.TfRefPtr","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"pxr.TfWeakPtr","type":"codeVoice"},{"text":" in Swift","type":"text"}],"url":"\/documentation\/swiftusd\/dereferencingpointers","title":"Dereferencing pointers","role":"collectionGroup"},"doc://SwiftUsd/documentation/SwiftUsd/CheckingForValidity":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","abstract":[{"type":"text","text":"Checking for "},{"type":"codeVoice","code":"IsValid()"},{"type":"text","text":" and null pointers in Swift"}],"type":"topic","role":"article","kind":"article","url":"\/documentation\/swiftusd\/checkingforvalidity","title":"Checking for validity"},"doc://SwiftUsd/documentation/SwiftUsd/UsingEditContexts":{"role":"collectionGroup","kind":"article","abstract":[{"text":"Using ","type":"text"},{"code":"pxr.UsdEditContext","type":"codeVoice"},{"text":" in Swift","type":"text"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","url":"\/documentation\/swiftusd\/usingeditcontexts","title":"Using edit contexts"},"doc://SwiftUsd/documentation/SwiftUsd/ConvenientExtensions":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","kind":"article","url":"\/documentation\/swiftusd\/convenientextensions","role":"collectionGroup","type":"topic","abstract":[{"type":"text","text":"Extensions that make OpenUSD nicer to use in Swift"}],"title":"Convenient extensions"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfDiagnosticFacilities":{"kind":"article","url":"\/documentation\/swiftusd\/workingwithtfdiagnosticfacilities","type":"topic","abstract":[{"text":"Learn how to use the Tf diagnostic facilities in Swift","type":"text"}],"role":"collectionGroup","title":"Working with Tf Diagnostic Facilities","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/TfRefPtr(_:)-v2wi":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TfRefPtr","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE8TfRefPtryx01_dE8BaseTypeQzSgAbCE01_deF8ProtocolRzlFZ1TL_xmfp","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"_TfRefBaseType","preciseIdentifier":"s:So7OverlayO7OpenUSDE17_TfRefPtrProtocolP01_dE8BaseTypeQa","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE8TfRefPtryx01_dE8BaseTypeQzSgAbCE01_deF8ProtocolRzlFZ1TL_xmfp","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/openusd\/c++\/overlay\/tfrefptr(_:)-v2wi","abstract":[{"type":"text","text":"Wraps the argument in a "},{"type":"codeVoice","code":"pxr::TfRefPtr<T>"}],"title":"TfRefPtr(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfRefPtr(_:)-v2wi"},"doc://SwiftUsd/documentation/SwiftUsd/TypeConversion":{"type":"topic","kind":"article","url":"\/documentation\/swiftusd\/typeconversion","title":"Type conversion","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion","role":"collectionGroup","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingLibWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"],"title":"New symbol documentation","generated":true,"anchor":"New-symbol-documentation"}],"op":"replace","path":"\/seeAlsoSections"}]}]}