{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"article","title":"Differences in Swift","modules":[{"name":"OpenUSD"}],"roleHeading":"Article"},"abstract":[{"type":"text","text":"Learn how the OpenUSD API is different in Swift"}],"seeAlsoSections":[{"generated":true,"anchor":"Essentials","title":"Essentials","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Capabilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CurrentLimitations"]}],"variants":[{"paths":["\/documentation\/swiftusd\/differencesinswift"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/differencesinswift"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DifferencesInSwift"},"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","text":"Overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"When using OpenUSD in Swift, there are some key differences and potential pitfalls you should know about."}]},{"anchor":"UsdStage","text":"UsdStage","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"In Swift, "},{"type":"codeVoice","code":"UsdStage"},{"type":"text","text":" is imported as a reference (class) type, meaning that you can hold a "},{"type":"codeVoice","code":"UsdStage"},{"type":"text","text":" directly in a Swift class, struct, enum, or local variable. Swift automatically inserts retain and release calls as needed when the stage is used, and can interoperate with C++ code that uses Pixar smart pointers for reference counting."}]},{"anchor":"Acquiring-a-stage","text":"Acquiring a stage","type":"heading","level":4},{"type":"paragraph","inlineContent":[{"text":"When acquiring a ","type":"text"},{"code":"UsdStage","type":"codeVoice"},{"text":", use ","type":"text"},{"isActive":true,"overridingTitle":"Overlay.Dereference(_:)","overridingTitleInlineContent":[{"type":"codeVoice","code":"Overlay.Dereference(_:)"}],"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/Dereference(_:)-67vpz"},{"text":" to dereference the ","type":"text"},{"code":"TfRefPtr<UsdStage>","type":"codeVoice"},{"text":" returned by C++.","type":"text"}]},{"code":["let stage: pxr.UsdStage = Overlay.Dereference(pxr.UsdStage.CreateInMemory(.LoadAll))"],"type":"codeListing","syntax":"swift"},{"name":"Warning","content":[{"inlineContent":[{"text":"The autogenerated ","type":"text"},{"type":"codeVoice","code":"pointee"},{"text":" property on ","type":"text"},{"type":"codeVoice","code":"TfRefPtr<UsdStage>"},{"text":" is not safe. Always use ","type":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/Dereference(_:)-67vpz","isActive":true,"type":"reference","overridingTitleInlineContent":[{"code":"Overlay.Dereference(_:)","type":"codeVoice"}],"overridingTitle":"Overlay.Dereference(_:)"},{"text":" instead.","type":"text"}],"type":"paragraph"}],"type":"aside","style":"warning"},{"code":["let stage: pxr.UsdStage = pxr.UsdStage.CreateInMemory(.LoadAll).pointee \/\/ ❌ unsafe! Use Overlay.Dereference(...) instead"],"type":"codeListing","syntax":"swift"},{"anchor":"Passing-a-stage","text":"Passing a stage","type":"heading","level":4},{"type":"paragraph","inlineContent":[{"text":"When passing a ","type":"text"},{"code":"UsdStage","type":"codeVoice"},{"text":" to the OpenUSD API, wrap it via ","type":"text"},{"overridingTitleInlineContent":[{"code":"Overlay.TfWeakPtr(_:)","type":"codeVoice"}],"overridingTitle":"Overlay.TfWeakPtr(_:)","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfWeakPtr(_:)-8de9g","type":"reference"},{"text":".","type":"text"}]},{"code":["let stage = Overlay.Dereference(pxr.UsdStage.CreateNew(\"\/tmp\/mystage.usda\", .LoadAll))","let xform = pxr.UsdGeomXform.Define(Overlay.TfWeakPtr(stage), \"\/hello\")"],"type":"codeListing","syntax":"swift"},{"level":4,"text":"Calling methods on a stage","anchor":"Calling-methods-on-a-stage","type":"heading"},{"inlineContent":[{"type":"text","text":"When calling methods on a "},{"code":"UsdStage","type":"codeVoice"},{"type":"text","text":", use the stage directly:"}],"type":"paragraph"},{"code":["let stage = Overlay.Dereference(pxr.UsdStage.Open(\"\/tmp\/mystage.usda\", .LoadAll))","let root = stage.GetPseudoRoot()"],"type":"codeListing","syntax":"swift"},{"level":3,"text":"SdfLayer","anchor":"SdfLayer","type":"heading"},{"inlineContent":[{"type":"text","text":"In Swift, "},{"code":"SdfLayer","type":"codeVoice"},{"type":"text","text":" is imported as a reference (class) type, just like "},{"code":"UsdStage","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"},{"level":4,"text":"Acquiring a layer","anchor":"Acquiring-a-layer","type":"heading"},{"inlineContent":[{"text":"When acquiring a ","type":"text"},{"code":"SdfLayer","type":"codeVoice"},{"text":", use ","type":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/Dereference(_:)-3edgv","isActive":true,"overridingTitle":"Overlay.Dereference(_:)","overridingTitleInlineContent":[{"code":"Overlay.Dereference(_:)","type":"codeVoice"}],"type":"reference"},{"text":" to dereference the ","type":"text"},{"code":"TfWeakPtr<SdfLayer>","type":"codeVoice"},{"text":" returned by C++.","type":"text"}],"type":"paragraph"},{"code":["let stage: pxr.UsdStage = Overlay.Dereference(pxr.UsdStage.CreateInMemory(.LoadAll))","let layer: pxr.SdfLayer = Overlay.Dereference(stage.GetRootLayer())"],"type":"codeListing","syntax":"swift"},{"style":"warning","name":"Warning","content":[{"type":"paragraph","inlineContent":[{"text":"The autogenerated ","type":"text"},{"code":"pointee","type":"codeVoice"},{"text":" property on ","type":"text"},{"code":"TfWeakPtr<SdfLayer>","type":"codeVoice"},{"text":" is not safe. Always use ","type":"text"},{"overridingTitleInlineContent":[{"code":"Overlay.Dereference(_:)","type":"codeVoice"}],"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/Dereference(_:)-3edgv","overridingTitle":"Overlay.Dereference(_:)","type":"reference"},{"text":" instead.","type":"text"}]}],"type":"aside"},{"syntax":"swift","code":["let stage: pxr.UsdStage = Overlay.Dereference(pxr.UsdStage.CreateInMemory(.LoadAll))","let layer: pxr.SdfLayer = stage.GetRootLayer().pointee \/\/ ❌ unsafe! Use Overlay.Dereference(...) instead"],"type":"codeListing"},{"level":4,"anchor":"Calling-methods-on-a-layer","text":"Calling methods on a layer","type":"heading"},{"inlineContent":[{"type":"text","text":"When calling methods on a "},{"type":"codeVoice","code":"SdfLayer"},{"type":"text","text":", use the layer directly:"}],"type":"paragraph"},{"syntax":"swift","code":["let layer = Overlay.Dereference(stage.GetRootLayer())","let dirty = layer.IsDirty()"],"type":"codeListing"},{"level":3,"anchor":"Converting-types-to-boolean-values","text":"Converting types to boolean values","type":"heading"},{"inlineContent":[{"text":"In C++, many OpenUSD types have an ","type":"text"},{"code":"operator bool() const","type":"codeVoice"},{"text":" method. In Swift, this has been mapped to an initializer on ","type":"text"},{"code":"Bool","type":"codeVoice"},{"text":". See ","type":"text"},{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","type":"reference"},{"text":" for more information.","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["let hasSessionLayer = Bool(stage.GetSessionLayer())","","let imageable = pxr.UsdGeomImageable(prim)","if Bool(imageable) { ... }","","let attribute = stage.GetAttributeAtPath(\"\/foo\/bar.baz\")","if Bool(attribute) { ... }"],"type":"codeListing"},{"level":3,"anchor":"Wrapped-types-for-unavailable-types","text":"Wrapped types for unavailable types","type":"heading"},{"inlineContent":[{"type":"text","text":"Some OpenUSD types are move-only in C++, which means they can’t be imported into Swift."},{"type":"text","text":"\n"},{"type":"text","text":"In some cases, a Swift wrapper type is provided in this Swift Package. For example, "},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","type":"reference","isActive":true},{"type":"text","text":". See "},{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","type":"reference","isActive":true},{"type":"text","text":" for more information."}],"type":"paragraph"},{"level":3,"anchor":"UsdPrimRange-and-for-loops","text":"UsdPrimRange and for loops","type":"heading"},{"inlineContent":[{"type":"codeVoice","code":"UsdPrimRange"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Sequence"},{"type":"text","text":", enabling the use of for-loops and "},{"type":"codeVoice","code":"Sequence"},{"type":"text","text":" methods like "},{"type":"codeVoice","code":"filter"},{"type":"text","text":", "},{"type":"codeVoice","code":"map"},{"type":"text","text":", and "},{"type":"codeVoice","code":"reduce"}],"type":"paragraph"},{"syntax":"swift","code":["for prim in pxr.UsdPrim.PreAndPostVisit(stage.GetPseudoRoot()) {","    print(prim)","}","","let abstractPrims: [pxr.UsdPrim] = stage.Traverse().filter { $0.IsAbstract() }"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"To access the "},{"type":"codeVoice","code":"iterator"},{"type":"text","text":" of "},{"type":"codeVoice","code":"UsdPrimRange"},{"type":"text","text":" in a for-loop, use "},{"type":"codeVoice","code":"UsdPrimRange.withIterator()"},{"type":"text","text":":"}],"type":"paragraph"},{"syntax":"swift","code":["for (iter, prim) in pxr.UsdPrim.PreAndPostVisit(stage.GetPseudoRoot()).withIterator() {","    let path = String(prim.GetPath().GetAsString())","    print(path, iter.IsPostVisit())","    if path == \"\/Hello\" {","        iter.PruneChildren()","    }","}"],"type":"codeListing"},{"level":3,"anchor":"TfNotice","text":"TfNotice","type":"heading"},{"inlineContent":[{"type":"text","text":"Swift code can register for "},{"type":"codeVoice","code":"TfNotice"},{"type":"text","text":" callbacks by using "},{"type":"reference","overridingTitle":"pxr.TfNotice.Register","overridingTitleInlineContent":[{"type":"codeVoice","code":"pxr.TfNotice.Register"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-99j13","isActive":true},{"type":"text","text":". Instead of creating a C++ class or struct that inherits from "},{"type":"codeVoice","code":"pxr::TfWeakBase"},{"type":"text","text":", call "},{"type":"reference","overridingTitle":"pxr.TfNotice.Register","overridingTitleInlineContent":[{"type":"codeVoice","code":"pxr.TfNotice.Register"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-99j13","isActive":true},{"type":"text","text":" and pass a closure:"}],"type":"paragraph"},{"syntax":"swift","code":["func registerWithRevoking(stage: pxr.UsdStage) {","    let key = pxr.TfNotice.Register(stage, pxr.UsdNotice.StageContentsChanged.self) { _ in","        print(\"Stage contents changed\")","    }","","    stage.SetStartTimeCode(5) \/\/ prints \"Stage contents changed\"","    stage.SetEndTimeCode(7) \/\/ prints \"Stage contents changed\"","    pxr.TfNotice.Revoke(key)","    stage.SetTimeCodesPerSecond(60) \/\/ no print","}"],"type":"codeListing"},{"inlineContent":[{"text":"For more information, see ","type":"text"},{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"},{"level":3,"anchor":"GfMatrix4d-static-factory-methods","text":"GfMatrix4d static factory methods","type":"heading"},{"inlineContent":[{"type":"text","text":"In C++, "},{"code":"pxr::GfMatrix4d().SetTranslate()","type":"codeVoice"},{"type":"text","text":" and "},{"code":"pxr::GfMatrix4d().SetRotate()","type":"codeVoice"},{"type":"text","text":" are valid expressions, but mutated method chaining on function return values is not supported in Swift."},{"type":"text","text":"\n"},{"type":"text","text":"This Swift Package provides "},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix4d\/MakeTranslate(_:)","type":"reference","isActive":true,"overridingTitle":"pxr.GfMatrix4d.MakeTranslate()","overridingTitleInlineContent":[{"type":"codeVoice","code":"pxr.GfMatrix4d.MakeTranslate()"}]},{"type":"text","text":" and "},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix4d\/MakeRotate(_:)","type":"reference","isActive":true,"overridingTitle":"pxr.GfMatrix4d.MakeRotate()","overridingTitleInlineContent":[{"type":"codeVoice","code":"pxr.GfMatrix4d.MakeRotate()"}]},{"type":"text","text":" to increase the ergonomics of "},{"code":"GfMatrix4d","type":"codeVoice"},{"type":"text","text":" in Swift."}],"type":"paragraph"},{"syntax":"swift","code":["override open func cameraTransformBeforeZupCorrection(stage: pxr.UsdStage) -> pxr.GfMatrix4d {","    pxr.GfMatrix4d.MakeRotate(pxr.GfRotation(.XAxis(), tilt * 180 \/ .pi)) *","    pxr.GfMatrix4d.MakeRotate(pxr.GfRotation(.YAxis(), pan * 180 \/ .pi)) *","    pxr.GfMatrix4d.MakeTranslate(position)","}"],"type":"codeListing"},{"level":3,"anchor":"GetPrim","text":"GetPrim()","type":"heading"},{"inlineContent":[{"type":"text","text":"In Swift, calling the "},{"code":"GetPrim()","type":"codeVoice"},{"type":"text","text":" method on a "},{"code":"UsdSchemaBase","type":"codeVoice"},{"type":"text","text":" subclass (e.g. "},{"code":"UsdGeomSphere","type":"codeVoice"},{"type":"text","text":") causes a compiler crash."},{"type":"text","text":"\n"},{"type":"text","text":"This Swift Package provides "},{"code":"Overlay.GetPrim<T>(_:T) -> pxr.UsdPrim","type":"codeVoice"},{"type":"text","text":", substituting "},{"code":"T","type":"codeVoice"},{"type":"text","text":" for each subclass of "},{"code":"UsdSchemaBase","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"},{"syntax":"swift","code":["let planePrim = pxr.UsdGeomMesh.Get(Overlay.TfWeakPtr(stage), planePath(anchor: anchor))","Overlay.GetPrim(planePrim).SetActive(true)"],"type":"codeListing"},{"level":3,"anchor":"Implicit-member-expressions","text":"Implicit member expressions","type":"heading"},{"inlineContent":[{"code":"SdfValueTypeNames","type":"codeVoice"},{"type":"text","text":" and tokens types like "},{"code":"UsdGeomTokensType","type":"codeVoice"},{"type":"text","text":" support implicit member expressions."}],"type":"paragraph"},{"syntax":"swift","code":["var pbrShader = pxr.UsdShadeShader.Define(Overlay.TfWeakPtr(stage), \"\/TexModel\/boardMat\/PBRShader\")","pbrShader.CreateInput(\"roughness\", pxr.SdfValueTypeName.Float) \/\/ Without implicit member expressions","pbrShader.CreateInput(\"metallic\", .Float) \/\/ With implicit member expressions"],"type":"codeListing"},{"syntax":"swift","code":["let xform1 = stage.DefinePrim(\"\/hello\", pxr.TfToken.UsdGeomTokens.Xform) \/\/ Without implicit member expressions","let xform2 = stage.DefinePrim(\"\/hello\/world\", .UsdGeomTokens.Xform) \/\/ With implicit member expressions"],"type":"codeListing"},{"level":3,"anchor":"Nested-enums","text":"Nested enums","type":"heading"},{"inlineContent":[{"type":"text","text":"C++ unscoped enums nested in a namespace are not currently imported into Swift."},{"type":"text","text":" "},{"type":"text","text":"This Swift Package provides workarounds for all public enums, replacing the "},{"type":"codeVoice","code":"pxr"},{"type":"text","text":" root namespace with "},{"type":"codeVoice","code":"Overlay"},{"type":"text","text":". For example, instead of "},{"type":"codeVoice","code":"pxr.UsdStage.LoadAll"},{"type":"text","text":", use "},{"type":"codeVoice","code":"Overlay.UsdStage.LoadAll"},{"type":"text","text":"."},{"type":"text","text":"\n"},{"type":"text","text":"See "},{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedEnums","isActive":true},{"type":"text","text":" for more information."}],"type":"paragraph"},{"level":3,"anchor":"Closure-based-API-for-UsdEditContext","text":"Closure-based API for UsdEditContext","type":"heading"},{"inlineContent":[{"type":"codeVoice","code":"UsdEditContext"},{"type":"text","text":" is a non-movable type in C++ and cannot currently be imported into Swift. Instead, use "},{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/withUsdEditContext(_:_:_:)","isActive":true,"overridingTitle":"Overlay.withUsdEditContext()","overridingTitleInlineContent":[{"type":"codeVoice","code":"Overlay.withUsdEditContext()"}]},{"type":"text","text":" for RAII-like patterns in Swift. See "},{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","isActive":true},{"type":"text","text":" for more details."}],"type":"paragraph"},{"syntax":"swift","code":["let target = stage.GetEditTargetForLocalLayer(stage.GetSessionLayer())","Overlay.withUsdEditContext(stage, target) {","    let refSphere2 = stage.GetPrimAtPath(\"\/refSphere2\")","    refSphere2.SetActive(false)","}"],"type":"codeListing"},{"syntax":"swift","code":["\/\/ Add a UsdVariantSet with variant \"red\"","let rootPrim = stage.GetPrimAtPath(\"\/hello\")","let colorAttr = rootPrim.GetAttribute(.UsdGeomTokens.primvarsDisplayColor)","var vsets = rootPrim.GetVariantSets()","var vset = vsets.AddVariantSet(\"shadingVariant\", .UsdListPositionBackOfPrependList)","vset.AddVariant(\"red\", .UsdListPositionBackOfPrependList)","","\/\/ Author a color in the \"red\" variant","vset.SetVariantSelection(\"red\")","Overlay.withUsdEditContext(vset.GetVariantEditContext(pxr.SdfLayerHandle())) {","    let colorValue: pxr.VtVec3fArray = [pxr.GfVec3f(1, 0, 0)]","    colorAttr.Set(colorValue, pxr.UsdTimeCode.Default())","}"],"type":"codeListing"}]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"kind":"article","references":{"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfMatrix4d/MakeRotate(_:)":{"type":"topic","kind":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/gfmatrix4d\/makerotate(_:)","abstract":[{"text":"Wrapper for ","type":"text"},{"type":"codeVoice","code":"pxr.GfMatrix().SetRotate(r)"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix4d\/MakeRotate(_:)","title":"MakeRotate(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MakeRotate"},{"kind":"text","text":"("},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@GfRotation","kind":"typeIdentifier","text":"GfRotation"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@GfMatrix4d","kind":"typeIdentifier","text":"GfMatrix4d"}]},"doc://SwiftUsd/documentation/SwiftUsd/CheckingForValidity":{"role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","abstract":[{"text":"Checking for ","type":"text"},{"code":"IsValid()","type":"codeVoice"},{"text":" and null pointers in Swift","type":"text"}],"title":"Checking for validity","url":"\/documentation\/swiftusd\/checkingforvalidity","kind":"article","type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/CurrentLimitations":{"type":"topic","title":"Current Limitations","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CurrentLimitations","kind":"article","abstract":[{"type":"text","text":"Learn about the current limitations of OpenUSD in Swift"}],"role":"article","url":"\/documentation\/swiftusd\/currentlimitations"},"doc://SwiftUsd/documentation/SwiftUsd/Capabilities":{"type":"topic","title":"Capabilities","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Capabilities","kind":"article","abstract":[{"type":"text","text":"Learn about the current capabilities of OpenUSD in Swift"}],"role":"article","url":"\/documentation\/swiftusd\/capabilities"},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","title":"OpenUSD","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","type":"topic","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/Dereference(_:)-3edgv":{"type":"topic","role":"symbol","title":"Dereference(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/Dereference(_:)-3edgv","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Dereference"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE11Dereferencey15_TfWeakBaseTypeQzxAbCE01_eF11PtrProtocolRzlFZ1TL_xmfp","text":"T"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE11Dereferencey15_TfWeakBaseTypeQzxAbCE01_eF11PtrProtocolRzlFZ1TL_xmfp","text":"T"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfWeakPtrProtocolP01_dE8BaseTypeQa","text":"_TfWeakBaseType"}],"kind":"symbol","abstract":[{"text":"Dereferences a ","type":"text"},{"type":"codeVoice","code":"pxr::TfWeakPtr<T>"},{"text":". Crashes if the pointer is null","type":"text"}],"url":"\/documentation\/openusd\/c++\/overlay\/dereference(_:)-3edgv"},"doc://SwiftUsd/documentation/SwiftUsd/UsingEditContexts":{"kind":"article","url":"\/documentation\/swiftusd\/usingeditcontexts","title":"Using edit contexts","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","abstract":[{"type":"text","text":"Using "},{"type":"codeVoice","code":"pxr.UsdEditContext"},{"type":"text","text":" in Swift"}],"role":"collectionGroup"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/Dereference(_:)-67vpz":{"type":"topic","role":"symbol","title":"Dereference(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/Dereference(_:)-67vpz","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Dereference"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE11Dereferencey14_TfRefBaseTypeQzxAbCE01_eF11PtrProtocolRzlFZ1TL_xmfp","text":"T"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE11Dereferencey14_TfRefBaseTypeQzxAbCE01_eF11PtrProtocolRzlFZ1TL_xmfp","text":"T"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE17_TfRefPtrProtocolP01_dE8BaseTypeQa","text":"_TfRefBaseType"}],"kind":"symbol","abstract":[{"text":"Dereferences a ","type":"text"},{"type":"codeVoice","code":"pxr::TfRefPtr<T>"},{"text":". Crashes if the pointer is null","type":"text"}],"url":"\/documentation\/openusd\/c++\/overlay\/dereference(_:)-67vpz"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/TfWeakPtr(_:)-8de9g":{"url":"\/documentation\/openusd\/c++\/overlay\/tfweakptr(_:)-8de9g","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TfWeakPtr"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE9TfWeakPtry01_deF4TypeQzxSgAbCE01_dE12BaseProtocolRzlFZ1TL_xmfp","kind":"typeIdentifier","text":"T"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE9TfWeakPtry01_deF4TypeQzxSgAbCE01_dE12BaseProtocolRzlFZ1TL_xmfp","kind":"typeIdentifier","text":"T"},{"kind":"text","text":"."},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE19_TfWeakBaseProtocolP01_dE7PtrTypeQa","kind":"typeIdentifier","text":"_TfWeakPtrType"}],"abstract":[{"text":"Wraps the argument in a ","type":"text"},{"type":"codeVoice","code":"pxr::TfWeakPtr<T>"}],"title":"TfWeakPtr(_:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfWeakPtr(_:)-8de9g","type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/WrappedTypes":{"url":"\/documentation\/swiftusd\/wrappedtypes","abstract":[],"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","title":"Wrapped types"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","title":"struct UsdPrimTypeInfoWrapper","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/GfMatrix4d/MakeTranslate(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MakeTranslate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"GfVec3d","preciseIdentifier":"c:@N@pxr@S@GfVec3d"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"GfMatrix4d","preciseIdentifier":"c:@N@pxr@S@GfMatrix4d"}],"role":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/gfmatrix4d\/maketranslate(_:)","title":"MakeTranslate(_:)","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/GfMatrix4d\/MakeTranslate(_:)","abstract":[{"text":"Wrapper for ","type":"text"},{"type":"codeVoice","code":"pxr.GfMatrix().SetTranslate(v)"}]},"doc://SwiftUsd/documentation/SwiftUsd/GettingStarted":{"url":"\/documentation\/swiftusd\/gettingstarted","role":"article","type":"topic","title":"Getting Started with OpenUSD","abstract":[{"text":"Adding SwiftUsd to your project or package","type":"text"}],"kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/withUsdEditContext(_:_:_:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withUsdEditContext"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdStage","text":"UsdStage"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdEditTarget","text":"UsdEditTarget"},{"kind":"text","text":", () "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ("},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE18withUsdEditContextyxSo021pxrInternal_v0_25_8__H10Reserved__O0E5StageV_AF0eF6TargetVxyKXEtKlFZ1TL_xmfp","text":"T"},{"kind":"text","text":")) "},{"kind":"keyword","text":"rethrows"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE18withUsdEditContextyxSo021pxrInternal_v0_25_8__H10Reserved__O0E5StageV_AF0eF6TargetVxyKXEtKlFZ1TL_xmfp","text":"T"}],"url":"\/documentation\/openusd\/c++\/overlay\/withusdeditcontext(_:_:_:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/withUsdEditContext(_:_:_:)","abstract":[{"type":"text","text":"Performs an edit using the edit target."}],"type":"topic","title":"withUsdEditContext(_:_:_:)"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:)-99j13":{"type":"topic","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-99j13","abstract":[{"text":"Register a listener as being interested in a TfNotice, regardless of sender.","type":"text"}],"title":"Register(_:_:)","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:)-99j13","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":">(","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp","text":"Notice","kind":"typeIdentifier"},{"text":".Type, (","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp","text":"Notice","kind":"typeIdentifier"},{"text":") -> ()) -> ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","text":"SwiftKey","kind":"typeIdentifier"}]},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfNotice":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","kind":"article","title":"Working with TfNotice","abstract":[{"type":"text","text":"Learn how to use the TfNotice notification subsystem in Swift"}],"url":"\/documentation\/swiftusd\/workingwithtfnotice","type":"topic","role":"article"},"doc://SwiftUsd/documentation/SwiftUsd/WrappedEnums":{"role":"article","abstract":[],"kind":"article","type":"topic","url":"\/documentation\/swiftusd\/wrappedenums","title":"Wrapped enums","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedEnums"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Capabilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CurrentLimitations"],"anchor":"Essentials","generated":true,"title":"Essentials"}],"op":"replace","path":"\/seeAlsoSections"},{"value":"UsdPrimTypeInfoWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/title"},{"value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/fragments"},{"value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}