{"metadata":{"title":"Foreign Reference Types and Smart Pointers","role":"article","modules":[{"name":"OpenUSD"}],"roleHeading":"Article"},"abstract":[{"type":"text","text":"Learn about "},{"code":"pxr::TfRefPtr","type":"codeVoice"},{"type":"text","text":" and "},{"code":"pxr::TfWeakPtr","type":"codeVoice"},{"type":"text","text":" in Swift"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"seeAlsoSections":[{"anchor":"Working-with-foreign-reference-types","title":"Working with foreign reference types","generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WhatIsAForeignReferenceType","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CastingBetweenForeignReferenceTypes"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In C++, types that inherit from "},{"type":"codeVoice","code":"pxr::TfRefBase"},{"type":"text","text":" should be used via the "},{"type":"codeVoice","code":"pxr::TfRefPtr<T>"},{"type":"text","text":" templated smart pointer. This smart pointer manipulates the reference count of the underlying value, ensuring that the lifetime of resources is managed properly and safely. But when using SwiftUsd to write Swift code, types that inherit from "},{"type":"codeVoice","code":"pxr::TfRefBase"},{"type":"text","text":" are marked as "},{"type":"codeVoice","code":"SWIFT_SHARED_REFERENCE"},{"type":"text","text":", meaning they can be used directly in Swift with automatic reference counting."}]},{"type":"paragraph","inlineContent":[{"text":"Using ","type":"text"},{"code":"SWIFT_SHARED_REFERENCE","type":"codeVoice"},{"text":" types directly improves the ergonomics of Swift code while maintaining the memory safety and lifetime guarantees of ","type":"text"},{"code":"pxr::TfRefPtr<T>","type":"codeVoice"},{"text":". You can use the ","type":"text"},{"code":"SWIFT_SHARED_REFERENCE","type":"codeVoice"},{"text":" type (for example, ","type":"text"},{"code":"pxr.UsdStage","type":"codeVoice"},{"text":") as the types of variables instead of ","type":"text"},{"code":"pxr.TfRefPtr<pxr.UsdStage>","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"pxr.UsdStageRefPtr","type":"codeVoice"},{"text":" (a typealias for ","type":"text"},{"code":"pxr::TfRefPtr<pxr::UsdStage>","type":"codeVoice"},{"text":"), and you can directly call methods on the ","type":"text"},{"code":"SWIFT_SHARED_REFERENCE","type":"codeVoice"},{"text":" type that aren’t available directly on the ","type":"text"},{"code":"pxr::TfRefPtr<T>","type":"codeVoice"},{"text":". For these reasons, when working with Swift code, prefer using the ","type":"text"},{"code":"SWIFT_SHARED_REFERENCE","type":"codeVoice"},{"text":" types directly.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In C++, types that inherit from "},{"type":"codeVoice","code":"pxr::TfWeakBase"},{"type":"text","text":" can be used via the "},{"type":"codeVoice","code":"pxr::TfWeakPtr<T>"},{"type":"text","text":" templated smart pointer. This smart pointer detects when the underlying value is deleted, without maintaining a strong reference to the underlying value. When C++ types inherit from both "},{"type":"codeVoice","code":"pxr::TfRefBase"},{"type":"text","text":" and "},{"type":"codeVoice","code":"pxr::TfWeakBase"},{"type":"text","text":", they are marked as "},{"type":"codeVoice","code":"SWIFT_SHARED_REFERENCE"},{"type":"text","text":". Since "},{"type":"codeVoice","code":"pxr::TfWeakPtr<T>"},{"type":"text","text":" suffers from similar ergonomics issues as "},{"type":"codeVoice","code":"pxr::TfRefPtr<T>"},{"type":"text","text":", you should avoid using "},{"type":"codeVoice","code":"pxr::TfWeakPtr<T>"},{"type":"text","text":"’s in your code. If you need to detect when an underlying value is deleted without maintaining a strong reference, use "},{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/WeakReferenceHolder","isActive":true},{"type":"text","text":" instead."}]},{"type":"heading","anchor":"Using-OpenUSD-APIs","level":2,"text":"Using OpenUSD APIs"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since the OpenUSD APIs are written using smart pointers, but Swift code should use "},{"type":"codeVoice","code":"SWIFT_SHARED_REFERENCE"},{"type":"text","text":" types directly instead of smart pointers, you may need to convert to and from smart pointers. For example, you should use "},{"type":"reference","overridingTitle":"Overlay.TfWeakPtr(_:)","overridingTitleInlineContent":[{"code":"Overlay.TfWeakPtr(_:)","type":"codeVoice"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfWeakPtr(_:)-8de9g","isActive":true},{"type":"text","text":" when calling the function "},{"type":"codeVoice","code":"pxr::TfToken pxr::UsdGeomGetStageUpAxis(const pxr::UsdStageWeakPtr& stage);"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use "},{"type":"reference","overridingTitle":"Overlay.DereferenceOrNil(_:)","overridingTitleInlineContent":[{"type":"codeVoice","code":"Overlay.DereferenceOrNil(_:)"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/DereferenceOrNil(_:)-4yt4i","isActive":true},{"type":"text","text":" to conditionally convert a smart pointer to its underlying type. If the smart pointer was pointing to null, Swift returns a "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" optional value."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Use ","type":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/Dereference(_:)-67vpz","type":"reference","overridingTitle":"Overlay.Dereference(_:)","isActive":true,"overridingTitleInlineContent":[{"type":"codeVoice","code":"Overlay.Dereference(_:)"}]},{"text":" to unconditionall convert a smart pointer to its underlying type. If the smart pointer was pointing to null, Swift terminates with an “unexpectedly found nil” error message.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Use ","type":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfRefPtr(_:)-7quy3","isActive":true,"type":"reference","overridingTitle":"Overlay.TfRefPtr(_:)","overridingTitleInlineContent":[{"type":"codeVoice","code":"Overlay.TfRefPtr(_:)"}]},{"text":" to create a ","type":"text"},{"type":"codeVoice","code":"pxr::TfRefPtr<T>"},{"text":" that strongly points to a ","type":"text"},{"type":"codeVoice","code":"SWIFT_SHARED_REFERENCE"},{"text":" type.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Use ","type":"text"},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"Overlay.TfWeakPtr(_:)"}],"isActive":true,"overridingTitle":"Overlay.TfWeakPtr(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfWeakPtr(_:)-8de9g","type":"reference"},{"text":" to create a ","type":"text"},{"code":"pxr::TfWeakPtr<T>","type":"codeVoice"},{"text":" that weakly points to a ","type":"text"},{"code":"SWIFT_SHARED_REFERENCE","type":"codeVoice"},{"text":" type.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use "},{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/Bool\/init(_:)-63kny","overridingTitle":"Bool.init(_:)","overridingTitleInlineContent":[{"type":"codeVoice","code":"Bool.init(_:)"}]},{"type":"text","text":" to determine whether a "},{"code":"pxr::TfRefPtr<T>","type":"codeVoice"},{"type":"text","text":" points to a valid instance or to null"}]}]},{"content":[{"inlineContent":[{"text":"Use ","type":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/Bool\/init(_:)-6azcc","isActive":true,"type":"reference","overridingTitleInlineContent":[{"code":"Bool.init(_:)","type":"codeVoice"}],"overridingTitle":"Bool.init(_:)"},{"text":" to determine whether a ","type":"text"},{"code":"pxr::TfWeakPtr<T>","type":"codeVoice"},{"text":" currently points to a valid instance or to null. (Keep in mind that a ","type":"text"},{"code":"pxr::TfWeakPtr<T>","type":"codeVoice"},{"text":" that currently points to a valid instance could point to null the next time it is used, even if that’s in the very next line of code.)","type":"text"}],"type":"paragraph"}]}]},{"type":"aside","style":"warning","content":[{"inlineContent":[{"text":"When mixing custom Swift and C++ code in the same target or project, using ","type":"text"},{"code":"SWIFT_SHARED_REFERENCE","type":"codeVoice"},{"text":" types directly can cause memory safety issues if you aren’t careful. See ","type":"text"},{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxInteropMemorySafety","type":"reference"},{"text":" for how to avoid these issues.","type":"text"}],"type":"paragraph"}],"name":"Warning"}]}],"kind":"article","variants":[{"paths":["\/documentation\/swiftusd\/foreignreferencetypesandsmartpointers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/foreignreferencetypesandsmartpointers"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ForeignReferenceTypesAndSmartPointers"},"references":{"doc://SwiftUsd/documentation/SwiftUsd/SwiftCxxInteropMemorySafety":{"type":"topic","url":"\/documentation\/swiftusd\/swiftcxxinteropmemorysafety","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxInteropMemorySafety","abstract":[{"text":"Learn how to avoid unsafe memory management issues when using Swift-Cxx interop","type":"text"}],"kind":"article","title":"Swift-Cxx Interop and Memory Safety","role":"article"},"doc://SwiftUsd/documentation/OpenUSD/Swift/Bool/init(_:)-63kny":{"type":"topic","abstract":[{"type":"text","text":"Returns "},{"code":"true","type":"codeVoice"},{"type":"text","text":" if the pointer is not null"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/Bool\/init(_:)-63kny","title":"init(_:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@Overlay","kind":"typeIdentifier","text":"Overlay"},{"kind":"text","text":"."},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE17_TfRefPtrProtocolP","kind":"typeIdentifier","text":"_TfRefPtrProtocol"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","url":"\/documentation\/openusd\/swift\/bool\/init(_:)-63kny"},"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","url":"\/documentation\/openusd","kind":"symbol","role":"collection","title":"OpenUSD","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/Dereference(_:)-67vpz":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/Dereference(_:)-67vpz","kind":"symbol","abstract":[{"type":"text","text":"Dereferences a "},{"type":"codeVoice","code":"pxr::TfRefPtr<T>"},{"type":"text","text":". Crashes if the pointer is null"}],"role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Dereference"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE11Dereferencey14_TfRefBaseTypeQzxAbCE01_eF11PtrProtocolRzlFZ1TL_xmfp","text":"T"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE11Dereferencey14_TfRefBaseTypeQzxAbCE01_eF11PtrProtocolRzlFZ1TL_xmfp","text":"T"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE17_TfRefPtrProtocolP01_dE8BaseTypeQa","text":"_TfRefBaseType"}],"title":"Dereference(_:)","url":"\/documentation\/openusd\/c++\/overlay\/dereference(_:)-67vpz"},"doc://SwiftUsd/documentation/OpenUSD/Swift/Bool/init(_:)-6azcc":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@Overlay","kind":"typeIdentifier","text":"Overlay"},{"kind":"text","text":"."},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfWeakPtrProtocolP","kind":"typeIdentifier","text":"_TfWeakPtrProtocol"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns "},{"code":"true","type":"codeVoice"},{"type":"text","text":" if the pointer is not null."}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/Bool\/init(_:)-6azcc","role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/swift\/bool\/init(_:)-6azcc","title":"init(_:)"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/WeakReferenceHolder":{"title":"Overlay.WeakReferenceHolder","type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/WeakReferenceHolder","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WeakReferenceHolder","kind":"identifier"}],"navigatorTitle":[{"text":"WeakReferenceHolder","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Holds a ","type":"text"},{"code":"pxr::TfWeakBase","type":"codeVoice"},{"text":" subclass weakly","type":"text"}],"url":"\/documentation\/openusd\/c++\/overlay\/weakreferenceholder"},"doc://SwiftUsd/documentation/SwiftUsd/WhatIsAForeignReferenceType":{"role":"article","kind":"article","type":"topic","url":"\/documentation\/swiftusd\/whatisaforeignreferencetype","abstract":[{"text":"Learn about foreign reference types and how to use them","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WhatIsAForeignReferenceType","title":"What is a Foreign Reference Type?"},"doc://SwiftUsd/documentation/SwiftUsd/CastingBetweenForeignReferenceTypes":{"kind":"article","abstract":[{"type":"text","text":"Learn about casting with Foreign Reference Types"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CastingBetweenForeignReferenceTypes","url":"\/documentation\/swiftusd\/castingbetweenforeignreferencetypes","role":"article","title":"Casting between Foreign Reference Types","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/TfRefPtr(_:)-7quy3":{"abstract":[{"type":"text","text":"Wraps the argument in a "},{"type":"codeVoice","code":"pxr::TfRefPtr<T>"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TfRefPtr"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE8TfRefPtry01_deF4TypeQzxSgAbCE01_dE12BaseProtocolRzlFZ1TL_xmfp","text":"T"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE8TfRefPtry01_deF4TypeQzxSgAbCE01_dE12BaseProtocolRzlFZ1TL_xmfp","text":"T"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolP01_dE7PtrTypeQa","text":"_TfRefPtrType"}],"title":"TfRefPtr(_:)","url":"\/documentation\/openusd\/c++\/overlay\/tfrefptr(_:)-7quy3","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfRefPtr(_:)-7quy3"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/TfWeakPtr(_:)-8de9g":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TfWeakPtr"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE9TfWeakPtry01_deF4TypeQzxSgAbCE01_dE12BaseProtocolRzlFZ1TL_xmfp"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE9TfWeakPtry01_deF4TypeQzxSgAbCE01_dE12BaseProtocolRzlFZ1TL_xmfp"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"_TfWeakPtrType","preciseIdentifier":"s:So7OverlayO7OpenUSDE19_TfWeakBaseProtocolP01_dE7PtrTypeQa"}],"url":"\/documentation\/openusd\/c++\/overlay\/tfweakptr(_:)-8de9g","title":"TfWeakPtr(_:)","abstract":[{"text":"Wraps the argument in a ","type":"text"},{"code":"pxr::TfWeakPtr<T>","type":"codeVoice"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/TfWeakPtr(_:)-8de9g"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/DereferenceOrNil(_:)-4yt4i":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DereferenceOrNil","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE16DereferenceOrNily14_TfRefBaseTypeQzSgxAbCE01_gH11PtrProtocolRzlFZ1TL_xmfp","text":"T","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE16DereferenceOrNily14_TfRefBaseTypeQzSgxAbCE01_gH11PtrProtocolRzlFZ1TL_xmfp","text":"T","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE17_TfRefPtrProtocolP01_dE8BaseTypeQa","text":"_TfRefBaseType","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/DereferenceOrNil(_:)-4yt4i","abstract":[{"text":"Dereferences a ","type":"text"},{"code":"pxr::TfRefPtr<T>","type":"codeVoice"},{"text":", returning either ","type":"text"},{"code":"T","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"nil","type":"codeVoice"}],"title":"DereferenceOrNil(_:)","type":"topic","url":"\/documentation\/openusd\/c++\/overlay\/dereferenceornil(_:)-4yt4i","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"anchor":"Working-with-foreign-reference-types","title":"Working with foreign reference types","generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WhatIsAForeignReferenceType","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CastingBetweenForeignReferenceTypes"]}]}],"traits":[{"interfaceLanguage":"occ"}]}]}