{"kind":"article","variants":[{"paths":["\/documentation\/swiftusd\/gettingstartedincplusplus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/gettingstartedincplusplus"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"content":[{"type":"heading","text":"Getting Started","anchor":"Getting-Started","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Before you can start using SwiftUsd, you need to add it as a dependency to your Xcode project or Swift Package, and then configure a few build settings."}]},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"Despite the fact that SwiftUsd is a Swift Package, you can use it in a pure-C++ Xcode project\/target, as well as in a pure-C++ Swift Package target.","type":"text"}]}],"name":"Note"},{"type":"aside","style":"important","content":[{"type":"paragraph","inlineContent":[{"text":"Swift Package targets cannot mix Swift and C++ code in a single target. ","type":"text"},{"identifier":"https:\/\/github.com\/swiftlang\/swift-package-manager\/issues\/8945","isActive":true,"type":"reference"}]}],"name":"Important"},{"type":"paragraph","inlineContent":[{"text":"To do so, follow the steps in ","type":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted#Getting-Started","type":"reference","isActive":true,"overridingTitle":"Getting Started for Swift","overridingTitleInlineContent":[{"type":"text","text":"Getting Started for Swift"}]},{"text":". If you’re using a pure-C++ target, you don’t need to change the ","type":"text"},{"type":"codeVoice","code":"C++ and Objective-C Interoperability"},{"text":" mode in Xcode or add ","type":"text"},{"type":"codeVoice","code":".interoperabilityMode(.Cxx)"},{"text":" to your target’s ","type":"text"},{"type":"codeVoice","code":"swiftSettings"},{"text":" in your Swift Package manifest.","type":"text"}]},{"type":"heading","text":"Using SwiftUsd","anchor":"Using-SwiftUsd","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"Once you’ve added SwiftUsd as a package dependency to your Xcode project or Swift package and set the C++ version to GNU++17, you’re ready to start using SwiftUsd:"}]},{"type":"codeListing","syntax":"c++","code":["#include <iostream>","#include \"pxr\/usd\/usd\/stage.h\"","#include \"pxr\/usd\/usd\/prim.h\"","#include \"pxr\/usd\/usdGeom\/tokens.h\"","","std::string makeHelloWorldString() {","    pxr::UsdStageRefPtr stage = pxr::UsdStage::CreateInMemory();","    stage->DefinePrim(pxr::SdfPath(\"\/hello\"), pxr::UsdGeomTokens->Cube);","    stage->DefinePrim(pxr::SdfPath(\"\/hello\/world\"), pxr::UsdGeomTokens->Sphere);","    std::string result;","    stage->ExportToString(&result);","    return result;","}","","int main(int argc, const char * argv[]) {","    std::cout << makeHelloWorldString() << std::endl;","    return 0;","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use new functions or types added by SwiftUsd, include the SwiftUsd umbrella header:"}]},{"type":"codeListing","syntax":"c++","code":["#include \"swiftUsd\/swiftUsd.h\""]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This header lets you use macros useful for Swift-Cxx interop, functions that are important for memory safety with Swift-Cxx interop, and Swift wrapper types for C++ types not imported by Swift-Cxx interop."}]},{"style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Don’t include other files in "},{"type":"codeVoice","code":"OpenUSD\/swiftUsd"},{"type":"text","text":", as they are implementation details and may change without warning"}]}],"type":"aside"}],"kind":"content"}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStartedInCPlusPlus","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"title":"Using SwiftUsd from C++","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxInteropMemorySafety","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxMacros"],"anchor":"Using-SwiftUsd-from-C++"}],"abstract":[{"type":"text","text":"Using SwiftUsd from C++"}],"sections":[],"metadata":{"modules":[{"name":"OpenUSD"}],"roleHeading":"Article","role":"article","title":"Getting Started In C++"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"references":{"doc://SwiftUsd/documentation/SwiftUsd/GettingStarted#Getting-Started":{"kind":"section","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted#Getting-Started","type":"topic","title":"Getting Started","url":"\/documentation\/swiftusd\/gettingstarted#Getting-Started","abstract":[]},"https://github.com/swiftlang/swift-package-manager/issues/8945":{"identifier":"https:\/\/github.com\/swiftlang\/swift-package-manager\/issues\/8945","titleInlineContent":[{"type":"text","text":"https:\/\/github.com\/swiftlang\/swift-package-manager\/issues\/8945: Support Swift-Cxx reverse interop, bidirectional interop, and mixed Swift-Cxx targets"}],"type":"link","url":"https:\/\/github.com\/swiftlang\/swift-package-manager\/issues\/8945","title":"https:\/\/github.com\/swiftlang\/swift-package-manager\/issues\/8945: Support Swift-Cxx reverse interop, bidirectional interop, and mixed Swift-Cxx targets"},"doc://SwiftUsd/documentation/SwiftUsd/SwiftCxxInteropMemorySafety":{"kind":"article","type":"topic","role":"article","url":"\/documentation\/swiftusd\/swiftcxxinteropmemorysafety","title":"Swift-Cxx Interop and Memory Safety","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxInteropMemorySafety","abstract":[{"text":"Learn how to avoid unsafe memory management issues when using Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/SwiftUsd/SwiftCxxMacros":{"abstract":[{"type":"text","text":"Learn about useful Swift-Cxx macros for writing C++ code used by Swift"}],"title":"Swift-Cxx Macros","type":"topic","kind":"article","url":"\/documentation\/swiftusd\/swiftcxxmacros","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxMacros","role":"article"},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","type":"topic","url":"\/documentation\/openusd","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxInteropMemorySafety","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxMacros"],"anchor":"Using-SwiftUsd-from-C++","title":"Using SwiftUsd from C++"}],"path":"\/seeAlsoSections","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}