{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedEnums"},"sections":[],"kind":"article","seeAlsoSections":[{"generated":true,"title":"Wrapped symbol documentation","anchor":"Wrapped-symbol-documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedFunctions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedOperators"]}],"variants":[{"paths":["\/documentation\/swiftusd\/wrappedenums"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/wrappedenums"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"OpenUSD"}],"title":"Wrapped enums","roleHeading":"Article","role":"article"},"primaryContentSections":[{"content":[{"type":"heading","anchor":"Overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Most public enums in OpenUSD aren’t correctly imported due to a bug in Swift-Cxx interop: ","type":"text"},{"identifier":"https:\/\/github.com\/swiftlang\/swift\/issues\/62127","type":"reference","isActive":true},{"text":"","type":"text"},{"text":"\n","type":"text"},{"text":"This Swift Package provides a workaround by migrating the enums to the ","type":"text"},{"type":"codeVoice","code":"Overlay"},{"text":" namespace. For example,","type":"text"}]},{"type":"codeListing","code":["let stage = Overlay.Dereference(pxr.UsdStage.CreateInMemory(pxr.UsdStage.LoadAll)) \/\/ error: can't find pxr.UsdStage.LoadAll","let stage = Overlay.Dereference(pxr.UsdStage.CreateInMemory(Overlay.UsdStage.LoadAll)) \/\/ success: finds Overlay.UsdStage.LoadAll"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Additionally, when Swift can infer the type of the enum, you can use implicit member expressions. For example,"}]},{"type":"codeListing","code":["let stage = Overlay.Dereference(pxr.UsdStage.CreateInMemory(.LoadAll)) \/\/ success: infers pxr.UsdStage.LoadAll"],"syntax":"swift"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"type":"topic","url":"\/documentation\/openusd\/overlay","fragments":[{"kind":"identifier","text":"Overlay"}],"title":"Overlay"},"https://github.com/swiftlang/swift/issues/62127":{"type":"link","identifier":"https:\/\/github.com\/swiftlang\/swift\/issues\/62127","title":"https:\/\/github.com\/swiftlang\/swift\/issues\/62127: C++ interop: nested enum not imported","titleInlineContent":[{"type":"text","text":"https:\/\/github.com\/swiftlang\/swift\/issues\/62127: C++ interop: nested enum not imported"}],"url":"https:\/\/github.com\/swiftlang\/swift\/issues\/62127"},"doc://SwiftUsd/documentation/SwiftUsd/WrappedFunctions":{"url":"\/documentation\/swiftusd\/wrappedfunctions","abstract":[],"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedFunctions","title":"Wrapped functions"},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","title":"OpenUSD","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","type":"topic","abstract":[]},"doc://SwiftUsd/documentation/SwiftUsd/WrappedOperators":{"url":"\/documentation\/swiftusd\/wrappedoperators","abstract":[],"type":"topic","kind":"article","role":"collectionGroup","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedOperators","title":"Wrapped operators"},"doc://SwiftUsd/documentation/SwiftUsd/WrappedTypes":{"url":"\/documentation\/swiftusd\/wrappedtypes","abstract":[],"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","title":"Wrapped types"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Wrapped-symbol-documentation","title":"Wrapped symbol documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedFunctions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedOperators"]}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"text":"Overlay","kind":"identifier"}],"op":"add"}]}]}