{"sections":[],"kind":"article","metadata":{"roleHeading":"API Collection","modules":[{"name":"OpenUSD"}],"role":"collectionGroup","title":"Wrapped operators"},"topicSections":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/*(_:_:)-4u2ih","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/*(_:_:)-770lp"],"anchor":"Topics"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedOperators"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftusd\/wrappedoperators"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/swiftusd\/wrappedoperators"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"seeAlsoSections":[{"title":"Wrapped symbol documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedEnums","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedFunctions"],"generated":true,"anchor":"Wrapped-symbol-documentation"}],"references":{"doc://SwiftUsd/documentation/OpenUSD":{"role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","abstract":[],"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol"},"doc://SwiftUsd/documentation/SwiftUsd/WrappedTypes":{"url":"\/documentation\/swiftusd\/wrappedtypes","type":"topic","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","role":"collectionGroup","abstract":[],"title":"Wrapped types"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"kind":"identifier","text":"Overlay"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","title":"Overlay","type":"topic","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/*(_:_:)-770lp":{"title":"*(_:_:)","url":"\/documentation\/openusd\/*(_:_:)-770lp","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/*(_:_:)-770lp","type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"*"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"GfVec3f","preciseIdentifier":"c:@N@pxr@S@GfVec3f"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"GfVec3f","preciseIdentifier":"c:@N@pxr@S@GfVec3f"}],"role":"symbol"},"doc://SwiftUsd/documentation/SwiftUsd/WrappedFunctions":{"kind":"article","url":"\/documentation\/swiftusd\/wrappedfunctions","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedFunctions","abstract":[],"title":"Wrapped functions","role":"collectionGroup"},"doc://SwiftUsd/documentation/OpenUSD/*(_:_:)-4u2ih":{"title":"*(_:_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/*(_:_:)-4u2ih","url":"\/documentation\/openusd\/*(_:_:)-4u2ih","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"*","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"GfVec3f","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@GfVec3f"},{"text":", ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":") -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"GfVec3f","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@GfVec3f"}],"type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/WrappedEnums":{"url":"\/documentation\/swiftusd\/wrappedenums","role":"article","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedEnums","type":"topic","kind":"article","title":"Wrapped enums"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":[{"title":"Wrapped symbol documentation","anchor":"Wrapped-symbol-documentation","generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedEnums","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedFunctions"]}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"text":"Overlay","kind":"identifier"}],"op":"add"}],"traits":[{"interfaceLanguage":"occ"}]}]}