{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"text":"The source code for these symbols can be found at ","type":"text"},{"type":"codeVoice","code":"source\/Wrappers"},{"text":". Only a subset of unavailable symbols are provided; if you need a wrapper type not provided by this Swift Package, you can write your own.","type":"text"}],"type":"paragraph"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Typedefs","title":"Typedefs","abstract":[{"text":"Since Swift-Cxx interop doesn’t currently support specializing class templates from Swift, these typedefs are provided under ","type":"text"},{"code":"Overlay","type":"codeVoice"}],"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiBlitCmds_SharedPtr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdStagePtr_UsdEditTarget_Pair","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/String_Vector","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Double_Vector","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GfVec4f_Vector","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdGeomXformOp_Vector","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAttribute_Vector","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdRelationship_Vector","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/String_Set","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfLayerHandle_Set"]},{"anchor":"Namespace-Overlay","title":"Namespace Overlay","abstract":[{"type":"text","text":"Access these types by prefixing their name with "},{"type":"codeVoice","code":"Overlay"}],"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfErrorMarkWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper"]}],"kind":"article","metadata":{"role":"collectionGroup","modules":[{"name":"OpenUSD"}],"roleHeading":"API Collection","title":"Wrapped types"},"seeAlsoSections":[{"title":"Wrapped symbol documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedEnums","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedFunctions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedOperators"],"generated":true,"anchor":"Wrapped-symbol-documentation"}],"variants":[{"paths":["\/documentation\/swiftusd\/wrappedtypes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/wrappedtypes"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/String_Vector":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/String_Vector","title":"String_Vector","abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/string_vector","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String_Vector","kind":"identifier"}],"navigatorTitle":[{"text":"String_Vector","kind":"identifier"}]},"doc://SwiftUsd/documentation/SwiftUsd/WrappedEnums":{"url":"\/documentation\/swiftusd\/wrappedenums","role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedEnums","title":"Wrapped enums","type":"topic","abstract":[],"kind":"article"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdAppUtilsFrameRecorderWrapper":{"url":"\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"navigatorTitle":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"title":"class UsdAppUtilsFrameRecorderWrapper","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper","type":"topic","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"kind":"symbol","navigatorTitle":[{"text":"HioImageWrapper","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HioImageWrapper","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper","title":"class HioImageWrapper","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/GfVec4f_Vector":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"GfVec4f_Vector"}],"navigatorTitle":[{"kind":"identifier","text":"GfVec4f_Vector"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GfVec4f_Vector","title":"GfVec4f_Vector","role":"symbol","url":"\/documentation\/openusd\/overlay\/gfvec4f_vector","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdStagePtr_UsdEditTarget_Pair":{"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdStagePtr_UsdEditTarget_Pair","kind":"identifier"}],"navigatorTitle":[{"text":"UsdStagePtr_UsdEditTarget_Pair","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdStagePtr_UsdEditTarget_Pair","title":"UsdStagePtr_UsdEditTarget_Pair","url":"\/documentation\/openusd\/overlay\/usdstageptr_usdedittarget_pair","kind":"symbol","abstract":[]},"doc://SwiftUsd/documentation/SwiftUsd/WrappedFunctions":{"title":"Wrapped functions","url":"\/documentation\/swiftusd\/wrappedfunctions","abstract":[],"type":"topic","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedFunctions","role":"collectionGroup"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/TfErrorMarkWrapper":{"navigatorTitle":[{"text":"TfErrorMarkWrapper","kind":"identifier"}],"role":"symbol","title":"struct TfErrorMarkWrapper","type":"topic","url":"\/documentation\/openusd\/overlay\/tferrormarkwrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfErrorMarkWrapper","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TfErrorMarkWrapper","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiBlitCmds_SharedPtr":{"url":"\/documentation\/openusd\/overlay\/hgiblitcmds_sharedptr","navigatorTitle":[{"kind":"identifier","text":"HgiBlitCmds_SharedPtr"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"HgiBlitCmds_SharedPtr"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiBlitCmds_SharedPtr","type":"topic","title":"HgiBlitCmds_SharedPtr"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper":{"url":"\/documentation\/openusd\/overlay\/arresolverwrapper","title":"class ArResolverWrapper","navigatorTitle":[{"kind":"identifier","text":"ArResolverWrapper"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArResolverWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"text":"Overlay","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","title":"Overlay","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdGeomXformOp_Vector":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdGeomXformOp_Vector","kind":"identifier"}],"navigatorTitle":[{"text":"UsdGeomXformOp_Vector","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/usdgeomxformop_vector","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdGeomXformOp_Vector","type":"topic","title":"UsdGeomXformOp_Vector"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper":{"title":"class HgiMetalWrapper","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiMetalWrapper","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"HgiMetalWrapper","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/SdfLayerHandle_Set":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SdfLayerHandle_Set","kind":"identifier"}],"navigatorTitle":[{"text":"SdfLayerHandle_Set","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/sdflayerhandle_set","abstract":[],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfLayerHandle_Set","kind":"symbol","type":"topic","title":"SdfLayerHandle_Set"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdAttribute_Vector":{"url":"\/documentation\/openusd\/overlay\/usdattribute_vector","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAttribute_Vector","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdAttribute_Vector"}],"role":"symbol","kind":"symbol","abstract":[],"title":"UsdAttribute_Vector","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UsdAttribute_Vector"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HgiWrapper"}],"title":"class HgiWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","url":"\/documentation\/openusd\/overlay\/hgiwrapper","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HgiWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdRelationship_Vector":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdRelationship_Vector","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"UsdRelationship_Vector","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdRelationship_Vector","abstract":[],"title":"UsdRelationship_Vector","role":"symbol","url":"\/documentation\/openusd\/overlay\/usdrelationship_vector","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","abstract":[],"url":"\/documentation\/openusd","kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Double_Vector":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Double_Vector","url":"\/documentation\/openusd\/overlay\/double_vector","type":"topic","abstract":[],"role":"symbol","title":"Double_Vector","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Double_Vector"}],"navigatorTitle":[{"kind":"identifier","text":"Double_Vector"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"title":"class UsdImagingGLEngineWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","navigatorTitle":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/String_Set":{"title":"String_Set","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String_Set","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/String_Set","type":"topic","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"String_Set","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/string_set"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper":{"url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper","navigatorTitle":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","title":"struct UsdPrimTypeInfoWrapper","type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}]},"doc://SwiftUsd/documentation/SwiftUsd/WrappedOperators":{"role":"collectionGroup","type":"topic","url":"\/documentation\/swiftusd\/wrappedoperators","title":"Wrapped operators","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedOperators","abstract":[],"kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper"],"anchor":"Namespace-Overlay","abstract":[{"text":"Access these types by prefixing their name with ","type":"text"},{"code":"Overlay","type":"codeVoice"}],"title":"Namespace Overlay"}],"path":"\/topicSections"},{"op":"replace","value":[{"generated":true,"title":"Wrapped symbol documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedEnums","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedFunctions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedOperators"],"anchor":"Wrapped-symbol-documentation"}],"path":"\/seeAlsoSections"},{"op":"replace","value":"UsdAppUtilsFrameRecorderWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"UsdAppUtilsFrameRecorderWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UsdAppUtilsFrameRecorderWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/navigatorTitle"},{"op":"replace","value":"HioImageWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HioImageWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HioImageWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle"},{"op":"replace","value":"ArResolverWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ArResolverWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ArResolverWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/navigatorTitle"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"op":"replace","value":"HgiMetalWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HgiMetalWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/fragments"},{"op":"replace","value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/navigatorTitle"},{"op":"replace","value":"HgiWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HgiWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/fragments"},{"op":"replace","value":[{"text":"HgiWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/navigatorTitle"},{"op":"replace","value":"UsdImagingGLEngineWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title"},{"op":"replace","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle"},{"op":"replace","value":"UsdPrimTypeInfoWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/title"},{"op":"replace","value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}