{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper"]]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"explicit"},{"kind":"text","text":" "},{"kind":"keyword","text":"operator"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"_Bool"},{"kind":"text","text":"() "},{"kind":"keyword","text":"const"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper\/operator_bool"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper\/operator_bool"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"OpenUSD"}],"symbolKind":"method","fragments":[{"kind":"identifier","text":"_Bool"}],"roleHeading":"Instance Method","title":"operator bool","navigatorTitle":[{"kind":"identifier","text":"operator bool"}],"role":"symbol","externalID":"c:@N@Overlay@S@UsdAppUtilsFrameRecorderWrapper@F@operator bool#1"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper\/operator_bool"},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"text":"Overlay","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdAppUtilsFrameRecorderWrapper/operator_bool":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper\/operator_bool","navigatorTitle":[{"kind":"identifier","text":"operator bool"}],"type":"topic","url":"\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper\/operator_bool","fragments":[{"kind":"identifier","text":"_Bool"}],"kind":"symbol","title":"operator bool","role":"symbol","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD":{"type":"topic","url":"\/documentation\/openusd","title":"OpenUSD","role":"collection","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdAppUtilsFrameRecorderWrapper":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"abstract":[],"title":"class UsdAppUtilsFrameRecorderWrapper","url":"\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper","navigatorTitle":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"operator bool","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"_Bool"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"operator bool"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"explicit","kind":"keyword"},{"text":" ","kind":"text"},{"text":"operator","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_Bool","kind":"typeIdentifier"},{"text":"() ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"Overlay","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"value":"operator bool","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper~1operator_bool\/title"},{"value":[{"text":"_Bool","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper~1operator_bool\/fragments"},{"value":[{"text":"operator bool","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper~1operator_bool\/navigatorTitle"},{"value":"UsdAppUtilsFrameRecorderWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/title"},{"value":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/fragments"},{"value":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}