// This file was generated by make-swift-package. Do not edit!

#ifndef SWIFTUSD_DEFINES_H
#define SWIFTUSD_DEFINES_H

#include "pxr/base/arch/defines.h"

#define SwiftUsd_PXR_ENABLE_ALEMBIC_SUPPORT 1
#define SwiftUsd_PXR_ENABLE_DRACO_SUPPORT 0
// Embree is not available on embedded platforms
#ifdef ARCH_OS_IPHONE
#define SwiftUsd_PXR_ENABLE_EMBREE_SUPPORT 0
#else
#define SwiftUsd_PXR_ENABLE_EMBREE_SUPPORT 1
#endif // #ifdef ARCH_OS_IPHONE
#define SwiftUsd_PXR_ENABLE_OPENCOLORIO_SUPPORT 0
// OpenImageIO is not available on embedded platforms
#ifdef ARCH_OS_IPHONE
#define SwiftUsd_PXR_ENABLE_OPENIMAGEIO_SUPPORT 0
#else
#define SwiftUsd_PXR_ENABLE_OPENIMAGEIO_SUPPORT 1
#endif // #ifdef ARCH_OS_IPHONE
#define SwiftUsd_PXR_ENABLE_PRMAN_SUPPORT 0
#define SwiftUsd_PXR_ENABLE_IMAGING_SUPPORT 1
#define SwiftUsd_PXR_ENABLE_USD_IMAGING_SUPPORT 1
#define SwiftUsd_PXR_ENABLE_MATERIALX_SUPPORT 1
#define SwiftUsd_PXR_ENABLE_OPENVDB_SUPPORT 0
#define SwiftUsd_PXR_ENABLE_PTEX_SUPPORT 0
#define SwiftUsd_PXR_ENABLE_PYTHON_SUPPORT 0

#endif // #ifndef SWIFTUSD_DEFINES_H