{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommitCommandBufferWaitType","kind":"identifier"}],"platforms":["macOS"]}]}],"topicSections":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType\/CommitCommandBuffer_NoWait","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType\/CommitCommandBuffer_WaitUntilCompleted","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType\/CommitCommandBuffer_WaitUntilScheduled"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper"]]},"sections":[],"metadata":{"symbolKind":"enum","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommitCommandBufferWaitType","kind":"identifier"}],"title":"CommitCommandBufferWaitType","modules":[{"name":"OpenUSD"}],"externalID":"c:@N@Overlay@S@HgiMetalWrapper@E@CommitCommandBufferWaitType","navigatorTitle":[{"text":"CommitCommandBufferWaitType","kind":"identifier"}],"roleHeading":"Enumeration"},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/CommitCommandBufferWaitType/CommitCommandBuffer_NoWait":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommitCommandBuffer_NoWait","kind":"identifier"}],"navigatorTitle":[{"text":"CommitCommandBuffer_NoWait","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType\/CommitCommandBuffer_NoWait","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype\/commitcommandbuffer_nowait","kind":"symbol","title":"CommitCommandBuffer_NoWait"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/CommitCommandBufferWaitType":{"title":"CommitCommandBufferWaitType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommitCommandBufferWaitType"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CommitCommandBufferWaitType"}],"url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype"},"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","url":"\/documentation\/openusd","kind":"symbol","role":"collection","title":"OpenUSD","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HgiMetalWrapper"}],"title":"class HgiMetalWrapper","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HgiMetalWrapper"}],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/CommitCommandBufferWaitType/CommitCommandBuffer_WaitUntilCompleted":{"abstract":[],"type":"topic","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype\/commitcommandbuffer_waituntilcompleted","kind":"symbol","title":"CommitCommandBuffer_WaitUntilCompleted","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommitCommandBuffer_WaitUntilCompleted","kind":"identifier"}],"navigatorTitle":[{"text":"CommitCommandBuffer_WaitUntilCompleted","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType\/CommitCommandBuffer_WaitUntilCompleted","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/CommitCommandBufferWaitType/CommitCommandBuffer_WaitUntilScheduled":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType\/CommitCommandBuffer_WaitUntilScheduled","navigatorTitle":[{"text":"CommitCommandBuffer_WaitUntilScheduled","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommitCommandBuffer_WaitUntilScheduled","kind":"identifier"}],"title":"CommitCommandBuffer_WaitUntilScheduled","role":"symbol","type":"topic","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype\/commitcommandbuffer_waituntilscheduled"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"kind":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","type":"topic","role":"symbol","fragments":[{"text":"Overlay","kind":"identifier"}],"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"CommitCommandBufferWaitType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"CommitCommandBufferWaitType","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"CommitCommandBufferWaitType","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType\/CommitCommandBuffer_NoWait","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType\/CommitCommandBuffer_WaitUntilCompleted","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType\/CommitCommandBuffer_WaitUntilScheduled"],"generated":true}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommitCommandBufferWaitType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"unsigned int","preciseIdentifier":"c:i","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["macOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType~1CommitCommandBuffer_NoWait\/title","value":"CommitCommandBuffer_NoWait"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType~1CommitCommandBuffer_NoWait\/fragments","value":[{"kind":"identifier","text":"CommitCommandBuffer_NoWait"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType~1CommitCommandBuffer_NoWait\/navigatorTitle","value":[{"text":"CommitCommandBuffer_NoWait","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType\/title","value":"CommitCommandBufferWaitType"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType\/fragments","value":[{"kind":"identifier","text":"CommitCommandBufferWaitType"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType\/navigatorTitle","value":[{"text":"CommitCommandBufferWaitType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/title","value":"HgiMetalWrapper"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/fragments","value":[{"text":"HgiMetalWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"HgiMetalWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType~1CommitCommandBuffer_WaitUntilCompleted\/title","value":"CommitCommandBuffer_WaitUntilCompleted"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType~1CommitCommandBuffer_WaitUntilCompleted\/fragments","value":[{"kind":"identifier","text":"CommitCommandBuffer_WaitUntilCompleted"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType~1CommitCommandBuffer_WaitUntilCompleted\/navigatorTitle","value":[{"kind":"identifier","text":"CommitCommandBuffer_WaitUntilCompleted"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType~1CommitCommandBuffer_WaitUntilScheduled\/title","value":"CommitCommandBuffer_WaitUntilScheduled"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType~1CommitCommandBuffer_WaitUntilScheduled\/fragments","value":[{"text":"CommitCommandBuffer_WaitUntilScheduled","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType~1CommitCommandBuffer_WaitUntilScheduled\/navigatorTitle","value":[{"kind":"identifier","text":"CommitCommandBuffer_WaitUntilScheduled"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"text":"Overlay","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}