{"variants":[{"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/hgimetalwrapper-68py1"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/hgimetalwrapper-68py1"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/HgiMetalWrapper-68py1","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper"]]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"_ptr"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@N@std","kind":"identifier","text":"std"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr","kind":"typeIdentifier","text":"std::shared_ptr"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"text":".","kind":"text"},{"text":"HgiMetal","preciseIdentifier":"c:@N@pxr@S@HgiMetal","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"HgiMetalWrapper","kind":"typeIdentifier"}]}],"kind":"declarations"}],"metadata":{"title":"init(_:)","navigatorTitle":[{"kind":"identifier","text":"HgiMetalWrapper"}],"symbolKind":"init","roleHeading":"Initializer","role":"symbol","externalID":"c:@N@Overlay@S@HgiMetalWrapper@F@HgiMetalWrapper#$@N@std@N@__1@S@shared_ptr>#$@N@pxr@S@HgiMetal#","modules":[{"name":"OpenUSD"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@std","text":"std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr","text":"std::shared_ptr"},{"kind":"text","text":"<"},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiMetal","text":"HgiMetal"},{"kind":"text","text":">"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"HgiMetalWrapper"}]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper":{"url":"\/documentation\/openusd\/overlay\/hgimetalwrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiMetalWrapper","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"class HgiMetalWrapper","role":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","navigatorTitle":[{"text":"HgiMetalWrapper","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/HgiMetalWrapper-68py1":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@N@std","kind":"identifier","text":"std"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr","kind":"typeIdentifier","text":"std::shared_ptr"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@HgiMetal","kind":"typeIdentifier","text":"HgiMetal"},{"kind":"text","text":">"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"HgiMetalWrapper"}],"role":"symbol","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/hgimetalwrapper-68py1","title":"init(_:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/HgiMetalWrapper-68py1","navigatorTitle":[{"text":"HgiMetalWrapper","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"role":"symbol","url":"\/documentation\/openusd\/overlay","fragments":[{"kind":"identifier","text":"Overlay"}],"kind":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","type":"topic","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","type":"topic","url":"\/documentation\/openusd","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Constructor","op":"replace"},{"path":"\/metadata\/title","value":"HgiMetalWrapper","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HgiMetalWrapper"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HgiMetalWrapper"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"HgiMetalWrapper"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@std","text":"std"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr","text":"std::shared_ptr"},{"kind":"text","text":"<"},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiMetal","text":"HgiMetal"},{"kind":"text","text":"> "},{"kind":"internalParam","text":"_ptr"},{"kind":"text","text":");"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/title","value":"HgiMetalWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/fragments","value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"HgiMetalWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1HgiMetalWrapper-68py1\/title","value":"HgiMetalWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1HgiMetalWrapper-68py1\/fragments","value":[{"kind":"identifier","text":"HgiMetalWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1HgiMetalWrapper-68py1\/navigatorTitle","value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"text":"Overlay","kind":"identifier"}],"op":"add"}]}]}