{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ReleaseSecondaryCommandBuffer"}],"role":"symbol","title":"ReleaseSecondaryCommandBuffer(_:)","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReleaseSecondaryCommandBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<MTLCommandBuffer>","preciseIdentifier":"c:Qoobjc(pl)MTLCommandBuffer","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"OpenUSD"}],"externalID":"c:@N@Overlay@S@HgiMetalWrapper@F@ReleaseSecondaryCommandBuffer#*Qoobjc(pl)MTLCommandBuffer#","symbolKind":"method","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/ReleaseSecondaryCommandBuffer","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReleaseSecondaryCommandBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"commandBuffer","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)MTLCommandBuffer","text":"id<MTLCommandBuffer>","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/releasesecondarycommandbuffer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/releasesecondarycommandbuffer"]}],"sections":[],"kind":"symbol","references":{"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","url":"\/documentation\/openusd","kind":"symbol","role":"collection","title":"OpenUSD","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"kind":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","type":"topic","role":"symbol","fragments":[{"text":"Overlay","kind":"identifier"}],"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/ReleaseSecondaryCommandBuffer":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/ReleaseSecondaryCommandBuffer","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"ReleaseSecondaryCommandBuffer","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/releasesecondarycommandbuffer","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReleaseSecondaryCommandBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)MTLCommandBuffer","text":"id<MTLCommandBuffer>","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"ReleaseSecondaryCommandBuffer(_:)"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HgiMetalWrapper"}],"title":"class HgiMetalWrapper","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HgiMetalWrapper"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ReleaseSecondaryCommandBuffer","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ReleaseSecondaryCommandBuffer","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"ReleaseSecondaryCommandBuffer","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"ReleaseSecondaryCommandBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<MTLCommandBuffer>","preciseIdentifier":"c:Qoobjc(pl)MTLCommandBuffer","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"commandBuffer","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"op":"replace","value":"ReleaseSecondaryCommandBuffer","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1ReleaseSecondaryCommandBuffer\/title"},{"op":"replace","value":[{"text":"ReleaseSecondaryCommandBuffer","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1ReleaseSecondaryCommandBuffer\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ReleaseSecondaryCommandBuffer"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1ReleaseSecondaryCommandBuffer\/navigatorTitle"},{"op":"replace","value":"HgiMetalWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HgiMetalWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/fragments"},{"op":"replace","value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}