{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommitCommandBuffer_WaitUntilCompleted","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType\/CommitCommandBuffer_WaitUntilCompleted","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommitCommandBuffer_WaitUntilCompleted"}],"navigatorTitle":[{"kind":"identifier","text":"CommitCommandBuffer_WaitUntilCompleted"}],"symbolKind":"case","roleHeading":"Enumeration Case","externalID":"c:@N@Overlay@S@HgiMetalWrapper@E@CommitCommandBufferWaitType@CommitCommandBuffer_WaitUntilCompleted","modules":[{"name":"OpenUSD"}],"role":"symbol","title":"CommitCommandBuffer_WaitUntilCompleted"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype\/commitcommandbuffer_waituntilcompleted"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype\/commitcommandbuffer_waituntilcompleted"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType"]]},"kind":"symbol","references":{"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","title":"OpenUSD","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","type":"topic","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/CommitCommandBufferWaitType":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"CommitCommandBufferWaitType","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType","title":"CommitCommandBufferWaitType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommitCommandBufferWaitType","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"type":"topic","url":"\/documentation\/openusd\/overlay","fragments":[{"kind":"identifier","text":"Overlay"}],"title":"Overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper":{"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","type":"topic","abstract":[],"url":"\/documentation\/openusd\/overlay\/hgimetalwrapper","kind":"symbol","title":"class HgiMetalWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiMetalWrapper","kind":"identifier"}],"navigatorTitle":[{"text":"HgiMetalWrapper","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/CommitCommandBufferWaitType/CommitCommandBuffer_WaitUntilCompleted":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommitCommandBuffer_WaitUntilCompleted"}],"navigatorTitle":[{"kind":"identifier","text":"CommitCommandBuffer_WaitUntilCompleted"}],"abstract":[],"url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype\/commitcommandbuffer_waituntilcompleted","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType\/CommitCommandBuffer_WaitUntilCompleted","kind":"symbol","title":"CommitCommandBuffer_WaitUntilCompleted"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"CommitCommandBuffer_WaitUntilCompleted","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"CommitCommandBuffer_WaitUntilCompleted","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CommitCommandBuffer_WaitUntilCompleted"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CommitCommandBuffer_WaitUntilCompleted"}],"languages":["occ"],"platforms":["macOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"CommitCommandBufferWaitType","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType\/title"},{"op":"replace","value":[{"text":"CommitCommandBufferWaitType","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType\/fragments"},{"op":"replace","value":[{"text":"CommitCommandBufferWaitType","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType\/navigatorTitle"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"op":"replace","value":"HgiMetalWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/title"},{"op":"replace","value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/fragments"},{"op":"replace","value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/navigatorTitle"},{"op":"replace","value":"CommitCommandBuffer_WaitUntilCompleted","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType~1CommitCommandBuffer_WaitUntilCompleted\/title"},{"op":"replace","value":[{"text":"CommitCommandBuffer_WaitUntilCompleted","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType~1CommitCommandBuffer_WaitUntilCompleted\/fragments"},{"op":"replace","value":[{"text":"CommitCommandBuffer_WaitUntilCompleted","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType~1CommitCommandBuffer_WaitUntilCompleted\/navigatorTitle"}]}]}