{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArCreateResolver"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"OpenUSD"}],"externalID":"c:@N@Overlay@F@ArCreateResolver#&1$@N@pxr@S@TfType#","roleHeading":"Function","title":"ArCreateResolver(_:)","symbolKind":"func","navigatorTitle":[{"text":"ArCreateResolver","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArCreateResolver"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TfType","preciseIdentifier":"c:@N@pxr@S@TfType"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"ArResolverWrapper","preciseIdentifier":"c:@N@Overlay@S@ArResolverWrapper"}]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArCreateResolver"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"resolverType"},{"kind":"text","text":": "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfType","text":"TfType"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@S@ArResolverWrapper","text":"ArResolverWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/openusd\/overlay\/arcreateresolver"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/arcreateresolver"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper":{"kind":"symbol","type":"topic","title":"class ArResolverWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","role":"symbol","navigatorTitle":[{"text":"ArResolverWrapper","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArResolverWrapper","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper"},"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","url":"\/documentation\/openusd","kind":"symbol","role":"collection","title":"OpenUSD","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArCreateResolver":{"type":"topic","url":"\/documentation\/openusd\/overlay\/arcreateresolver","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArCreateResolver"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TfType","preciseIdentifier":"c:@N@pxr@S@TfType"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"ArResolverWrapper","preciseIdentifier":"c:@N@Overlay@S@ArResolverWrapper"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArCreateResolver","title":"ArCreateResolver(_:)","navigatorTitle":[{"text":"ArCreateResolver","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"kind":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","type":"topic","role":"symbol","fragments":[{"text":"Overlay","kind":"identifier"}],"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Function","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ArCreateResolver","path":"\/metadata\/title","op":"replace"},{"value":"func","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"ArCreateResolver","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ArCreateResolver"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"typeIdentifier","text":"ArResolverWrapper","preciseIdentifier":"c:@N@Overlay@S@ArResolverWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArCreateResolver"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","text":"TfType","preciseIdentifier":"c:@N@pxr@S@TfType"},{"kind":"text","text":" & "},{"kind":"internalParam","text":"resolverType"},{"kind":"text","text":");"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ArResolverWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ArResolverWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ArResolverWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/navigatorTitle","op":"replace"},{"value":"ArCreateResolver","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArCreateResolver\/title","op":"replace"},{"value":[{"text":"ArCreateResolver","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArCreateResolver\/fragments","op":"replace"},{"value":[{"text":"ArCreateResolver","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArCreateResolver\/navigatorTitle","op":"replace"},{"value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace"},{"value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add"}],"traits":[{"interfaceLanguage":"occ"}]}]}