{"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/ArResolverWrapper-1a4nr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/ArResolverWrapper-3q8zx"],"title":"Initializers"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/BeginCacheScope","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/BindContext","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CanWriteAssetToPath","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateContextFromString-2r7xk","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateContextFromString-59xki","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateContextFromStrings","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateDefaultContext","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateDefaultContextForAsset","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateIdentifier","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateIdentifierForNewAsset","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/EndCacheScope","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/GetAssetInfo","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/GetCurrentContext","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/GetExtension","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/GetModificationTimestamp","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/IsContextDependentPath","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/IsRepositoryPath","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/OpenAsset","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/OpenAssetForWrite","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/RefreshContext","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/Resolve","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/ResolveForNewAsset","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/UnbindContext","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/get","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/get_shared","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/operator_bool"],"title":"Instance Methods"},{"generated":true,"title":"Enumerations","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/WriteMode"],"anchor":"Enumerations"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArResolverWrapper","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay"]]},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OpenUSD"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArResolverWrapper","kind":"identifier"}],"symbolKind":"class","navigatorTitle":[{"text":"ArResolverWrapper","kind":"identifier"}],"roleHeading":"Class","title":"class ArResolverWrapper","externalID":"c:@N@Overlay@S@ArResolverWrapper"},"seeAlsoSections":[{"generated":true,"title":"Namespace Overlay","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfErrorMarkWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper"],"anchor":"Namespace-Overlay"}],"variants":[{"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/operator_bool":{"kind":"symbol","title":"operator bool","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/operator_bool","role":"symbol","fragments":[{"text":"_Bool","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/operator_bool","abstract":[],"type":"topic","navigatorTitle":[{"text":"operator bool","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/CreateContextFromStrings":{"title":"CreateContextFromStrings(_:_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateContextFromStrings","abstract":[],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/createcontextfromstrings","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateContextFromStrings"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@N@std","kind":"identifier","text":"std"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@std@N@__1@ST>2#T#T@vector","kind":"typeIdentifier","text":"std::vector"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@std","kind":"identifier","text":"std"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@std@N@__1@ST>2#T#T@pair","kind":"typeIdentifier","text":"std::pair"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@std","kind":"identifier","text":"std"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C","kind":"typeIdentifier","text":"string"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@std","kind":"identifier","text":"std"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C","kind":"typeIdentifier","text":"string"},{"kind":"text","text":">> "},{"kind":"text","text":">"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArResolverContext","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArResolverContext"}],"role":"symbol","navigatorTitle":[{"text":"CreateContextFromStrings","kind":"identifier"}],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/CanWriteAssetToPath":{"kind":"symbol","title":"CanWriteAssetToPath(_:_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CanWriteAssetToPath","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CanWriteAssetToPath"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ArResolvedPath","preciseIdentifier":"c:@N@pxr@S@ArResolvedPath"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C","kind":"typeIdentifier","text":"string"},{"kind":"text","text":">"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:b","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/canwriteassettopath","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CanWriteAssetToPath"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/ArResolverWrapper-3q8zx":{"abstract":[],"title":"init(_:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"ArResolver","preciseIdentifier":"c:@N@pxr@S@ArResolver","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"ArResolverWrapper","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/ArResolverWrapper-3q8zx","type":"topic","navigatorTitle":[{"text":"ArResolverWrapper","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/arresolverwrapper-3q8zx"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper":{"type":"topic","role":"symbol","title":"class HgiWrapper","url":"\/documentation\/openusd\/overlay\/hgiwrapper","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"HgiWrapper","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HgiWrapper","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/IsContextDependentPath":{"kind":"symbol","title":"IsContextDependentPath(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/IsContextDependentPath","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"IsContextDependentPath"},{"kind":"text","text":"("},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"string","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:b","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/iscontextdependentpath","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"IsContextDependentPath"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","title":"struct UsdPrimTypeInfoWrapper","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/ResolveForNewAsset":{"kind":"symbol","title":"ResolveForNewAsset(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/ResolveForNewAsset","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResolveForNewAsset"},{"kind":"text","text":"("},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"string","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArResolvedPath","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArResolvedPath"}],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/resolvefornewasset","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResolveForNewAsset"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/WriteMode":{"type":"topic","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/WriteMode","navigatorTitle":[{"kind":"identifier","text":"WriteMode"}],"kind":"symbol","abstract":[],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/writemode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WriteMode"}],"title":"WriteMode"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/CreateIdentifier":{"kind":"symbol","title":"CreateIdentifier(_:_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateIdentifier","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateIdentifier"},{"kind":"text","text":"("},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"string","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"kind":"text","text":", "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ArResolvedPath","preciseIdentifier":"c:@N@pxr@S@ArResolvedPath"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"std","kind":"identifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"}],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/createidentifier","abstract":[],"type":"topic","navigatorTitle":[{"text":"CreateIdentifier","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/GetModificationTimestamp":{"kind":"symbol","title":"GetModificationTimestamp(_:_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/GetModificationTimestamp","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetModificationTimestamp"},{"kind":"text","text":"("},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"string","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"kind":"text","text":", "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ArResolvedPath","preciseIdentifier":"c:@N@pxr@S@ArResolvedPath"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArTimestamp","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArTimestamp"}],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/getmodificationtimestamp","abstract":[],"type":"topic","navigatorTitle":[{"text":"GetModificationTimestamp","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/GetAssetInfo":{"kind":"symbol","title":"GetAssetInfo(_:_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/GetAssetInfo","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetAssetInfo"},{"kind":"text","text":"("},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"string","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"kind":"text","text":", "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ArResolvedPath","preciseIdentifier":"c:@N@pxr@S@ArResolvedPath"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArAssetInfo","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArAssetInfo"}],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/getassetinfo","abstract":[],"type":"topic","navigatorTitle":[{"text":"GetAssetInfo","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","title":"OpenUSD","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","type":"topic","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/BeginCacheScope":{"kind":"symbol","title":"BeginCacheScope(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/BeginCacheScope","role":"symbol","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BeginCacheScope"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"VtValue","preciseIdentifier":"c:@N@pxr@S@VtValue"},{"text":">","kind":"text"},{"text":")","kind":"text"}],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/begincachescope","abstract":[],"type":"topic","navigatorTitle":[{"text":"BeginCacheScope","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/CreateContextFromString-2r7xk":{"kind":"symbol","title":"CreateContextFromString(_:_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateContextFromString-2r7xk","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateContextFromString"},{"kind":"text","text":"("},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"string","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"kind":"text","text":", "},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"string","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArResolverContext","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArResolverContext"}],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/createcontextfromstring-2r7xk","abstract":[],"type":"topic","navigatorTitle":[{"text":"CreateContextFromString","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/get":{"kind":"symbol","title":"get()","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/get","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"text":"ArResolver","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArResolver"},{"text":">","kind":"text"}],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/get","abstract":[],"type":"topic","navigatorTitle":[{"text":"get","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/BindContext":{"navigatorTitle":[{"kind":"identifier","text":"BindContext"}],"title":"BindContext(_:_:)","url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/bindcontext","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BindContext"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ArResolverContext","preciseIdentifier":"c:@N@pxr@S@ArResolverContext"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@VtValue","text":"VtValue"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/BindContext","role":"symbol","kind":"symbol","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","url":"\/documentation\/openusd\/overlay\/hioimagewrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HioImageWrapper","kind":"identifier"}],"title":"class HioImageWrapper","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"HioImageWrapper","kind":"identifier"}],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/ArResolverWrapper-1a4nr":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/ArResolverWrapper-1a4nr","url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/arresolverwrapper-1a4nr","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ArResolverWrapper"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"std::shared_ptr","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ArResolver","preciseIdentifier":"c:@N@pxr@S@ArResolver"},{"kind":"text","text":">"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"ArResolverWrapper"}],"kind":"symbol","type":"topic","title":"init(_:)","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/CreateDefaultContextForAsset":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateDefaultContextForAsset","title":"CreateDefaultContextForAsset(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateDefaultContextForAsset","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","kind":"identifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArResolverContext","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArResolverContext"}],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/createdefaultcontextforasset","navigatorTitle":[{"kind":"identifier","text":"CreateDefaultContextForAsset"}],"type":"topic","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/GetExtension":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/GetExtension","url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/getextension","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GetExtension"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetExtension"},{"kind":"text","text":"("},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"string","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@std","kind":"identifier","text":"std"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C","kind":"typeIdentifier","text":"string"}],"kind":"symbol","type":"topic","title":"GetExtension(_:)","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/Resolve":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Resolve","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","kind":"identifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArResolvedPath","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArResolvedPath"}],"navigatorTitle":[{"text":"Resolve","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/resolve","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/Resolve","title":"Resolve(_:)","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/OpenAssetForWrite":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/OpenAssetForWrite","title":"OpenAssetForWrite(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenAssetForWrite","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArResolvedPath","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArResolvedPath"},{"text":", ","kind":"text"},{"text":"WriteMode","kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@S@ArResolverWrapper@E@WriteMode"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"std","kind":"identifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"std::shared_ptr","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr"},{"text":"<","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArWritableAsset","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArWritableAsset"},{"text":">","kind":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/openassetforwrite","navigatorTitle":[{"text":"OpenAssetForWrite","kind":"identifier"}],"type":"topic","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/get_shared":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/get_shared","url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/get_shared","role":"symbol","navigatorTitle":[{"text":"get_shared","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get_shared"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"std::shared_ptr","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ArResolver","preciseIdentifier":"c:@N@pxr@S@ArResolver"},{"kind":"text","text":">"}],"kind":"symbol","type":"topic","title":"get_shared()","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/OpenAsset":{"kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenAsset"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ArResolvedPath","preciseIdentifier":"c:@N@pxr@S@ArResolvedPath"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"std::shared_ptr","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ArAsset","preciseIdentifier":"c:@N@pxr@S@ArAsset"},{"kind":"text","text":">"}],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/openasset","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/OpenAsset","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenAsset"}],"title":"OpenAsset(_:)"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/GetCurrentContext":{"kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetCurrentContext"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ArResolverContext","preciseIdentifier":"c:@N@pxr@S@ArResolverContext"}],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/getcurrentcontext","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/GetCurrentContext","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GetCurrentContext"}],"title":"GetCurrentContext()"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper":{"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","type":"topic","abstract":[],"url":"\/documentation\/openusd\/overlay\/hgimetalwrapper","kind":"symbol","title":"class HgiMetalWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiMetalWrapper","kind":"identifier"}],"navigatorTitle":[{"text":"HgiMetalWrapper","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/RefreshContext":{"fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"RefreshContext"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ArResolverContext","preciseIdentifier":"c:@N@pxr@S@ArResolverContext"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"RefreshContext"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/RefreshContext","title":"RefreshContext(_:)","url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/refreshcontext","kind":"symbol","type":"topic","abstract":[],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"type":"topic","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"navigatorTitle":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"abstract":[],"title":"class UsdImagingGLEngineWrapper","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/CreateIdentifierForNewAsset":{"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/createidentifierfornewasset","navigatorTitle":[{"kind":"identifier","text":"CreateIdentifierForNewAsset"}],"abstract":[],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateIdentifierForNewAsset","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateIdentifierForNewAsset"},{"kind":"text","text":"("},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"string","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"kind":"text","text":", "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ArResolvedPath","preciseIdentifier":"c:@N@pxr@S@ArResolvedPath"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"string","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"}],"kind":"symbol","title":"CreateIdentifierForNewAsset(_:_:)"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArResolverWrapper"}],"navigatorTitle":[{"kind":"identifier","text":"ArResolverWrapper"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/openusd\/overlay\/arresolverwrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","title":"class ArResolverWrapper","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/UnbindContext":{"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/unbindcontext","navigatorTitle":[{"kind":"identifier","text":"UnbindContext"}],"abstract":[],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/UnbindContext","role":"symbol","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnbindContext"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ArResolverContext","preciseIdentifier":"c:@N@pxr@S@ArResolverContext"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"VtValue","preciseIdentifier":"c:@N@pxr@S@VtValue"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"kind":"symbol","title":"UnbindContext(_:_:)"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/CreateDefaultContext":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateDefaultContext","abstract":[],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/createdefaultcontext","title":"CreateDefaultContext()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateDefaultContext","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"ArResolverContext","preciseIdentifier":"c:@N@pxr@S@ArResolverContext","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"CreateDefaultContext","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/CreateContextFromString-59xki":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CreateContextFromString"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateContextFromString-59xki","abstract":[],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/createcontextfromstring-59xki","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateContextFromString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","kind":"identifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArResolverContext","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArResolverContext"}],"title":"CreateContextFromString(_:)","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdAppUtilsFrameRecorderWrapper":{"title":"class UsdAppUtilsFrameRecorderWrapper","navigatorTitle":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper","role":"symbol","url":"\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper","type":"topic","abstract":[],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/EndCacheScope":{"fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EndCacheScope","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"VtValue","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@VtValue"},{"text":">","kind":"text"},{"text":")","kind":"text"}],"role":"symbol","title":"EndCacheScope(_:)","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/endcachescope","navigatorTitle":[{"text":"EndCacheScope","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/EndCacheScope"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"type":"topic","url":"\/documentation\/openusd\/overlay","fragments":[{"kind":"identifier","text":"Overlay"}],"title":"Overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/TfErrorMarkWrapper":{"kind":"symbol","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfErrorMarkWrapper","navigatorTitle":[{"kind":"identifier","text":"TfErrorMarkWrapper"}],"title":"struct TfErrorMarkWrapper","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TfErrorMarkWrapper"}],"url":"\/documentation\/openusd\/overlay\/tferrormarkwrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/IsRepositoryPath":{"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/isrepositorypath","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsRepositoryPath","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@std","text":"std","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C","text":"string","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:b","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"IsRepositoryPath","kind":"identifier"}],"title":"IsRepositoryPath(_:)","abstract":[],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/IsRepositoryPath"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ArResolverWrapper","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ArResolverWrapper"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ArResolverWrapper"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/ArResolverWrapper-1a4nr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/ArResolverWrapper-3q8zx","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/BeginCacheScope","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/BindContext","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CanWriteAssetToPath","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateContextFromString-2r7xk","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateContextFromString-59xki","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateContextFromStrings","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateDefaultContext","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateDefaultContextForAsset","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateIdentifier","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateIdentifierForNewAsset","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/EndCacheScope","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/GetAssetInfo","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/GetCurrentContext","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/GetExtension","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/GetModificationTimestamp","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/IsContextDependentPath","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/IsRepositoryPath","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/OpenAsset","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/OpenAssetForWrite","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/RefreshContext","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/Resolve","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/ResolveForNewAsset","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/UnbindContext","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/get","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/get_shared","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/operator_bool"]},{"generated":true,"anchor":"Enumerations","title":"Enumerations","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/WriteMode"]}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"anchor":"Namespace-Overlay","title":"Namespace Overlay","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper"],"generated":true}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArResolverWrapper"},{"kind":"text","text":";"}],"platforms":["macOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"operator bool","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1operator_bool\/title"},{"op":"replace","value":[{"kind":"identifier","text":"_Bool"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1operator_bool\/fragments"},{"op":"replace","value":[{"text":"operator bool","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1operator_bool\/navigatorTitle"},{"op":"replace","value":"CreateContextFromStrings","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateContextFromStrings\/title"},{"op":"replace","value":[{"text":"CreateContextFromStrings","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateContextFromStrings\/fragments"},{"op":"replace","value":[{"text":"CreateContextFromStrings","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateContextFromStrings\/navigatorTitle"},{"op":"replace","value":"CanWriteAssetToPath","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CanWriteAssetToPath\/title"},{"op":"replace","value":[{"text":"CanWriteAssetToPath","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CanWriteAssetToPath\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CanWriteAssetToPath"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CanWriteAssetToPath\/navigatorTitle"},{"op":"replace","value":"ArResolverWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1ArResolverWrapper-3q8zx\/title"},{"op":"replace","value":[{"text":"ArResolverWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1ArResolverWrapper-3q8zx\/fragments"},{"op":"replace","value":[{"text":"ArResolverWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1ArResolverWrapper-3q8zx\/navigatorTitle"},{"op":"replace","value":"HgiWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/title"},{"op":"replace","value":[{"text":"HgiWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/fragments"},{"op":"replace","value":[{"text":"HgiWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/navigatorTitle"},{"op":"replace","value":"IsContextDependentPath","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1IsContextDependentPath\/title"},{"op":"replace","value":[{"kind":"identifier","text":"IsContextDependentPath"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1IsContextDependentPath\/fragments"},{"op":"replace","value":[{"text":"IsContextDependentPath","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1IsContextDependentPath\/navigatorTitle"},{"op":"replace","value":"UsdPrimTypeInfoWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/fragments"},{"op":"replace","value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/navigatorTitle"},{"op":"replace","value":"ResolveForNewAsset","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1ResolveForNewAsset\/title"},{"op":"replace","value":[{"text":"ResolveForNewAsset","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1ResolveForNewAsset\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ResolveForNewAsset"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1ResolveForNewAsset\/navigatorTitle"},{"op":"replace","value":"WriteMode","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode\/title"},{"op":"replace","value":[{"text":"WriteMode","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode\/fragments"},{"op":"replace","value":[{"text":"WriteMode","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode\/navigatorTitle"},{"op":"replace","value":"CreateIdentifier","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateIdentifier\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CreateIdentifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateIdentifier\/fragments"},{"op":"replace","value":[{"text":"CreateIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateIdentifier\/navigatorTitle"},{"op":"replace","value":"GetModificationTimestamp","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1GetModificationTimestamp\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GetModificationTimestamp"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1GetModificationTimestamp\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GetModificationTimestamp"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1GetModificationTimestamp\/navigatorTitle"},{"op":"replace","value":"GetAssetInfo","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1GetAssetInfo\/title"},{"op":"replace","value":[{"text":"GetAssetInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1GetAssetInfo\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GetAssetInfo"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1GetAssetInfo\/navigatorTitle"},{"op":"replace","value":"BeginCacheScope","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1BeginCacheScope\/title"},{"op":"replace","value":[{"text":"BeginCacheScope","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1BeginCacheScope\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"BeginCacheScope"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1BeginCacheScope\/navigatorTitle"},{"op":"replace","value":"CreateContextFromString","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateContextFromString-2r7xk\/title"},{"op":"replace","value":[{"text":"CreateContextFromString","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateContextFromString-2r7xk\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CreateContextFromString"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateContextFromString-2r7xk\/navigatorTitle"},{"op":"replace","value":"get","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1get\/title"},{"op":"replace","value":[{"kind":"identifier","text":"get"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1get\/fragments"},{"op":"replace","value":[{"text":"get","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1get\/navigatorTitle"},{"op":"replace","value":"BindContext","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1BindContext\/title"},{"op":"replace","value":[{"text":"BindContext","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1BindContext\/fragments"},{"op":"replace","value":[{"text":"BindContext","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1BindContext\/navigatorTitle"},{"op":"replace","value":"HioImageWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HioImageWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments"},{"op":"replace","value":[{"text":"HioImageWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle"},{"op":"replace","value":"ArResolverWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1ArResolverWrapper-1a4nr\/title"},{"op":"replace","value":[{"text":"ArResolverWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1ArResolverWrapper-1a4nr\/fragments"},{"op":"replace","value":[{"text":"ArResolverWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1ArResolverWrapper-1a4nr\/navigatorTitle"},{"op":"replace","value":"CreateDefaultContextForAsset","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateDefaultContextForAsset\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CreateDefaultContextForAsset"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateDefaultContextForAsset\/fragments"},{"op":"replace","value":[{"text":"CreateDefaultContextForAsset","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateDefaultContextForAsset\/navigatorTitle"},{"op":"replace","value":"GetExtension","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1GetExtension\/title"},{"op":"replace","value":[{"text":"GetExtension","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1GetExtension\/fragments"},{"op":"replace","value":[{"text":"GetExtension","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1GetExtension\/navigatorTitle"},{"op":"replace","value":"Resolve","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1Resolve\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Resolve"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1Resolve\/fragments"},{"op":"replace","value":[{"text":"Resolve","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1Resolve\/navigatorTitle"},{"op":"replace","value":"OpenAssetForWrite","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1OpenAssetForWrite\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OpenAssetForWrite"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1OpenAssetForWrite\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OpenAssetForWrite"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1OpenAssetForWrite\/navigatorTitle"},{"op":"replace","value":"get_shared","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1get_shared\/title"},{"op":"replace","value":[{"text":"get_shared","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1get_shared\/fragments"},{"op":"replace","value":[{"text":"get_shared","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1get_shared\/navigatorTitle"},{"op":"replace","value":"OpenAsset","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1OpenAsset\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OpenAsset"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1OpenAsset\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OpenAsset"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1OpenAsset\/navigatorTitle"},{"op":"replace","value":"GetCurrentContext","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1GetCurrentContext\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GetCurrentContext"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1GetCurrentContext\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GetCurrentContext"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1GetCurrentContext\/navigatorTitle"},{"op":"replace","value":"HgiMetalWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HgiMetalWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/fragments"},{"op":"replace","value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/navigatorTitle"},{"op":"replace","value":"RefreshContext","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1RefreshContext\/title"},{"op":"replace","value":[{"text":"RefreshContext","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1RefreshContext\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"RefreshContext"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1RefreshContext\/navigatorTitle"},{"op":"replace","value":"UsdImagingGLEngineWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments"},{"op":"replace","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle"},{"op":"replace","value":"CreateIdentifierForNewAsset","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateIdentifierForNewAsset\/title"},{"op":"replace","value":[{"text":"CreateIdentifierForNewAsset","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateIdentifierForNewAsset\/fragments"},{"op":"replace","value":[{"text":"CreateIdentifierForNewAsset","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateIdentifierForNewAsset\/navigatorTitle"},{"op":"replace","value":"ArResolverWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/title"},{"op":"replace","value":[{"text":"ArResolverWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ArResolverWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/navigatorTitle"},{"op":"replace","value":"UnbindContext","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1UnbindContext\/title"},{"op":"replace","value":[{"text":"UnbindContext","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1UnbindContext\/fragments"},{"op":"replace","value":[{"text":"UnbindContext","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1UnbindContext\/navigatorTitle"},{"op":"replace","value":"CreateDefaultContext","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateDefaultContext\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CreateDefaultContext"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateDefaultContext\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CreateDefaultContext"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateDefaultContext\/navigatorTitle"},{"op":"replace","value":"CreateContextFromString","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateContextFromString-59xki\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CreateContextFromString"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateContextFromString-59xki\/fragments"},{"op":"replace","value":[{"text":"CreateContextFromString","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateContextFromString-59xki\/navigatorTitle"},{"op":"replace","value":"UsdAppUtilsFrameRecorderWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/title"},{"op":"replace","value":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UsdAppUtilsFrameRecorderWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/navigatorTitle"},{"op":"replace","value":"EndCacheScope","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1EndCacheScope\/title"},{"op":"replace","value":[{"text":"EndCacheScope","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1EndCacheScope\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"EndCacheScope"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1EndCacheScope\/navigatorTitle"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"op":"replace","value":"IsRepositoryPath","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1IsRepositoryPath\/title"},{"op":"replace","value":[{"kind":"identifier","text":"IsRepositoryPath"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1IsRepositoryPath\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"IsRepositoryPath"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1IsRepositoryPath\/navigatorTitle"}]}]}