{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfErrorMarkWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper"],"anchor":"Namespace-Overlay","title":"Namespace Overlay","generated":true}],"variants":[{"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HioImageWrapper","kind":"identifier"}]}]}],"kind":"symbol","metadata":{"symbolKind":"class","externalID":"c:@N@Overlay@S@HioImageWrapper","navigatorTitle":[{"kind":"identifier","text":"HioImageWrapper"}],"role":"symbol","roleHeading":"Class","title":"class HioImageWrapper","modules":[{"name":"OpenUSD"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HioImageWrapper"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper"},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/StorageSpec"],"anchor":"Classes","title":"Classes","generated":true},{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/HioImageWrapper"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetBytesPerPixel","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetFilename","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetFormat","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetHeight","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetMetadata-84xbi","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetMetadata-8bl3d","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetNumMipLevels","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetSamplerMetadata","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetWidth","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/IsColorSpaceSRGB","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/Read","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ReadCropped","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/Write","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/get","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/get_shared","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/operator_bool"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true},{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/IsSupportedImageFile","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/OpenForReading","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/OpenForWriting"],"anchor":"Type-Methods","title":"Type Methods","generated":true},{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/SourceColorSpace"],"anchor":"Enumerations","title":"Enumerations","generated":true}],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/GetMetadata-8bl3d":{"title":"GetMetadata(_:_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetMetadata-8bl3d","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"VtValue","preciseIdentifier":"c:@N@pxr@S@VtValue","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"GetMetadata","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/getmetadata-8bl3d","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"type":"topic","url":"\/documentation\/openusd\/overlay","fragments":[{"kind":"identifier","text":"Overlay"}],"title":"Overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper":{"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","type":"topic","abstract":[],"url":"\/documentation\/openusd\/overlay\/hgimetalwrapper","kind":"symbol","title":"class HgiMetalWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiMetalWrapper","kind":"identifier"}],"navigatorTitle":[{"text":"HgiMetalWrapper","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArResolverWrapper"}],"navigatorTitle":[{"kind":"identifier","text":"ArResolverWrapper"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/openusd\/overlay\/arresolverwrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","title":"class ArResolverWrapper","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/GetNumMipLevels":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetNumMipLevels","title":"GetNumMipLevels()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetNumMipLevels","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"CInt","preciseIdentifier":"c:I","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/getnummiplevels","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"GetNumMipLevels","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/get_shared":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get_shared","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"std","preciseIdentifier":"c:@N@std","kind":"identifier"},{"text":".","kind":"text"},{"text":"std::shared_ptr","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"HioImage","preciseIdentifier":"c:@N@pxr@S@HioImage","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/get_shared","type":"topic","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"get_shared"}],"title":"get_shared()","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/get_shared"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/GetHeight":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetHeight","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"CInt","preciseIdentifier":"c:I","kind":"typeIdentifier"}],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/getheight","type":"topic","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"GetHeight","kind":"identifier"}],"title":"GetHeight()","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetHeight"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/ReadCropped":{"abstract":[],"fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReadCropped"},{"kind":"text","text":"("},{"preciseIdentifier":"c:I","kind":"typeIdentifier","text":"CInt"},{"kind":"text","text":", "},{"preciseIdentifier":"c:I","kind":"typeIdentifier","text":"CInt"},{"kind":"text","text":", "},{"preciseIdentifier":"c:I","kind":"typeIdentifier","text":"CInt"},{"kind":"text","text":", "},{"preciseIdentifier":"c:I","kind":"typeIdentifier","text":"CInt"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@N@Overlay@S@HioImageWrapper@S@StorageSpec","kind":"typeIdentifier","text":"StorageSpec"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:b","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"ReadCropped"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ReadCropped","role":"symbol","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/readcropped","title":"ReadCropped(_:_:_:_:_:)"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/ImageOriginLocation":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageOriginLocation"}],"abstract":[],"kind":"symbol","role":"symbol","title":"ImageOriginLocation","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/imageoriginlocation","navigatorTitle":[{"kind":"identifier","text":"ImageOriginLocation"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/OpenForReading":{"abstract":[],"title":"OpenForReading(_:_:_:_:_:)","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/OpenForReading","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenForReading","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","kind":"identifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"text":", ","kind":"text"},{"text":"CInt","kind":"typeIdentifier","preciseIdentifier":"c:I"},{"kind":"text","text":", "},{"preciseIdentifier":"c:I","kind":"typeIdentifier","text":"CInt"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@N@Overlay@S@HioImageWrapper@E@SourceColorSpace","kind":"typeIdentifier","text":"SourceColorSpace"},{"kind":"text","text":", "},{"preciseIdentifier":"c:b","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@Overlay@S@HioImageWrapper","kind":"typeIdentifier","text":"HioImageWrapper"}],"navigatorTitle":[{"kind":"identifier","text":"OpenForReading"}],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/openforreading","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/IsColorSpaceSRGB":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsColorSpaceSRGB","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/iscolorspacesrgb","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/IsColorSpaceSRGB","title":"IsColorSpaceSRGB()","role":"symbol","navigatorTitle":[{"text":"IsColorSpaceSRGB","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/IsSupportedImageFile":{"title":"IsSupportedImageFile(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/IsSupportedImageFile","navigatorTitle":[{"text":"IsSupportedImageFile","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsSupportedImageFile","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","preciseIdentifier":"c:@N@std","kind":"identifier"},{"text":".","kind":"text"},{"text":"string","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/issupportedimagefile"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/OpenForWriting":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/OpenForWriting","abstract":[],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenForWriting","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","preciseIdentifier":"c:@N@std","kind":"identifier"},{"text":".","kind":"text"},{"text":"string","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"HioImageWrapper","preciseIdentifier":"c:@N@Overlay@S@HioImageWrapper","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"OpenForWriting","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/openforwriting","role":"symbol","title":"OpenForWriting(_:)","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/GetWidth":{"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/getwidth","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetWidth","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetWidth","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"CInt","preciseIdentifier":"c:I","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"GetWidth","kind":"identifier"}],"role":"symbol","title":"GetWidth()","abstract":[],"type":"topic","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/GetFormat":{"title":"GetFormat()","abstract":[],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/getformat","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GetFormat"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetFormat"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HioFormat","preciseIdentifier":"c:@N@pxr@E@HioFormat"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetFormat"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"type":"topic","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"navigatorTitle":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"abstract":[],"title":"class UsdImagingGLEngineWrapper","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/operator_bool":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/operator_bool","navigatorTitle":[{"text":"operator bool","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/operator_bool","fragments":[{"text":"_Bool","kind":"identifier"}],"type":"topic","role":"symbol","title":"operator bool"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/HioImageWrapper":{"title":"init(_:)","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/HioImageWrapper","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/hioimagewrapper","role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@std","text":"std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr","text":"std::shared_ptr"},{"kind":"text","text":"<"},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HioImage","text":"HioImage"},{"kind":"text","text":">"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"HioImageWrapper"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HioImageWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/TfErrorMarkWrapper":{"kind":"symbol","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfErrorMarkWrapper","navigatorTitle":[{"kind":"identifier","text":"TfErrorMarkWrapper"}],"title":"struct TfErrorMarkWrapper","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TfErrorMarkWrapper"}],"url":"\/documentation\/openusd\/overlay\/tferrormarkwrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/SourceColorSpace":{"role":"symbol","navigatorTitle":[{"text":"SourceColorSpace","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/sourcecolorspace","title":"SourceColorSpace","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceColorSpace","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/SourceColorSpace","abstract":[],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/Read":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/Read","navigatorTitle":[{"kind":"identifier","text":"Read"}],"abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/read","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Read"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@N@Overlay@S@HioImageWrapper@S@StorageSpec","kind":"typeIdentifier","text":"StorageSpec"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:b","kind":"typeIdentifier","text":"Bool"}],"type":"topic","role":"symbol","title":"Read(_:)"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/GetBytesPerPixel":{"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/getbytesperpixel","type":"topic","title":"GetBytesPerPixel()","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetBytesPerPixel","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetBytesPerPixel","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"CInt","kind":"typeIdentifier","preciseIdentifier":"c:I"}],"navigatorTitle":[{"text":"GetBytesPerPixel","kind":"identifier"}],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/GetMetadata-84xbi":{"fragments":[{"kind":"identifier","text":"GetMetadata"}],"kind":"symbol","abstract":[],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/getmetadata-84xbi","title":"GetMetadata","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetMetadata-84xbi","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","title":"struct UsdPrimTypeInfoWrapper","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper":{"type":"topic","role":"symbol","title":"class HgiWrapper","url":"\/documentation\/openusd\/overlay\/hgiwrapper","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"HgiWrapper","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HgiWrapper","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","url":"\/documentation\/openusd\/overlay\/hioimagewrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HioImageWrapper","kind":"identifier"}],"title":"class HioImageWrapper","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"HioImageWrapper","kind":"identifier"}],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/Write":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/Write","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Write"}],"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Write"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@N@Overlay@S@HioImageWrapper@S@StorageSpec","kind":"typeIdentifier","text":"StorageSpec"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@VtDictionary","kind":"typeIdentifier","text":"VtDictionary"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"kind":"text","text":" "},{"preciseIdentifier":"c:b","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/write","title":"Write(_:_:)"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/get":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"HioImage","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HioImage"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"get","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/get","title":"get()","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/get","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/GetFilename":{"title":"GetFilename()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GetFilename"}],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/getfilename","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetFilename","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetFilename"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@std","kind":"identifier","text":"std"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C","kind":"typeIdentifier","text":"string"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/StorageSpec":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/StorageSpec","abstract":[],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/storagespec","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StorageSpec","kind":"identifier"}],"title":"class StorageSpec","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"StorageSpec","kind":"identifier"}],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdAppUtilsFrameRecorderWrapper":{"title":"class UsdAppUtilsFrameRecorderWrapper","navigatorTitle":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper","role":"symbol","url":"\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper","type":"topic","abstract":[],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/GetSamplerMetadata":{"kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetSamplerMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"HioAddressDimension","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@E@HioAddressDimension"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"HioAddressMode","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@E@HioAddressMode"},{"text":">","kind":"text"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetSamplerMetadata","type":"topic","navigatorTitle":[{"text":"GetSamplerMetadata","kind":"identifier"}],"title":"GetSamplerMetadata(_:_:)","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/getsamplermetadata"},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","title":"OpenUSD","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"HioImageWrapper","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"HioImageWrapper","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HioImageWrapper"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/StorageSpec"],"anchor":"Classes","title":"Classes"},{"generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetBytesPerPixel","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetFilename","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetFormat","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetHeight","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetMetadata-84xbi","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetMetadata-8bl3d","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetNumMipLevels","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetSamplerMetadata","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetWidth","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/HioImageWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/IsColorSpaceSRGB","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/Read","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ReadCropped","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/Write","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/get","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/get_shared","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/operator_bool"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/IsSupportedImageFile","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/OpenForReading","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/OpenForWriting"],"anchor":"Type-Methods","title":"Type Methods"},{"generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/ImageOriginLocation","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/SourceColorSpace"],"anchor":"Enumerations","title":"Enumerations"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper"],"title":"Namespace Overlay","anchor":"Namespace-Overlay","generated":true}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HioImageWrapper","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"GetMetadata","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetMetadata-8bl3d\/title"},{"value":[{"kind":"identifier","text":"GetMetadata"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetMetadata-8bl3d\/fragments"},{"value":[{"kind":"identifier","text":"GetMetadata"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetMetadata-8bl3d\/navigatorTitle"},{"value":"Overlay","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"value":[{"kind":"identifier","text":"Overlay"}],"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"value":"HgiMetalWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/title"},{"value":[{"kind":"identifier","text":"HgiMetalWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/fragments"},{"value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/navigatorTitle"},{"value":"ArResolverWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/title"},{"value":[{"kind":"identifier","text":"ArResolverWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/fragments"},{"value":[{"kind":"identifier","text":"ArResolverWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/navigatorTitle"},{"value":"GetNumMipLevels","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetNumMipLevels\/title"},{"value":[{"text":"GetNumMipLevels","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetNumMipLevels\/fragments"},{"value":[{"text":"GetNumMipLevels","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetNumMipLevels\/navigatorTitle"},{"value":"get_shared","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1get_shared\/title"},{"value":[{"text":"get_shared","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1get_shared\/fragments"},{"value":[{"kind":"identifier","text":"get_shared"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1get_shared\/navigatorTitle"},{"value":"GetHeight","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetHeight\/title"},{"value":[{"text":"GetHeight","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetHeight\/fragments"},{"value":[{"kind":"identifier","text":"GetHeight"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetHeight\/navigatorTitle"},{"value":"ReadCropped","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ReadCropped\/title"},{"value":[{"kind":"identifier","text":"ReadCropped"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ReadCropped\/fragments"},{"value":[{"kind":"identifier","text":"ReadCropped"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ReadCropped\/navigatorTitle"},{"value":"ImageOriginLocation","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation\/title"},{"value":[{"text":"ImageOriginLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation\/fragments"},{"value":[{"kind":"identifier","text":"ImageOriginLocation"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1ImageOriginLocation\/navigatorTitle"},{"value":"OpenForReading","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1OpenForReading\/title"},{"value":[{"text":"OpenForReading","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1OpenForReading\/fragments"},{"value":[{"text":"OpenForReading","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1OpenForReading\/navigatorTitle"},{"value":"IsColorSpaceSRGB","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1IsColorSpaceSRGB\/title"},{"value":[{"text":"IsColorSpaceSRGB","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1IsColorSpaceSRGB\/fragments"},{"value":[{"text":"IsColorSpaceSRGB","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1IsColorSpaceSRGB\/navigatorTitle"},{"value":"IsSupportedImageFile","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1IsSupportedImageFile\/title"},{"value":[{"kind":"identifier","text":"IsSupportedImageFile"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1IsSupportedImageFile\/fragments"},{"value":[{"text":"IsSupportedImageFile","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1IsSupportedImageFile\/navigatorTitle"},{"value":"OpenForWriting","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1OpenForWriting\/title"},{"value":[{"kind":"identifier","text":"OpenForWriting"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1OpenForWriting\/fragments"},{"value":[{"text":"OpenForWriting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1OpenForWriting\/navigatorTitle"},{"value":"GetWidth","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetWidth\/title"},{"value":[{"kind":"identifier","text":"GetWidth"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetWidth\/fragments"},{"value":[{"text":"GetWidth","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetWidth\/navigatorTitle"},{"value":"GetFormat","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetFormat\/title"},{"value":[{"kind":"identifier","text":"GetFormat"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetFormat\/fragments"},{"value":[{"text":"GetFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetFormat\/navigatorTitle"},{"value":"UsdImagingGLEngineWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title"},{"value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments"},{"value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle"},{"value":"operator bool","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1operator_bool\/title"},{"value":[{"kind":"identifier","text":"_Bool"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1operator_bool\/fragments"},{"value":[{"kind":"identifier","text":"operator bool"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1operator_bool\/navigatorTitle"},{"value":"HioImageWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1HioImageWrapper\/title"},{"value":[{"text":"HioImageWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1HioImageWrapper\/fragments"},{"value":[{"kind":"identifier","text":"HioImageWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1HioImageWrapper\/navigatorTitle"},{"value":"SourceColorSpace","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1SourceColorSpace\/title"},{"value":[{"kind":"identifier","text":"SourceColorSpace"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1SourceColorSpace\/fragments"},{"value":[{"kind":"identifier","text":"SourceColorSpace"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1SourceColorSpace\/navigatorTitle"},{"value":"Read","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1Read\/title"},{"value":[{"kind":"identifier","text":"Read"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1Read\/fragments"},{"value":[{"kind":"identifier","text":"Read"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1Read\/navigatorTitle"},{"value":"GetBytesPerPixel","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetBytesPerPixel\/title"},{"value":[{"text":"GetBytesPerPixel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetBytesPerPixel\/fragments"},{"value":[{"text":"GetBytesPerPixel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetBytesPerPixel\/navigatorTitle"},{"value":"GetMetadata","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetMetadata-84xbi\/title"},{"value":[{"text":"GetMetadata","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetMetadata-84xbi\/fragments"},{"value":[{"kind":"identifier","text":"GetMetadata"}],"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetMetadata-84xbi\/navigatorTitle"},{"value":"UsdPrimTypeInfoWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/title"},{"value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/fragments"},{"value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/navigatorTitle"},{"value":"HgiWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/title"},{"value":[{"text":"HgiWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/fragments"},{"value":[{"text":"HgiWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/navigatorTitle"},{"value":"HioImageWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title"},{"value":[{"kind":"identifier","text":"HioImageWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments"},{"value":[{"kind":"identifier","text":"HioImageWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle"},{"value":"Write","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1Write\/title"},{"value":[{"text":"Write","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1Write\/fragments"},{"value":[{"text":"Write","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1Write\/navigatorTitle"},{"value":"get","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1get\/title"},{"value":[{"kind":"identifier","text":"get"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1get\/fragments"},{"value":[{"text":"get","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1get\/navigatorTitle"},{"value":"GetFilename","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetFilename\/title"},{"value":[{"text":"GetFilename","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetFilename\/fragments"},{"value":[{"text":"GetFilename","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetFilename\/navigatorTitle"},{"value":"StorageSpec","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1StorageSpec\/title"},{"value":[{"text":"StorageSpec","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1StorageSpec\/fragments"},{"value":[{"text":"StorageSpec","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1StorageSpec\/navigatorTitle"},{"value":"UsdAppUtilsFrameRecorderWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/title"},{"value":[{"kind":"identifier","text":"UsdAppUtilsFrameRecorderWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/fragments"},{"value":[{"kind":"identifier","text":"UsdAppUtilsFrameRecorderWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/navigatorTitle"},{"value":"GetSamplerMetadata","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetSamplerMetadata\/title"},{"value":[{"text":"GetSamplerMetadata","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetSamplerMetadata\/fragments"},{"value":[{"text":"GetSamplerMetadata","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetSamplerMetadata\/navigatorTitle"}]}]}