{"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"seeAlsoSections":[{"title":"Namespace Overlay","anchor":"Namespace-Overlay","generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfErrorMarkWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper"]}],"metadata":{"title":"struct UsdPrimTypeInfoWrapper","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"navigatorTitle":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"symbolKind":"struct","role":"symbol","modules":[{"name":"OpenUSD"}],"roleHeading":"Structure","externalID":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper"},"kind":"symbol","topicSections":[{"title":"Operators","anchor":"Operators","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/operator!=","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/operator=="],"generated":true},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/UsdPrimTypeInfoWrapper-7b7hr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/UsdPrimTypeInfoWrapper-9x5fy"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetAppliedAPISchemas","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetSchemaType","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetSchemaTypeName","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetTypeName","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/get","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/operator_bool"],"generated":true},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetEmptyPrimType"],"generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","url":"\/documentation\/openusd","kind":"symbol","role":"collection","title":"OpenUSD","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper/operator==":{"abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/operator==","role":"symbol","title":"==(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"==","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"operator==","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/operator=="},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper/UsdPrimTypeInfoWrapper-9x5fy":{"abstract":[],"title":"init(_:)","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/usdprimtypeinfowrapper-9x5fy","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdPrim","preciseIdentifier":"c:@N@pxr@S@UsdPrim","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","kind":"typeIdentifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/UsdPrimTypeInfoWrapper-9x5fy","navigatorTitle":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper/UsdPrimTypeInfoWrapper-7b7hr":{"title":"init(_:)","navigatorTitle":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/UsdPrimTypeInfoWrapper-7b7hr","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/usdprimtypeinfowrapper-7b7hr","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdPrimTypeInfo","text":"UsdPrimTypeInfo"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"UsdPrimTypeInfoWrapper"}],"type":"topic","role":"symbol","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HgiMetalWrapper"}],"title":"class HgiMetalWrapper","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HgiMetalWrapper"}],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper":{"kind":"symbol","type":"topic","title":"class ArResolverWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","role":"symbol","navigatorTitle":[{"text":"ArResolverWrapper","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArResolverWrapper","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"type":"topic","title":"struct UsdPrimTypeInfoWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper/operator_bool":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/operator_bool","title":"operator bool","navigatorTitle":[{"text":"operator bool","kind":"identifier"}],"fragments":[{"text":"_Bool","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/operator_bool","role":"symbol","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"kind":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","type":"topic","role":"symbol","fragments":[{"text":"Overlay","kind":"identifier"}],"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiWrapper","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","type":"topic","title":"class HgiWrapper","navigatorTitle":[{"text":"HgiWrapper","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper/operator!=":{"role":"symbol","type":"topic","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/operator!=","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/operator!=","title":"!=(_:_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper","text":"UsdPrimTypeInfoWrapper"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper","text":"UsdPrimTypeInfoWrapper"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:b","text":"Bool"}],"navigatorTitle":[{"text":"operator!=","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdAppUtilsFrameRecorderWrapper":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdAppUtilsFrameRecorderWrapper"}],"title":"class UsdAppUtilsFrameRecorderWrapper","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UsdAppUtilsFrameRecorderWrapper"}],"url":"\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper","kind":"symbol","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"role":"symbol","url":"\/documentation\/openusd\/overlay\/hioimagewrapper","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","navigatorTitle":[{"kind":"identifier","text":"HioImageWrapper"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HioImageWrapper"}],"title":"class HioImageWrapper","abstract":[],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper/get":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/get","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@UsdPrimTypeInfo","kind":"typeIdentifier","text":"UsdPrimTypeInfo"},{"kind":"text","text":">"}],"url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/get","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"get"}],"title":"get()"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper/GetEmptyPrimType":{"kind":"symbol","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/getemptyprimtype","navigatorTitle":[{"kind":"identifier","text":"GetEmptyPrimType"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetEmptyPrimType","role":"symbol","title":"GetEmptyPrimType()","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetEmptyPrimType"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"UsdPrimTypeInfoWrapper","preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper/GetSchemaTypeName":{"url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/getschematypename","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetSchemaTypeName","navigatorTitle":[{"kind":"identifier","text":"GetSchemaTypeName"}],"title":"GetSchemaTypeName()","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetSchemaTypeName","kind":"identifier"},{"text":"()","kind":"text"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfToken","text":"TfToken"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper/GetTypeName":{"abstract":[],"url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/gettypename","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetTypeName","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken","kind":"typeIdentifier"}],"title":"GetTypeName()","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"GetTypeName","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetTypeName"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper/GetSchemaType":{"url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/getschematype","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GetSchemaType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetSchemaType","title":"GetSchemaType()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetSchemaType","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfType","text":"TfType","kind":"typeIdentifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper/GetAppliedAPISchemas":{"abstract":[],"navigatorTitle":[{"text":"GetAppliedAPISchemas","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetAppliedAPISchemas","kind":"symbol","type":"topic","title":"GetAppliedAPISchemas()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetAppliedAPISchemas","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfTokenVector","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfToken#$@N@std@N@__1@S@allocator>#S0_"}],"url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/getappliedapischemas"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/TfErrorMarkWrapper":{"title":"struct TfErrorMarkWrapper","navigatorTitle":[{"kind":"identifier","text":"TfErrorMarkWrapper"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfErrorMarkWrapper","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TfErrorMarkWrapper"}],"url":"\/documentation\/openusd\/overlay\/tferrormarkwrapper","abstract":[],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"title":"class UsdImagingGLEngineWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Structure","op":"replace"},{"path":"\/metadata\/title","value":"UsdPrimTypeInfoWrapper","op":"replace"},{"path":"\/metadata\/symbolKind","value":"struct","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetAppliedAPISchemas","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetSchemaType","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetSchemaTypeName","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetTypeName","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/UsdPrimTypeInfoWrapper-7b7hr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/UsdPrimTypeInfoWrapper-9x5fy","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/get","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/operator!=","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/operator==","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/operator_bool"]},{"anchor":"Type-Methods","title":"Type Methods","generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetEmptyPrimType"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Namespace-Overlay","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper"],"title":"Namespace Overlay"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1operator==\/title","op":"replace","value":"operator=="},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1operator==\/fragments","op":"replace","value":[{"kind":"identifier","text":"operator=="}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1operator==\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"operator=="}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1UsdPrimTypeInfoWrapper-9x5fy\/title","op":"replace","value":"UsdPrimTypeInfoWrapper"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1UsdPrimTypeInfoWrapper-9x5fy\/fragments","op":"replace","value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1UsdPrimTypeInfoWrapper-9x5fy\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1UsdPrimTypeInfoWrapper-7b7hr\/title","op":"replace","value":"UsdPrimTypeInfoWrapper"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1UsdPrimTypeInfoWrapper-7b7hr\/fragments","op":"replace","value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1UsdPrimTypeInfoWrapper-7b7hr\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/title","op":"replace","value":"HgiMetalWrapper"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/fragments","op":"replace","value":[{"kind":"identifier","text":"HgiMetalWrapper"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/navigatorTitle","op":"replace","value":[{"text":"HgiMetalWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/title","op":"replace","value":"ArResolverWrapper"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/fragments","op":"replace","value":[{"text":"ArResolverWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ArResolverWrapper"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/title","op":"replace","value":"UsdPrimTypeInfoWrapper"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/fragments","op":"replace","value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/navigatorTitle","op":"replace","value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1operator_bool\/title","op":"replace","value":"operator bool"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1operator_bool\/fragments","op":"replace","value":[{"text":"_Bool","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1operator_bool\/navigatorTitle","op":"replace","value":[{"text":"operator bool","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace","value":"Overlay"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace","value":[{"text":"Overlay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add","value":[{"text":"Overlay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/title","op":"replace","value":"HgiWrapper"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/fragments","op":"replace","value":[{"kind":"identifier","text":"HgiWrapper"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/navigatorTitle","op":"replace","value":[{"text":"HgiWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1operator!=\/title","op":"replace","value":"operator!="},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1operator!=\/fragments","op":"replace","value":[{"kind":"identifier","text":"operator!="}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1operator!=\/navigatorTitle","op":"replace","value":[{"text":"operator!=","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/title","op":"replace","value":"UsdAppUtilsFrameRecorderWrapper"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/fragments","op":"replace","value":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/navigatorTitle","op":"replace","value":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title","op":"replace","value":"HioImageWrapper"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments","op":"replace","value":[{"text":"HioImageWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle","op":"replace","value":[{"text":"HioImageWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1get\/title","op":"replace","value":"get"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1get\/fragments","op":"replace","value":[{"text":"get","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1get\/navigatorTitle","op":"replace","value":[{"text":"get","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetEmptyPrimType\/title","op":"replace","value":"GetEmptyPrimType"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetEmptyPrimType\/fragments","op":"replace","value":[{"text":"GetEmptyPrimType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetEmptyPrimType\/navigatorTitle","op":"replace","value":[{"text":"GetEmptyPrimType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetSchemaTypeName\/title","op":"replace","value":"GetSchemaTypeName"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetSchemaTypeName\/fragments","op":"replace","value":[{"kind":"identifier","text":"GetSchemaTypeName"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetSchemaTypeName\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GetSchemaTypeName"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetTypeName\/title","op":"replace","value":"GetTypeName"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetTypeName\/fragments","op":"replace","value":[{"kind":"identifier","text":"GetTypeName"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetTypeName\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GetTypeName"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetSchemaType\/title","op":"replace","value":"GetSchemaType"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetSchemaType\/fragments","op":"replace","value":[{"kind":"identifier","text":"GetSchemaType"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetSchemaType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GetSchemaType"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetAppliedAPISchemas\/title","op":"replace","value":"GetAppliedAPISchemas"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetAppliedAPISchemas\/fragments","op":"replace","value":[{"text":"GetAppliedAPISchemas","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetAppliedAPISchemas\/navigatorTitle","op":"replace","value":[{"text":"GetAppliedAPISchemas","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title","op":"replace","value":"UsdImagingGLEngineWrapper"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments","op":"replace","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}