{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitprimarycommandbuffer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitprimarycommandbuffer"]}],"metadata":{"navigatorTitle":[{"text":"CommitPrimaryCommandBuffer","kind":"identifier"}],"role":"symbol","title":"CommitPrimaryCommandBuffer(_:_:)","symbolKind":"method","externalID":"c:@N@Overlay@S@HgiMetalWrapper@F@CommitPrimaryCommandBuffer#$@N@Overlay@S@HgiMetalWrapper@E@CommitCommandBufferWaitType#b#","modules":[{"name":"OpenUSD"}],"fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommitPrimaryCommandBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CommitCommandBufferWaitType","preciseIdentifier":"c:@N@Overlay@S@HgiMetalWrapper@E@CommitCommandBufferWaitType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitPrimaryCommandBuffer"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommitPrimaryCommandBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"waitType","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType","text":"CommitCommandBufferWaitType","kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@S@HgiMetalWrapper@E@CommitCommandBufferWaitType"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"forceNewBuffer","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiMetalWrapper","kind":"identifier"}],"title":"class HgiMetalWrapper","navigatorTitle":[{"text":"HgiMetalWrapper","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","abstract":[],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"title":"Overlay","type":"topic","fragments":[{"kind":"identifier","text":"Overlay"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/CommitPrimaryCommandBuffer":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitPrimaryCommandBuffer","abstract":[],"kind":"symbol","role":"symbol","title":"CommitPrimaryCommandBuffer(_:_:)","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommitPrimaryCommandBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CommitCommandBufferWaitType","preciseIdentifier":"c:@N@Overlay@S@HgiMetalWrapper@E@CommitCommandBufferWaitType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"CommitPrimaryCommandBuffer","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitprimarycommandbuffer"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/CommitCommandBufferWaitType":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommitCommandBufferWaitType"}],"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CommitCommandBufferWaitType"}],"kind":"symbol","role":"symbol","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype","title":"CommitCommandBufferWaitType"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"CommitPrimaryCommandBuffer","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"CommitPrimaryCommandBuffer","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"CommitPrimaryCommandBuffer","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"CommitPrimaryCommandBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@Overlay@S@HgiMetalWrapper@E@CommitCommandBufferWaitType","text":"CommitCommandBufferWaitType","kind":"typeIdentifier","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType"},{"text":" ","kind":"text"},{"text":"waitType","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:b","text":"bool","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"forceNewBuffer","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"HgiMetalWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/title"},{"op":"replace","value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HgiMetalWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/navigatorTitle"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"op":"replace","value":"CommitPrimaryCommandBuffer","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitPrimaryCommandBuffer\/title"},{"op":"replace","value":[{"text":"CommitPrimaryCommandBuffer","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitPrimaryCommandBuffer\/fragments"},{"op":"replace","value":[{"text":"CommitPrimaryCommandBuffer","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitPrimaryCommandBuffer\/navigatorTitle"},{"op":"replace","value":"CommitCommandBufferWaitType","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CommitCommandBufferWaitType"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType\/fragments"},{"op":"replace","value":[{"text":"CommitCommandBufferWaitType","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}