{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommitSecondaryCommandBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"commandBuffer","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"id<MTLCommandBuffer>","preciseIdentifier":"c:Qoobjc(pl)MTLCommandBuffer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"waitType","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CommitCommandBufferWaitType","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType","preciseIdentifier":"c:@N@Overlay@S@HgiMetalWrapper@E@CommitCommandBufferWaitType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitsecondarycommandbuffer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitsecondarycommandbuffer"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@N@Overlay@S@HgiMetalWrapper@F@CommitSecondaryCommandBuffer#*Qoobjc(pl)MTLCommandBuffer#$@N@Overlay@S@HgiMetalWrapper@E@CommitCommandBufferWaitType#","title":"CommitSecondaryCommandBuffer(_:_:)","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommitSecondaryCommandBuffer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MTLCommandBuffer","text":"id<MTLCommandBuffer>"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@S@HgiMetalWrapper@E@CommitCommandBufferWaitType","text":"CommitCommandBufferWaitType"},{"kind":"text","text":")"}],"symbolKind":"method","modules":[{"name":"OpenUSD"}],"navigatorTitle":[{"kind":"identifier","text":"CommitSecondaryCommandBuffer"}],"roleHeading":"Instance Method","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitSecondaryCommandBuffer"},"references":{"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","abstract":[],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiMetalWrapper","kind":"identifier"}],"title":"class HgiMetalWrapper","navigatorTitle":[{"text":"HgiMetalWrapper","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/CommitSecondaryCommandBuffer":{"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitSecondaryCommandBuffer","type":"topic","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitsecondarycommandbuffer","kind":"symbol","abstract":[],"fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommitSecondaryCommandBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<MTLCommandBuffer>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MTLCommandBuffer"},{"text":", ","kind":"text"},{"text":"CommitCommandBufferWaitType","kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@S@HgiMetalWrapper@E@CommitCommandBufferWaitType"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"CommitSecondaryCommandBuffer","kind":"identifier"}],"title":"CommitSecondaryCommandBuffer(_:_:)"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/CommitCommandBufferWaitType":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommitCommandBufferWaitType"}],"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CommitCommandBufferWaitType"}],"kind":"symbol","role":"symbol","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype","title":"CommitCommandBufferWaitType"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"title":"Overlay","type":"topic","fragments":[{"kind":"identifier","text":"Overlay"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"CommitSecondaryCommandBuffer","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"CommitSecondaryCommandBuffer"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"CommitSecondaryCommandBuffer"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommitSecondaryCommandBuffer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MTLCommandBuffer>","preciseIdentifier":"c:Qoobjc(pl)MTLCommandBuffer"},{"kind":"text","text":" "},{"kind":"internalParam","text":"commandBuffer"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"CommitCommandBufferWaitType","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType","preciseIdentifier":"c:@N@Overlay@S@HgiMetalWrapper@E@CommitCommandBufferWaitType"},{"kind":"text","text":" "},{"kind":"internalParam","text":"waitType"},{"kind":"text","text":");"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"HgiMetalWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/title"},{"value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/fragments"},{"value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/navigatorTitle"},{"value":"CommitSecondaryCommandBuffer","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitSecondaryCommandBuffer\/title"},{"value":[{"kind":"identifier","text":"CommitSecondaryCommandBuffer"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitSecondaryCommandBuffer\/fragments"},{"value":[{"kind":"identifier","text":"CommitSecondaryCommandBuffer"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitSecondaryCommandBuffer\/navigatorTitle"},{"value":"CommitCommandBufferWaitType","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType\/title"},{"value":[{"text":"CommitCommandBufferWaitType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType\/fragments"},{"value":[{"kind":"identifier","text":"CommitCommandBufferWaitType"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType\/navigatorTitle"},{"value":"Overlay","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"text":"Overlay","kind":"identifier"}]}]}]}