{"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetSecondaryCommandBuffer"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:Qoobjc(pl)MTLCommandBuffer","kind":"typeIdentifier","text":"id<MTLCommandBuffer>"}],"navigatorTitle":[{"text":"GetSecondaryCommandBuffer","kind":"identifier"}],"externalID":"c:@N@Overlay@S@HgiMetalWrapper@F@GetSecondaryCommandBuffer#","title":"GetSecondaryCommandBuffer()","role":"symbol","symbolKind":"method","modules":[{"name":"OpenUSD"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetSecondaryCommandBuffer","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"id<MTLCommandBuffer>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MTLCommandBuffer"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/getsecondarycommandbuffer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/getsecondarycommandbuffer"]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/GetSecondaryCommandBuffer","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","kind":"symbol","abstract":[],"url":"\/documentation\/openusd","role":"collection","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/GetSecondaryCommandBuffer":{"title":"GetSecondaryCommandBuffer()","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/getsecondarycommandbuffer","type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/GetSecondaryCommandBuffer","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetSecondaryCommandBuffer","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"id<MTLCommandBuffer>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MTLCommandBuffer"}],"navigatorTitle":[{"text":"GetSecondaryCommandBuffer","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HgiMetalWrapper"}],"type":"topic","abstract":[],"title":"class HgiMetalWrapper","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HgiMetalWrapper"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"url":"\/documentation\/openusd\/overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol","title":"Overlay","type":"topic","kind":"symbol","fragments":[{"text":"Overlay","kind":"identifier"}],"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"GetSecondaryCommandBuffer","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"GetSecondaryCommandBuffer","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"GetSecondaryCommandBuffer"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"text":"id<MTLCommandBuffer>","preciseIdentifier":"c:Qoobjc(pl)MTLCommandBuffer","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"GetSecondaryCommandBuffer","kind":"identifier"},{"text":"();","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"GetSecondaryCommandBuffer","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1GetSecondaryCommandBuffer\/title"},{"value":[{"kind":"identifier","text":"GetSecondaryCommandBuffer"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1GetSecondaryCommandBuffer\/fragments"},{"value":[{"text":"GetSecondaryCommandBuffer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1GetSecondaryCommandBuffer\/navigatorTitle"},{"value":"HgiMetalWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/title"},{"value":[{"kind":"identifier","text":"HgiMetalWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/fragments"},{"value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/navigatorTitle"},{"value":"Overlay","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"}]}]}