{"metadata":{"modules":[{"name":"OpenUSD"}],"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"GetTextureArgumentEncoder","kind":"identifier"}],"title":"GetTextureArgumentEncoder()","externalID":"c:@N@Overlay@S@HgiMetalWrapper@F@GetTextureArgumentEncoder#1","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetTextureArgumentEncoder","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)MTLArgumentEncoder","text":"id<MTLArgumentEncoder>","kind":"typeIdentifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/gettextureargumentencoder"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/gettextureargumentencoder"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/GetTextureArgumentEncoder","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetTextureArgumentEncoder","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"id<MTLArgumentEncoder>","preciseIdentifier":"c:Qoobjc(pl)MTLArgumentEncoder","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper":{"abstract":[],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","type":"topic","title":"class HgiMetalWrapper","navigatorTitle":[{"kind":"identifier","text":"HgiMetalWrapper"}],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HgiMetalWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD":{"type":"topic","url":"\/documentation\/openusd","title":"OpenUSD","role":"collection","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/GetTextureArgumentEncoder":{"url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/gettextureargumentencoder","title":"GetTextureArgumentEncoder()","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/GetTextureArgumentEncoder","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetTextureArgumentEncoder"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"id<MTLArgumentEncoder>","preciseIdentifier":"c:Qoobjc(pl)MTLArgumentEncoder"}],"navigatorTitle":[{"kind":"identifier","text":"GetTextureArgumentEncoder"}],"abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"text":"Overlay","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"GetTextureArgumentEncoder","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"GetTextureArgumentEncoder","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"GetTextureArgumentEncoder"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"id<MTLArgumentEncoder>","preciseIdentifier":"c:Qoobjc(pl)MTLArgumentEncoder","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"GetTextureArgumentEncoder","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["macOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/title","value":"HgiMetalWrapper"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/fragments","value":[{"kind":"identifier","text":"HgiMetalWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/navigatorTitle","value":[{"text":"HgiMetalWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1GetTextureArgumentEncoder\/title","value":"GetTextureArgumentEncoder"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1GetTextureArgumentEncoder\/fragments","value":[{"kind":"identifier","text":"GetTextureArgumentEncoder"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1GetTextureArgumentEncoder\/navigatorTitle","value":[{"text":"GetTextureArgumentEncoder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"text":"Overlay","kind":"identifier"}]}]}]}