{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"device","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"id<MTLDevice>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MTLDevice"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"HgiMetalWrapper","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/HgiMetalWrapper-72qmz","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"HgiMetalWrapper","kind":"identifier"}],"modules":[{"name":"OpenUSD"}],"title":"init(_:)","role":"symbol","symbolKind":"init","externalID":"c:@N@Overlay@S@HgiMetalWrapper@F@HgiMetalWrapper#*Qoobjc(pl)MTLDevice#","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)MTLDevice","text":"id<MTLDevice>","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"HgiMetalWrapper","kind":"typeIdentifier"}],"roleHeading":"Initializer"},"variants":[{"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/hgimetalwrapper-72qmz"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/hgimetalwrapper-72qmz"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper"]]},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"title":"Overlay","type":"topic","fragments":[{"kind":"identifier","text":"Overlay"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiMetalWrapper","kind":"identifier"}],"title":"class HgiMetalWrapper","navigatorTitle":[{"text":"HgiMetalWrapper","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","abstract":[],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/HgiMetalWrapper-72qmz":{"url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/hgimetalwrapper-72qmz","title":"init(_:)","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/HgiMetalWrapper-72qmz","navigatorTitle":[{"text":"HgiMetalWrapper","kind":"identifier"}],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<MTLDevice>","preciseIdentifier":"c:Qoobjc(pl)MTLDevice","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"HgiMetalWrapper","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Constructor","path":"\/metadata\/roleHeading","op":"replace"},{"value":"HgiMetalWrapper","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"text":"HgiMetalWrapper","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)MTLDevice","text":"id<MTLDevice>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"device","kind":"internalParam"},{"text":");","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace"},{"value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add"},{"value":"HgiMetalWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/title","op":"replace"},{"value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/fragments","op":"replace"},{"value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/navigatorTitle","op":"replace"},{"value":"HgiMetalWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1HgiMetalWrapper-72qmz\/title","op":"replace"},{"value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1HgiMetalWrapper-72qmz\/fragments","op":"replace"},{"value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1HgiMetalWrapper-72qmz\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}