{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hgi"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@N@Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","kind":"identifier","text":"Overlay"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@Overlay@S@HgiWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","kind":"typeIdentifier","text":"HgiWrapper"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"HgiMetalWrapper"}]}]}],"variants":[{"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/hgimetalwrapper-8xa1x"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/hgimetalwrapper-8xa1x"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper"]]},"kind":"symbol","identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/HgiMetalWrapper-8xa1x","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"HgiMetalWrapper"}],"role":"symbol","externalID":"c:@N@Overlay@S@HgiMetalWrapper@F@HgiMetalWrapper#$@N@Overlay@S@HgiWrapper#","modules":[{"name":"OpenUSD"}],"symbolKind":"init","title":"init(_:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@N@Overlay","kind":"identifier","text":"Overlay"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@Overlay@S@HgiWrapper","kind":"typeIdentifier","text":"HgiWrapper"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"HgiMetalWrapper"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper":{"navigatorTitle":[{"text":"HgiWrapper","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/openusd\/overlay\/hgiwrapper","title":"class HgiWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiWrapper","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/HgiMetalWrapper-8xa1x":{"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/HgiMetalWrapper-8xa1x","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Overlay","preciseIdentifier":"c:@N@Overlay","kind":"identifier"},{"text":".","kind":"text"},{"text":"HgiWrapper","preciseIdentifier":"c:@N@Overlay@S@HgiWrapper","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"HgiMetalWrapper","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"HgiMetalWrapper","kind":"identifier"}],"kind":"symbol","title":"init(_:)","type":"topic","abstract":[],"url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/hgimetalwrapper-8xa1x"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","abstract":[],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"title":"Overlay","type":"topic","fragments":[{"kind":"identifier","text":"Overlay"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiMetalWrapper","kind":"identifier"}],"title":"class HgiMetalWrapper","navigatorTitle":[{"text":"HgiMetalWrapper","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Constructor"},{"op":"replace","path":"\/metadata\/title","value":"HgiMetalWrapper"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"HgiMetalWrapper","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HgiMetalWrapper"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"HgiMetalWrapper","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Overlay","preciseIdentifier":"c:@N@Overlay","kind":"identifier","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay"},{"text":"::","kind":"text"},{"text":"HgiWrapper","preciseIdentifier":"c:@N@Overlay@S@HgiWrapper","kind":"typeIdentifier","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper"},{"text":" ","kind":"text"},{"text":"hgi","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/title","value":"HgiWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/fragments","value":[{"text":"HgiWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/navigatorTitle","value":[{"text":"HgiWrapper","kind":"identifier"}],"op":"replace"},{"value":"HgiMetalWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1HgiMetalWrapper-8xa1x\/title"},{"value":[{"kind":"identifier","text":"HgiMetalWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1HgiMetalWrapper-8xa1x\/fragments"},{"value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1HgiMetalWrapper-8xa1x\/navigatorTitle"},{"value":"Overlay","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"value":[{"kind":"identifier","text":"Overlay"}],"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"value":"HgiMetalWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/title"},{"value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/fragments"},{"value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}