{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/operator_"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"<"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"text","text":": "},{"preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","kind":"typeIdentifier","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","text":"SwiftKey"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"other"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","kind":"typeIdentifier","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","text":"SwiftKey"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:b","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"],"platforms":["macOS"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/openusd\/swiftkey\/operator_"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/swiftkey\/operator_"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@N@pxr@S@TfNotice@S@SwiftKey@F@operator<#&1$@N@pxr@S@TfNotice@S@SwiftKey#1","modules":[{"name":"OpenUSD"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"<","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SwiftKey","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"SwiftKey","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"symbolKind":"op","roleHeading":"Operator","navigatorTitle":[{"kind":"identifier","text":"operator<"}],"title":"<(_:_:)"},"kind":"symbol","abstract":[{"type":"text","text":"Enables sorting and holding "},{"type":"codeVoice","code":"SwiftKey"},{"type":"text","text":"s in a map."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey"]]},"references":{"doc://SwiftUsd/documentation/OpenUSD/SwiftKey/operator_":{"navigatorTitle":[{"text":"operator<","kind":"identifier"}],"url":"\/documentation\/openusd\/swiftkey\/operator_","kind":"symbol","abstract":[{"type":"text","text":"Enables sorting and holding "},{"code":"SwiftKey","type":"codeVoice"},{"type":"text","text":"s in a map."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"<"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SwiftKey","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"SwiftKey","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"c:b"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/operator_","role":"symbol","title":"<(_:_:)"},"doc://SwiftUsd/documentation/OpenUSD":{"role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","abstract":[],"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/SwiftKey":{"navigatorTitle":[{"text":"SwiftKey","kind":"identifier"}],"title":"class SwiftKey","abstract":[{"type":"text","text":"A key representing a listener registered from either Swift or C++"}],"role":"symbol","url":"\/documentation\/openusd\/swiftkey","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SwiftKey","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"operator<","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"operator<","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"operator<","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"bool","preciseIdentifier":"c:b","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"operator<","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","text":"SwiftKey","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"other","kind":"internalParam"},{"text":") ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1operator_\/title","op":"replace","value":"operator<"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1operator_\/fragments","op":"replace","value":[{"kind":"identifier","text":"operator<"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1operator_\/navigatorTitle","op":"replace","value":[{"text":"operator<","kind":"identifier"}]},{"value":"SwiftKey","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/title"},{"value":[{"kind":"identifier","text":"SwiftKey"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/fragments"},{"value":[{"kind":"identifier","text":"SwiftKey"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}