{"variants":[{"paths":["\/documentation\/openusd\/swiftkey\/operator_bool"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/swiftkey\/operator_bool"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Does this key refer to a valid notification?","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"operator"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"_Bool"},{"kind":"text","text":"() "},{"kind":"keyword","text":"const"},{"kind":"text","text":";"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"text":"The boolean operator is identical to ","type":"text"},{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/IsValid","type":"reference"},{"text":" above.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"fragments":[{"text":"_Bool","kind":"identifier"}],"navigatorTitle":[{"text":"operator bool","kind":"identifier"}],"roleHeading":"Instance Method","title":"operator bool","role":"symbol","modules":[{"name":"OpenUSD"}],"externalID":"c:@N@pxr@S@TfNotice@S@SwiftKey@F@operator bool#1","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/operator_bool"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","references":{"doc://SwiftUsd/documentation/OpenUSD/SwiftKey/IsValid":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsValid","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"IsValid","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Does this key refer to a valid notification?"}],"title":"IsValid()","url":"\/documentation\/openusd\/swiftkey\/isvalid","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/IsValid"},"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","url":"\/documentation\/openusd","kind":"symbol","role":"collection","title":"OpenUSD","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/SwiftKey/operator_bool":{"abstract":[{"type":"text","text":"Does this key refer to a valid notification?"}],"fragments":[{"kind":"identifier","text":"_Bool"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/operator_bool","type":"topic","kind":"symbol","url":"\/documentation\/openusd\/swiftkey\/operator_bool","role":"symbol","title":"operator bool","navigatorTitle":[{"kind":"identifier","text":"operator bool"}]},"doc://SwiftUsd/documentation/OpenUSD/SwiftKey":{"navigatorTitle":[{"kind":"identifier","text":"SwiftKey"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwiftKey"}],"type":"topic","title":"class SwiftKey","abstract":[{"type":"text","text":"A key representing a listener registered from either Swift or C++"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","url":"\/documentation\/openusd\/swiftkey","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"operator bool"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"_Bool","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"operator bool","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"operator","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_Bool","kind":"typeIdentifier"},{"text":"() ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1IsValid\/title","value":"IsValid"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1IsValid\/fragments","value":[{"text":"IsValid","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1IsValid\/navigatorTitle","value":[{"kind":"identifier","text":"IsValid"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1operator_bool\/title","value":"operator bool"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1operator_bool\/fragments","value":[{"text":"_Bool","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1operator_bool\/navigatorTitle","value":[{"text":"operator bool","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/title","value":"SwiftKey"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/fragments","value":[{"text":"SwiftKey","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/navigatorTitle","value":[{"kind":"identifier","text":"SwiftKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}