{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Converts a C++ key into a Swift key. The resulting Swift key can be used to cancel the C++ listener in Swift or in C++.","type":"text"}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/SwiftKey-59c3e","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"registrationKey","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice@S@Key","text":"Key","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","title":"init(_:)","navigatorTitle":[{"text":"SwiftKey","kind":"identifier"}],"roleHeading":"Initializer","externalID":"c:@N@pxr@S@TfNotice@S@SwiftKey@F@SwiftKey#$@N@pxr@S@TfNotice@S@Key#","modules":[{"name":"OpenUSD"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"Key","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@Key"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/swiftkey\/swiftkey-59c3e"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/swiftkey\/swiftkey-59c3e"]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey"]]},"references":{"doc://SwiftUsd/documentation/OpenUSD/SwiftKey":{"navigatorTitle":[{"text":"SwiftKey","kind":"identifier"}],"title":"class SwiftKey","abstract":[{"type":"text","text":"A key representing a listener registered from either Swift or C++"}],"role":"symbol","url":"\/documentation\/openusd\/swiftkey","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SwiftKey","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/SwiftKey/SwiftKey-59c3e":{"title":"init(_:)","abstract":[{"type":"text","text":"Converts a C++ key into a Swift key. The resulting Swift key can be used to cancel the C++ listener in Swift or in C++."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SwiftKey"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@Key","text":"Key"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SwiftKey"}],"url":"\/documentation\/openusd\/swiftkey\/swiftkey-59c3e","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/SwiftKey-59c3e","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","abstract":[],"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Constructor"},{"op":"replace","path":"\/metadata\/title","value":"SwiftKey"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SwiftKey"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SwiftKey"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SwiftKey"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","text":"Key","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@Key"},{"kind":"text","text":" "},{"kind":"internalParam","text":"registrationKey"},{"kind":"text","text":");"}],"platforms":["macOS"],"languages":["occ"]}]}},{"op":"replace","value":"SwiftKey","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/title"},{"op":"replace","value":[{"text":"SwiftKey","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/fragments"},{"op":"replace","value":[{"text":"SwiftKey","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/navigatorTitle"},{"op":"replace","value":"SwiftKey","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1SwiftKey-59c3e\/title"},{"op":"replace","value":[{"text":"SwiftKey","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1SwiftKey-59c3e\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SwiftKey"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1SwiftKey-59c3e\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}