{"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SdfZipFileIteratorWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@S@SdfZipFileIteratorWrapper"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"SdfZipFileIteratorWrapper","kind":"typeIdentifier"}],"modules":[{"name":"OpenUSD"}],"symbolKind":"init","navigatorTitle":[{"text":"SdfZipFileIteratorWrapper","kind":"identifier"}],"externalID":"c:@N@Overlay@S@SdfZipFileIteratorWrapper@F@SdfZipFileIteratorWrapper#&1$@N@Overlay@S@SdfZipFileIteratorWrapper#","title":"init(_:)","roleHeading":"Initializer","role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfZipFileIteratorWrapper"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"other","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfZipFileIteratorWrapper","preciseIdentifier":"c:@N@Overlay@S@SdfZipFileIteratorWrapper","text":"SdfZipFileIteratorWrapper","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"SdfZipFileIteratorWrapper"}],"platforms":["macOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/openusd\/overlay\/sdfzipfileiteratorwrapper\/sdfzipfileiteratorwrapper-xpt6"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfZipFileIteratorWrapper\/SdfZipFileIteratorWrapper-xpt6","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/SdfZipFileIteratorWrapper":{"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SdfZipFileIteratorWrapper","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfZipFileIteratorWrapper","role":"symbol","url":"\/documentation\/openusd\/overlay\/sdfzipfileiteratorwrapper","type":"topic","navigatorTitle":[{"text":"SdfZipFileIteratorWrapper","kind":"identifier"}],"title":"struct SdfZipFileIteratorWrapper","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"text":"Overlay","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/SdfZipFileIteratorWrapper/SdfZipFileIteratorWrapper-xpt6":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfZipFileIteratorWrapper\/SdfZipFileIteratorWrapper-xpt6","role":"symbol","type":"topic","url":"\/documentation\/openusd\/overlay\/sdfzipfileiteratorwrapper\/sdfzipfileiteratorwrapper-xpt6","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SdfZipFileIteratorWrapper","preciseIdentifier":"c:@N@Overlay@S@SdfZipFileIteratorWrapper"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SdfZipFileIteratorWrapper"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SdfZipFileIteratorWrapper"}],"title":"init(_:)","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"type":"topic","url":"\/documentation\/openusd","title":"OpenUSD","role":"collection","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace","value":"Overlay"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace","value":[{"text":"Overlay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add","value":[{"kind":"identifier","text":"Overlay"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}