{"metadata":{"fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"DecodeIntersection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:c","text":"unsigned char"},{"kind":"text","text":" "},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@SdfPath","text":"SdfPath"},{"kind":"text","text":">"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:I","text":"CInt"},{"kind":"text","text":">"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@std@N@__1@S@pair>#$@N@pxr@S@SdfPath#I#$@N@std@N@__1@S@allocator>#S0_","text":"HdInstancerContext"},{"kind":"text","text":">"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:b","text":"Bool"}],"externalID":"c:@N@Overlay@S@UsdImagingGLEngineWrapper@F@DecodeIntersection#*1c#S0_#*$@N@pxr@S@SdfPath#S1_#*I#*$@N@std@N@__1@S@vector>#$@N@std@N@__1@S@pair>#S2_#I#$@N@std@N@__1@S@allocator>#S6_#","title":"DecodeIntersection(_:_:_:_:)","navigatorTitle":[{"text":"DecodeIntersection","kind":"identifier"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"OpenUSD"}]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"DecodeIntersection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"outHitPrimPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafePointer"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:c","text":"unsigned char","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"primIdColor","kind":"internalParam"},{"text":"[","kind":"text"},{"text":"4","kind":"number"},{"text":"], ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:c","text":"unsigned char","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"instanceIdColor","kind":"internalParam"},{"text":"[","kind":"text"},{"text":"4","kind":"number"},{"text":"], ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@SdfPath","text":"SdfPath","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"outHitInstancerPath","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@SdfPath","text":"SdfPath","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"outHitInstanceIndex","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:I","text":"CInt","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"outInstancerContext","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@std@N@__1@S@pair>#$@N@pxr@S@SdfPath#I#$@N@std@N@__1@S@allocator>#S0_","text":"HdInstancerContext","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:b","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/DecodeIntersection-1rw0g","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/decodeintersection-1rw0g"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/decodeintersection-1rw0g"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"kind":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","type":"topic","role":"symbol","fragments":[{"text":"Overlay","kind":"identifier"}],"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/DecodeIntersection-1rw0g":{"fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"DecodeIntersection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:c","text":"unsigned char"},{"kind":"text","text":" "},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@SdfPath","text":"SdfPath"},{"kind":"text","text":">"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:I","text":"CInt"},{"kind":"text","text":">"},{"kind":"text","text":", "},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"HdInstancerContext","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@std@N@__1@S@pair>#$@N@pxr@S@SdfPath#I#$@N@std@N@__1@S@allocator>#S0_"},{"text":">","kind":"text"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}],"url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/decodeintersection-1rw0g","abstract":[],"type":"topic","navigatorTitle":[{"text":"DecodeIntersection","kind":"identifier"}],"title":"DecodeIntersection(_:_:_:_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/DecodeIntersection-1rw0g","kind":"symbol","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"title":"class UsdImagingGLEngineWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"},"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","url":"\/documentation\/openusd","kind":"symbol","role":"collection","title":"OpenUSD","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"DecodeIntersection"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DecodeIntersection"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DecodeIntersection","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"preciseIdentifier":"c:b","text":"bool","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"DecodeIntersection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:c","text":"unsigned char","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"primIdColor","kind":"internalParam"},{"text":"[","kind":"text"},{"text":"4","kind":"number"},{"text":"], ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:c","text":"unsigned char","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"instanceIdColor","kind":"internalParam"},{"text":"[","kind":"text"},{"text":"4","kind":"number"},{"text":"], ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":"::","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@SdfPath","text":"SdfPath","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"outHitPrimPath","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":"::","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@SdfPath","text":"SdfPath","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"outHitInstancerPath","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:I","text":"int","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"outHitInstanceIndex","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":"::","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@std@N@__1@S@pair>#$@N@pxr@S@SdfPath#I#$@N@std@N@__1@S@allocator>#S0_","text":"HdInstancerContext","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"outInstancerContext","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace","value":"Overlay"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace","value":[{"text":"Overlay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add","value":[{"text":"Overlay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1DecodeIntersection-1rw0g\/title","op":"replace","value":"DecodeIntersection"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1DecodeIntersection-1rw0g\/fragments","op":"replace","value":[{"text":"DecodeIntersection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1DecodeIntersection-1rw0g\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DecodeIntersection"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title","op":"replace","value":"UsdImagingGLEngineWrapper"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments","op":"replace","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle","op":"replace","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}]}]}]}