{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/InvokeRendererCommand"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvokeRendererCommand"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"command"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@TfToken","kind":"typeIdentifier","text":"TfToken"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"args"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@VtDictionary","kind":"typeIdentifier","text":"HdCommandArgs"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:b","kind":"typeIdentifier","text":"Bool"}],"platforms":["macOS"],"languages":["swift"]}]}],"metadata":{"externalID":"c:@N@Overlay@S@UsdImagingGLEngineWrapper@F@InvokeRendererCommand#&1$@N@pxr@S@TfToken#&1$@N@pxr@S@VtDictionary#1","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvokeRendererCommand","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfToken","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfToken"},{"text":", ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"HdCommandArgs","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@VtDictionary"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}],"navigatorTitle":[{"text":"InvokeRendererCommand","kind":"identifier"}],"title":"InvokeRendererCommand(_:_:)","modules":[{"name":"OpenUSD"}],"symbolKind":"method","role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/invokerenderercommand"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/invokerenderercommand"]}],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"type":"topic","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"navigatorTitle":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"abstract":[],"title":"class UsdImagingGLEngineWrapper","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","title":"OpenUSD","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","type":"topic","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/InvokeRendererCommand":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvokeRendererCommand"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfToken","text":"TfToken"},{"kind":"text","text":", "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@VtDictionary","text":"HdCommandArgs"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:b","text":"Bool"}],"type":"topic","abstract":[],"title":"InvokeRendererCommand(_:_:)","kind":"symbol","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/invokerenderercommand","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/InvokeRendererCommand","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"InvokeRendererCommand"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"type":"topic","url":"\/documentation\/openusd\/overlay","fragments":[{"kind":"identifier","text":"Overlay"}],"title":"Overlay"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"InvokeRendererCommand"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"InvokeRendererCommand","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"InvokeRendererCommand"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"bool","kind":"typeIdentifier","preciseIdentifier":"c:b"},{"text":" ","kind":"text"},{"text":"InvokeRendererCommand","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":"::","kind":"text"},{"text":"TfToken","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfToken"},{"text":" & ","kind":"text"},{"text":"command","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":"::","kind":"text"},{"text":"HdCommandArgs","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@VtDictionary"},{"text":" & ","kind":"text"},{"text":"args","kind":"internalParam"},{"text":") ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["macOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title","op":"replace","value":"UsdImagingGLEngineWrapper"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments","op":"replace","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1InvokeRendererCommand\/title","value":"InvokeRendererCommand","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1InvokeRendererCommand\/fragments","value":[{"kind":"identifier","text":"InvokeRendererCommand"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1InvokeRendererCommand\/navigatorTitle","value":[{"kind":"identifier","text":"InvokeRendererCommand"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"kind":"identifier","text":"Overlay"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"text":"Overlay","kind":"identifier"}],"op":"add"}]}]}