{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"]]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters"},"variants":[{"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/parameters"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/parameters"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"struct Parameters","navigatorTitle":[{"kind":"identifier","text":"Parameters"}],"role":"symbol","roleHeading":"Structure","modules":[{"name":"OpenUSD"}],"symbolKind":"struct","externalID":"c:@N@Overlay@S@UsdImagingGLEngineWrapper@S@Parameters","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Parameters"}]},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/allowAsynchronousSceneProcessing","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/displayUnloadedPrimsWithBounds","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/driver","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/enableUsdDrawModes","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/excludedPaths","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/gpuEnabled","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/invisedPaths","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/rendererPluginId","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/rootPath","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/sceneDelegateID"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Parameters","kind":"identifier"}]}]}],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/Parameters/invisedPaths":{"navigatorTitle":[{"kind":"identifier","text":"invisedPaths"}],"role":"symbol","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/parameters\/invisedpaths","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"invisedPaths"},{"kind":"text","text":": "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@SdfPath#$@N@std@N@__1@S@allocator>#S0_","text":"SdfPathVector"}],"title":"invisedPaths","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/invisedPaths","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"role":"symbol","url":"\/documentation\/openusd\/overlay","fragments":[{"kind":"identifier","text":"Overlay"}],"kind":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","type":"topic","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/Parameters/enableUsdDrawModes":{"kind":"symbol","title":"enableUsdDrawModes","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/enableUsdDrawModes","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableUsdDrawModes","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:b","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/parameters\/enableusddrawmodes","abstract":[],"navigatorTitle":[{"text":"enableUsdDrawModes","kind":"identifier"}],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","type":"topic","url":"\/documentation\/openusd","abstract":[],"role":"collection"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/Parameters/rootPath":{"abstract":[],"url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/parameters\/rootpath","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/rootPath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootPath"},{"kind":"text","text":": "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SdfPath","preciseIdentifier":"c:@N@pxr@S@SdfPath"}],"title":"rootPath","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rootPath"}],"kind":"symbol","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/Parameters/displayUnloadedPrimsWithBounds":{"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayUnloadedPrimsWithBounds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}],"abstract":[],"navigatorTitle":[{"text":"displayUnloadedPrimsWithBounds","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/parameters\/displayunloadedprimswithbounds","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/displayUnloadedPrimsWithBounds","title":"displayUnloadedPrimsWithBounds","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/Parameters/driver":{"title":"driver","navigatorTitle":[{"kind":"identifier","text":"driver"}],"abstract":[],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/driver","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"driver"},{"kind":"text","text":": "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HdDriver","preciseIdentifier":"c:@N@pxr@S@HdDriver"}],"url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/parameters\/driver","role":"symbol","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/Parameters/rendererPluginId":{"url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/parameters\/rendererpluginid","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rendererPluginId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfToken","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfToken"}],"navigatorTitle":[{"text":"rendererPluginId","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"rendererPluginId","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/rendererPluginId","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/Parameters/excludedPaths":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"excludedPaths"},{"kind":"text","text":": "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SdfPathVector","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@SdfPath#$@N@std@N@__1@S@allocator>#S0_"}],"url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/parameters\/excludedpaths","navigatorTitle":[{"kind":"identifier","text":"excludedPaths"}],"abstract":[],"type":"topic","title":"excludedPaths","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/excludedPaths"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"title":"class UsdImagingGLEngineWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","type":"topic","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/Parameters/allowAsynchronousSceneProcessing":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/allowAsynchronousSceneProcessing","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/parameters\/allowasynchronoussceneprocessing","type":"topic","title":"allowAsynchronousSceneProcessing","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowAsynchronousSceneProcessing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"c:b"}],"navigatorTitle":[{"kind":"identifier","text":"allowAsynchronousSceneProcessing"}],"abstract":[],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/Parameters/sceneDelegateID":{"kind":"symbol","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/parameters\/scenedelegateid","navigatorTitle":[{"text":"sceneDelegateID","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/sceneDelegateID","type":"topic","abstract":[],"title":"sceneDelegateID","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sceneDelegateID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"SdfPath","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@SdfPath"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/Parameters":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/parameters","type":"topic","title":"struct Parameters","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Parameters"}],"navigatorTitle":[{"kind":"identifier","text":"Parameters"}],"abstract":[],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/Parameters/gpuEnabled":{"title":"gpuEnabled","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/parameters\/gpuenabled","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/gpuEnabled","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gpuEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"c:b"}],"navigatorTitle":[{"kind":"identifier","text":"gpuEnabled"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Structure"},{"op":"replace","path":"\/metadata\/title","value":"Parameters"},{"op":"replace","value":"struct","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"Parameters"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Parameters"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/allowAsynchronousSceneProcessing","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/displayUnloadedPrimsWithBounds","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/driver","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/enableUsdDrawModes","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/excludedPaths","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/gpuEnabled","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/invisedPaths","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/rendererPluginId","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/rootPath","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/Parameters\/sceneDelegateID"]}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Parameters"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"invisedPaths","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1invisedPaths\/title"},{"op":"replace","value":[{"text":"invisedPaths","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1invisedPaths\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"invisedPaths"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1invisedPaths\/navigatorTitle"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"op":"replace","value":"enableUsdDrawModes","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1enableUsdDrawModes\/title"},{"op":"replace","value":[{"kind":"identifier","text":"enableUsdDrawModes"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1enableUsdDrawModes\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"enableUsdDrawModes"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1enableUsdDrawModes\/navigatorTitle"},{"op":"replace","value":"rootPath","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1rootPath\/title"},{"op":"replace","value":[{"text":"rootPath","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1rootPath\/fragments"},{"op":"replace","value":[{"text":"rootPath","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1rootPath\/navigatorTitle"},{"op":"replace","value":"displayUnloadedPrimsWithBounds","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1displayUnloadedPrimsWithBounds\/title"},{"op":"replace","value":[{"kind":"identifier","text":"displayUnloadedPrimsWithBounds"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1displayUnloadedPrimsWithBounds\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"displayUnloadedPrimsWithBounds"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1displayUnloadedPrimsWithBounds\/navigatorTitle"},{"op":"replace","value":"driver","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1driver\/title"},{"op":"replace","value":[{"text":"driver","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1driver\/fragments"},{"op":"replace","value":[{"text":"driver","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1driver\/navigatorTitle"},{"op":"replace","value":"rendererPluginId","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1rendererPluginId\/title"},{"op":"replace","value":[{"text":"rendererPluginId","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1rendererPluginId\/fragments"},{"op":"replace","value":[{"text":"rendererPluginId","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1rendererPluginId\/navigatorTitle"},{"op":"replace","value":"excludedPaths","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1excludedPaths\/title"},{"op":"replace","value":[{"kind":"identifier","text":"excludedPaths"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1excludedPaths\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"excludedPaths"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1excludedPaths\/navigatorTitle"},{"op":"replace","value":"UsdImagingGLEngineWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle"},{"op":"replace","value":"allowAsynchronousSceneProcessing","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1allowAsynchronousSceneProcessing\/title"},{"op":"replace","value":[{"kind":"identifier","text":"allowAsynchronousSceneProcessing"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1allowAsynchronousSceneProcessing\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"allowAsynchronousSceneProcessing"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1allowAsynchronousSceneProcessing\/navigatorTitle"},{"op":"replace","value":"sceneDelegateID","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1sceneDelegateID\/title"},{"op":"replace","value":[{"kind":"identifier","text":"sceneDelegateID"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1sceneDelegateID\/fragments"},{"op":"replace","value":[{"text":"sceneDelegateID","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1sceneDelegateID\/navigatorTitle"},{"op":"replace","value":"Parameters","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters\/title"},{"op":"replace","value":[{"text":"Parameters","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Parameters"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters\/navigatorTitle"},{"op":"replace","value":"gpuEnabled","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1gpuEnabled\/title"},{"op":"replace","value":[{"text":"gpuEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1gpuEnabled\/fragments"},{"op":"replace","value":[{"text":"gpuEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1Parameters~1gpuEnabled\/navigatorTitle"}]}]}