{"kind":"symbol","sections":[],"metadata":{"externalID":"c:@N@Overlay@S@UsdImagingGLEngineWrapper@F@SetActiveRenderSettingsPrimPath#&1$@N@pxr@S@SdfPath#","title":"SetActiveRenderSettingsPrimPath(_:)","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SetActiveRenderSettingsPrimPath"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SdfPath","preciseIdentifier":"c:@N@pxr@S@SdfPath"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"OpenUSD"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SetActiveRenderSettingsPrimPath"}]},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/SetActiveRenderSettingsPrimPath"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SetActiveRenderSettingsPrimPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"path","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"SdfPath","preciseIdentifier":"c:@N@pxr@S@SdfPath","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/setactiverendersettingsprimpath"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/setactiverendersettingsprimpath"]}],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"type":"topic","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"navigatorTitle":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"abstract":[],"title":"class UsdImagingGLEngineWrapper","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"type":"topic","url":"\/documentation\/openusd\/overlay","fragments":[{"kind":"identifier","text":"Overlay"}],"title":"Overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/SetActiveRenderSettingsPrimPath":{"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SetActiveRenderSettingsPrimPath"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/SetActiveRenderSettingsPrimPath","role":"symbol","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/setactiverendersettingsprimpath","type":"topic","title":"SetActiveRenderSettingsPrimPath(_:)","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SetActiveRenderSettingsPrimPath"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SdfPath","preciseIdentifier":"c:@N@pxr@S@SdfPath"},{"kind":"text","text":")"}]},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","title":"OpenUSD","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SetActiveRenderSettingsPrimPath","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SetActiveRenderSettingsPrimPath"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SetActiveRenderSettingsPrimPath"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SetActiveRenderSettingsPrimPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":"::","kind":"text"},{"text":"SdfPath","preciseIdentifier":"c:@N@pxr@S@SdfPath","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"path","kind":"internalParam"},{"text":");","kind":"text"}],"languages":["occ"],"platforms":["macOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title","value":"UsdImagingGLEngineWrapper"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"kind":"identifier","text":"Overlay"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1SetActiveRenderSettingsPrimPath\/title","value":"SetActiveRenderSettingsPrimPath"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1SetActiveRenderSettingsPrimPath\/fragments","value":[{"kind":"identifier","text":"SetActiveRenderSettingsPrimPath"}]},{"value":[{"kind":"identifier","text":"SetActiveRenderSettingsPrimPath"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1SetActiveRenderSettingsPrimPath\/navigatorTitle"}]}]}