{"variants":[{"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/setselectioncolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/setselectioncolor"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/SetSelectionColor","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"OpenUSD"}],"fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SetSelectionColor"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"GfVec4f","preciseIdentifier":"c:@N@pxr@S@GfVec4f"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"SetSelectionColor"}],"roleHeading":"Instance Method","externalID":"c:@N@Overlay@S@UsdImagingGLEngineWrapper@F@SetSelectionColor#&1$@N@pxr@S@GfVec4f#","title":"SetSelectionColor(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SetSelectionColor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"color","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"GfVec4f","preciseIdentifier":"c:@N@pxr@S@GfVec4f","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["macOS"]}]}],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/SetSelectionColor":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/SetSelectionColor","title":"SetSelectionColor(_:)","type":"topic","navigatorTitle":[{"text":"SetSelectionColor","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SetSelectionColor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"GfVec4f","preciseIdentifier":"c:@N@pxr@S@GfVec4f","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/setselectioncolor","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","url":"\/documentation\/openusd","kind":"symbol","role":"collection","title":"OpenUSD","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"kind":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","type":"topic","role":"symbol","fragments":[{"text":"Overlay","kind":"identifier"}],"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"title":"class UsdImagingGLEngineWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"SetSelectionColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SetSelectionColor","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SetSelectionColor","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SetSelectionColor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":"::","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@GfVec4f","text":"GfVec4f","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"color","kind":"internalParam"},{"text":");","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1SetSelectionColor\/title","value":"SetSelectionColor"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1SetSelectionColor\/fragments","value":[{"kind":"identifier","text":"SetSelectionColor"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1SetSelectionColor\/navigatorTitle","value":[{"kind":"identifier","text":"SetSelectionColor"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"kind":"identifier","text":"Overlay"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title","value":"UsdImagingGLEngineWrapper"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}]}]}]}