{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-30vnv"},"metadata":{"externalID":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Sender","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Sender","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Notice","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","kind":"typeIdentifier"},{"text":".Type, (","kind":"text"},{"text":"Notice","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Sender","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"borrowing","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"NoticeCaster","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV","kind":"typeIdentifier"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SwiftKey","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","kind":"typeIdentifier"}],"roleHeading":"Type Method","title":"Register(_:_:_:)","symbolKind":"method","extendedModule":"C++","modules":[{"relatedModules":["C++"],"name":"OpenUSD"}]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Register a listener as being interested in a TfNotice from a particular sender."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Register"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Notice"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"Sender"},{"text":">(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Sender","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Notice","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","kind":"typeIdentifier"},{"text":".Type = Notice.self, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"callback","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"Notice","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Sender","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"borrowing","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"NoticeCaster","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/NoticeCaster","kind":"typeIdentifier"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SwiftKey","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Notice","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"SwiftUsd","preciseIdentifier":"c:@N@SwiftUsd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"TfNoticeProtocol","preciseIdentifier":"s:So8SwiftUsdO7OpenUSDE16TfNoticeProtocolP","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/SwiftUsd\/TfNoticeProtocol","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Sender","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Overlay","preciseIdentifier":"c:@N@Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"_TfWeakBaseProtocol","preciseIdentifier":"s:So7OverlayO7OpenUSDE19_TfWeakBaseProtocolP","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfWeakBaseProtocol","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Sender","kind":"typeIdentifier"},{"text":" == ","kind":"text"},{"text":"Sender","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"_SelfType","preciseIdentifier":"s:So7OverlayO7OpenUSDE30_SwiftUsdReferenceTypeProtocolP05_SelfG0Qa","kind":"typeIdentifier"}],"platforms":["macOS"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Registration of interest in a notice class ","type":"text"},{"code":"N","type":"codeVoice"},{"text":" automatically registers interest in all classes derived from ","type":"text"},{"code":"N","type":"codeVoice"},{"text":". When a notice of appropriate type is received, the ","type":"text"},{"code":"callback","type":"codeVoice"},{"text":" is called with the notice. To dynamically downcast notice types in the callback, use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/NoticeCaster"},{"text":" parameter.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To reverse the registration, call "},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0","type":"reference","isActive":true},{"type":"text","text":" on the "},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","type":"reference","isActive":true},{"type":"text","text":" object returned by this call."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This form of registration listens for notices from a particular sender, receiving the sender in the callback. The sender being registered for must be derived from "},{"code":"pxr::TfWeakBase","type":"codeVoice"},{"type":"text","text":"."}]}]}],"seeAlsoSections":[{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-olq9","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-u8ws","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-c3be","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-9hzry","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-8nkmw","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-2xoh5","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-7ycue","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-9e095"],"anchor":"Type-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-30vnv"]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice"]]},"references":{"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-u8ws":{"kind":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-u8ws","type":"topic","title":"Register(_:_:_:)","abstract":[{"type":"text","text":"Register a listener as being interested in a TfNotice from a particular sender."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Sender","kind":"genericParameter"},{"text":">(","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyxYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp","text":"Sender","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyxYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice","kind":"typeIdentifier"},{"text":".Type, (","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyxYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice","kind":"typeIdentifier"},{"text":") -> ()) -> ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","text":"SwiftKey","kind":"typeIdentifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-u8ws","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","url":"\/documentation\/openusd","kind":"symbol","role":"collection","title":"OpenUSD","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice","type":"topic","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier"},{"text":".","kind":"text"},{"text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice","kind":"identifier"}],"abstract":[],"role":"symbol","title":"pxr.TfNotice","kind":"symbol","navigatorTitle":[{"text":"TfNotice","kind":"identifier"}],"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-8nkmw":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-8nkmw","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Sender","kind":"genericParameter"},{"text":">(","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp","text":"Sender","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice"},{"kind":"text","text":".Type, ("},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice"},{"kind":"text","text":", "},{"kind":"keyword","text":"borrowing"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV","text":"NoticeCaster"},{"kind":"text","text":") -> ()) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","text":"SwiftKey"}],"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-8nkmw","abstract":[{"type":"text","text":"Register a listener as being interested in a TfNotice from a particular sender."}],"type":"topic","title":"Register(_:_:_:)"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-c3be":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Register"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Notice"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"Sender"},{"kind":"text","text":">("},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp","text":"Sender"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice"},{"kind":"text","text":".Type, ("},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp","text":"Sender"},{"kind":"text","text":") -> ()) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","text":"SwiftKey"}],"type":"topic","title":"Register(_:_:_:)","abstract":[{"type":"text","text":"Register a listener as being interested in a TfNotice from a particular sender."}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-c3be","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-c3be","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"kind":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","type":"topic","role":"symbol","fragments":[{"text":"Overlay","kind":"identifier"}],"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:)-9hzry":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"text":", ","kind":"text"},{"text":"borrowing","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"NoticeCaster","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"type":"topic","title":"Register(_:_:)","abstract":[{"text":"Register a listener as being interested in a TfNotice, regardless of sender.","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-9hzry","kind":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:)-9hzry","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++":{"role":"collection","title":"C++","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++","url":"\/documentation\/openusd\/c++"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd","type":"topic","fragments":[{"kind":"identifier","text":"SwiftUsd"}],"role":"symbol","abstract":[],"title":"SwiftUsd","url":"\/documentation\/openusd\/swiftusd"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/_TfWeakBaseProtocol":{"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_TfWeakBaseProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"_TfWeakBaseProtocol","kind":"identifier"}],"url":"\/documentation\/openusd\/c++\/overlay\/_tfweakbaseprotocol","title":"Overlay._TfWeakBaseProtocol","abstract":[{"text":"Protocol representing ","type":"text"},{"code":"pxr::TfWeakBase","type":"codeVoice"},{"text":" subclasses. Don’t use this unless you know what you’re doing","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfWeakBaseProtocol","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/SwiftUsd/TfNoticeProtocol":{"kind":"symbol","abstract":[{"type":"text","text":"Protocol representing "},{"type":"codeVoice","code":"pxr::TfNotice"},{"type":"text","text":" subclasses."}],"url":"\/documentation\/openusd\/c++\/swiftusd\/tfnoticeprotocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TfNoticeProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"TfNoticeProtocol","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/SwiftUsd\/TfNoticeProtocol","type":"topic","title":"SwiftUsd.TfNoticeProtocol"},"doc://SwiftUsd/documentation/OpenUSD/RevokeAndWait-9e095":{"navigatorTitle":[{"text":"RevokeAndWait","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"RevokeAndWait"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S0_","text":"SwiftKeys"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"type":"topic","title":"RevokeAndWait(_:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-9e095","url":"\/documentation\/openusd\/revokeandwait-9e095","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Revoke-31sr0":{"navigatorTitle":[{"text":"Revoke","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Revoke","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}],"type":"topic","title":"Revoke(_:)","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0","kind":"symbol","url":"\/documentation\/openusd\/revoke-31sr0","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/SwiftKey":{"navigatorTitle":[{"kind":"identifier","text":"SwiftKey"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwiftKey"}],"type":"topic","title":"class SwiftKey","abstract":[{"type":"text","text":"A key representing a listener registered from either Swift or C++"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","url":"\/documentation\/openusd\/swiftkey","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Revoke-2xoh5":{"navigatorTitle":[{"kind":"identifier","text":"Revoke"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Revoke"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S0_","text":"SwiftKeys"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"type":"topic","title":"Revoke(_:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-2xoh5","url":"\/documentation\/openusd\/revoke-2xoh5","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:)-olq9":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"type":"topic","title":"Register(_:_:)","abstract":[{"text":"Register a listener as being interested in a TfNotice, regardless of sender.","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-olq9","kind":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:)-olq9","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/NoticeCaster":{"kind":"symbol","abstract":[{"text":"Utility struct that lets uses cast ","type":"text"},{"code":"pxr::TfNotice","type":"codeVoice"},{"text":" subclasses in a ","type":"text"},{"code":"pxr::TfNotice::Register","type":"codeVoice"},{"text":" callback","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NoticeCaster","kind":"identifier"}],"navigatorTitle":[{"text":"NoticeCaster","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/noticecaster","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/NoticeCaster","title":"pxr.TfNotice.NoticeCaster"},"doc://SwiftUsd/documentation/OpenUSD/RevokeAndWait-7ycue":{"navigatorTitle":[{"text":"RevokeAndWait","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RevokeAndWait","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}],"type":"topic","title":"RevokeAndWait(_:)","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-7ycue","kind":"symbol","url":"\/documentation\/openusd\/revokeandwait-7ycue","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-30vnv":{"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-30vnv","role":"symbol","type":"topic","kind":"symbol","title":"Register(_:_:_:)","abstract":[{"type":"text","text":"Register a listener as being interested in a TfNotice from a particular sender."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Sender","kind":"genericParameter"},{"text":">(","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp","text":"Sender","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice","kind":"typeIdentifier"},{"text":".Type, (","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp","text":"Sender","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"borrowing","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_5__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV","text":"NoticeCaster","kind":"typeIdentifier"},{"text":") -> ()) -> ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","text":"SwiftKey","kind":"typeIdentifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-30vnv"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr","type":"topic","navigatorTitle":[{"text":"pxr","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openusd\/c++\/pxr","role":"symbol","title":"pxr"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"op":"replace","value":"SwiftUsd","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SwiftUsd"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/fragments"},{"op":"add","value":[{"text":"SwiftUsd","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/navigatorTitle"},{"op":"replace","value":"RevokeAndWait","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-9e095\/title"},{"op":"replace","value":[{"text":"RevokeAndWait","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-9e095\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"RevokeAndWait"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-9e095\/navigatorTitle"},{"op":"replace","value":"Revoke","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/title"},{"op":"replace","value":[{"text":"Revoke","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Revoke"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/navigatorTitle"},{"op":"replace","value":"SwiftKey","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SwiftKey"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/fragments"},{"op":"replace","value":[{"text":"SwiftKey","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/navigatorTitle"},{"op":"replace","value":"Revoke","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-2xoh5\/title"},{"op":"replace","value":[{"text":"Revoke","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-2xoh5\/fragments"},{"op":"replace","value":[{"text":"Revoke","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-2xoh5\/navigatorTitle"},{"op":"replace","value":"RevokeAndWait","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-7ycue\/title"},{"op":"replace","value":[{"kind":"identifier","text":"RevokeAndWait"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-7ycue\/fragments"},{"op":"replace","value":[{"text":"RevokeAndWait","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-7ycue\/navigatorTitle"}]}]}