{"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/HdCachingSceneIndex\/as(_:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Dynamically casts ","type":"text"},{"code":"self","type":"codeVoice"},{"text":" to the argument type.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`as`","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"t","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolPACE2asyqd__Sgqd__mAbCEADRd__9_SelfTypeQyd__Rsd__lF1TL_qd__mfp","text":"T","kind":"typeIdentifier"},{"text":".Type = T.self) -> ","kind":"text"},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolPACE2asyqd__Sgqd__mAbCEADRd__9_SelfTypeQyd__Rsd__lF1TL_qd__mfp","text":"T","kind":"typeIdentifier"},{"text":"? ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","preciseIdentifier":"c:@N@Overlay","text":"Overlay","kind":"typeIdentifier"},{"text":".","kind":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfRefBaseProtocol","preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolP","text":"_TfRefBaseProtocol","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":" == ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE30_SwiftUsdReferenceTypeProtocolP05_SelfG0Qa","text":"_SelfType","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["macOS"]}]},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"In Swift 6.0, the built-in "},{"type":"codeVoice","code":"as\/as?\/as!"},{"type":"text","text":" operators don’t work properly on foreign reference types."},{"type":"text","text":" "},{"type":"text","text":"Instead, use this function to conditionally cast between subclasses of "},{"type":"codeVoice","code":"pxr::TfRefBase"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/openusd\/c++\/pxr\/hdcachingsceneindex\/as(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/HdCachingSceneIndex"]]},"metadata":{"modules":[{"name":"OpenUSD"}],"externalID":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolPACE2asyqd__Sgqd__mAbCEADRd__9_SelfTypeQyd__Rsd__lF::SYNTHESIZED::c:@N@pxr@S@HdCachingSceneIndex","role":"symbol","roleHeading":"Instance Method","title":"as(_:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`as`","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolPACE2asyqd__Sgqd__mAbCEADRd__9_SelfTypeQyd__Rsd__lF1TL_qd__mfp","kind":"typeIdentifier"},{"text":".Type) -> ","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolPACE2asyqd__Sgqd__mAbCEADRd__9_SelfTypeQyd__Rsd__lF1TL_qd__mfp","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"extendedModule":"OpenUSD"},"references":{"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/_TfRefBaseProtocol":{"kind":"symbol","title":"Overlay._TfRefBaseProtocol","abstract":[{"type":"text","text":"Protocol representing "},{"type":"codeVoice","code":"pxr::TfRefBase"},{"type":"text","text":" subclasses. Don’t use this unless you know what you’re doing"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfRefBaseProtocol","type":"topic","url":"\/documentation\/openusd\/c++\/overlay\/_tfrefbaseprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_TfRefBaseProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"_TfRefBaseProtocol","kind":"identifier"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/HdCachingSceneIndex/as(_:)":{"type":"topic","abstract":[{"type":"text","text":"Dynamically casts "},{"code":"self","type":"codeVoice"},{"type":"text","text":" to the argument type."}],"url":"\/documentation\/openusd\/c++\/pxr\/hdcachingsceneindex\/as(_:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/HdCachingSceneIndex\/as(_:)","title":"as(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`as`","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolPACE2asyqd__Sgqd__mAbCEADRd__9_SelfTypeQyd__Rsd__lF1TL_qd__mfp","text":"T","kind":"typeIdentifier"},{"text":".Type) -> ","kind":"text"},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfRefBaseProtocolPACE2asyqd__Sgqd__mAbCEADRd__9_SelfTypeQyd__Rsd__lF1TL_qd__mfp","text":"T","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/HdCachingSceneIndex":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"HdCachingSceneIndex","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier"},{"text":".","kind":"text"},{"text":"HdCachingSceneIndex","preciseIdentifier":"c:@N@pxr@S@HdCachingSceneIndex","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/HdCachingSceneIndex","title":"pxr.HdCachingSceneIndex","url":"\/documentation\/openusd\/c++\/pxr\/hdcachingsceneindex"},"doc://SwiftUsd/documentation/OpenUSD":{"role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","abstract":[],"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr":{"kind":"symbol","type":"topic","title":"pxr","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr","navigatorTitle":[{"text":"pxr","kind":"identifier"}],"url":"\/documentation\/openusd\/c++\/pxr","abstract":[],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++":{"type":"topic","kind":"symbol","title":"C++","url":"\/documentation\/openusd\/c++","role":"collection","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"kind":"identifier","text":"Overlay"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","title":"Overlay","type":"topic","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/overlay"}},"variantOverrides":[{"patch":[{"value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace"},{"value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add"}],"traits":[{"interfaceLanguage":"occ"}]}]}