{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType\/CommitCommandBuffer_WaitUntilScheduled"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype\/commitcommandbuffer_waituntilscheduled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype\/commitcommandbuffer_waituntilscheduled"]}],"kind":"symbol","metadata":{"role":"symbol","title":"CommitCommandBuffer_WaitUntilScheduled","externalID":"c:@N@Overlay@S@HgiMetalWrapper@E@CommitCommandBufferWaitType@CommitCommandBuffer_WaitUntilScheduled","roleHeading":"Enumeration Case","navigatorTitle":[{"text":"CommitCommandBuffer_WaitUntilScheduled","kind":"identifier"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommitCommandBuffer_WaitUntilScheduled","kind":"identifier"}],"modules":[{"name":"OpenUSD"}]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommitCommandBuffer_WaitUntilScheduled"}]}],"kind":"declarations"}],"references":{"doc://SwiftUsd/documentation/OpenUSD":{"type":"topic","url":"\/documentation\/openusd","title":"OpenUSD","role":"collection","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/CommitCommandBufferWaitType/CommitCommandBuffer_WaitUntilScheduled":{"navigatorTitle":[{"kind":"identifier","text":"CommitCommandBuffer_WaitUntilScheduled"}],"role":"symbol","type":"topic","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype\/commitcommandbuffer_waituntilscheduled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommitCommandBuffer_WaitUntilScheduled"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType\/CommitCommandBuffer_WaitUntilScheduled","abstract":[],"title":"CommitCommandBuffer_WaitUntilScheduled","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper":{"abstract":[],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","type":"topic","title":"class HgiMetalWrapper","navigatorTitle":[{"kind":"identifier","text":"HgiMetalWrapper"}],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HgiMetalWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"text":"Overlay","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/CommitCommandBufferWaitType":{"type":"topic","title":"CommitCommandBufferWaitType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommitCommandBufferWaitType"}],"navigatorTitle":[{"kind":"identifier","text":"CommitCommandBufferWaitType"}],"url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CommitCommandBuffer_WaitUntilScheduled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"CommitCommandBuffer_WaitUntilScheduled","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"CommitCommandBuffer_WaitUntilScheduled","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"identifier","text":"CommitCommandBuffer_WaitUntilScheduled"}],"languages":["occ"]}]}},{"op":"replace","value":"CommitCommandBuffer_WaitUntilScheduled","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType~1CommitCommandBuffer_WaitUntilScheduled\/title"},{"op":"replace","value":[{"text":"CommitCommandBuffer_WaitUntilScheduled","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType~1CommitCommandBuffer_WaitUntilScheduled\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CommitCommandBuffer_WaitUntilScheduled"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType~1CommitCommandBuffer_WaitUntilScheduled\/navigatorTitle"},{"op":"replace","value":"HgiMetalWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/title"},{"op":"replace","value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HgiMetalWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/navigatorTitle"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"op":"replace","value":"CommitCommandBufferWaitType","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CommitCommandBufferWaitType"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType\/fragments"},{"op":"replace","value":[{"text":"CommitCommandBufferWaitType","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}