{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++"]]},"metadata":{"extendedModule":"C++","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SwiftUsd","kind":"identifier","preciseIdentifier":"c:@N@SwiftUsd"}],"roleHeading":"Extended Enumeration","symbolKind":"extension","role":"symbol","modules":[{"name":"OpenUSD","relatedModules":["C++"]}],"navigatorTitle":[{"text":"SwiftUsd","kind":"identifier"}],"externalID":"s:e:s:So8SwiftUsdO7OpenUSDE16TfNoticeProtocolP","title":"SwiftUsd"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/c++\/swiftusd"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/SwiftUsd"},"kind":"symbol","sections":[],"topicSections":[{"generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/SwiftUsd\/TfNoticeProtocol"],"title":"Protocols","anchor":"Protocols"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@SwiftUsd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd","kind":"typeIdentifier","text":"SwiftUsd"}],"languages":["swift"]}]}],"references":{"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","abstract":[],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/SwiftUsd":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/SwiftUsd","navigatorTitle":[{"text":"SwiftUsd","kind":"identifier"}],"abstract":[],"title":"SwiftUsd","kind":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"text":" ","kind":"text"},{"text":"SwiftUsd","kind":"identifier","preciseIdentifier":"c:@N@SwiftUsd"}],"url":"\/documentation\/openusd\/c++\/swiftusd","type":"topic","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++":{"abstract":[],"role":"collection","url":"\/documentation\/openusd\/c++","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++","type":"topic","kind":"symbol","title":"C++"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd","kind":"symbol","url":"\/documentation\/openusd\/swiftusd","type":"topic","title":"SwiftUsd","role":"symbol","fragments":[{"text":"SwiftUsd","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/SwiftUsd/TfNoticeProtocol":{"navigatorTitle":[{"kind":"identifier","text":"TfNoticeProtocol"}],"title":"SwiftUsd.TfNoticeProtocol","abstract":[{"type":"text","text":"Protocol representing "},{"type":"codeVoice","code":"pxr::TfNotice"},{"type":"text","text":" subclasses."}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/SwiftUsd\/TfNoticeProtocol","url":"\/documentation\/openusd\/c++\/swiftusd\/tfnoticeprotocol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TfNoticeProtocol"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/title","value":"SwiftUsd"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/fragments","value":[{"kind":"identifier","text":"SwiftUsd"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/navigatorTitle","value":[{"text":"SwiftUsd","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}