{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get_shared","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"std","preciseIdentifier":"c:@N@std","kind":"identifier"},{"text":".","kind":"text"},{"text":"std::shared_ptr","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdAppUtilsFrameRecorder","preciseIdentifier":"c:@N@pxr@S@UsdAppUtilsFrameRecorder","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["macOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper"]]},"metadata":{"title":"get_shared()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get_shared"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"std::shared_ptr","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"UsdAppUtilsFrameRecorder","preciseIdentifier":"c:@N@pxr@S@UsdAppUtilsFrameRecorder"},{"kind":"text","text":">"}],"externalID":"c:@N@Overlay@S@UsdAppUtilsFrameRecorderWrapper@F@get_shared#1","modules":[{"name":"OpenUSD"}],"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"get_shared","kind":"identifier"}],"symbolKind":"method"},"variants":[{"paths":["\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper\/get_shared"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper\/get_shared"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper\/get_shared","interfaceLanguage":"swift"},"sections":[],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdAppUtilsFrameRecorderWrapper/get_shared":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper\/get_shared","title":"get_shared()","abstract":[],"url":"\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper\/get_shared","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get_shared"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@N@std","text":"std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr","text":"std::shared_ptr"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@UsdAppUtilsFrameRecorder","kind":"typeIdentifier","text":"UsdAppUtilsFrameRecorder"},{"kind":"text","text":">"}],"navigatorTitle":[{"kind":"identifier","text":"get_shared"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdAppUtilsFrameRecorderWrapper":{"navigatorTitle":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"title":"class UsdAppUtilsFrameRecorderWrapper","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"type":"topic","url":"\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"role":"symbol","url":"\/documentation\/openusd\/overlay","fragments":[{"kind":"identifier","text":"Overlay"}],"kind":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","type":"topic","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","type":"topic","url":"\/documentation\/openusd","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"get_shared","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"get_shared","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"get_shared"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"std","preciseIdentifier":"c:@N@std","kind":"identifier"},{"text":"::","kind":"text"},{"text":"std::shared_ptr","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":"::","kind":"text"},{"text":"UsdAppUtilsFrameRecorder","preciseIdentifier":"c:@N@pxr@S@UsdAppUtilsFrameRecorder","kind":"typeIdentifier"},{"text":"> ","kind":"text"},{"text":"get_shared","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}],"platforms":["macOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"get_shared","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper~1get_shared\/title"},{"value":[{"text":"get_shared","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper~1get_shared\/fragments"},{"value":[{"text":"get_shared","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper~1get_shared\/navigatorTitle"},{"value":"UsdAppUtilsFrameRecorderWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/title"},{"value":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/fragments"},{"value":[{"kind":"identifier","text":"UsdAppUtilsFrameRecorderWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/navigatorTitle"},{"value":"Overlay","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}