{"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper\/SetImageWidth","interfaceLanguage":"swift"},"metadata":{"role":"symbol","navigatorTitle":[{"text":"SetImageWidth","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"OpenUSD"}],"fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SetImageWidth","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@size_t","text":"size_t","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@N@Overlay@S@UsdAppUtilsFrameRecorderWrapper@F@SetImageWidth#l#","title":"SetImageWidth(_:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SetImageWidth"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"imageWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"size_t","preciseIdentifier":"c:@T@size_t"},{"text":")","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper\/setimagewidth"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper\/setimagewidth"]}],"sections":[],"kind":"symbol","references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdAppUtilsFrameRecorderWrapper/SetImageWidth":{"url":"\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper\/setimagewidth","title":"SetImageWidth(_:)","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SetImageWidth","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@size_t","text":"size_t","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper\/SetImageWidth","navigatorTitle":[{"text":"SetImageWidth","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","abstract":[],"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"kind":"identifier","text":"Overlay"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","title":"Overlay","type":"topic","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdAppUtilsFrameRecorderWrapper":{"navigatorTitle":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper","abstract":[],"title":"class UsdAppUtilsFrameRecorderWrapper","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SetImageWidth","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SetImageWidth"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SetImageWidth"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" "},{"kind":"identifier","text":"SetImageWidth"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"size_t","preciseIdentifier":"c:@T@size_t"},{"kind":"text","text":" "},{"kind":"internalParam","text":"imageWidth"},{"kind":"text","text":");"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SetImageWidth","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper~1SetImageWidth\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SetImageWidth"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper~1SetImageWidth\/fragments"},{"op":"replace","value":[{"text":"SetImageWidth","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper~1SetImageWidth\/navigatorTitle"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"op":"replace","value":"UsdAppUtilsFrameRecorderWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"UsdAppUtilsFrameRecorderWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/fragments"},{"op":"replace","value":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}