{"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"OpenUSD"}],"externalID":"c:@N@Overlay@S@UsdAppUtilsFrameRecorderWrapper@F@SetPrimaryCameraPrimPath#&1$@N@pxr@S@SdfPath#","title":"SetPrimaryCameraPrimPath(_:)","symbolKind":"method","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SetPrimaryCameraPrimPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"SdfPath","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@SdfPath"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"SetPrimaryCameraPrimPath","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper\/SetPrimaryCameraPrimPath"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SetPrimaryCameraPrimPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"cameraPath","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"SdfPath","preciseIdentifier":"c:@N@pxr@S@SdfPath","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper\/setprimarycameraprimpath"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper\/setprimarycameraprimpath"]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper"]]},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"type":"topic","url":"\/documentation\/openusd\/overlay","fragments":[{"kind":"identifier","text":"Overlay"}],"title":"Overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdAppUtilsFrameRecorderWrapper":{"title":"class UsdAppUtilsFrameRecorderWrapper","navigatorTitle":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper","role":"symbol","url":"\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper","type":"topic","abstract":[],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","title":"OpenUSD","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","type":"topic","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdAppUtilsFrameRecorderWrapper/SetPrimaryCameraPrimPath":{"navigatorTitle":[{"kind":"identifier","text":"SetPrimaryCameraPrimPath"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper\/SetPrimaryCameraPrimPath","url":"\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper\/setprimarycameraprimpath","abstract":[],"title":"SetPrimaryCameraPrimPath(_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SetPrimaryCameraPrimPath"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@SdfPath","text":"SdfPath"},{"kind":"text","text":")"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SetPrimaryCameraPrimPath","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SetPrimaryCameraPrimPath"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SetPrimaryCameraPrimPath","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" "},{"kind":"identifier","text":"SetPrimaryCameraPrimPath"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"::"},{"preciseIdentifier":"c:@N@pxr@S@SdfPath","kind":"typeIdentifier","text":"SdfPath"},{"kind":"text","text":" & "},{"kind":"internalParam","text":"cameraPath"},{"kind":"text","text":");"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"text":"Overlay","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/title","value":"UsdAppUtilsFrameRecorderWrapper"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/fragments","value":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/navigatorTitle","value":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper~1SetPrimaryCameraPrimPath\/title","value":"SetPrimaryCameraPrimPath"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper~1SetPrimaryCameraPrimPath\/fragments","value":[{"kind":"identifier","text":"SetPrimaryCameraPrimPath"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper~1SetPrimaryCameraPrimPath\/navigatorTitle","value":[{"kind":"identifier","text":"SetPrimaryCameraPrimPath"}]}]}]}