{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetAppliedAPISchemas","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfToken#$@N@std@N@__1@S@allocator>#S0_","text":"TfTokenVector","kind":"typeIdentifier"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper@F@GetAppliedAPISchemas#1","symbolKind":"method","roleHeading":"Instance Method","title":"GetAppliedAPISchemas()","navigatorTitle":[{"text":"GetAppliedAPISchemas","kind":"identifier"}],"modules":[{"name":"OpenUSD"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetAppliedAPISchemas","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfTokenVector","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfToken#$@N@std@N@__1@S@allocator>#S0_"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetAppliedAPISchemas"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper"]]},"variants":[{"paths":["\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/getappliedapischemas"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/getappliedapischemas"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"references":{"doc://SwiftUsd/documentation/OpenUSD":{"role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","abstract":[],"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper/GetAppliedAPISchemas":{"title":"GetAppliedAPISchemas()","role":"symbol","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/getappliedapischemas","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetAppliedAPISchemas","kind":"symbol","type":"topic","navigatorTitle":[{"text":"GetAppliedAPISchemas","kind":"identifier"}],"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetAppliedAPISchemas","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfTokenVector","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfToken#$@N@std@N@__1@S@allocator>#S0_"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper":{"url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","abstract":[],"kind":"symbol","title":"struct UsdPrimTypeInfoWrapper","role":"symbol","navigatorTitle":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"kind":"identifier","text":"Overlay"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","title":"Overlay","type":"topic","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/overlay"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"GetAppliedAPISchemas"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GetAppliedAPISchemas","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GetAppliedAPISchemas","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"::"},{"preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfToken#$@N@std@N@__1@S@allocator>#S0_","kind":"typeIdentifier","text":"TfTokenVector"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetAppliedAPISchemas"},{"kind":"text","text":"() "},{"kind":"keyword","text":"const"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"GetAppliedAPISchemas","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetAppliedAPISchemas\/title"},{"op":"replace","value":[{"text":"GetAppliedAPISchemas","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetAppliedAPISchemas\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GetAppliedAPISchemas"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetAppliedAPISchemas\/navigatorTitle"},{"op":"replace","value":"UsdPrimTypeInfoWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/navigatorTitle"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"}]}]}