{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper"]]},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"UsdPrimTypeInfo","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdPrimTypeInfo"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","kind":"typeIdentifier"}],"externalID":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper@F@UsdPrimTypeInfoWrapper#&1$@N@pxr@S@UsdPrimTypeInfo#","modules":[{"name":"OpenUSD"}],"symbolKind":"init","roleHeading":"Initializer","title":"init(_:)","role":"symbol","navigatorTitle":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"_impl","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"UsdPrimTypeInfo","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdPrimTypeInfo"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"UsdPrimTypeInfoWrapper"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/usdprimtypeinfowrapper-7b7hr"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/usdprimtypeinfowrapper-7b7hr"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/UsdPrimTypeInfoWrapper-7b7hr"},"references":{"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","title":"OpenUSD","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","type":"topic","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper/UsdPrimTypeInfoWrapper-7b7hr":{"title":"init(_:)","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/usdprimtypeinfowrapper-7b7hr","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/UsdPrimTypeInfoWrapper-7b7hr","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"UsdPrimTypeInfo","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdPrimTypeInfo"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","title":"struct UsdPrimTypeInfoWrapper","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"type":"topic","url":"\/documentation\/openusd\/overlay","fragments":[{"kind":"identifier","text":"Overlay"}],"title":"Overlay"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Constructor","path":"\/metadata\/roleHeading"},{"op":"replace","value":"UsdPrimTypeInfoWrapper","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","text":"UsdPrimTypeInfo","preciseIdentifier":"c:@N@pxr@S@UsdPrimTypeInfo"},{"kind":"text","text":" & "},{"kind":"internalParam","text":"_impl"},{"kind":"text","text":");"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"UsdPrimTypeInfoWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1UsdPrimTypeInfoWrapper-7b7hr\/title"},{"op":"replace","value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1UsdPrimTypeInfoWrapper-7b7hr\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1UsdPrimTypeInfoWrapper-7b7hr\/navigatorTitle"},{"op":"replace","value":"UsdPrimTypeInfoWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/navigatorTitle"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"}]}]}