{"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/GetRendererSetting"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetRendererSetting"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"id"},{"kind":"text","text":": "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfToken","text":"TfToken"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@VtValue","text":"VtValue"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/getrenderersetting"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/getrenderersetting"]}],"metadata":{"role":"symbol","externalID":"c:@N@Overlay@S@UsdImagingGLEngineWrapper@F@GetRendererSetting#&1$@N@pxr@S@TfToken#1","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetRendererSetting","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"VtValue","preciseIdentifier":"c:@N@pxr@S@VtValue","kind":"typeIdentifier"}],"roleHeading":"Instance Method","title":"GetRendererSetting(_:)","navigatorTitle":[{"text":"GetRendererSetting","kind":"identifier"}],"modules":[{"name":"OpenUSD"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"]]},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"fragments":[{"text":"Overlay","kind":"identifier"}],"role":"symbol","title":"Overlay","type":"topic","url":"\/documentation\/openusd\/overlay","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay"},"doc://SwiftUsd/documentation/OpenUSD":{"url":"\/documentation\/openusd","kind":"symbol","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"navigatorTitle":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"role":"symbol","title":"class UsdImagingGLEngineWrapper","type":"topic","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/GetRendererSetting":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/GetRendererSetting","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetRendererSetting"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfToken","text":"TfToken"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@VtValue","text":"VtValue"}],"type":"topic","title":"GetRendererSetting(_:)","kind":"symbol","navigatorTitle":[{"text":"GetRendererSetting","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/getrenderersetting"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"GetRendererSetting","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"GetRendererSetting","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GetRendererSetting"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":"::","kind":"text"},{"text":"VtValue","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@VtValue"},{"text":" ","kind":"text"},{"text":"GetRendererSetting","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":"::","kind":"text"},{"text":"TfToken","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfToken"},{"text":" & ","kind":"text"},{"text":"id","kind":"internalParam"},{"text":") ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"text":"Overlay","kind":"identifier"}],"op":"add"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title","value":"UsdImagingGLEngineWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1GetRendererSetting\/title","value":"GetRendererSetting","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1GetRendererSetting\/fragments","value":[{"kind":"identifier","text":"GetRendererSetting"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1GetRendererSetting\/navigatorTitle","value":[{"kind":"identifier","text":"GetRendererSetting"}],"op":"replace"}]}]}