{"sections":[],"kind":"symbol","metadata":{"symbolKind":"typealias","roleHeading":"Type Alias","navigatorTitle":[{"text":"IntersectionResultVector","kind":"identifier"}],"externalID":"c:@N@Overlay@S@UsdImagingGLEngineWrapper@T@IntersectionResultVector","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntersectionResultVector","kind":"identifier"}],"role":"symbol","modules":[{"name":"OpenUSD"}],"title":"IntersectionResultVector"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/IntersectionResultVector"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntersectionResultVector"},{"kind":"text","text":" = "},{"kind":"identifier","preciseIdentifier":"c:@N@std","text":"std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@ST>2#T#T@vector","text":"std::vector"},{"kind":"text","text":"<"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/IntersectionResult","preciseIdentifier":"c:@N@Overlay@S@UsdImagingGLEngineWrapper@S@IntersectionResult","text":"IntersectionResult"},{"text":">","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"]]},"variants":[{"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/intersectionresultvector"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/intersectionresultvector"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","abstract":[],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"title":"Overlay","type":"topic","fragments":[{"kind":"identifier","text":"Overlay"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/IntersectionResult":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/IntersectionResult","title":"struct IntersectionResult","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/intersectionresult","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntersectionResult"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IntersectionResult"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","title":"class UsdImagingGLEngineWrapper","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"navigatorTitle":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/IntersectionResultVector":{"type":"topic","title":"IntersectionResultVector","abstract":[],"role":"symbol","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/intersectionresultvector","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntersectionResultVector","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"IntersectionResultVector","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/IntersectionResultVector"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"path":"\/metadata\/title","op":"replace","value":"IntersectionResultVector"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"IntersectionResultVector"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"IntersectionResultVector","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","text":"std::vector","preciseIdentifier":"c:@N@std@N@__1@ST>2#T#T@vector"},{"kind":"text","text":"<"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/IntersectionResult","text":"IntersectionResult","preciseIdentifier":"c:@N@Overlay@S@UsdImagingGLEngineWrapper@S@IntersectionResult"},{"kind":"text","text":"> "},{"kind":"identifier","text":"IntersectionResultVector"},{"kind":"text","text":";"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"Overlay","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"value":"IntersectionResult","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IntersectionResult\/title"},{"value":[{"text":"IntersectionResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IntersectionResult\/fragments"},{"value":[{"text":"IntersectionResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IntersectionResult\/navigatorTitle"},{"value":"UsdImagingGLEngineWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title"},{"value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments"},{"value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle"},{"value":"IntersectionResultVector","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IntersectionResultVector\/title"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IntersectionResultVector\/fragments","value":[{"text":"IntersectionResultVector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IntersectionResultVector\/navigatorTitle","value":[{"kind":"identifier","text":"IntersectionResultVector"}]}]}]}