{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/isstoprenderersupported"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/isstoprenderersupported"]}],"metadata":{"symbolKind":"method","externalID":"c:@N@Overlay@S@UsdImagingGLEngineWrapper@F@IsStopRendererSupported#1","title":"IsStopRendererSupported()","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"OpenUSD"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsStopRendererSupported","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"IsStopRendererSupported","kind":"identifier"}]},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/IsStopRendererSupported","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"IsStopRendererSupported"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:b","text":"Bool"}]}]}],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/IsStopRendererSupported":{"type":"topic","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/isstoprenderersupported","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsStopRendererSupported","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/IsStopRendererSupported","abstract":[],"title":"IsStopRendererSupported()","role":"symbol","navigatorTitle":[{"text":"IsStopRendererSupported","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"type":"topic","kind":"symbol","url":"\/documentation\/openusd\/overlay","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"fragments":[{"kind":"identifier","text":"Overlay"}],"title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"type":"topic","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","title":"class UsdImagingGLEngineWrapper","navigatorTitle":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"IsStopRendererSupported","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IsStopRendererSupported"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IsStopRendererSupported"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"typeIdentifier","preciseIdentifier":"c:b","text":"bool"},{"kind":"text","text":" "},{"kind":"identifier","text":"IsStopRendererSupported"},{"kind":"text","text":"() "},{"kind":"keyword","text":"const"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IsStopRendererSupported\/title","value":"IsStopRendererSupported","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IsStopRendererSupported\/fragments","value":[{"kind":"identifier","text":"IsStopRendererSupported"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IsStopRendererSupported\/navigatorTitle","value":[{"kind":"identifier","text":"IsStopRendererSupported"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"text":"Overlay","kind":"identifier"}],"op":"add"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title","value":"UsdImagingGLEngineWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"op":"replace"}]}]}