{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/setpresentationoutput"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/setpresentationoutput"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SetPresentationOutput","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"api","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfToken","text":"TfToken","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"framebuffer","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@VtValue","text":"VtValue","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["macOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/SetPresentationOutput"},"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"OpenUSD"}],"role":"symbol","externalID":"c:@N@Overlay@S@UsdImagingGLEngineWrapper@F@SetPresentationOutput#&1$@N@pxr@S@TfToken#&1$@N@pxr@S@VtValue#","title":"SetPresentationOutput(_:_:)","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SetPresentationOutput"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken"},{"kind":"text","text":", "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"VtValue","preciseIdentifier":"c:@N@pxr@S@VtValue"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"SetPresentationOutput"}],"symbolKind":"method","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","kind":"symbol","abstract":[],"url":"\/documentation\/openusd","role":"collection","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/SetPresentationOutput":{"fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SetPresentationOutput","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfToken","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfToken"},{"text":", ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"VtValue","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@VtValue"},{"text":")","kind":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/SetPresentationOutput","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/setpresentationoutput","kind":"symbol","type":"topic","title":"SetPresentationOutput(_:_:)","abstract":[],"role":"symbol","navigatorTitle":[{"text":"SetPresentationOutput","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"navigatorTitle":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"kind":"symbol","type":"topic","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","abstract":[],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","title":"class UsdImagingGLEngineWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"url":"\/documentation\/openusd\/overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol","title":"Overlay","type":"topic","kind":"symbol","fragments":[{"text":"Overlay","kind":"identifier"}],"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SetPresentationOutput","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SetPresentationOutput","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SetPresentationOutput"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SetPresentationOutput","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":"::","kind":"text"},{"text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"api","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":"::","kind":"text"},{"text":"VtValue","preciseIdentifier":"c:@N@pxr@S@VtValue","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"framebuffer","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SetPresentationOutput","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1SetPresentationOutput\/title"},{"value":[{"text":"SetPresentationOutput","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1SetPresentationOutput\/fragments"},{"value":[{"kind":"identifier","text":"SetPresentationOutput"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1SetPresentationOutput\/navigatorTitle"},{"value":"UsdImagingGLEngineWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title"},{"value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments"},{"value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}