{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/usdimagingglenginewrapper-1yly3"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/usdimagingglenginewrapper-1yly3"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"impl"},{"kind":"text","text":": "},{"kind":"identifier","preciseIdentifier":"c:@N@std","text":"std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr","text":"std::shared_ptr"},{"kind":"text","text":"<"},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdImagingGLEngine","text":"UsdImagingGLEngine"},{"kind":"text","text":">"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"UsdImagingGLEngineWrapper"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/UsdImagingGLEngineWrapper-1yly3"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"]]},"sections":[],"metadata":{"title":"init(_:)","role":"symbol","modules":[{"name":"OpenUSD"}],"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@std","text":"std","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr","text":"std::shared_ptr","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@UsdImagingGLEngine","text":"UsdImagingGLEngine","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"UsdImagingGLEngineWrapper","kind":"typeIdentifier"}],"externalID":"c:@N@Overlay@S@UsdImagingGLEngineWrapper@F@UsdImagingGLEngineWrapper#$@N@std@N@__1@S@shared_ptr>#$@N@pxr@S@UsdImagingGLEngine#"},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/UsdImagingGLEngineWrapper-1yly3":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"std::shared_ptr","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"UsdImagingGLEngine","preciseIdentifier":"c:@N@pxr@S@UsdImagingGLEngine"},{"kind":"text","text":">"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"UsdImagingGLEngineWrapper"}],"type":"topic","abstract":[],"url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/usdimagingglenginewrapper-1yly3","title":"init(_:)","role":"symbol","navigatorTitle":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/UsdImagingGLEngineWrapper-1yly3","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","kind":"symbol","abstract":[],"url":"\/documentation\/openusd","role":"collection","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"navigatorTitle":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"kind":"symbol","type":"topic","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","abstract":[],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","title":"class UsdImagingGLEngineWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"url":"\/documentation\/openusd\/overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol","title":"Overlay","type":"topic","kind":"symbol","fragments":[{"text":"Overlay","kind":"identifier"}],"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Constructor","path":"\/metadata\/roleHeading"},{"op":"replace","value":"UsdImagingGLEngineWrapper","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","preciseIdentifier":"c:@N@std","kind":"identifier"},{"text":"::","kind":"text"},{"text":"std::shared_ptr","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":"::","kind":"text"},{"text":"UsdImagingGLEngine","preciseIdentifier":"c:@N@pxr@S@UsdImagingGLEngine","kind":"typeIdentifier"},{"text":"> ","kind":"text"},{"text":"impl","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"UsdImagingGLEngineWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1UsdImagingGLEngineWrapper-1yly3\/title"},{"op":"replace","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1UsdImagingGLEngineWrapper-1yly3\/fragments"},{"op":"replace","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1UsdImagingGLEngineWrapper-1yly3\/navigatorTitle"},{"op":"replace","value":"UsdImagingGLEngineWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments"},{"op":"replace","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"}]}]}