{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd"]]},"metadata":{"title":"PassToSwiftAsReturnValue","modules":[{"name":"OpenUSD"}],"externalID":"c:@N@SwiftUsd@FT@>1#TPassToSwiftAsReturnValue#&t0.0#*^type-parameter-0-0:::DataType#","fragments":[{"text":"PassToSwiftAsReturnValue","kind":"identifier"}],"role":"symbol","symbolKind":"func","navigatorTitle":[{"text":"PassToSwiftAsReturnValue","kind":"identifier"}],"roleHeading":"Function Template"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/PassToSwiftAsReturnValue"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/swiftusd\/passtoswiftasreturnvalue"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"template","kind":"keyword"},{"text":" <","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmartPointer","kind":"genericParameter"},{"text":"> ","kind":"text"},{"text":"typename SmartPointer::DataType","preciseIdentifier":"c:^type-parameter-0-0:::DataType","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"PassToSwiftAsReturnValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SmartPointer","preciseIdentifier":"c:t0.0","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"x","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Use this function to pass a ","type":"text"},{"code":"pxr::TfRefPtr<T>","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"pxr::TfWeakPtr<T>","type":"codeVoice"},{"text":" to Swift as a raw pointer being returned from a C++ function. Apply the ","type":"text"},{"code":"SWIFT_RETURNS_RETAINED","type":"codeVoice"},{"text":" macro to your function declaration, and make sure that ","type":"text"},{"code":"SwiftUsd::PassToSwiftAsReturnValue(SmartPointer&)","type":"codeVoice"},{"text":" isn’t called until the return statement:","type":"text"}]},{"syntax":"c++","type":"codeListing","code":["\/\/ foo.hpp","#include \"swiftUsd\/swiftUsd.h\"","#include \"pxr\/usd\/usd\/stage.h\"","","pxr::UsdStage* _Nonnull returnStageByRawPointer() SWIFT_RETURNS_RETAINED;"]},{"syntax":"c++","type":"codeListing","code":["\/\/ foo.mm","#include \"foo.h\"","","pxr::UsdStage* _Nonnull returnStageByRawPointer() SWIFT_RETURNS_RETAINED {","    pxr::UsdStageRefPtr stage = pxr::UsdStage::CreateInMemory();","    return SwiftUsd::PassToSwiftAsReturnValue(stage);","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"See "},{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxInteropMemorySafety","isActive":true,"type":"reference"},{"type":"text","text":" for more information."}]}],"kind":"content"}],"references":{"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd":{"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd","title":"SwiftUsd","url":"\/documentation\/openusd\/swiftusd","fragments":[{"kind":"identifier","text":"SwiftUsd"}],"role":"symbol","abstract":[]},"doc://SwiftUsd/documentation/SwiftUsd/SwiftCxxInteropMemorySafety":{"url":"\/documentation\/swiftusd\/swiftcxxinteropmemorysafety","type":"topic","abstract":[{"text":"Learn how to avoid unsafe memory management issues when using Swift-Cxx interop","type":"text"}],"title":"Swift-Cxx Interop and Memory Safety","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxInteropMemorySafety","kind":"article","role":"article"},"doc://SwiftUsd/documentation/OpenUSD":{"type":"topic","url":"\/documentation\/openusd","title":"OpenUSD","role":"collection","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd/PassToSwiftAsReturnValue":{"type":"topic","title":"PassToSwiftAsReturnValue","abstract":[],"url":"\/documentation\/openusd\/swiftusd\/passtoswiftasreturnvalue","kind":"symbol","role":"symbol","fragments":[{"text":"PassToSwiftAsReturnValue","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/PassToSwiftAsReturnValue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/title","value":"SwiftUsd"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/fragments","value":[{"text":"SwiftUsd","kind":"identifier"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/navigatorTitle","value":[{"text":"SwiftUsd","kind":"identifier"}]}]}]}