{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper"]]},"metadata":{"externalID":"c:@N@Overlay@S@HioImageWrapper@F@GetFormat#1","role":"symbol","title":"GetFormat()","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetFormat","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"HioFormat","preciseIdentifier":"c:@N@pxr@E@HioFormat","kind":"typeIdentifier"}],"symbolKind":"method","modules":[{"name":"OpenUSD"}],"navigatorTitle":[{"text":"GetFormat","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/getformat"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/getformat"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetFormat","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@E@HioFormat","text":"HioFormat","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetFormat","interfaceLanguage":"swift"},"references":{"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","kind":"symbol","abstract":[],"url":"\/documentation\/openusd","role":"collection","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"url":"\/documentation\/openusd\/overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol","title":"Overlay","type":"topic","kind":"symbol","fragments":[{"text":"Overlay","kind":"identifier"}],"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HioImageWrapper","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","navigatorTitle":[{"text":"HioImageWrapper","kind":"identifier"}],"kind":"symbol","title":"class HioImageWrapper","url":"\/documentation\/openusd\/overlay\/hioimagewrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/GetFormat":{"navigatorTitle":[{"kind":"identifier","text":"GetFormat"}],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/getformat","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetFormat","kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetFormat"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HioFormat","preciseIdentifier":"c:@N@pxr@E@HioFormat"}],"title":"GetFormat()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"GetFormat","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"GetFormat","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GetFormat"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":"::","kind":"text"},{"preciseIdentifier":"c:@N@pxr@E@HioFormat","text":"HioFormat","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"GetFormat","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"kind":"identifier","text":"Overlay"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"kind":"identifier","text":"Overlay"}],"op":"add"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title","value":"HioImageWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments","value":[{"kind":"identifier","text":"HioImageWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle","value":[{"text":"HioImageWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetFormat\/title","value":"GetFormat","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetFormat\/fragments","value":[{"text":"GetFormat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetFormat\/navigatorTitle","value":[{"text":"GetFormat","kind":"identifier"}],"op":"replace"}]}]}