{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetMetadata-84xbi"},"metadata":{"roleHeading":"Method Template","externalID":"c:@N@Overlay@S@HioImageWrapper@FT@>1#TGetMetadata#&1$@N@pxr@S@TfToken#*t0.0#b#1","navigatorTitle":[{"text":"GetMetadata","kind":"identifier"}],"fragments":[{"text":"GetMetadata","kind":"identifier"}],"modules":[{"name":"OpenUSD"}],"title":"GetMetadata","role":"symbol","symbolKind":"method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/getmetadata-84xbi"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/getmetadata-84xbi"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"template"},{"kind":"text","text":" <"},{"kind":"keyword","text":"typename"},{"kind":"text","text":" "},{"kind":"genericParameter","text":"T"},{"kind":"text","text":"> "},{"kind":"typeIdentifier","text":"bool","preciseIdentifier":"c:b"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetMetadata"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken"},{"kind":"text","text":" & "},{"kind":"internalParam","text":"key"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"T *","preciseIdentifier":"c:t0.0"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"value"},{"kind":"text","text":");"}],"platforms":["macOS"],"languages":["swift"]}]}],"sections":[],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/GetMetadata-84xbi":{"abstract":[],"title":"GetMetadata","fragments":[{"kind":"identifier","text":"GetMetadata"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetMetadata-84xbi","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/getmetadata-84xbi","kind":"symbol","role":"symbol","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"title":"class HioImageWrapper","role":"symbol","url":"\/documentation\/openusd\/overlay\/hioimagewrapper","type":"topic","navigatorTitle":[{"text":"HioImageWrapper","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HioImageWrapper","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","abstract":[],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"title":"Overlay","type":"topic","fragments":[{"kind":"identifier","text":"Overlay"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Method Template","path":"\/metadata\/roleHeading","op":"replace"},{"value":"GetMetadata","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"GetMetadata"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"GetMetadata"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"text":"template","kind":"keyword"},{"text":" <","kind":"text"},{"text":"typename","kind":"keyword"},{"text":" ","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":"> ","kind":"text"},{"text":"bool","preciseIdentifier":"c:b","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"GetMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":"::","kind":"text"},{"text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"key","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"T *","preciseIdentifier":"c:t0.0","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"value","kind":"internalParam"},{"text":");","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"GetMetadata","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetMetadata-84xbi\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GetMetadata"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetMetadata-84xbi\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"GetMetadata"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetMetadata-84xbi\/navigatorTitle","op":"add"},{"value":"HioImageWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title","op":"replace"},{"value":[{"text":"HioImageWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments","op":"replace"},{"value":[{"text":"HioImageWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle","op":"replace"},{"value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace"},{"value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add"}],"traits":[{"interfaceLanguage":"occ"}]}]}