{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"modules":[{"name":"OpenUSD"}],"externalID":"c:@N@Overlay@S@HioImageWrapper@F@GetWidth#1","roleHeading":"Instance Method","title":"GetWidth()","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetWidth","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"CInt","kind":"typeIdentifier","preciseIdentifier":"c:I"}],"navigatorTitle":[{"kind":"identifier","text":"GetWidth"}]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetWidth"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"CInt","preciseIdentifier":"c:I"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/getwidth"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/getwidth"]}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetWidth","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"type":"topic","kind":"symbol","url":"\/documentation\/openusd\/overlay","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"fragments":[{"kind":"identifier","text":"Overlay"}],"title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/GetWidth":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetWidth","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"CInt","preciseIdentifier":"c:I","kind":"typeIdentifier"}],"abstract":[],"title":"GetWidth()","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetWidth","navigatorTitle":[{"text":"GetWidth","kind":"identifier"}],"type":"topic","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/getwidth"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"title":"class HioImageWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","navigatorTitle":[{"kind":"identifier","text":"HioImageWrapper"}],"type":"topic","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HioImageWrapper"}],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"GetWidth","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"GetWidth"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"GetWidth","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"typeIdentifier","preciseIdentifier":"c:I","text":"int"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetWidth"},{"kind":"text","text":"() "},{"kind":"keyword","text":"const"},{"kind":"text","text":";"}],"platforms":["macOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"op":"replace","value":"GetWidth","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetWidth\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GetWidth"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetWidth\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GetWidth"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetWidth\/navigatorTitle"},{"op":"replace","value":"HioImageWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"HioImageWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments"},{"op":"replace","value":[{"text":"HioImageWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle"}]}]}