{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/sourcecolorspace"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/sourcecolorspace"]}],"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/SourceColorSpace\/Auto","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/SourceColorSpace\/Raw","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/SourceColorSpace\/SRGB"],"anchor":"Enumeration-Cases"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceColorSpace"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"text":"SourceColorSpace","kind":"identifier"}],"externalID":"c:@N@Overlay@S@HioImageWrapper@E@SourceColorSpace","roleHeading":"Enumeration","role":"symbol","modules":[{"name":"OpenUSD"}],"symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceColorSpace","kind":"identifier"}],"title":"SourceColorSpace"},"kind":"symbol","identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/SourceColorSpace","interfaceLanguage":"swift"},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/SourceColorSpace/Auto":{"role":"symbol","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/sourcecolorspace\/auto","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Auto"}],"navigatorTitle":[{"kind":"identifier","text":"Auto"}],"type":"topic","kind":"symbol","abstract":[],"title":"Auto","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/SourceColorSpace\/Auto"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/SourceColorSpace/Raw":{"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/SourceColorSpace\/Raw","navigatorTitle":[{"text":"Raw","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/sourcecolorspace\/raw","kind":"symbol","title":"Raw","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Raw","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HioImageWrapper","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","navigatorTitle":[{"text":"HioImageWrapper","kind":"identifier"}],"kind":"symbol","title":"class HioImageWrapper","url":"\/documentation\/openusd\/overlay\/hioimagewrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"url":"\/documentation\/openusd\/overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol","title":"Overlay","type":"topic","kind":"symbol","fragments":[{"text":"Overlay","kind":"identifier"}],"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","kind":"symbol","abstract":[],"url":"\/documentation\/openusd","role":"collection","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/SourceColorSpace/SRGB":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/SourceColorSpace\/SRGB","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/sourcecolorspace\/srgb","kind":"symbol","role":"symbol","type":"topic","title":"SRGB","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SRGB"}],"navigatorTitle":[{"kind":"identifier","text":"SRGB"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/SourceColorSpace":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/SourceColorSpace","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceColorSpace","kind":"identifier"}],"title":"SourceColorSpace","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/sourcecolorspace","navigatorTitle":[{"text":"SourceColorSpace","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SourceColorSpace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SourceColorSpace"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SourceColorSpace","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/SourceColorSpace\/Auto","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/SourceColorSpace\/Raw","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/SourceColorSpace\/SRGB"],"generated":true,"anchor":"Enumeration-Cases"}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceColorSpace","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:i","text":"unsigned int","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1SourceColorSpace~1Auto\/title","value":"Auto"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1SourceColorSpace~1Auto\/fragments","value":[{"kind":"identifier","text":"Auto"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1SourceColorSpace~1Auto\/navigatorTitle","value":[{"text":"Auto","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1SourceColorSpace~1Raw\/title","value":"Raw"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1SourceColorSpace~1Raw\/fragments","value":[{"kind":"identifier","text":"Raw"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1SourceColorSpace~1Raw\/navigatorTitle","value":[{"text":"Raw","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title","value":"HioImageWrapper"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments","value":[{"kind":"identifier","text":"HioImageWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"HioImageWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"text":"Overlay","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1SourceColorSpace~1SRGB\/title","value":"SRGB"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1SourceColorSpace~1SRGB\/fragments","value":[{"text":"SRGB","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1SourceColorSpace~1SRGB\/navigatorTitle","value":[{"kind":"identifier","text":"SRGB"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1SourceColorSpace\/title","value":"SourceColorSpace"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1SourceColorSpace\/fragments","value":[{"kind":"identifier","text":"SourceColorSpace"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1SourceColorSpace\/navigatorTitle","value":[{"kind":"identifier","text":"SourceColorSpace"}]}]}]}