{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay"},"topicSections":[{"generated":true,"title":"Classes","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"],"anchor":"Classes"},{"generated":true,"title":"Structures","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfZipFileIteratorWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfErrorMarkWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper"],"anchor":"Structures"},{"generated":true,"title":"Variables","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/DefaultPropertyPredicateFunc","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimDefaultPredicate","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimAbstractFlag","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimActiveFlag","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimClipsFlag","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimComponentFlag","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimDeadFlag","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimDefinedFlag","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimGroupFlag","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimHasDefiningSpecifierFlag","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimHasPayloadFlag","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimInstanceFlag","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimInstanceProxyFlag","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimLoadedFlag","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimModelFlag","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimNumFlags","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimPrototypeFlag","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimPseudoRootFlag"],"anchor":"Variables"},{"generated":true,"title":"Functions","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArCreateResolver","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArGetResolver","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArGetUnderlyingResolver","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ClearMetadata","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/CopyTextureGpuToCpu","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/CreateExtentAttr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Get","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetAttr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetDescriptor","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetMetadata","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetPath-1gxko","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetPath-9ig6g","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetStage","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HasAuthoredMetadata","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HasMetadata","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiTextureHandleGetTextureId","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Set","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SetMetadata","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdProperty_As","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/allowedTokensForAttribute","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/formTfEnum"],"anchor":"Functions"},{"generated":true,"title":"Type Aliases","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Double_Vector","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GfVec4f_Vector","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiBlitCmds_SharedPtr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfAssetPath_VtArray","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfLayerHandle_Set","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfLayer_RefPtr_Vector","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/String_Set","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/String_String_Pair_Vector","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/String_Vector","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfDiagnosticBase_Shared_Ptr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfDiagnosticBase_Shared_Ptr_Vector","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfDiagnosticBase_Unique_Ptr_Vector","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAttribute_Vector","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdGeomXformOp_Vector","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdProperty_Vector","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdRelationship_Vector","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdShadeInput_Vector","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdStagePtr_UsdEditTarget_Pair","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/VtDictionary_Iterator_Bool_Pair"],"anchor":"Type-Aliases"},{"generated":true,"title":"Enumerations","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfLayer"],"anchor":"Enumerations"}],"metadata":{"fragments":[{"kind":"identifier","text":"Overlay"}],"role":"symbol","externalID":"c:@N@Overlay","title":"Overlay","modules":[{"name":"OpenUSD"}],"symbolKind":"enum","roleHeading":"enum","navigatorTitle":[{"text":"Overlay","kind":"identifier"}]},"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Overlay"}],"platforms":["macOS"]}]},{"content":[{"type":"heading","anchor":"Discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"This Swift Package uses the ","type":"text"},{"type":"codeVoice","code":"Overlay"},{"text":" namespace to group workarounds to limitations in Swift-Cxx interop, as well as proposed additions to make OpenUSD in Swift feel more natural and easy to use.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For example, see "},{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","type":"reference"},{"type":"text","text":" and "},{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","type":"reference"},{"type":"text","text":"."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"kind":"symbol","sections":[],"seeAlsoSections":[{"generated":true,"title":"Wrapped symbol documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedEnums","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedFunctions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedOperators"],"anchor":"Wrapped-symbol-documentation"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArGetUnderlyingResolver":{"type":"topic","url":"\/documentation\/openusd\/overlay\/argetunderlyingresolver","kind":"symbol","title":"ArGetUnderlyingResolver()","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArGetUnderlyingResolver","navigatorTitle":[{"text":"ArGetUnderlyingResolver","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArGetUnderlyingResolver","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@Overlay@S@ArResolverWrapper","text":"ArResolverWrapper","kind":"typeIdentifier"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/TfDiagnosticBase_Shared_Ptr":{"url":"\/documentation\/openusd\/overlay\/tfdiagnosticbase_shared_ptr","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TfDiagnosticBase_Shared_Ptr"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfDiagnosticBase_Shared_Ptr","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TfDiagnosticBase_Shared_Ptr"}],"kind":"symbol","title":"TfDiagnosticBase_Shared_Ptr"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","title":"class UsdImagingGLEngineWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Usd_PrimPrototypeFlag":{"title":"Usd_PrimPrototypeFlag","navigatorTitle":[{"text":"Usd_PrimPrototypeFlag","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimPrototypeFlag","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Usd_PrimPrototypeFlag","kind":"identifier"},{"text":": ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"Usd_PrimFlags","preciseIdentifier":"c:@N@pxr@E@Usd_PrimFlags","kind":"typeIdentifier"}],"url":"\/documentation\/openusd\/overlay\/usd_primprototypeflag","abstract":[],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"role":"collection","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","abstract":[],"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"kind":"identifier","text":"Overlay"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","title":"Overlay","type":"topic","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Set":{"url":"\/documentation\/openusd\/overlay\/set","type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Set","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Set","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdAttribute","preciseIdentifier":"c:@N@pxr@S@UsdAttribute","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"VtValue","preciseIdentifier":"c:@N@pxr@S@VtValue","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdTimeCode","preciseIdentifier":"c:@N@pxr@S@UsdTimeCode","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"Set","kind":"identifier"}],"abstract":[],"title":"Set(_:_:_:)"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper":{"url":"\/documentation\/openusd\/overlay\/hgimetalwrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiMetalWrapper","kind":"identifier"}],"navigatorTitle":[{"text":"HgiMetalWrapper","kind":"identifier"}],"title":"class HgiMetalWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Usd_PrimPseudoRootFlag":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"Usd_PrimPseudoRootFlag","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimPseudoRootFlag","url":"\/documentation\/openusd\/overlay\/usd_primpseudorootflag","title":"Usd_PrimPseudoRootFlag","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"Usd_PrimPseudoRootFlag"},{"kind":"text","text":": "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Usd_PrimFlags","preciseIdentifier":"c:@N@pxr@E@Usd_PrimFlags"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HasMetadata":{"kind":"symbol","title":"HasMetadata(_:_:)","abstract":[],"type":"topic","url":"\/documentation\/openusd\/overlay\/hasmetadata","navigatorTitle":[{"text":"HasMetadata","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HasMetadata","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HasMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdRelationship","preciseIdentifier":"c:@N@pxr@S@UsdRelationship","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Usd_PrimModelFlag":{"kind":"symbol","title":"Usd_PrimModelFlag","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Usd_PrimModelFlag","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@E@Usd_PrimFlags","text":"Usd_PrimFlags","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"Usd_PrimModelFlag","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimModelFlag","url":"\/documentation\/openusd\/overlay\/usd_primmodelflag"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Usd_PrimInstanceProxyFlag":{"abstract":[],"title":"Usd_PrimInstanceProxyFlag","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Usd_PrimInstanceProxyFlag","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@E@Usd_PrimFlags","text":"Usd_PrimFlags","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"Usd_PrimInstanceProxyFlag","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/usd_priminstanceproxyflag","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimInstanceProxyFlag","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/SdfLayerHandle_Set":{"url":"\/documentation\/openusd\/overlay\/sdflayerhandle_set","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SdfLayerHandle_Set","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","title":"SdfLayerHandle_Set","navigatorTitle":[{"text":"SdfLayerHandle_Set","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfLayerHandle_Set"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Usd_PrimNumFlags":{"type":"topic","url":"\/documentation\/openusd\/overlay\/usd_primnumflags","kind":"symbol","abstract":[],"role":"symbol","title":"Usd_PrimNumFlags","navigatorTitle":[{"text":"Usd_PrimNumFlags","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Usd_PrimNumFlags","kind":"identifier"},{"text":": ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"Usd_PrimFlags","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@E@Usd_PrimFlags"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimNumFlags"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/String_String_Pair_Vector":{"type":"topic","title":"String_String_Pair_Vector","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/String_String_Pair_Vector","navigatorTitle":[{"kind":"identifier","text":"String_String_Pair_Vector"}],"abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"String_String_Pair_Vector"}],"url":"\/documentation\/openusd\/overlay\/string_string_pair_vector","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/CreateExtentAttr":{"navigatorTitle":[{"kind":"identifier","text":"CreateExtentAttr"}],"title":"CreateExtentAttr(_:_:_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateExtentAttr","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdGeomMesh","preciseIdentifier":"c:@N@pxr@S@UsdGeomMesh","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"VtValue","preciseIdentifier":"c:@N@pxr@S@VtValue","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdAttribute","preciseIdentifier":"c:@N@pxr@S@UsdAttribute","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/CreateExtentAttr","type":"topic","url":"\/documentation\/openusd\/overlay\/createextentattr","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ClearMetadata":{"navigatorTitle":[{"text":"ClearMetadata","kind":"identifier"}],"title":"ClearMetadata(_:_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClearMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdRelationship","preciseIdentifier":"c:@N@pxr@S@UsdRelationship","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ClearMetadata","type":"topic","url":"\/documentation\/openusd\/overlay\/clearmetadata","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/String_Vector":{"navigatorTitle":[{"text":"String_Vector","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/string_vector","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String_Vector","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/String_Vector","abstract":[],"title":"String_Vector","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/SetMetadata":{"navigatorTitle":[{"text":"SetMetadata","kind":"identifier"}],"title":"SetMetadata(_:_:_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SetMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdRelationship","preciseIdentifier":"c:@N@pxr@S@UsdRelationship","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"VtValue","preciseIdentifier":"c:@N@pxr@S@VtValue","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SetMetadata","type":"topic","url":"\/documentation\/openusd\/overlay\/setmetadata","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/GetStage":{"navigatorTitle":[{"text":"GetStage","kind":"identifier"}],"title":"GetStage(_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetStage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdAttribute","preciseIdentifier":"c:@N@pxr@S@UsdAttribute","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdStagePtr","preciseIdentifier":"c:@N@pxr@T@UsdStagePtr","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetStage","type":"topic","url":"\/documentation\/openusd\/overlay\/getstage","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Usd_PrimHasDefiningSpecifierFlag":{"type":"topic","role":"symbol","kind":"symbol","title":"Usd_PrimHasDefiningSpecifierFlag","abstract":[],"url":"\/documentation\/openusd\/overlay\/usd_primhasdefiningspecifierflag","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimHasDefiningSpecifierFlag","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"Usd_PrimHasDefiningSpecifierFlag"},{"kind":"text","text":": "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Usd_PrimFlags","preciseIdentifier":"c:@N@pxr@E@Usd_PrimFlags"}],"navigatorTitle":[{"kind":"identifier","text":"Usd_PrimHasDefiningSpecifierFlag"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdProperty_Vector":{"abstract":[],"kind":"symbol","title":"UsdProperty_Vector","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdProperty_Vector","kind":"identifier"}],"navigatorTitle":[{"text":"UsdProperty_Vector","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdProperty_Vector","url":"\/documentation\/openusd\/overlay\/usdproperty_vector","type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/WrappedEnums":{"url":"\/documentation\/swiftusd\/wrappedenums","role":"article","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedEnums","type":"topic","kind":"article","title":"Wrapped enums"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/formTfEnum":{"title":"formTfEnum","abstract":[],"type":"topic","url":"\/documentation\/openusd\/overlay\/formtfenum","fragments":[{"kind":"identifier","text":"formTfEnum"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/formTfEnum"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArCreateResolver":{"title":"ArCreateResolver(_:)","abstract":[],"type":"topic","url":"\/documentation\/openusd\/overlay\/arcreateresolver","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArCreateResolver"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TfType","preciseIdentifier":"c:@N@pxr@S@TfType"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"ArResolverWrapper","preciseIdentifier":"c:@N@Overlay@S@ArResolverWrapper"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ArCreateResolver"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArCreateResolver"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Double_Vector":{"url":"\/documentation\/openusd\/overlay\/double_vector","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Double_Vector","title":"Double_Vector","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Double_Vector"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Double_Vector"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiTextureHandleGetTextureId":{"navigatorTitle":[{"text":"HgiTextureHandleGetTextureId","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiTextureHandleGetTextureId","kind":"symbol","url":"\/documentation\/openusd\/overlay\/hgitexturehandlegettextureid","abstract":[],"title":"HgiTextureHandleGetTextureId(_:)","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiTextureHandleGetTextureId","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"HgiTextureHandle","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiTexture","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"id<MTLTexture>","preciseIdentifier":"c:Qoobjc(pl)MTLTexture","kind":"typeIdentifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Usd_PrimAbstractFlag":{"type":"topic","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/overlay\/usd_primabstractflag","navigatorTitle":[{"kind":"identifier","text":"Usd_PrimAbstractFlag"}],"title":"Usd_PrimAbstractFlag","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"Usd_PrimAbstractFlag"},{"kind":"text","text":": "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Usd_PrimFlags","preciseIdentifier":"c:@N@pxr@E@Usd_PrimFlags"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimAbstractFlag"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper":{"type":"topic","url":"\/documentation\/openusd\/overlay\/arresolverwrapper","navigatorTitle":[{"kind":"identifier","text":"ArResolverWrapper"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArResolverWrapper"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","kind":"symbol","title":"class ArResolverWrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/VtDictionary_Iterator_Bool_Pair":{"navigatorTitle":[{"kind":"identifier","text":"VtDictionary_Iterator_Bool_Pair"}],"url":"\/documentation\/openusd\/overlay\/vtdictionary_iterator_bool_pair","title":"VtDictionary_Iterator_Bool_Pair","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/VtDictionary_Iterator_Bool_Pair","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"VtDictionary_Iterator_Bool_Pair"}],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/GetDescriptor":{"navigatorTitle":[{"text":"GetDescriptor","kind":"identifier"}],"title":"GetDescriptor(_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetDescriptor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"HgiTextureHandle","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiTexture","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"HgiTextureDesc","preciseIdentifier":"c:@N@pxr@S@HgiTextureDesc","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetDescriptor","type":"topic","url":"\/documentation\/openusd\/overlay\/getdescriptor","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdAttribute_Vector":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAttribute_Vector","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UsdAttribute_Vector"}],"title":"UsdAttribute_Vector","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdAttribute_Vector"}],"url":"\/documentation\/openusd\/overlay\/usdattribute_vector"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HioImageWrapper","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","url":"\/documentation\/openusd\/overlay\/hioimagewrapper","role":"symbol","type":"topic","navigatorTitle":[{"text":"HioImageWrapper","kind":"identifier"}],"title":"class HioImageWrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Usd_PrimClipsFlag":{"title":"Usd_PrimClipsFlag","type":"topic","url":"\/documentation\/openusd\/overlay\/usd_primclipsflag","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Usd_PrimClipsFlag","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@E@Usd_PrimFlags","text":"Usd_PrimFlags","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Usd_PrimClipsFlag"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimClipsFlag"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiBlitCmds_SharedPtr":{"url":"\/documentation\/openusd\/overlay\/hgiblitcmds_sharedptr","role":"symbol","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiBlitCmds_SharedPtr","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiBlitCmds_SharedPtr","kind":"symbol","type":"topic","title":"HgiBlitCmds_SharedPtr","navigatorTitle":[{"text":"HgiBlitCmds_SharedPtr","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/String_Set":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/String_Set","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String_Set","kind":"identifier"}],"navigatorTitle":[{"text":"String_Set","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/openusd\/overlay\/string_set","title":"String_Set"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/SdfAssetPath_VtArray":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfAssetPath_VtArray","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SdfAssetPath_VtArray"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SdfAssetPath_VtArray"}],"url":"\/documentation\/openusd\/overlay\/sdfassetpath_vtarray","title":"SdfAssetPath_VtArray"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/GetPath-9ig6g":{"type":"topic","abstract":[],"kind":"symbol","title":"GetPath(_:)","url":"\/documentation\/openusd\/overlay\/getpath-9ig6g","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetPath-9ig6g","navigatorTitle":[{"text":"GetPath","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdRelationship","preciseIdentifier":"c:@N@pxr@S@UsdRelationship","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"SdfPath","preciseIdentifier":"c:@N@pxr@S@SdfPath","kind":"typeIdentifier"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimDefaultPredicate":{"title":"UsdPrimDefaultPredicate","type":"topic","abstract":[],"url":"\/documentation\/openusd\/overlay\/usdprimdefaultpredicate","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimDefaultPredicate","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdPrimDefaultPredicate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@Usd_PrimFlagsPredicate","text":"Usd_PrimFlagsPredicate"}],"navigatorTitle":[{"kind":"identifier","text":"UsdPrimDefaultPredicate"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Usd_PrimDeadFlag":{"abstract":[],"navigatorTitle":[{"text":"Usd_PrimDeadFlag","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Usd_PrimDeadFlag","kind":"identifier"},{"text":": ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"Usd_PrimFlags","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@E@Usd_PrimFlags"}],"type":"topic","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimDeadFlag","url":"\/documentation\/openusd\/overlay\/usd_primdeadflag","kind":"symbol","title":"Usd_PrimDeadFlag"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArGetResolver":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArGetResolver","type":"topic","navigatorTitle":[{"text":"ArGetResolver","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/argetresolver","title":"ArGetResolver()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArGetResolver","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@Overlay@S@ArResolverWrapper","text":"ArResolverWrapper","kind":"typeIdentifier"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Get":{"navigatorTitle":[{"kind":"identifier","text":"Get"}],"title":"Get(_:_:_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Get","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdAttribute","preciseIdentifier":"c:@N@pxr@S@UsdAttribute","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"VtValue","preciseIdentifier":"c:@N@pxr@S@VtValue","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":", ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdTimeCode","preciseIdentifier":"c:@N@pxr@S@UsdTimeCode","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Get","type":"topic","url":"\/documentation\/openusd\/overlay\/get","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/GetAttr":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetAttr","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetAttr","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdGeomXformOp","preciseIdentifier":"c:@N@pxr@S@UsdGeomXformOp","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdAttribute","preciseIdentifier":"c:@N@pxr@S@UsdAttribute","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"GetAttr","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openusd\/overlay\/getattr","type":"topic","title":"GetAttr(_:)","kind":"symbol"},"doc://SwiftUsd/documentation/SwiftUsd/WrappedOperators":{"kind":"article","url":"\/documentation\/swiftusd\/wrappedoperators","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedOperators","abstract":[],"title":"Wrapped operators","role":"collectionGroup"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Usd_PrimGroupFlag":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/openusd\/overlay\/usd_primgroupflag","title":"Usd_PrimGroupFlag","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Usd_PrimGroupFlag","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@E@Usd_PrimFlags","text":"Usd_PrimFlags","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"Usd_PrimGroupFlag","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimGroupFlag"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdShadeInput_Vector":{"url":"\/documentation\/openusd\/overlay\/usdshadeinput_vector","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdShadeInput_Vector","title":"UsdShadeInput_Vector","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdShadeInput_Vector"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UsdShadeInput_Vector"}],"abstract":[],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdGeomXformOp_Vector":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdGeomXformOp_Vector","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdGeomXformOp_Vector","kind":"identifier"}],"role":"symbol","title":"UsdGeomXformOp_Vector","url":"\/documentation\/openusd\/overlay\/usdgeomxformop_vector","navigatorTitle":[{"text":"UsdGeomXformOp_Vector","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","type":"topic","role":"symbol","navigatorTitle":[{"text":"HgiWrapper","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiWrapper","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper","abstract":[],"kind":"symbol","title":"class HgiWrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/DefaultPropertyPredicateFunc":{"kind":"symbol","url":"\/documentation\/openusd\/overlay\/defaultpropertypredicatefunc","role":"symbol","title":"DefaultPropertyPredicateFunc","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultPropertyPredicateFunc","kind":"identifier"},{"text":": ","kind":"text"},{"text":"std","preciseIdentifier":"c:@N@std","kind":"identifier"},{"text":".","kind":"text"},{"text":"std::function","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@function","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"_Bool (const class pxr::TfToken &)","preciseIdentifier":"c:Fb(#&1$@N@pxr@S@TfToken)","kind":"typeIdentifier"},{"text":">","kind":"text"}],"abstract":[],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/DefaultPropertyPredicateFunc","navigatorTitle":[{"kind":"identifier","text":"DefaultPropertyPredicateFunc"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/GetPath-1gxko":{"kind":"symbol","url":"\/documentation\/openusd\/overlay\/getpath-1gxko","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdAttribute","preciseIdentifier":"c:@N@pxr@S@UsdAttribute","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"SdfPath","preciseIdentifier":"c:@N@pxr@S@SdfPath","kind":"typeIdentifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetPath-1gxko","title":"GetPath(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GetPath"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/GfVec4f_Vector":{"title":"GfVec4f_Vector","url":"\/documentation\/openusd\/overlay\/gfvec4f_vector","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GfVec4f_Vector"}],"abstract":[],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GfVec4f_Vector","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"GfVec4f_Vector"}],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdAppUtilsFrameRecorderWrapper":{"navigatorTitle":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper","abstract":[],"title":"class UsdAppUtilsFrameRecorderWrapper","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Dereference-3t65r":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Dereference-3t65r","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/openusd\/overlay\/dereference-3t65r","role":"symbol","title":"Dereference","fragments":[{"kind":"identifier","text":"Dereference"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdStagePtr_UsdEditTarget_Pair":{"title":"UsdStagePtr_UsdEditTarget_Pair","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdStagePtr_UsdEditTarget_Pair","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdStagePtr_UsdEditTarget_Pair","kind":"identifier"}],"type":"topic","url":"\/documentation\/openusd\/overlay\/usdstageptr_usdedittarget_pair","navigatorTitle":[{"text":"UsdStagePtr_UsdEditTarget_Pair","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Usd_PrimLoadedFlag":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimLoadedFlag","title":"Usd_PrimLoadedFlag","type":"topic","abstract":[],"url":"\/documentation\/openusd\/overlay\/usd_primloadedflag","navigatorTitle":[{"text":"Usd_PrimLoadedFlag","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Usd_PrimLoadedFlag","kind":"identifier"},{"text":": ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"Usd_PrimFlags","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@E@Usd_PrimFlags"}],"role":"symbol","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/SdfZipFileIteratorWrapper":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfZipFileIteratorWrapper","url":"\/documentation\/openusd\/overlay\/sdfzipfileiteratorwrapper","role":"symbol","type":"topic","title":"struct SdfZipFileIteratorWrapper","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SdfZipFileIteratorWrapper"}],"navigatorTitle":[{"kind":"identifier","text":"SdfZipFileIteratorWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/CopyTextureGpuToCpu":{"navigatorTitle":[{"text":"CopyTextureGpuToCpu","kind":"identifier"}],"title":"CopyTextureGpuToCpu(_:_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CopyTextureGpuToCpu","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","preciseIdentifier":"c:@N@std","kind":"identifier"},{"text":".","kind":"text"},{"text":"std::shared_ptr","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"HgiBlitCmds","preciseIdentifier":"c:@N@pxr@S@HgiBlitCmds","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":", ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"HgiTextureGpuToCpuOp","preciseIdentifier":"c:@N@pxr@S@HgiTextureGpuToCpuOp","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/CopyTextureGpuToCpu","type":"topic","url":"\/documentation\/openusd\/overlay\/copytexturegputocpu","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Usd_PrimActiveFlag":{"url":"\/documentation\/openusd\/overlay\/usd_primactiveflag","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimActiveFlag","title":"Usd_PrimActiveFlag","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Usd_PrimActiveFlag","kind":"identifier"},{"text":": ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"Usd_PrimFlags","preciseIdentifier":"c:@N@pxr@E@Usd_PrimFlags","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"Usd_PrimActiveFlag","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Usd_PrimDefinedFlag":{"title":"Usd_PrimDefinedFlag","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimDefinedFlag","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Usd_PrimDefinedFlag","kind":"identifier"},{"text":": ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"Usd_PrimFlags","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@E@Usd_PrimFlags"}],"role":"symbol","navigatorTitle":[{"text":"Usd_PrimDefinedFlag","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/usd_primdefinedflag","kind":"symbol","type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/WrappedTypes":{"url":"\/documentation\/swiftusd\/wrappedtypes","type":"topic","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","role":"collectionGroup","abstract":[],"title":"Wrapped types"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/GetMetadata":{"navigatorTitle":[{"text":"GetMetadata","kind":"identifier"}],"title":"GetMetadata(_:_:_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdRelationship","preciseIdentifier":"c:@N@pxr@S@UsdRelationship","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"VtValue","preciseIdentifier":"c:@N@pxr@S@VtValue","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetMetadata","type":"topic","url":"\/documentation\/openusd\/overlay\/getmetadata","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/SdfLayer":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfLayer","url":"\/documentation\/openusd\/overlay\/sdflayer","title":"SdfLayer","type":"topic","fragments":[{"kind":"identifier","text":"SdfLayer"}],"role":"symbol","kind":"symbol"},"doc://SwiftUsd/documentation/SwiftUsd/WrappedFunctions":{"kind":"article","url":"\/documentation\/swiftusd\/wrappedfunctions","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedFunctions","abstract":[],"title":"Wrapped functions","role":"collectionGroup"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdProperty_As":{"navigatorTitle":[{"text":"UsdProperty_As","kind":"identifier"}],"title":"UsdProperty_As(_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdProperty_As","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdProperty","preciseIdentifier":"c:@N@pxr@S@UsdProperty","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdRelationship","preciseIdentifier":"c:@N@pxr@S@UsdRelationship","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdProperty_As","type":"topic","url":"\/documentation\/openusd\/overlay\/usdproperty_as","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/allowedTokensForAttribute":{"navigatorTitle":[{"text":"allowedTokensForAttribute","kind":"identifier"}],"title":"allowedTokensForAttribute(_:_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowedTokensForAttribute","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdAttribute","preciseIdentifier":"c:@N@pxr@S@UsdAttribute","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"pxr::VtArray","preciseIdentifier":"c:@N@pxr@ST>1#T@VtArray","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken","kind":"typeIdentifier"},{"text":"> ","kind":"text"},{"text":">","kind":"text"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/allowedTokensForAttribute","type":"topic","url":"\/documentation\/openusd\/overlay\/allowedtokensforattribute","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdRelationship_Vector":{"url":"\/documentation\/openusd\/overlay\/usdrelationship_vector","role":"symbol","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdRelationship_Vector","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdRelationship_Vector","type":"topic","kind":"symbol","title":"UsdRelationship_Vector","navigatorTitle":[{"text":"UsdRelationship_Vector","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/TfDiagnosticBase_Shared_Ptr_Vector":{"navigatorTitle":[{"kind":"identifier","text":"TfDiagnosticBase_Shared_Ptr_Vector"}],"abstract":[],"url":"\/documentation\/openusd\/overlay\/tfdiagnosticbase_shared_ptr_vector","title":"TfDiagnosticBase_Shared_Ptr_Vector","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfDiagnosticBase_Shared_Ptr_Vector","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TfDiagnosticBase_Shared_Ptr_Vector"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Dereference-9or49":{"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Dereference-9or49","title":"Dereference","role":"symbol","fragments":[{"kind":"identifier","text":"Dereference"}],"abstract":[],"url":"\/documentation\/openusd\/overlay\/dereference-9or49"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Usd_PrimComponentFlag":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimComponentFlag","navigatorTitle":[{"kind":"identifier","text":"Usd_PrimComponentFlag"}],"url":"\/documentation\/openusd\/overlay\/usd_primcomponentflag","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"Usd_PrimComponentFlag"},{"kind":"text","text":": "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@E@Usd_PrimFlags","text":"Usd_PrimFlags"}],"title":"Usd_PrimComponentFlag"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/TfErrorMarkWrapper":{"title":"struct TfErrorMarkWrapper","role":"symbol","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfErrorMarkWrapper","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TfErrorMarkWrapper"}],"navigatorTitle":[{"kind":"identifier","text":"TfErrorMarkWrapper"}],"abstract":[],"url":"\/documentation\/openusd\/overlay\/tferrormarkwrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Usd_PrimHasPayloadFlag":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimHasPayloadFlag","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Usd_PrimHasPayloadFlag"}],"title":"Usd_PrimHasPayloadFlag","kind":"symbol","role":"symbol","url":"\/documentation\/openusd\/overlay\/usd_primhaspayloadflag","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"Usd_PrimHasPayloadFlag"},{"kind":"text","text":": "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@E@Usd_PrimFlags","text":"Usd_PrimFlags"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/TfDiagnosticBase_Unique_Ptr_Vector":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfDiagnosticBase_Unique_Ptr_Vector","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TfDiagnosticBase_Unique_Ptr_Vector"}],"type":"topic","url":"\/documentation\/openusd\/overlay\/tfdiagnosticbase_unique_ptr_vector","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TfDiagnosticBase_Unique_Ptr_Vector"}],"title":"TfDiagnosticBase_Unique_Ptr_Vector"},"doc://SwiftUsd/documentation/SwiftUsd/DereferencingPointers":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","url":"\/documentation\/swiftusd\/dereferencingpointers","abstract":[{"type":"text","text":"Safely dereferencing "},{"type":"codeVoice","code":"pxr.TfRefPtr"},{"type":"text","text":" and "},{"type":"codeVoice","code":"pxr.TfWeakPtr"},{"type":"text","text":" in Swift"}],"title":"Dereferencing pointers","type":"topic","kind":"article","role":"collectionGroup"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper":{"url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","abstract":[],"kind":"symbol","title":"struct UsdPrimTypeInfoWrapper","role":"symbol","navigatorTitle":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Usd_PrimInstanceFlag":{"url":"\/documentation\/openusd\/overlay\/usd_priminstanceflag","title":"Usd_PrimInstanceFlag","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Usd_PrimInstanceFlag","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"Usd_PrimInstanceFlag"},{"kind":"text","text":": "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@E@Usd_PrimFlags","text":"Usd_PrimFlags"}],"navigatorTitle":[{"kind":"identifier","text":"Usd_PrimInstanceFlag"}],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/SdfLayer_RefPtr_Vector":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfLayer_RefPtr_Vector","type":"topic","abstract":[],"url":"\/documentation\/openusd\/overlay\/sdflayer_refptr_vector","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SdfLayer_RefPtr_Vector"}],"navigatorTitle":[{"kind":"identifier","text":"SdfLayer_RefPtr_Vector"}],"title":"SdfLayer_RefPtr_Vector"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HasAuthoredMetadata":{"kind":"symbol","url":"\/documentation\/openusd\/overlay\/hasauthoredmetadata","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HasAuthoredMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdRelationship","preciseIdentifier":"c:@N@pxr@S@UsdRelationship","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HasAuthoredMetadata","title":"HasAuthoredMetadata(_:_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"HasAuthoredMetadata"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Namespace","path":"\/metadata\/roleHeading","op":"replace"},{"value":"Overlay","path":"\/metadata\/title","op":"replace"},{"value":"namespace","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"Overlay","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"Overlay","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"],"generated":true,"title":"Classes","anchor":"Classes"},{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper"],"generated":true,"title":"Structures","anchor":"Structures"},{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArCreateResolver","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArGetResolver","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArGetUnderlyingResolver","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Dereference-3t65r","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Dereference-9or49"],"generated":true,"title":"Functions","anchor":"Functions"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedEnums","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedFunctions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedOperators"],"title":"Wrapped symbol documentation","generated":true,"anchor":"Wrapped-symbol-documentation"}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"tokens":[{"text":"namespace","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Overlay","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArGetUnderlyingResolver\/title","value":"ArGetUnderlyingResolver","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArGetUnderlyingResolver\/fragments","value":[{"text":"ArGetUnderlyingResolver","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArGetUnderlyingResolver\/navigatorTitle","value":[{"text":"ArGetUnderlyingResolver","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title","value":"UsdImagingGLEngineWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"text":"Overlay","kind":"identifier"}],"op":"add"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/title","value":"HgiMetalWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/fragments","value":[{"kind":"identifier","text":"HgiMetalWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/navigatorTitle","value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArCreateResolver\/title","value":"ArCreateResolver","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArCreateResolver\/fragments","value":[{"text":"ArCreateResolver","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArCreateResolver\/navigatorTitle","value":[{"kind":"identifier","text":"ArCreateResolver"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/title","value":"ArResolverWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/fragments","value":[{"text":"ArResolverWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"ArResolverWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title","value":"HioImageWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments","value":[{"text":"HioImageWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle","value":[{"text":"HioImageWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArGetResolver\/title","value":"ArGetResolver","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArGetResolver\/fragments","value":[{"text":"ArGetResolver","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArGetResolver\/navigatorTitle","value":[{"text":"ArGetResolver","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/title","value":"HgiWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/fragments","value":[{"text":"HgiWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"HgiWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/title","value":"UsdAppUtilsFrameRecorderWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/fragments","value":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/navigatorTitle","value":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/title","value":"UsdPrimTypeInfoWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/fragments","value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}