{"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-9e095","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@N@pxr@S@TfNotice@F@RevokeAndWait#*$@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S2_#S","title":"RevokeAndWait(_:)","symbolKind":"method","modules":[{"name":"OpenUSD"}],"navigatorTitle":[{"text":"RevokeAndWait","kind":"identifier"}],"roleHeading":"Static Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RevokeAndWait","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKeys","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S0_"},{"text":">","kind":"text"},{"text":")","kind":"text"}]},"variants":[{"paths":["\/documentation\/openusd\/revokeandwait-9e095"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/revokeandwait-9e095"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RevokeAndWait","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"keys","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S0_","text":"SwiftKeys"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"platforms":["macOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"seeAlsoSections":[{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-99j13","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-8j5mu","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-6we16","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-2cm0u","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-7toj3","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-17h9z","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-2xoh5","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-7ycue"],"generated":true}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://SwiftUsd/documentation/OpenUSD/Revoke-31sr0":{"abstract":[],"url":"\/documentation\/openusd\/revoke-31sr0","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0","type":"topic","title":"Revoke(_:)","role":"symbol","navigatorTitle":[{"text":"Revoke","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Revoke","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}]},"doc://SwiftUsd/documentation/OpenUSD/RevokeAndWait-7ycue":{"type":"topic","title":"RevokeAndWait(_:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RevokeAndWait","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SwiftKey","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/openusd\/revokeandwait-7ycue","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RevokeAndWait"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-7ycue"},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","type":"topic","url":"\/documentation\/openusd","abstract":[],"role":"collection"},"doc://SwiftUsd/documentation/OpenUSD/RevokeAndWait-9e095":{"kind":"symbol","title":"RevokeAndWait(_:)","navigatorTitle":[{"kind":"identifier","text":"RevokeAndWait"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RevokeAndWait","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SwiftKeys","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S0_","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-9e095","url":"\/documentation\/openusd\/revokeandwait-9e095","abstract":[],"role":"symbol","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-7toj3":{"type":"topic","abstract":[{"text":"Register a listener as being interested in a TfNotice from a particular sender.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Sender","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Sender","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"text":", ","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":", ","kind":"text"},{"text":"borrowing","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"NoticeCaster","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-7toj3","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-7toj3","kind":"symbol","title":"Register(_:_:_:)"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-8j5mu":{"kind":"symbol","abstract":[{"text":"Register a listener as being interested in a TfNotice from a particular sender.","type":"text"}],"title":"Register(_:_:_:)","type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-8j5mu","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-8j5mu","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Sender","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Sender","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyxYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"text":", ","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyxYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyxYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:)-2cm0u":{"kind":"symbol","abstract":[{"text":"Register a listener as being interested in a TfNotice, regardless of sender.","type":"text"}],"title":"Register(_:_:)","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:)-2cm0u","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-2cm0u","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"text":", ","kind":"text"},{"text":"borrowing","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"NoticeCaster","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-17h9z":{"kind":"symbol","abstract":[{"text":"Register a listener as being interested in a TfNotice from a particular sender.","type":"text"}],"title":"Register(_:_:_:)","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-17h9z","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-17h9z","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Sender","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Sender","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"text":", ","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":", ","kind":"text"},{"text":"Sender","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"text":", ","kind":"text"},{"text":"borrowing","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"NoticeCaster","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:)-99j13":{"type":"topic","abstract":[{"text":"Register a listener as being interested in a TfNotice, regardless of sender.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:)-99j13","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-99j13","kind":"symbol","title":"Register(_:_:)"},"doc://SwiftUsd/documentation/OpenUSD/Revoke-2xoh5":{"navigatorTitle":[{"kind":"identifier","text":"Revoke"}],"type":"topic","url":"\/documentation\/openusd\/revoke-2xoh5","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Revoke","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SwiftKeys","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S0_","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-2xoh5","title":"Revoke(_:)"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-6we16":{"type":"topic","abstract":[{"text":"Register a listener as being interested in a TfNotice from a particular sender.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Sender","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Sender","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"text":", ","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":", ","kind":"text"},{"text":"Sender","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-6we16","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-6we16","kind":"symbol","title":"Register(_:_:_:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Static Method"},{"path":"\/metadata\/title","op":"replace","value":"RevokeAndWait"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"RevokeAndWait"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"RevokeAndWait","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-2xoh5","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-7ycue"],"title":"Type Methods","anchor":"Type-Methods","generated":true}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" "},{"kind":"identifier","text":"RevokeAndWait"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","text":"SwiftKeys","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S0_"},{"text":" * ","kind":"text"},{"text":"keys","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/title","value":"Revoke","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/fragments","value":[{"text":"Revoke","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/navigatorTitle","value":[{"text":"Revoke","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-7ycue\/title","value":"RevokeAndWait","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-7ycue\/fragments","value":[{"text":"RevokeAndWait","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-7ycue\/navigatorTitle","value":[{"text":"RevokeAndWait","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-9e095\/title","value":"RevokeAndWait","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-9e095\/fragments","value":[{"text":"RevokeAndWait","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-9e095\/navigatorTitle","value":[{"text":"RevokeAndWait","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-2xoh5\/title","value":"Revoke","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-2xoh5\/fragments","value":[{"text":"Revoke","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-2xoh5\/navigatorTitle","value":[{"kind":"identifier","text":"Revoke"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}