{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/openusd\/swiftusd"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/swiftusd"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SwiftUsd","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@N@SwiftUsd","role":"symbol","roleHeading":"enum","symbolKind":"enum","navigatorTitle":[{"text":"SwiftUsd","kind":"identifier"}],"title":"SwiftUsd","fragments":[{"kind":"identifier","text":"SwiftUsd"}],"modules":[{"name":"OpenUSD"}]},"sections":[],"references":{"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd/TakeReturnValueFromSwift":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/TakeReturnValueFromSwift","url":"\/documentation\/openusd\/swiftusd\/takereturnvaluefromswift","fragments":[{"text":"TakeReturnValueFromSwift","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[],"title":"TakeReturnValueFromSwift"},"doc://SwiftUsd/documentation/OpenUSD":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","type":"topic","url":"\/documentation\/openusd","abstract":[],"role":"collection"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd/PassToSwiftAsReturnValue":{"role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"PassToSwiftAsReturnValue"}],"type":"topic","title":"PassToSwiftAsReturnValue","url":"\/documentation\/openusd\/swiftusd\/passtoswiftasreturnvalue","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/PassToSwiftAsReturnValue","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd":{"title":"SwiftUsd","abstract":[],"url":"\/documentation\/openusd\/swiftusd","fragments":[{"text":"SwiftUsd","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd","kind":"symbol","role":"symbol","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd/TakeFunctionParameterFromSwift":{"abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"TakeFunctionParameterFromSwift"}],"type":"topic","url":"\/documentation\/openusd\/swiftusd\/takefunctionparameterfromswift","title":"TakeFunctionParameterFromSwift","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/TakeFunctionParameterFromSwift"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd/PassToSwiftAsFunctionParameter":{"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"PassToSwiftAsFunctionParameter"}],"title":"PassToSwiftAsFunctionParameter","abstract":[],"url":"\/documentation\/openusd\/swiftusd\/passtoswiftasfunctionparameter","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/PassToSwiftAsFunctionParameter"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Namespace"},{"op":"replace","path":"\/metadata\/title","value":"SwiftUsd"},{"op":"replace","path":"\/metadata\/symbolKind","value":"namespace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SwiftUsd"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SwiftUsd","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":[{"generated":true,"title":"Functions","anchor":"Functions","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/PassToSwiftAsFunctionParameter","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/PassToSwiftAsReturnValue","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/TakeFunctionParameterFromSwift","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/TakeReturnValueFromSwift"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"namespace"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwiftUsd"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/title","value":"SwiftUsd"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/fragments","value":[{"kind":"identifier","text":"SwiftUsd"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/navigatorTitle","value":[{"text":"SwiftUsd","kind":"identifier"}]}]}]}