{"metadata":{"externalID":"c:@N@pxr@S@TfNotice@S@SwiftKey","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SwiftKey","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"SwiftKey","kind":"identifier"}],"role":"symbol","modules":[{"name":"OpenUSD"}],"title":"class SwiftKey"},"variants":[{"paths":["\/documentation\/openusd\/swiftkey"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/swiftkey"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"A key representing a listener registered from either Swift or C++","type":"text"}],"topicSections":[{"generated":true,"title":"Operators","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/operator_"],"anchor":"Operators"},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/SwiftKey-2l2b4","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/SwiftKey-59c3e","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/SwiftKey-5p2qq"],"anchor":"Initializers"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/IsValid","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/operator_bool"],"anchor":"Instance-Methods"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SwiftKey","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","interfaceLanguage":"swift"},"references":{"doc://SwiftUsd/documentation/OpenUSD/SwiftKey/SwiftKey-59c3e":{"kind":"symbol","title":"init(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/SwiftKey-59c3e","url":"\/documentation\/openusd\/swiftkey\/swiftkey-59c3e","type":"topic","abstract":[{"type":"text","text":"Converts a C++ key into a Swift key. The resulting Swift key can be used to cancel the C++ listener in Swift or in C++."}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Key","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@Key","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"SwiftKey"}],"navigatorTitle":[{"kind":"identifier","text":"SwiftKey"}]},"doc://SwiftUsd/documentation/OpenUSD/SwiftKey/operator_":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/operator_","abstract":[{"text":"Enables sorting and holding ","type":"text"},{"code":"SwiftKey","type":"codeVoice"},{"text":"s in a map.","type":"text"}],"navigatorTitle":[{"text":"operator<","kind":"identifier"}],"title":"<(_:_:)","kind":"symbol","url":"\/documentation\/openusd\/swiftkey\/operator_","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"<"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SwiftKey","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"SwiftKey","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"c:b"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/SwiftKey/SwiftKey-5p2qq":{"title":"init()","navigatorTitle":[{"text":"SwiftKey","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/SwiftKey-5p2qq","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier"}],"abstract":[{"text":"Creates an empty (invalid) key not tied to any listener.","type":"text"}],"kind":"symbol","url":"\/documentation\/openusd\/swiftkey\/swiftkey-5p2qq"},"doc://SwiftUsd/documentation/OpenUSD/SwiftKey/SwiftKey-2l2b4":{"kind":"symbol","url":"\/documentation\/openusd\/swiftkey\/swiftkey-2l2b4","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/SwiftKey-2l2b4","title":"init(_:_:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@ST>1#T@TfWeakPtr","kind":"typeIdentifier","text":"pxr::TfWeakPtr"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@__SwiftUsd","kind":"identifier","text":"__SwiftUsd"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@__SwiftUsd@N@TfNotice","kind":"identifier","text":"TfNotice"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@__SwiftUsd@N@TfNotice@S@ListenerBase","kind":"typeIdentifier","text":"ListenerBase"},{"kind":"text","text":">"},{"kind":"text","text":", "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@Key","text":"Key"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SwiftKey"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SwiftKey"}],"abstract":[],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/SwiftKey":{"navigatorTitle":[{"kind":"identifier","text":"SwiftKey"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwiftKey"}],"type":"topic","title":"class SwiftKey","abstract":[{"type":"text","text":"A key representing a listener registered from either Swift or C++"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","url":"\/documentation\/openusd\/swiftkey","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/SwiftKey/operator_bool":{"abstract":[{"type":"text","text":"Does this key refer to a valid notification?"}],"fragments":[{"kind":"identifier","text":"_Bool"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/operator_bool","type":"topic","kind":"symbol","url":"\/documentation\/openusd\/swiftkey\/operator_bool","role":"symbol","title":"operator bool","navigatorTitle":[{"kind":"identifier","text":"operator bool"}]},"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","type":"topic","url":"\/documentation\/openusd","kind":"symbol","role":"collection","title":"OpenUSD","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/SwiftKey/IsValid":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsValid","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"IsValid","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Does this key refer to a valid notification?"}],"title":"IsValid()","url":"\/documentation\/openusd\/swiftkey\/isvalid","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/IsValid"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SwiftKey","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SwiftKey","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SwiftKey","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/IsValid","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/SwiftKey-2l2b4","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/SwiftKey-59c3e","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/SwiftKey-5p2qq","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/operator_","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/operator_bool"]}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SwiftKey","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SwiftKey","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1SwiftKey-59c3e\/title"},{"op":"replace","value":[{"text":"SwiftKey","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1SwiftKey-59c3e\/fragments"},{"op":"replace","value":[{"text":"SwiftKey","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1SwiftKey-59c3e\/navigatorTitle"},{"op":"replace","value":"operator<","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1operator_\/title"},{"op":"replace","value":[{"text":"operator<","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1operator_\/fragments"},{"op":"replace","value":[{"text":"operator<","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1operator_\/navigatorTitle"},{"op":"replace","value":"SwiftKey","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1SwiftKey-5p2qq\/title"},{"op":"replace","value":[{"text":"SwiftKey","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1SwiftKey-5p2qq\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SwiftKey"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1SwiftKey-5p2qq\/navigatorTitle"},{"op":"replace","value":"SwiftKey","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1SwiftKey-2l2b4\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SwiftKey"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1SwiftKey-2l2b4\/fragments"},{"op":"replace","value":[{"text":"SwiftKey","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1SwiftKey-2l2b4\/navigatorTitle"},{"op":"replace","value":"SwiftKey","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/title"},{"op":"replace","value":[{"text":"SwiftKey","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SwiftKey"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/navigatorTitle"},{"op":"replace","value":"operator bool","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1operator_bool\/title"},{"op":"replace","value":[{"kind":"identifier","text":"_Bool"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1operator_bool\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"operator bool"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1operator_bool\/navigatorTitle"},{"op":"replace","value":"IsValid","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1IsValid\/title"},{"op":"replace","value":[{"text":"IsValid","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1IsValid\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"IsValid"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1IsValid\/navigatorTitle"}]}]}