{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetEmptyPrimType"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetEmptyPrimType","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper","kind":"typeIdentifier","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper"}],"platforms":["macOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/getemptyprimtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/getemptyprimtype"]}],"metadata":{"roleHeading":"Static Method","title":"GetEmptyPrimType()","navigatorTitle":[{"kind":"identifier","text":"GetEmptyPrimType"}],"modules":[{"name":"OpenUSD"}],"externalID":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper@F@GetEmptyPrimType#S","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetEmptyPrimType"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper","kind":"typeIdentifier","text":"UsdPrimTypeInfoWrapper"}]},"sections":[],"references":{"doc://SwiftUsd/documentation/OpenUSD":{"url":"\/documentation\/openusd","kind":"symbol","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"fragments":[{"text":"Overlay","kind":"identifier"}],"role":"symbol","title":"Overlay","type":"topic","url":"\/documentation\/openusd\/overlay","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"kind":"symbol","title":"struct UsdPrimTypeInfoWrapper","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper/GetEmptyPrimType":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetEmptyPrimType","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper","text":"UsdPrimTypeInfoWrapper","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"GetEmptyPrimType","kind":"identifier"}],"title":"GetEmptyPrimType()","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/getemptyprimtype","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetEmptyPrimType","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Static Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"GetEmptyPrimType","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"GetEmptyPrimType"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"GetEmptyPrimType"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","text":"UsdPrimTypeInfoWrapper"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetEmptyPrimType"},{"kind":"text","text":"();"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"Overlay","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"value":[{"kind":"identifier","text":"Overlay"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"value":"UsdPrimTypeInfoWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/title"},{"value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/fragments"},{"value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/navigatorTitle"},{"value":"GetEmptyPrimType","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetEmptyPrimType\/title"},{"value":[{"text":"GetEmptyPrimType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetEmptyPrimType\/fragments"},{"value":[{"kind":"identifier","text":"GetEmptyPrimType"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetEmptyPrimType\/navigatorTitle"}]}]}