{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetTypeName","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfToken","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfToken"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/gettypename"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/gettypename"]}],"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetTypeName","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"GetTypeName","kind":"identifier"}],"externalID":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper@F@GetTypeName#1","roleHeading":"Instance Method","title":"GetTypeName()","role":"symbol","modules":[{"name":"OpenUSD"}]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetTypeName"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper/GetTypeName":{"abstract":[],"role":"symbol","title":"GetTypeName()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetTypeName","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfToken","text":"TfToken","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"GetTypeName"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/GetTypeName","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/gettypename","kind":"symbol","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"kind":"symbol","title":"struct UsdPrimTypeInfoWrapper","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper"},"doc://SwiftUsd/documentation/OpenUSD":{"url":"\/documentation\/openusd","kind":"symbol","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"fragments":[{"text":"Overlay","kind":"identifier"}],"role":"symbol","title":"Overlay","type":"topic","url":"\/documentation\/openusd\/overlay","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"GetTypeName"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GetTypeName","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GetTypeName"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":"::","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfToken","text":"TfToken","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"GetTypeName","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetTypeName\/title","op":"replace","value":"GetTypeName"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetTypeName\/fragments","op":"replace","value":[{"kind":"identifier","text":"GetTypeName"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1GetTypeName\/navigatorTitle","op":"replace","value":[{"text":"GetTypeName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/title","op":"replace","value":"UsdPrimTypeInfoWrapper"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/fragments","op":"replace","value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/navigatorTitle","op":"replace","value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace","value":"Overlay"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace","value":[{"kind":"identifier","text":"Overlay"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add","value":[{"kind":"identifier","text":"Overlay"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}