{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper"]]},"variants":[{"paths":["\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/operator_bool"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/operator_bool"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/operator_bool"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"explicit","kind":"keyword"},{"text":" ","kind":"text"},{"text":"operator","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_Bool","kind":"typeIdentifier"},{"text":"() ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}]}]}],"metadata":{"title":"operator bool","externalID":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper@F@operator bool#1","fragments":[{"kind":"identifier","text":"_Bool"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"operator bool"}],"modules":[{"name":"OpenUSD"}],"roleHeading":"Instance Method"},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"fragments":[{"text":"Overlay","kind":"identifier"}],"role":"symbol","title":"Overlay","type":"topic","url":"\/documentation\/openusd\/overlay","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"kind":"symbol","title":"struct UsdPrimTypeInfoWrapper","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper/operator_bool":{"fragments":[{"kind":"identifier","text":"_Bool"}],"title":"operator bool","navigatorTitle":[{"kind":"identifier","text":"operator bool"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/operator_bool","kind":"symbol","role":"symbol","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/operator_bool","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD":{"url":"\/documentation\/openusd","kind":"symbol","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"operator bool"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"_Bool"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"operator bool","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"explicit","kind":"keyword"},{"text":" ","kind":"text"},{"text":"operator","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_Bool","kind":"typeIdentifier"},{"text":"() ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}],"platforms":["macOS"]}]}},{"value":"Overlay","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"value":[{"kind":"identifier","text":"Overlay"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"value":"UsdPrimTypeInfoWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/title"},{"value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/fragments"},{"value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/navigatorTitle"},{"value":"operator bool","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1operator_bool\/title"},{"value":[{"kind":"identifier","text":"_Bool"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1operator_bool\/fragments"},{"value":[{"text":"operator bool","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1operator_bool\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}