{"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/UsdPrimTypeInfoWrapper-9x5fy","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/usdprimtypeinfowrapper-9x5fy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/usdprimtypeinfowrapper-9x5fy"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"prim"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@UsdPrim","kind":"typeIdentifier","text":"UsdPrim"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"UsdPrimTypeInfoWrapper"}],"languages":["swift"],"platforms":["macOS"]}]}],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdPrim","text":"UsdPrim"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"UsdPrimTypeInfoWrapper"}],"externalID":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper@F@UsdPrimTypeInfoWrapper#&1$@N@pxr@S@UsdPrim#","symbolKind":"init","roleHeading":"Initializer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"modules":[{"name":"OpenUSD"}],"title":"init(_:)"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper"]]},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"text":"Overlay","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"title":"struct UsdPrimTypeInfoWrapper","navigatorTitle":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","abstract":[],"url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper"},"doc://SwiftUsd/documentation/OpenUSD":{"type":"topic","url":"\/documentation\/openusd","title":"OpenUSD","role":"collection","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper/UsdPrimTypeInfoWrapper-9x5fy":{"title":"init(_:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@UsdPrim","text":"UsdPrim","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","kind":"typeIdentifier"}],"url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/usdprimtypeinfowrapper-9x5fy","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/UsdPrimTypeInfoWrapper-9x5fy","role":"symbol","abstract":[],"navigatorTitle":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Constructor","path":"\/metadata\/roleHeading","op":"replace"},{"value":"UsdPrimTypeInfoWrapper","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdPrim","text":"UsdPrim"},{"kind":"text","text":" & "},{"kind":"internalParam","text":"prim"},{"kind":"text","text":");"}],"platforms":["macOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace"},{"value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add"},{"value":"UsdPrimTypeInfoWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/title","op":"replace"},{"value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/fragments","op":"replace"},{"value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/navigatorTitle","op":"replace"},{"value":"UsdPrimTypeInfoWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1UsdPrimTypeInfoWrapper-9x5fy\/title","op":"replace"},{"value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1UsdPrimTypeInfoWrapper-9x5fy\/fragments","op":"replace"},{"value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1UsdPrimTypeInfoWrapper-9x5fy\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}