{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/IntersectionResult"]]},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/IntersectionResult\/instancerContext","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/intersectionresult\/instancercontext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/intersectionresult\/instancercontext"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instancerContext","kind":"identifier"},{"text":": ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"HdInstancerContext","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@std@N@__1@S@pair>#$@N@pxr@S@SdfPath#I#$@N@std@N@__1@S@allocator>#S0_","kind":"typeIdentifier"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"modules":[{"name":"OpenUSD"}],"title":"instancerContext","navigatorTitle":[{"kind":"identifier","text":"instancerContext"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@N@Overlay@S@UsdImagingGLEngineWrapper@S@IntersectionResult@FI@instancerContext","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instancerContext","kind":"identifier"},{"text":": ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"HdInstancerContext","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@std@N@__1@S@pair>#$@N@pxr@S@SdfPath#I#$@N@std@N@__1@S@allocator>#S0_"}],"role":"symbol"},"sections":[],"references":{"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","kind":"symbol","abstract":[],"url":"\/documentation\/openusd","role":"collection","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"url":"\/documentation\/openusd\/overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol","title":"Overlay","type":"topic","kind":"symbol","fragments":[{"text":"Overlay","kind":"identifier"}],"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"navigatorTitle":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"kind":"symbol","type":"topic","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","abstract":[],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","title":"class UsdImagingGLEngineWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/IntersectionResult":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntersectionResult"}],"url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/intersectionresult","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IntersectionResult"}],"kind":"symbol","abstract":[],"title":"struct IntersectionResult","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/IntersectionResult","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/IntersectionResult/instancerContext":{"kind":"symbol","title":"instancerContext","navigatorTitle":[{"text":"instancerContext","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/IntersectionResult\/instancerContext","abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instancerContext","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@std@N@__1@S@pair>#$@N@pxr@S@SdfPath#I#$@N@std@N@__1@S@allocator>#S0_","text":"HdInstancerContext","kind":"typeIdentifier"}],"url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/intersectionresult\/instancercontext","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"instancerContext","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"instancerContext"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"instancerContext"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":"::","kind":"text"},{"text":"HdInstancerContext","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@std@N@__1@S@pair>#$@N@pxr@S@SdfPath#I#$@N@std@N@__1@S@allocator>#S0_"},{"text":" ","kind":"text"},{"text":"instancerContext","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace"},{"value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace"},{"value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add"},{"value":"UsdImagingGLEngineWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title","op":"replace"},{"value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments","op":"replace"},{"value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle","op":"replace"},{"value":"IntersectionResult","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IntersectionResult\/title","op":"replace"},{"value":[{"kind":"identifier","text":"IntersectionResult"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IntersectionResult\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"IntersectionResult"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IntersectionResult\/navigatorTitle","op":"replace"},{"value":"instancerContext","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IntersectionResult~1instancerContext\/title","op":"replace"},{"value":[{"text":"instancerContext","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IntersectionResult~1instancerContext\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"instancerContext"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IntersectionResult~1instancerContext\/navigatorTitle","op":"replace"}]}]}