{"abstract":[{"type":"text","text":"Learn about the changes this Swift Package makes to OpenUSD"}],"seeAlsoSections":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DetectingOpenUSDFeatureFlags","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/BuildingLocally"],"generated":true,"anchor":"Technical-details","title":"Technical details"}],"kind":"article","identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangesToOpenUSD","interfaceLanguage":"swift"},"metadata":{"role":"article","roleHeading":"Article","title":"Changes to OpenUSD","modules":[{"name":"OpenUSD"}]},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"sections":[],"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"text":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This repo makes changes to OpenUSD to support Swift-Cxx interop and make Usd easier to use in Xcode."}]},{"anchor":"Changes-to-OpenUSD-before-building","level":3,"text":"Changes to OpenUSD before building","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"These changes are contained in "},{"type":"codeVoice","code":"SwiftUsd\/openusd-patch.patch"},{"type":"text","text":":"}]},{"anchor":"Usd-specific-changes-to-OpenUSD-before-building","level":4,"text":"Usd-specific changes to OpenUSD before building","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"These changes fix bugs or add features to Usd that aren’t part of vanilla OpenUSD"}]},{"items":[{"content":[{"inlineContent":[{"text":"None","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"anchor":"Swift-specific-changes-to-OpenUSD-before-building","text":"Swift-specific changes to OpenUSD before building","level":4,"type":"heading"},{"inlineContent":[{"text":"These changes work around Swift-specific issues in vanilla OpenUSD, add Swift-specific features, and work around issues in the Swift compiler.","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Header modularization fixes:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Modified: ","type":"text"},{"type":"codeVoice","code":"pxr\/base\/arch\/fileSystem.h"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Modified: ","type":"text"},{"type":"codeVoice","code":"pxr\/base\/tf\/notice.h"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Modified: "},{"type":"codeVoice","code":"pxr\/base\/vt\/dictionary.h"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Modified: ","type":"text"},{"type":"codeVoice","code":"pxr\/usd\/sdf\/predicateProgram.h"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Modified: "},{"type":"codeVoice","code":"pxr\/exec\/vdf\/parallelExecutorEngineBase.h"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Modified: ","type":"text"},{"code":"pxr\/exec\/vdf\/pullBasedExecutorEngine.h","type":"codeVoice"}]}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Support importing ","type":"text"},{"type":"codeVoice","code":"pxr::TfRefBase"},{"text":" subclasses as reference types in Swift:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Modified: "},{"code":"pxr\/base\/tf\/CMakeLists.txt","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Modified: "},{"type":"codeVoice","code":"pxr\/base\/tf\/refBase.h"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Modified: "},{"type":"codeVoice","code":"pxr\/base\/tf\/refPtr.h"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Added: ","type":"text"},{"code":"pxr\/base\/tf\/retainReleaseHelper.h","type":"codeVoice"}]}]}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Support MaterialX in Swift Package:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Modified: ","type":"text"},{"type":"codeVoice","code":"pxr\/usd\/usdMtlx\/utils.cpp"}]}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"text":"Support using ","type":"text"},{"type":"codeVoice","code":"pxr::TfNotice::Register"},{"text":" from Swift:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"Modified: ","type":"text"},{"code":"pxr\/base\/tf\/notice.h","type":"codeVoice"}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"rdar:\/\/148534260","type":"reference"},{"text":" ","type":"text"},{"text":"Annotations of C++ operators have to go in header files until they’re supported in API Notes","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Modified: "},{"type":"codeVoice","code":"pxr\/base\/tf\/refPtr.h"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Modified: ","type":"text"},{"code":"pxr\/base\/tf\/weakPtrFacade.h","type":"codeVoice"}],"type":"paragraph"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/swiftlang\/swift\/issues\/83117"}]},{"items":[{"content":[{"inlineContent":[{"text":"Modified: ","type":"text"},{"code":"pxr\/base\/tf\/iterator.h","type":"codeVoice"}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"https:\/\/github.com\/swiftlang\/swift\/issues\/83116","isActive":true},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"This issue can be worked around by making sure that the default arguments to methods in class templates are valid expressions for all specialization of that template, even if a particular specialization does not use some methods."}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Modified: ","type":"text"},{"code":"pxr\/imaging\/hd\/dependencySchema.h","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Modified: "},{"type":"codeVoice","code":"pxr\/imaging\/hd\/schema.h"}]}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"rdar:\/\/150456875","type":"reference"},{"type":"text","text":" "},{"type":"text","text":"This issue is worked around by moving the definition of a type from a source file into a header file, and by making a private header publig"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Modified: ","type":"text"},{"code":"pxr\/exec\/exec\/CMakeLists.txt","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Modified: ","type":"text"},{"code":"pxr\/imaging\/hdsi\/debuggingSceneIndex.cpp","type":"codeVoice"}]}]},{"content":[{"inlineContent":[{"text":"Modified: ","type":"text"},{"code":"pxr\/imaging\/hdsi\/debuggingSceneIndex.h","type":"codeVoice"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"type":"unorderedList"},{"anchor":"Changes-to-OpenUSD-while-making-a-Swift-Package","text":"Changes to OpenUSD while making a Swift Package","level":3,"type":"heading"},{"inlineContent":[{"text":"These changes are applied by ","type":"text"},{"code":"SwiftUsd\/scripts\/make-swift-package","type":"codeVoice"},{"text":", after ","type":"text"},{"code":"build_usd.py","type":"codeVoice"},{"text":" has finished compiling OpenUSD. (This list is non-exhaustive, see ","type":"text"},{"code":"SwiftUsd\/scripts\/make-swift-package","type":"codeVoice"},{"text":" for full details)","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Wrapping dylibs into frameworks:"},{"type":"text","text":"\n"},{"type":"text","text":"All required dylibs are found using "},{"code":"otool","type":"codeVoice"},{"type":"text","text":", then each dylib is converted to a framework bundle. This involves:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Modifying "},{"type":"codeVoice","code":"plugInfo.json"},{"type":"text","text":" files"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Uppercasing Usd plugin "},{"type":"codeVoice","code":"resources"},{"type":"text","text":" directories to "},{"type":"codeVoice","code":"Resources"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Copying Usd plugins, Hydra plugins, and MaterialX libraries","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Fixing the dylib’s load commands"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Code-signing the framework"}],"type":"paragraph"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Combining versions of the same framework compiled for different platforms into a single multi-platform XCFramework","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Making a Swift Package:","type":"text"},{"text":"\n","type":"text"},{"text":"This includes:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Copying headers from ","type":"text"},{"type":"codeVoice","code":"USD_BUILD_DIRECTORY\/include"},{"text":" into the Swift Package","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Writing out a modulemap file and copying an API Notes file into the public headers directory","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Other Swift-Package specific manipulation that doesn’t modify OpenUSD"}]}]}]}]}],"type":"unorderedList"},{"anchor":"Improving-OpenUSD-ergonomics-in-Swift","text":"Improving OpenUSD ergonomics in Swift","level":3,"type":"heading"},{"anchor":"Automatic-improvements","text":"Automatic improvements","level":4,"type":"heading"},{"inlineContent":[{"text":"Some ergonomic improvements are done automatically using ","type":"text"},{"identifier":"https:\/\/github.com\/apple\/SwiftUsd-ast-answerer","isActive":true,"type":"reference"},{"text":" for code generation:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"pxr::TfRefBase"},{"text":" subclasses like ","type":"text"},{"type":"codeVoice","code":"pxr::UsdStage"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"pxr::SdfLayer"},{"text":" are imported as reference types, along with functions to convert to\/from Usd smart pointers to raw pointers","type":"text"}]}]},{"content":[{"inlineContent":[{"code":"operator bool()","type":"codeVoice"},{"text":" is mapped to ","type":"text"},{"code":"Bool.init(_:)","type":"codeVoice"},{"text":" for smart pointers, Usd schemas, and other Usd types","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Many Usd types are conformed to standard library protocols:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Comparable"}]}]},{"content":[{"inlineContent":[{"code":"CustomStringConvertible","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Equatable"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Hashable"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Sendable"}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Unscoped enums are wrapped to work around "},{"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/swiftlang\/swift\/issues\/62127"}]}]},{"content":[{"inlineContent":[{"text":"Unscoped enums have support for implicit member expressions","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"code":"Overlay.GetPrim(_:T)","type":"codeVoice"},{"text":" is provided to workaround ","type":"text"},{"code":"T.GetPrim()","type":"codeVoice"},{"text":" ","type":"text"},{"isActive":true,"identifier":"https:\/\/github.com\/swiftlang\/swift\/pull\/81709","type":"reference"},{"text":", for all ","type":"text"},{"code":"T: UsdSchemaBase","type":"codeVoice"}],"type":"paragraph"}]}],"type":"unorderedList"},{"anchor":"Manual-improvements","text":"Manual improvements","level":4,"type":"heading"},{"inlineContent":[{"type":"text","text":"Other ergonomic improvements are done by hand:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Support for implicit member expressions for all token types  (e.g. ","type":"text"},{"type":"codeVoice","code":"UsdGeomTokensType"},{"text":")","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Conformances of a few types to ","type":"text"},{"code":"ExpressibleByFOOLiteral","type":"codeVoice"},{"text":" protocols","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Wrapping of various behavior\/types that can’t be implemented\/imported into Swift","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Wrapping of various methods on Usd types that return const-ref values to return the result by copied value","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Wrapping of methods on "},{"type":"codeVoice","code":"pxr::UsdReferences"},{"type":"text","text":" and "},{"type":"codeVoice","code":"pxr::UsdPayloads"},{"type":"text","text":" to have nonmutating Swift versions, despite having non-const C++ versions"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Conformances of a few Usd types to ","type":"text"},{"code":"Sequence","type":"codeVoice"}]}]},{"content":[{"inlineContent":[{"text":"Conformances of some ","type":"text"},{"code":"std::vector","type":"codeVoice"},{"text":" specializations to ","type":"text"},{"code":"Equatable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"CustomStringConvertible","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Typedefs to work around ","type":"text"},{"identifier":"rdar:\/\/121886233","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Support for iterating over "},{"code":"pxr::UsdPrimRange","type":"codeVoice"},{"type":"text","text":" while calling "},{"code":"IsPostVisit()","type":"codeVoice"},{"type":"text","text":" and "},{"code":"PruneChildren()","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Conformances of many "},{"type":"codeVoice","code":"pxr::VtArray"},{"type":"text","text":" specializations to "},{"type":"codeVoice","code":"Equatable"},{"type":"text","text":", "},{"type":"codeVoice","code":"ExpressibleByArrayLiteral"},{"type":"text","text":", "},{"type":"codeVoice","code":"Sequence"},{"type":"text","text":", and "},{"type":"codeVoice","code":"CustomStringConvertible"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"overridingTitleInlineContent":[{"type":"codeVoice","code":"Overlay.withUsdEditContext(_:_:_:)"}],"overridingTitle":"Overlay.withUsdEditContext(_:_:_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/withUsdEditContext(_:_:_:)","isActive":true,"type":"reference"},{"text":" to wrap ","type":"text"},{"code":"pxr::UsdEditContext","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","overridingTitle":"Overlay.withTfErrorMark(_:)","isActive":true,"overridingTitleInlineContent":[{"type":"codeVoice","code":"Overlay.withTfErrorMark(_:)"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/withTfErrorMark(_:)"},{"text":" to wrap ","type":"text"},{"type":"codeVoice","code":"pxr::TfErrorMark"}]}]}],"type":"unorderedList"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/swiftusd\/changestoopenusd"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/changestoopenusd"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"https://github.com/swiftlang/swift/pull/81709":{"title":"https:\/\/github.com\/swiftlang\/swift\/pull\/81709: [cxx-interop] Fix ambiguous methods in long chains of inheritance","url":"https:\/\/github.com\/swiftlang\/swift\/pull\/81709","type":"link","identifier":"https:\/\/github.com\/swiftlang\/swift\/pull\/81709","titleInlineContent":[{"type":"text","text":"https:\/\/github.com\/swiftlang\/swift\/pull\/81709: [cxx-interop] Fix ambiguous methods in long chains of inheritance"}]},"rdar://150456875":{"type":"link","title":"rdar:\/\/150456875: Forward declaring std::map’s value causes an error for Swift but not C++ (Swift 6.1 regression)","titleInlineContent":[{"type":"text","text":"rdar:\/\/150456875: Forward declaring std::map’s value causes an error for Swift but not C++ (Swift 6.1 regression)"}],"identifier":"rdar:\/\/150456875","url":"rdar:\/\/150456875"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/withUsdEditContext(_:_:_:)":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/withUsdEditContext(_:_:_:)","role":"symbol","title":"withUsdEditContext(_:_:_:)","url":"\/documentation\/openusd\/c++\/overlay\/withusdeditcontext(_:_:_:)","abstract":[{"type":"text","text":"Performs an edit using the edit target."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withUsdEditContext"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"UsdStage","preciseIdentifier":"c:@N@pxr@S@UsdStage"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"UsdEditTarget","preciseIdentifier":"c:@N@pxr@S@UsdEditTarget"},{"kind":"text","text":", () "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ("},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE18withUsdEditContextyxSo021pxrInternal_v0_25_8__H10Reserved__O0E5StageV_AF0eF6TargetVxyKXEtKlFZ1TL_xmfp"},{"kind":"text","text":")) "},{"kind":"keyword","text":"rethrows"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE18withUsdEditContextyxSo021pxrInternal_v0_25_8__H10Reserved__O0E5StageV_AF0eF6TargetVxyKXEtKlFZ1TL_xmfp"}],"kind":"symbol"},"doc://SwiftUsd/documentation/SwiftUsd/BuildingLocally":{"abstract":[{"text":"Learn how to use SwiftUsd with local\/existing OpenUSD binaries","type":"text"}],"type":"topic","url":"\/documentation\/swiftusd\/buildinglocally","role":"article","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/BuildingLocally","title":"Building locally"},"doc://SwiftUsd/documentation/SwiftUsd/DetectingOpenUSDFeatureFlags":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DetectingOpenUSDFeatureFlags","url":"\/documentation\/swiftusd\/detectingopenusdfeatureflags","kind":"article","title":"Detecting OpenUSD feature flags","type":"topic","role":"article","abstract":[{"type":"text","text":"Learn how to detect OpenUSD feature flags"}]},"https://github.com/swiftlang/swift/issues/62127":{"type":"link","title":"https:\/\/github.com\/swiftlang\/swift\/issues\/62127: C++ interop: nested enum not imported","titleInlineContent":[{"type":"text","text":"https:\/\/github.com\/swiftlang\/swift\/issues\/62127: C++ interop: nested enum not imported"}],"identifier":"https:\/\/github.com\/swiftlang\/swift\/issues\/62127","url":"https:\/\/github.com\/swiftlang\/swift\/issues\/62127"},"https://github.com/swiftlang/swift/issues/83116":{"title":"https:\/\/github.com\/swiftlang\/swift\/issues\/83116: Swift instantiates default arguments for function templates too eagerly","url":"https:\/\/github.com\/swiftlang\/swift\/issues\/83116","type":"link","identifier":"https:\/\/github.com\/swiftlang\/swift\/issues\/83116","titleInlineContent":[{"type":"text","text":"https:\/\/github.com\/swiftlang\/swift\/issues\/83116: Swift instantiates default arguments for function templates too eagerly"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/withTfErrorMark(_:)":{"role":"symbol","abstract":[{"text":"Performs work with a ","type":"text"},{"type":"codeVoice","code":"pxr::TfErrorMark"},{"text":" in scope","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withTfErrorMark","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"E","kind":"genericParameter"},{"text":">((","kind":"text"},{"text":"borrowing","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Overlay","preciseIdentifier":"c:@N@Overlay","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"TfErrorMarkWrapper","preciseIdentifier":"c:@N@Overlay@S@TfErrorMarkWrapper","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":"(","kind":"text"},{"text":"E","preciseIdentifier":"s:So7OverlayO7OpenUSDE15withTfErrorMarkyxxAB0efG7WrapperVq_YKXEq_YKs0F0R_r0_lFZ1EL_q_mfp","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE15withTfErrorMarkyxxAB0efG7WrapperVq_YKXEq_YKs0F0R_r0_lFZ1TL_xmfp","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":"(","kind":"text"},{"text":"E","preciseIdentifier":"s:So7OverlayO7OpenUSDE15withTfErrorMarkyxxAB0efG7WrapperVq_YKXEq_YKs0F0R_r0_lFZ1EL_q_mfp","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE15withTfErrorMarkyxxAB0efG7WrapperVq_YKXEq_YKs0F0R_r0_lFZ1TL_xmfp","kind":"typeIdentifier"}],"url":"\/documentation\/openusd\/c++\/overlay\/withtferrormark(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/withTfErrorMark(_:)","type":"topic","kind":"symbol","title":"withTfErrorMark(_:)"},"rdar://148534260":{"type":"link","title":"rdar:\/\/148534260: API notes should support annotating C++ operators","titleInlineContent":[{"type":"text","text":"rdar:\/\/148534260: API notes should support annotating C++ operators"}],"identifier":"rdar:\/\/148534260","url":"rdar:\/\/148534260"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol"},"https://github.com/swiftlang/swift/issues/83117":{"title":"https:\/\/github.com\/swiftlang\/swift\/issues\/83117: Swift Array addition causes unrelated C++ static_assert to fail","url":"https:\/\/github.com\/swiftlang\/swift\/issues\/83117","type":"link","identifier":"https:\/\/github.com\/swiftlang\/swift\/issues\/83117","titleInlineContent":[{"type":"text","text":"https:\/\/github.com\/swiftlang\/swift\/issues\/83117: Swift Array addition causes unrelated C++ static_assert to fail"}]},"rdar://121886233":{"type":"link","title":"rdar:\/\/121886233: Support specializing class templates with concrete types using <> syntax","titleInlineContent":[{"type":"text","text":"rdar:\/\/121886233: Support specializing class templates with concrete types using <> syntax"}],"identifier":"rdar:\/\/121886233","url":"rdar:\/\/121886233"},"https://github.com/apple/SwiftUsd-ast-answerer":{"title":"https:\/\/github.com\/apple\/SwiftUsd-ast-answerer","url":"https:\/\/github.com\/apple\/SwiftUsd-ast-answerer","type":"link","identifier":"https:\/\/github.com\/apple\/SwiftUsd-ast-answerer","titleInlineContent":[{"type":"text","text":"https:\/\/github.com\/apple\/SwiftUsd-ast-answerer"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Technical-details","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DetectingOpenUSDFeatureFlags","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/BuildingLocally"],"title":"Technical details"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}