{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftusd\/checkingforvalidity"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/swiftusd\/checkingforvalidity"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","interfaceLanguage":"swift"},"abstract":[{"text":"Checking for ","type":"text"},{"code":"IsValid()","type":"codeVoice"},{"text":" and null pointers in Swift","type":"text"}],"kind":"article","sections":[],"metadata":{"role":"article","title":"Checking for validity","roleHeading":"Article","modules":[{"name":"OpenUSD"}]},"seeAlsoSections":[{"title":"New symbol documentation","anchor":"New-symbol-documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"],"generated":true}],"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"In Swift, ","type":"text"},{"type":"codeVoice","code":"operator bool()"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"IsValid()"},{"text":" are mapped to initializers on ","type":"text"},{"type":"codeVoice","code":"Bool"},{"text":", like so:","type":"text"}]},{"syntax":"swift","code":["let prim = stage.GetPrimAtPath(\"\/foo\")","if Bool(prim) {","    \/\/ prim is valid","} else {","    \/\/ prim is invalid","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"The following types have support using ","type":"text"},{"type":"codeVoice","code":"Bool"},{"text":" to check for validity in Swift:","type":"text"}]},{"text":"Smart pointers","level":3,"type":"heading","anchor":"Smart-pointers"},{"items":[{"content":[{"inlineContent":[{"code":"pxr::TfRefPtr<T>","type":"codeVoice"},{"type":"text","text":" supports this "},{"code":"Bool","type":"codeVoice"},{"type":"text","text":" initializer:"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"links","items":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/Bool\/init(_:)-63kny"],"style":"list"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"code":"pxr::TfRefPtr<const T>","type":"codeVoice"},{"text":" supports this ","type":"text"},{"code":"Bool","type":"codeVoice"},{"text":" initializer:","type":"text"}],"type":"paragraph"}]}]},{"type":"links","items":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/Bool\/init(_:)-8lpgx"],"style":"list"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"pxr::TfWeakPtr<T>"},{"type":"text","text":" supports this "},{"type":"codeVoice","code":"Bool"},{"type":"text","text":" initializer:"}],"type":"paragraph"}]}]},{"type":"links","items":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/Bool\/init(_:)-6azcc"],"style":"list"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"pxr::TfWeakPtr<T>","type":"codeVoice"},{"text":" supports this ","type":"text"},{"code":"Bool","type":"codeVoice"},{"text":" initializer:","type":"text"}]}]}]},{"style":"list","type":"links","items":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/Bool\/init(_:)-6azcc"]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/SdfHandle_pxr.SdfPrimSpec_","type":"reference","isActive":true}],"type":"paragraph"}]}]},{"text":"Usd objects","type":"heading","level":3,"anchor":"Usd-objects"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdObject","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdPrim","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdProperty","type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdAttribute","type":"reference","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdRelationship","type":"reference","isActive":true}]}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdShadeInput","type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdShadeOutput","type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdGeomXformOp","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper"}],"type":"paragraph"}]}],"type":"unorderedList"},{"level":3,"anchor":"Usd-schemas","text":"Usd schemas","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"All subclasses of "},{"type":"codeVoice","code":"UsdSchemaBase"},{"type":"text","text":" support using "},{"type":"codeVoice","code":"Bool"},{"type":"text","text":" to check for validity in Swift."}]}]}],"references":{"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfDiagnosticFacilities":{"type":"topic","title":"Working with Tf Diagnostic Facilities","kind":"article","abstract":[{"text":"Learn how to use the Tf diagnostic facilities in Swift","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","url":"\/documentation\/swiftusd\/workingwithtfdiagnosticfacilities","role":"collectionGroup"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/UsdObject":{"type":"topic","title":"pxr.UsdObject","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdObject","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"UsdObject","kind":"identifier","preciseIdentifier":"c:@N@pxr@S@UsdObject"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"UsdObject","kind":"identifier"}],"url":"\/documentation\/openusd\/c++\/pxr\/usdobject","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/UsdGeomXformOp":{"url":"\/documentation\/openusd\/c++\/pxr\/usdgeomxformop","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdGeomXformOp","type":"topic","title":"pxr.UsdGeomXformOp","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"UsdGeomXformOp","kind":"identifier"}],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdGeomXformOp","preciseIdentifier":"c:@N@pxr@S@UsdGeomXformOp","kind":"identifier"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/UsdAttribute":{"kind":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/usdattribute","abstract":[],"type":"topic","role":"symbol","title":"pxr.UsdAttribute","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdAttribute","navigatorTitle":[{"text":"UsdAttribute","kind":"identifier"}],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdAttribute","preciseIdentifier":"c:@N@pxr@S@UsdAttribute","kind":"identifier"}]},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfNotice":{"kind":"article","title":"Working with TfNotice","type":"topic","role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","abstract":[{"text":"Learn how to use the TfNotice notification subsystem in Swift","type":"text"}],"url":"\/documentation\/swiftusd\/workingwithtfnotice"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/SdfHandle_pxr.SdfPrimSpec_":{"type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/sdfhandle_pxr.sdfprimspec_","kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SdfHandle<pxr.SdfPrimSpec>"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/SdfHandle_pxr.SdfPrimSpec_","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:types.h@N@pxr@T@SdfPrimSpecHandle","text":"SdfPrimSpecHandle"}],"title":"pxr.SdfHandle<pxr.SdfPrimSpec>"},"doc://SwiftUsd/documentation/OpenUSD/Swift/Bool/init(_:)-63kny":{"title":"init(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/Bool\/init(_:)-63kny","type":"topic","abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the pointer is not null"}],"url":"\/documentation\/openusd\/swift\/bool\/init(_:)-63kny","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Overlay","preciseIdentifier":"c:@N@Overlay"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"_TfRefPtrProtocol","preciseIdentifier":"s:So7OverlayO7OpenUSDE17_TfRefPtrProtocolP"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://SwiftUsd/documentation/SwiftUsd/CreatingPointers":{"kind":"article","url":"\/documentation\/swiftusd\/creatingpointers","abstract":[{"text":"Creating ","type":"text"},{"code":"pxr.TfRefPtr","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"pxr.TfWeakPtr","type":"codeVoice"},{"text":" in Swift","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","type":"topic","title":"Creating pointers","role":"collectionGroup"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/UsdPrim":{"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@UsdPrim","kind":"identifier","text":"UsdPrim"}],"navigatorTitle":[{"kind":"identifier","text":"UsdPrim"}],"title":"pxr.UsdPrim","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdPrim","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/openusd\/c++\/pxr\/usdprim","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/UsdRelationship":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdRelationship","url":"\/documentation\/openusd\/c++\/pxr\/usdrelationship","role":"symbol","title":"pxr.UsdRelationship","type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@UsdRelationship","kind":"identifier","text":"UsdRelationship"}],"navigatorTitle":[{"kind":"identifier","text":"UsdRelationship"}]},"doc://SwiftUsd/documentation/SwiftUsd/DereferencingPointers":{"title":"Dereferencing pointers","url":"\/documentation\/swiftusd\/dereferencingpointers","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","abstract":[{"text":"Safely dereferencing ","type":"text"},{"type":"codeVoice","code":"pxr.TfRefPtr"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"pxr.TfWeakPtr"},{"text":" in Swift","type":"text"}],"type":"topic","kind":"article","role":"collectionGroup"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfErrorMark":{"abstract":[{"type":"text","text":"Learn how to use TfErrorMark in Swift"}],"title":"Working with TfErrorMark","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","url":"\/documentation\/swiftusd\/workingwithtferrormark","type":"topic","role":"article"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/UsdShadeOutput":{"url":"\/documentation\/openusd\/c++\/pxr\/usdshadeoutput","kind":"symbol","title":"pxr.UsdShadeOutput","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdShadeOutput","role":"symbol","type":"topic","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"identifier","preciseIdentifier":"c:@N@pxr@S@UsdShadeOutput","text":"UsdShadeOutput"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"UsdShadeOutput"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/UsdProperty":{"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdProperty","preciseIdentifier":"c:@N@pxr@S@UsdProperty","kind":"identifier"}],"navigatorTitle":[{"text":"UsdProperty","kind":"identifier"}],"title":"pxr.UsdProperty","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdProperty","url":"\/documentation\/openusd\/c++\/pxr\/usdproperty","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Swift/Bool/init(_:)-6azcc":{"type":"topic","title":"init(_:)","url":"\/documentation\/openusd\/swift\/bool\/init(_:)-6azcc","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/Bool\/init(_:)-6azcc","abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the pointer is not null."}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay","text":"Overlay"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfWeakPtrProtocolP","text":"_TfWeakPtrProtocol"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"title":"class HioImageWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","navigatorTitle":[{"kind":"identifier","text":"HioImageWrapper"}],"type":"topic","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HioImageWrapper"}],"url":"\/documentation\/openusd\/overlay\/hioimagewrapper"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/UsdShadeInput":{"title":"pxr.UsdShadeInput","role":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdShadeInput","preciseIdentifier":"c:@N@pxr@S@UsdShadeInput","kind":"identifier"}],"navigatorTitle":[{"text":"UsdShadeInput","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/UsdShadeInput","type":"topic","kind":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/usdshadeinput","abstract":[]},"doc://SwiftUsd/documentation/SwiftUsd/TypeConversion":{"kind":"article","type":"topic","url":"\/documentation\/swiftusd\/typeconversion","role":"collectionGroup","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion","title":"Type conversion","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Swift/Bool/init(_:)-8lpgx":{"type":"topic","url":"\/documentation\/openusd\/swift\/bool\/init(_:)-8lpgx","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/Bool\/init(_:)-8lpgx","kind":"symbol","title":"init(_:)","abstract":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" if the pointer is not null","type":"text"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Overlay","preciseIdentifier":"c:@N@Overlay","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"_TfConstRefPtrProtocol","preciseIdentifier":"s:So7OverlayO7OpenUSDE22_TfConstRefPtrProtocolP","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://SwiftUsd/documentation/SwiftUsd/ConvenientExtensions":{"role":"collectionGroup","kind":"article","abstract":[{"type":"text","text":"Extensions that make OpenUSD nicer to use in Swift"}],"title":"Convenient extensions","url":"\/documentation\/swiftusd\/convenientextensions","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions"},"doc://SwiftUsd/documentation/SwiftUsd/UsingEditContexts":{"abstract":[{"type":"text","text":"Using "},{"type":"codeVoice","code":"pxr.UsdEditContext"},{"type":"text","text":" in Swift"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","role":"collectionGroup","title":"Using edit contexts","url":"\/documentation\/swiftusd\/usingeditcontexts","kind":"article","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"New symbol documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"],"generated":true,"anchor":"New-symbol-documentation"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title","value":"HioImageWrapper"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments","value":[{"kind":"identifier","text":"HioImageWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle","value":[{"text":"HioImageWrapper","kind":"identifier"}]}]}]}