{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftusd\/dereferencingpointers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/swiftusd\/dereferencingpointers"]}],"seeAlsoSections":[{"anchor":"New-symbol-documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"],"generated":true,"title":"New symbol documentation"}],"abstract":[{"text":"Safely dereferencing ","type":"text"},{"code":"pxr.TfRefPtr","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"pxr.TfWeakPtr","type":"codeVoice"},{"text":" in Swift","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"topicSections":[{"anchor":"Topics","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/Dereference(_:)-67vpz","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/Dereference(_:)-3edgv","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/Dereference(_:)-6tke1","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/Dereference(_:)-4h0lb","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/DereferenceOrNil(_:)-4yt4i","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/DereferenceOrNil(_:)-5pwch","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/DereferenceOrNil(_:)-6ehce","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/DereferenceOrNil(_:)-34drv"],"abstract":[{"type":"text","text":"In Swift, these functions live under "},{"type":"codeVoice","code":"Overlay"},{"type":"text","text":"."}]}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"Overview","text":"Overview","type":"heading"},{"inlineContent":[{"type":"text","text":"Using Swift interop, the compiler automatically generates "},{"type":"codeVoice","code":"pointee"},{"type":"text","text":" properties for "},{"type":"codeVoice","code":"pxr.TfRefPtr"},{"type":"text","text":" and "},{"type":"codeVoice","code":"pxr.TfWeakPtr"},{"type":"text","text":". However, these properties are unavailable."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This Swift Package provides workarounds in the form of "},{"type":"codeVoice","code":"Overlay.Dereference(_:)"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"For more information, see "},{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WhatIsAForeignReferenceType"},{"type":"text","text":" and "},{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ForeignReferenceTypesAndSmartPointers"}],"type":"paragraph"}]}],"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers"},"sections":[],"metadata":{"role":"collectionGroup","modules":[{"name":"OpenUSD"}],"roleHeading":"API Collection","title":"Dereferencing pointers"},"references":{"doc://SwiftUsd/documentation/SwiftUsd/WhatIsAForeignReferenceType":{"title":"What is a Foreign Reference Type?","url":"\/documentation\/swiftusd\/whatisaforeignreferencetype","abstract":[{"text":"Learn about foreign reference types and how to use them","type":"text"}],"role":"article","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WhatIsAForeignReferenceType","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/DereferenceOrNil(_:)-5pwch":{"abstract":[{"text":"Dereferences a ","type":"text"},{"code":"pxr::TfWeakPtr<T>","type":"codeVoice"},{"text":", returning either ","type":"text"},{"code":"T","type":"codeVoice"},{"text":" (held strongly) or ","type":"text"},{"code":"nil","type":"codeVoice"}],"url":"\/documentation\/openusd\/c++\/overlay\/dereferenceornil(_:)-5pwch","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/DereferenceOrNil(_:)-5pwch","title":"DereferenceOrNil(_:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DereferenceOrNil","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE16DereferenceOrNily15_TfWeakBaseTypeQzSgxAbCE01_gH11PtrProtocolRzlFZ1TL_xmfp","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE16DereferenceOrNily15_TfWeakBaseTypeQzSgxAbCE01_gH11PtrProtocolRzlFZ1TL_xmfp","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"_TfWeakBaseType","preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfWeakPtrProtocolP01_dE8BaseTypeQa","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://SwiftUsd/documentation/SwiftUsd/TypeConversion":{"role":"collectionGroup","title":"Type conversion","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion","type":"topic","url":"\/documentation\/swiftusd\/typeconversion","abstract":[],"kind":"article"},"doc://SwiftUsd/documentation/SwiftUsd/CreatingPointers":{"type":"topic","title":"Creating pointers","url":"\/documentation\/swiftusd\/creatingpointers","role":"collectionGroup","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","abstract":[{"type":"text","text":"Creating "},{"type":"codeVoice","code":"pxr.TfRefPtr"},{"type":"text","text":" and "},{"type":"codeVoice","code":"pxr.TfWeakPtr"},{"type":"text","text":" in Swift"}],"kind":"article"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/Dereference(_:)-67vpz":{"kind":"symbol","abstract":[{"text":"Dereferences a ","type":"text"},{"code":"pxr::TfRefPtr<T>","type":"codeVoice"},{"text":". Crashes if the pointer is null","type":"text"}],"role":"symbol","type":"topic","title":"Dereference(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/Dereference(_:)-67vpz","url":"\/documentation\/openusd\/c++\/overlay\/dereference(_:)-67vpz","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Dereference","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE11Dereferencey14_TfRefBaseTypeQzxAbCE01_eF11PtrProtocolRzlFZ1TL_xmfp","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE11Dereferencey14_TfRefBaseTypeQzxAbCE01_eF11PtrProtocolRzlFZ1TL_xmfp","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"_TfRefBaseType","preciseIdentifier":"s:So7OverlayO7OpenUSDE17_TfRefPtrProtocolP01_dE8BaseTypeQa","kind":"typeIdentifier"}]},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfNotice":{"abstract":[{"text":"Learn how to use the TfNotice notification subsystem in Swift","type":"text"}],"url":"\/documentation\/swiftusd\/workingwithtfnotice","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","kind":"article","title":"Working with TfNotice","role":"article"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfErrorMark":{"role":"article","title":"Working with TfErrorMark","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","type":"topic","url":"\/documentation\/swiftusd\/workingwithtferrormark","abstract":[{"type":"text","text":"Learn how to use TfErrorMark in Swift"}],"kind":"article"},"doc://SwiftUsd/documentation/SwiftUsd/CheckingForValidity":{"abstract":[{"text":"Checking for ","type":"text"},{"code":"IsValid()","type":"codeVoice"},{"text":" and null pointers in Swift","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","kind":"article","type":"topic","url":"\/documentation\/swiftusd\/checkingforvalidity","title":"Checking for validity","role":"article"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/DereferenceOrNil(_:)-34drv":{"url":"\/documentation\/openusd\/c++\/overlay\/dereferenceornil(_:)-34drv","kind":"symbol","title":"DereferenceOrNil(_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DereferenceOrNil","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE16DereferenceOrNily15_TfWeakBaseTypeQzSgxAbCE01_g5ConstH11PtrProtocolRzlFZ1TL_xmfp","text":"T","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE16DereferenceOrNily15_TfWeakBaseTypeQzSgxAbCE01_g5ConstH11PtrProtocolRzlFZ1TL_xmfp","text":"T","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE23_TfConstWeakPtrProtocolP01_dF8BaseTypeQa","text":"_TfWeakBaseType","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Dereferences a "},{"type":"codeVoice","code":"pxr::TfWeakPtr<const T>"},{"type":"text","text":", returning either "},{"type":"codeVoice","code":"T"},{"type":"text","text":" (without const qualification) or "},{"type":"codeVoice","code":"nil"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/DereferenceOrNil(_:)-34drv"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/DereferenceOrNil(_:)-4yt4i":{"title":"DereferenceOrNil(_:)","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/DereferenceOrNil(_:)-4yt4i","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"DereferenceOrNil"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE16DereferenceOrNily14_TfRefBaseTypeQzSgxAbCE01_gH11PtrProtocolRzlFZ1TL_xmfp","text":"T"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE16DereferenceOrNily14_TfRefBaseTypeQzSgxAbCE01_gH11PtrProtocolRzlFZ1TL_xmfp","text":"T"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE17_TfRefPtrProtocolP01_dE8BaseTypeQa","text":"_TfRefBaseType"},{"kind":"text","text":"?"}],"url":"\/documentation\/openusd\/c++\/overlay\/dereferenceornil(_:)-4yt4i","abstract":[{"text":"Dereferences a ","type":"text"},{"code":"pxr::TfRefPtr<T>","type":"codeVoice"},{"text":", returning either ","type":"text"},{"code":"T","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"nil","type":"codeVoice"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/Dereference(_:)-4h0lb":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/Dereference(_:)-4h0lb","role":"symbol","title":"Dereference(_:)","url":"\/documentation\/openusd\/c++\/overlay\/dereference(_:)-4h0lb","type":"topic","abstract":[{"text":"Dereferences a ","type":"text"},{"code":"pxr::TfWeakPtr<const T>","type":"codeVoice"},{"text":". Crashes if the pointer is null","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Dereference","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE11Dereferencey15_TfWeakBaseTypeQzxAbCE01_e5ConstF11PtrProtocolRzlFZ1TL_xmfp","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE11Dereferencey15_TfWeakBaseTypeQzxAbCE01_e5ConstF11PtrProtocolRzlFZ1TL_xmfp","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"_TfWeakBaseType","preciseIdentifier":"s:So7OverlayO7OpenUSDE23_TfConstWeakPtrProtocolP01_dF8BaseTypeQa","kind":"typeIdentifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/DereferenceOrNil(_:)-6ehce":{"title":"DereferenceOrNil(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/DereferenceOrNil(_:)-6ehce","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"DereferenceOrNil"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE16DereferenceOrNily14_TfRefBaseTypeQzSgxAbCE01_g5ConstH11PtrProtocolRzlFZ1TL_xmfp","text":"T"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE16DereferenceOrNily14_TfRefBaseTypeQzSgxAbCE01_g5ConstH11PtrProtocolRzlFZ1TL_xmfp","text":"T"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:So7OverlayO7OpenUSDE22_TfConstRefPtrProtocolP01_dF8BaseTypeQa","text":"_TfRefBaseType"},{"kind":"text","text":"?"}],"abstract":[{"text":"Dereferences a ","type":"text"},{"code":"pxr::TfRefPtr<const T>","type":"codeVoice"},{"text":", returning either ","type":"text"},{"code":"T","type":"codeVoice"},{"text":" (without const qualification) or ","type":"text"},{"code":"nil","type":"codeVoice"}],"url":"\/documentation\/openusd\/c++\/overlay\/dereferenceornil(_:)-6ehce"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","abstract":[],"type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/ForeignReferenceTypesAndSmartPointers":{"abstract":[{"text":"Learn about ","type":"text"},{"code":"pxr::TfRefPtr","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"pxr::TfWeakPtr","type":"codeVoice"},{"text":" in Swift","type":"text"}],"url":"\/documentation\/swiftusd\/foreignreferencetypesandsmartpointers","kind":"article","type":"topic","title":"Foreign Reference Types and Smart Pointers","role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ForeignReferenceTypesAndSmartPointers"},"doc://SwiftUsd/documentation/SwiftUsd/UsingEditContexts":{"type":"topic","url":"\/documentation\/swiftusd\/usingeditcontexts","title":"Using edit contexts","role":"collectionGroup","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","abstract":[{"type":"text","text":"Using "},{"code":"pxr.UsdEditContext","type":"codeVoice"},{"type":"text","text":" in Swift"}],"kind":"article"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/Dereference(_:)-3edgv":{"kind":"symbol","abstract":[{"text":"Dereferences a ","type":"text"},{"code":"pxr::TfWeakPtr<T>","type":"codeVoice"},{"text":". Crashes if the pointer is null","type":"text"}],"role":"symbol","type":"topic","title":"Dereference(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/Dereference(_:)-3edgv","url":"\/documentation\/openusd\/c++\/overlay\/dereference(_:)-3edgv","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Dereference","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE11Dereferencey15_TfWeakBaseTypeQzxAbCE01_eF11PtrProtocolRzlFZ1TL_xmfp","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE11Dereferencey15_TfWeakBaseTypeQzxAbCE01_eF11PtrProtocolRzlFZ1TL_xmfp","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"_TfWeakBaseType","preciseIdentifier":"s:So7OverlayO7OpenUSDE18_TfWeakPtrProtocolP01_dE8BaseTypeQa","kind":"typeIdentifier"}]},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfDiagnosticFacilities":{"role":"collectionGroup","title":"Working with Tf Diagnostic Facilities","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","type":"topic","url":"\/documentation\/swiftusd\/workingwithtfdiagnosticfacilities","abstract":[{"type":"text","text":"Learn how to use the Tf diagnostic facilities in Swift"}],"kind":"article"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/Dereference(_:)-6tke1":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/Dereference(_:)-6tke1","role":"symbol","title":"Dereference(_:)","url":"\/documentation\/openusd\/c++\/overlay\/dereference(_:)-6tke1","type":"topic","abstract":[{"text":"Dereferences a ","type":"text"},{"code":"pxr::TfRefPtr<const T>","type":"codeVoice"},{"text":". Crashes if the pointer is null","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Dereference","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE11Dereferencey14_TfRefBaseTypeQzxAbCE01_e5ConstF11PtrProtocolRzlFZ1TL_xmfp","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE11Dereferencey14_TfRefBaseTypeQzxAbCE01_e5ConstF11PtrProtocolRzlFZ1TL_xmfp","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"_TfRefBaseType","preciseIdentifier":"s:So7OverlayO7OpenUSDE22_TfConstRefPtrProtocolP01_dF8BaseTypeQa","kind":"typeIdentifier"}]},"doc://SwiftUsd/documentation/SwiftUsd/ConvenientExtensions":{"url":"\/documentation\/swiftusd\/convenientextensions","role":"collectionGroup","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","title":"Convenient extensions","type":"topic","kind":"article","abstract":[{"type":"text","text":"Extensions that make OpenUSD nicer to use in Swift"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"New-symbol-documentation","title":"New symbol documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"],"generated":true}]}]}]}