{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DetectingOpenUSDFeatureFlags","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Learn how to detect OpenUSD feature flags"}],"kind":"article","seeAlsoSections":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/BuildingLocally","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangesToOpenUSD"],"generated":true,"title":"Technical details","anchor":"Technical-details"}],"variants":[{"paths":["\/documentation\/swiftusd\/detectingopenusdfeatureflags"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/detectingopenusdfeatureflags"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"type":"heading","anchor":"Overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"SwiftUsd comes with a pre-built version of OpenUSD, but it supports creating Swift Packages from existing OpenUSD builds, including builds with different OpenUSD feature flags. For example, OpenUSD might be built without imaging support, or with OpenVDB support. To write code that supports different feature flag sets (or handles incompatible feature flag sets gracefully), use these techniques."}]},{"level":2,"type":"heading","anchor":"Supported-feature-flags","text":"Supported feature flags:"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Alembic plugin ("},{"type":"codeVoice","code":"ALEMBIC"},{"type":"text","text":"): "},{"type":"codeVoice","code":"--alembic"},{"type":"text","text":", "},{"type":"codeVoice","code":"--no-alembic"}]}]},{"content":[{"inlineContent":[{"text":"Draco plugin (","type":"text"},{"type":"codeVoice","code":"DRACO"},{"text":"): ","type":"text"},{"type":"codeVoice","code":"--draco"},{"text":", ","type":"text"},{"type":"codeVoice","code":"--no-draco"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Embree plugin ("},{"code":"EMBREE","type":"codeVoice"},{"type":"text","text":"): "},{"code":"--embree","type":"codeVoice"},{"type":"text","text":", "},{"code":"--no-embree","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"OpenColorIO plugin ("},{"code":"OPENCOLORIO","type":"codeVoice"},{"type":"text","text":"): "},{"code":"--opencolorio","type":"codeVoice"},{"type":"text","text":", "},{"code":"--no-opencolorio","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"OpenImageIO plugin ("},{"code":"OPENIMAGEIO","type":"codeVoice"},{"type":"text","text":"): "},{"code":"--openimageio","type":"codeVoice"},{"type":"text","text":", "},{"code":"--no-openimageio","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"RenderMan plugin (","type":"text"},{"code":"PRMAN","type":"codeVoice"},{"text":"): ","type":"text"},{"code":"--prman","type":"codeVoice"},{"text":", ","type":"text"},{"code":"--no-prman","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Imaging component (","type":"text"},{"code":"IMAGING","type":"codeVoice"},{"text":"): ","type":"text"},{"code":"--imaging","type":"codeVoice"},{"text":", ","type":"text"},{"code":"--no-imaging","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"UsdImaging component ("},{"code":"USD_IMAGING","type":"codeVoice"},{"type":"text","text":"): "},{"code":"--usd-imaging","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MaterialX support ("},{"type":"codeVoice","code":"MATERIALX"},{"type":"text","text":"): "},{"type":"codeVoice","code":"--materialx"},{"type":"text","text":", "},{"type":"codeVoice","code":"--no-materialx"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"OpenVDB support (","type":"text"},{"code":"OPENVDB","type":"codeVoice"},{"text":"): ","type":"text"},{"code":"--openvdb","type":"codeVoice"},{"text":", ","type":"text"},{"code":"--no-openvdb","type":"codeVoice"}]}]},{"content":[{"inlineContent":[{"text":"Ptex support (","type":"text"},{"type":"codeVoice","code":"PTEX"},{"text":"): ","type":"text"},{"type":"codeVoice","code":"--ptex"},{"text":", ","type":"text"},{"type":"codeVoice","code":"--no-ptex"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Python support ("},{"type":"codeVoice","code":"PYTHON"},{"type":"text","text":"): "},{"type":"codeVoice","code":"--python"},{"type":"text","text":", "},{"type":"codeVoice","code":"--no-python"}],"type":"paragraph"}]}]},{"level":2,"type":"heading","anchor":"Detecting-feature-flags-in-Swift","text":"Detecting feature flags in Swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can detect OpenUSD feature flags at compile time by using "},{"code":"#if canImport(SwiftUsd_PXR_ENABLE_<flag>_SUPPORT)","type":"codeVoice"},{"type":"text","text":". For example,"}]},{"code":["#if canImport(SwiftUsd_PXR_ENABLE_OPENVDB_SUPPORT)","\/\/ Compiled when SwiftUsd is based on an OpenUSD build with OpenVDB","#else","\/\/ Compiled when SwiftUsd is based on an OpenUSD build without OpenVDB","#endif","","#if !canImport(SwiftUsd_PXR_ENABLE_USD_IMAGING_SUPPORT)","\/\/ Compiled when SwiftUsd is based on an OpenUSD build without UsdImaging","#else","\/\/ Compiled when SwiftUsd is based on an OpenUSD build with UsdImaging","#endif"],"type":"codeListing","syntax":"swift"},{"level":2,"type":"heading","anchor":"Detecting-feature-flags-in-C++","text":"Detecting feature flags in C++"},{"type":"paragraph","inlineContent":[{"text":"You can detect OpenUSD feature flags at compile time by using ","type":"text"},{"code":"#if SwiftUsd_PXR_ENABLE_<FLAG>_SUPPORT","type":"codeVoice"},{"text":". For example,","type":"text"}]},{"code":["#include \"swiftUsd\/swiftUsd.h\"","","#if SwiftUsd_PXR_ENABLE_OPENVDB_SUPPORT","\/\/ Compiled when SwiftUsd is based on an OpenUSD build with OpenVDB","#else","\/\/ Compiled when SwiftUsd is based on an OpenUSD build without OpenVDB","#endif","","#if !SwiftUsd_PXR_ENABLE_USD_IMAGING_SUPPORT","\/\/ Compiled when SwiftUsd is based on an OpenUSD build without UsdImaging","#else","\/\/ Compiled when SwiftUsd is based on an OpenUSD build with UsdImaging","#endif"],"type":"codeListing","syntax":"c++"}]}],"sections":[],"metadata":{"modules":[{"name":"OpenUSD"}],"role":"article","roleHeading":"Article","title":"Detecting OpenUSD feature flags"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"references":{"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol"},"doc://SwiftUsd/documentation/SwiftUsd/BuildingLocally":{"abstract":[{"text":"Learn how to use SwiftUsd with local\/existing OpenUSD binaries","type":"text"}],"type":"topic","url":"\/documentation\/swiftusd\/buildinglocally","role":"article","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/BuildingLocally","title":"Building locally"},"doc://SwiftUsd/documentation/SwiftUsd/ChangesToOpenUSD":{"abstract":[{"text":"Learn about the changes this Swift Package makes to OpenUSD","type":"text"}],"type":"topic","url":"\/documentation\/swiftusd\/changestoopenusd","role":"article","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangesToOpenUSD","title":"Changes to OpenUSD"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Technical details","anchor":"Technical-details","generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/BuildingLocally","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangesToOpenUSD"]}]}],"traits":[{"interfaceLanguage":"occ"}]}]}