{"schemaVersion":{"minor":3,"patch":0,"major":0},"seeAlsoSections":[{"title":"About this repo","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangeLog","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UpgradeChecklist","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ReleaseChecklist"],"anchor":"About-this-repo","generated":true}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","text":"Links:","level":3,"anchor":"Links"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Github repo: ","type":"text"},{"identifier":"https:\/\/github.com\/apple\/SwiftUsd","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Repo documentation: ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/apple.github.io\/SwiftUsd\/documentation\/openusd\/"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"OpenUSD: "},{"type":"reference","identifier":"https:\/\/openusd.org\/release\/index.html","isActive":true}]}]},{"content":[{"inlineContent":[{"text":"C++ documentation: ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/openusd.org\/release\/api\/index.html"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"SwiftUsd-Tests: "},{"type":"reference","identifier":"https:\/\/github.com\/apple\/SwiftUsd-Tests","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"SwiftUsd-ast-answerer: "},{"type":"reference","identifier":"https:\/\/github.com\/apple\/SwiftUsd-ast-answerer","isActive":true}],"type":"paragraph"}]}]},{"type":"heading","text":"Repo structure","level":3,"anchor":"Repo-structure"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"SwiftUsd\/.build"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"Swift Package Manager build directory from running "},{"type":"codeVoice","code":".\/scripts\/build_symbol_graphs.zsh"},{"type":"text","text":". Only needed by advanced users. Not tracked by git."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"SwiftUsd\/.spi.yml"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"Swift Package Index Manifest file."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"SwiftUsd\/.symbol-graphs"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"Symbol graph directory from running "},{"type":"codeVoice","code":".\/scripts\/build_symbol_graphs.zsh"},{"type":"text","text":". Only needed by advanced users. Not tracked by git."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"SwiftUsd\/ACKNOWLEDGEMENTS"},{"type":"text","text":" "},{"type":"text","text":"Acknowledgements file."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"SwiftUsd\/CONTRIBUTING.md"},{"type":"text","text":" "},{"type":"text","text":"Contributing guildlines"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"SwiftUsd\/docs"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"Online documentation for GitHub. See "},{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet#Documentation","overridingTitle":"the cheatsheet","overridingTitleInlineContent":[{"text":"the cheatsheet","type":"text"}]},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"SwiftUsd\/Examples","type":"codeVoice"},{"text":"","type":"text"},{"text":"\n","type":"text"},{"text":"Example code\/projects","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"SwiftUsd\/extraArgs.txt"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"Extra command line arguments to use when building a Swift Package\/Xcode project from the command line that has a dependnecy on SwiftUsd. This file is automatically generated by "},{"type":"codeVoice","code":"scripts\/make-swift-package"},{"type":"text","text":" and should not be edited by hand."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"SwiftUsd\/LICENSE"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"License file."}]}]},{"content":[{"inlineContent":[{"code":"SwiftUsd\/NOTICE","type":"codeVoice"},{"text":" ","type":"text"},{"text":"Notice file.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"SwiftUsd\/openusd-builds"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"Parent build directory for builds of the core C++ OpenUSD repo. Only needed by advanced users. Not tracked by git."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"SwiftUsd\/openusd-patch.patch","type":"codeVoice"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"The patch file applied to OpenUSD before building the core C++ libraries. See "},{"type":"reference","overridingTitle":"the cheatsheet","isActive":true,"overridingTitleInlineContent":[{"type":"text","text":"the cheatsheet"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet#Patches"},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"SwiftUsd\/openusd-source"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"Source code for the core C++ OpenUSD repo, slightly modified by "},{"type":"codeVoice","code":"SwiftUsd\/openusd-patch.patch"},{"type":"text","text":"to build for Swift-Cxx interop. Only needed by advanced users. Not tracked by git."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"SwiftUsd\/Package.resolved"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"Package resolution file from running "},{"type":"codeVoice","code":".\/scripts\/build_symbol_graphs.zsh"},{"type":"text","text":". Only needed by advanced users. Not tracked by git."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"SwiftUsd\/Package.swift","type":"codeVoice"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"Package manifest file for the "},{"code":"SwiftUsd","type":"codeVoice"},{"type":"text","text":" Swift Package. This file is automatically generated by "},{"code":"scripts\/make-swift-package","type":"codeVoice"},{"type":"text","text":" and should not be edited by hand."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"SwiftUsd\/README.md"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"Landing page for GitHub."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"SwiftUsd\/scripts"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"Parent directory for utility scripts used while maintaining "},{"type":"codeVoice","code":"SwiftUsd"},{"type":"text","text":". Only needed by advanced users."}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"SwiftUsd\/scripts\/docc"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"Parent directory for documentation scripts. See "},{"overridingTitle":"the cheatsheet","overridingTitleInlineContent":[{"type":"text","text":"the cheatsheet"}],"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet#Documentation"},{"type":"text","text":" for more information."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"SwiftUsd\/scripts\/make-swift-package.zsh","type":"codeVoice"},{"text":" ","type":"text"},{"text":"Helper script that invokes make-swift-package.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"SwiftUsd\/scripts\/make-swift-package","type":"codeVoice"},{"text":"","type":"text"},{"text":"\n","type":"text"},{"text":"Script that sets up the Swift Package in ","type":"text"},{"code":"SwiftUsd","type":"codeVoice"},{"text":" with a package manifest, headers, pre-built OpenUSD binaries, and sources. See ","type":"text"},{"overridingTitleInlineContent":[{"type":"text","text":"building locally"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/BuildingLocally","isActive":true,"type":"reference","overridingTitle":"building locally"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"SwiftUsd\/scripts\/patch-exploder.py"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"Script that explodes a unified diff into one file per file in the diff."}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"SwiftUsd\/SECURITY.md"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"Security disclosure file."}]}]},{"content":[{"inlineContent":[{"code":"SwiftUsd\/source","type":"codeVoice"},{"text":"","type":"text"},{"text":"\n","type":"text"},{"text":"Parent directory for the Swift bindings for ","type":"text"},{"code":"SwiftUsd","type":"codeVoice"},{"text":". (The “source-of-truth” for the source code and resources provided by this package)","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"code":"SwiftUsd\/source\/Package.swift.in","type":"codeVoice"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"The template for the package manifest file "},{"code":"SwiftUsd\/Package.swift","type":"codeVoice"},{"type":"text","text":". This file may be edited by hand."}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"SwiftUsd\/swift-package"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"Parent directory for the file system structure expected by Swift Package Manager. This directory is created by "},{"type":"codeVoice","code":"SwiftUsd\/scripts\/make-swift-package"},{"type":"text","text":", and is "},{"type":"strong","inlineContent":[{"type":"text","text":"not"}]},{"type":"text","text":" the “source-of-truth” for any source code, resources, or binaries provided by this package. "},{"type":"strong","inlineContent":[{"type":"text","text":"Manual changes made to this directory will be lost"}]},{"type":"text","text":"."}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"code":"SwiftUsd\/swift-package\/Sources","type":"codeVoice"},{"text":"","type":"text"},{"text":"\n","type":"text"},{"text":"The SPM ","type":"text"},{"code":"Sources","type":"codeVoice"},{"text":" directory.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"SwiftUsd\/swift-package\/XCFrameworks","type":"codeVoice"},{"text":"","type":"text"},{"text":"\n","type":"text"},{"text":"Parent directory for the XCFrameworks created by ","type":"text"},{"code":"SwiftUsd\/scripts\/make-swift-package","type":"codeVoice"},{"text":".","type":"text"}]}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"SwiftUsd\/SwiftUsd.docc"},{"text":"","type":"text"},{"text":"\n","type":"text"},{"text":"Documentation catalog for ","type":"text"},{"type":"codeVoice","code":"SwiftUsd"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"SwiftUsd\/SwiftUsd.doccarchive","type":"codeVoice"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"Swift DocC archive, for local viewing in Xcode. See "},{"overridingTitle":"the cheatsheet","overridingTitleInlineContent":[{"text":"the cheatsheet","type":"text"}],"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet#Documentation","isActive":true},{"type":"text","text":"."}]}]}]}]}],"kind":"article","identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Miscellaneous","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/swiftusd\/miscellaneous"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/miscellaneous"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"Miscellaneous","role":"article","roleHeading":"Article","modules":[{"name":"OpenUSD"}]},"sections":[],"abstract":[{"text":"Miscellaneous details about this repo","type":"text"}],"references":{"doc://SwiftUsd/documentation/SwiftUsd/BuildingLocally":{"title":"Building locally","role":"article","type":"topic","kind":"article","url":"\/documentation\/swiftusd\/buildinglocally","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/BuildingLocally","abstract":[{"text":"Learn how to use SwiftUsd with local\/existing OpenUSD binaries","type":"text"}]},"https://openusd.org/release/api/index.html":{"type":"link","titleInlineContent":[{"type":"text","text":"https:\/\/openusd.org\/release\/api\/index.html"}],"url":"https:\/\/openusd.org\/release\/api\/index.html","title":"https:\/\/openusd.org\/release\/api\/index.html","identifier":"https:\/\/openusd.org\/release\/api\/index.html"},"doc://SwiftUsd/documentation/OpenUSD":{"url":"\/documentation\/openusd","kind":"symbol","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD"},"https://github.com/apple/SwiftUsd-ast-answerer":{"type":"link","title":"https:\/\/github.com\/apple\/SwiftUsd-ast-answerer","titleInlineContent":[{"text":"https:\/\/github.com\/apple\/SwiftUsd-ast-answerer","type":"text"}],"url":"https:\/\/github.com\/apple\/SwiftUsd-ast-answerer","identifier":"https:\/\/github.com\/apple\/SwiftUsd-ast-answerer"},"https://apple.github.io/SwiftUsd/documentation/openusd/":{"identifier":"https:\/\/apple.github.io\/SwiftUsd\/documentation\/openusd\/","url":"https:\/\/apple.github.io\/SwiftUsd\/documentation\/openusd\/","titleInlineContent":[{"type":"text","text":"https:\/\/apple.github.io\/SwiftUsd\/documentation\/openusd\/"}],"title":"https:\/\/apple.github.io\/SwiftUsd\/documentation\/openusd\/","type":"link"},"doc://SwiftUsd/documentation/SwiftUsd/ChangeLog":{"role":"article","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangeLog","title":"Change Log","url":"\/documentation\/swiftusd\/changelog","type":"topic","abstract":[{"text":"Changes to SwiftUsd","type":"text"}]},"doc://SwiftUsd/documentation/SwiftUsd/UpgradeChecklist":{"title":"Upgrade Checklist","role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UpgradeChecklist","abstract":[{"text":"Checklist for upgrading SwiftUsd to be based on a new OpenUSD version","type":"text"}],"kind":"article","url":"\/documentation\/swiftusd\/upgradechecklist","type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/CheatSheet":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet","kind":"article","url":"\/documentation\/swiftusd\/cheatsheet","title":"Cheat sheet","abstract":[{"type":"text","text":"Tips for advanced users modifying this repo"}],"role":"article"},"doc://SwiftUsd/documentation/SwiftUsd/ReleaseChecklist":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ReleaseChecklist","kind":"article","url":"\/documentation\/swiftusd\/releasechecklist","abstract":[{"type":"text","text":"Checklist for releasing new versions of SwiftUsd"}],"title":"Release Checklist","role":"article"},"https://openusd.org/release/index.html":{"url":"https:\/\/openusd.org\/release\/index.html","type":"link","identifier":"https:\/\/openusd.org\/release\/index.html","title":"https:\/\/openusd.org\/release\/index.html","titleInlineContent":[{"type":"text","text":"https:\/\/openusd.org\/release\/index.html"}]},"https://github.com/apple/SwiftUsd":{"type":"link","titleInlineContent":[{"type":"text","text":"https:\/\/github.com\/apple\/SwiftUsd"}],"url":"https:\/\/github.com\/apple\/SwiftUsd","title":"https:\/\/github.com\/apple\/SwiftUsd","identifier":"https:\/\/github.com\/apple\/SwiftUsd"},"https://github.com/apple/SwiftUsd-Tests":{"url":"https:\/\/github.com\/apple\/SwiftUsd-Tests","type":"link","identifier":"https:\/\/github.com\/apple\/SwiftUsd-Tests","title":"https:\/\/github.com\/apple\/SwiftUsd-Tests","titleInlineContent":[{"type":"text","text":"https:\/\/github.com\/apple\/SwiftUsd-Tests"}]},"doc://SwiftUsd/documentation/SwiftUsd/CheatSheet#Patches":{"type":"topic","kind":"section","url":"\/documentation\/swiftusd\/cheatsheet#Patches","title":"Patches","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet#Patches"},"doc://SwiftUsd/documentation/SwiftUsd/OngoingWork":{"kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork","role":"article","abstract":[{"text":"In-progress and future tasks for improving OpenUSD in Swift","type":"text"}],"url":"\/documentation\/swiftusd\/ongoingwork","type":"topic","title":"Ongoing Work"},"doc://SwiftUsd/documentation/SwiftUsd/CheatSheet#Documentation":{"type":"topic","abstract":[],"kind":"section","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet#Documentation","title":"Documentation","url":"\/documentation\/swiftusd\/cheatsheet#Documentation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","value":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangeLog","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UpgradeChecklist","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ReleaseChecklist"],"anchor":"About-this-repo","generated":true,"title":"About this repo"}],"path":"\/seeAlsoSections"}]}]}