{"abstract":[{"text":"Checklist for releasing new versions of SwiftUsd","type":"text"}],"sections":[],"metadata":{"roleHeading":"Article","modules":[{"name":"OpenUSD"}],"title":"Release Checklist","role":"article"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"primaryContentSections":[{"kind":"content","content":[{"anchor":"1-Decide-on-a-new-SwiftUsd-version-number","text":"1. Decide on a new SwiftUsd version number","type":"heading","level":2},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If creating a new major version, make sure all small source-breaking changes are done"}]}]}]},{"anchor":"2-If-OpenUSD-was-changed","text":"2. If OpenUSD was changed","type":"heading","level":2},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"overridingTitle":"Rebuild OpenUSD","overridingTitleInlineContent":[{"text":"Rebuild OpenUSD","type":"text"}],"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/BuildingLocally","type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"overridingTitle":"Generate a new openusd-patch.patch","overridingTitleInlineContent":[{"text":"Generate a new ","type":"text"},{"code":"openusd-patch.patch","type":"codeVoice"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet#Generating-a-new-patch","type":"reference","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet#Comparing-the-differences-between-an-old-patch-and-a-new-patch","isActive":true,"overridingTitle":"Compare changes to the patch","overridingTitleInlineContent":[{"text":"Compare changes to the patch","type":"text"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Move the patch to ","type":"text"},{"code":"SwiftUsd\/openusd-patch.patch","type":"codeVoice"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Update "},{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangesToOpenUSD","overridingTitle":"Changes to OpenUSD","overridingTitleInlineContent":[{"type":"text","text":"Changes to OpenUSD"}]}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Remove ","type":"text"},{"type":"codeVoice","code":"swift-package"},{"type":"text","text":" and run "},{"type":"codeVoice","code":".\/scripts\/make-swift-package.py openusd-builds\/macOS openusd-builds\/iOS"}]}]}]},{"anchor":"3-If-ast-answerer-was-changed","text":"3. If ast-answerer was changed","type":"heading","level":2},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Run "},{"type":"codeVoice","code":"ast-answerer\/analysis_change.py"},{"type":"text","text":" and look at the differences in the analysis outputs"}]}]}]},{"anchor":"4-If-source-files-have-been-added-or-removed","text":"4. If source files have been added or removed","type":"heading","level":2},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Remove "},{"type":"codeVoice","code":"swift-package"},{"type":"text","text":" and run "},{"type":"codeVoice","code":"python3 scripts\/make-swift-package.py"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add to "},{"type":"codeVoice","code":"swiftUsd.h"},{"type":"text","text":" umbrella header"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Review changes via ","type":"text"},{"code":"git status","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"git diff","type":"codeVoice"}]}]}]},{"anchor":"5-Testing","text":"5. Testing","type":"heading","level":2},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add tests for all added, changed, deprecated API"}]}]},{"content":[{"inlineContent":[{"text":"Run ","type":"text"},{"code":"SwiftUsdTests","type":"codeVoice"},{"text":" in Release mode on current compiler","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Run "},{"type":"codeVoice","code":"SwiftUsdTests"},{"type":"text","text":" in Debug mode on current compiler"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Run "},{"type":"codeVoice","code":"SwiftUsdTests"},{"type":"text","text":" in Release mode on pre-release compiler"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Run "},{"type":"codeVoice","code":"SwiftUsdTests"},{"type":"text","text":" in Debug mode on pre-release compiler"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"If major changes have been made, test all sample projects","type":"text"}],"type":"paragraph"}]}]},{"anchor":"6-Documentation-manual","text":"6. Documentation, manual","type":"heading","level":2},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Update versions:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"text":"OpenUSD","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"overridingTitle":"Getting Started","isActive":true,"overridingTitleInlineContent":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted","type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/BuildingLocally","isActive":true,"type":"reference","overridingTitleInlineContent":[{"text":"Building Locally","type":"text"}],"overridingTitle":"Building Locally"}]}]}],"type":"orderedList"}]},{"content":[{"inlineContent":[{"type":"text","text":"Pixar namespace"}],"type":"paragraph"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted#Using-SwiftUsd","type":"reference","isActive":true,"overridingTitle":"Getting Started, “Using SwiftUsd”","overridingTitleInlineContent":[{"text":"Getting Started, “Using SwiftUsd”","type":"text"}]}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted#Common-issues","isActive":true,"overridingTitle":"Getting Started, “Common Issues”","overridingTitleInlineContent":[{"text":"Getting Started, “Common Issues”","type":"text"}]}],"type":"paragraph"}]}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Xcode, OS"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"overridingTitle":"Getting Started","type":"reference","overridingTitleInlineContent":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted","isActive":true},{"type":"text","text":". Include build numbers as well"}]}]}],"type":"orderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"SwiftUsd","type":"text"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"README.md, “Swift Package”"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted#Swift-Package","overridingTitle":"Getting Started, “Swift Package”","overridingTitleInlineContent":[{"type":"text","text":"Getting Started, “Swift Package”"}],"type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"make-spm-tests.py in SwiftUsdTests"}]}]}]}]}],"type":"orderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"If files have been added or removed, update ","type":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Miscellaneous#Repo-structure","isActive":true,"overridingTitle":"Miscellaneous, “Repo structure”","type":"reference","overridingTitleInlineContent":[{"type":"text","text":"Miscellaneous, “Repo structure”"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Update "},{"overridingTitleInlineContent":[{"text":"Ongoing Work","type":"text"}],"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork","isActive":true,"overridingTitle":"Ongoing Work"}]}]},{"content":[{"inlineContent":[{"text":"Update the ","type":"text"},{"overridingTitle":"Change Log","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangeLog","overridingTitleInlineContent":[{"type":"text","text":"Change Log"}],"type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Review changes via ","type":"text"},{"code":"git status","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"git diff","type":"codeVoice"}]}]}]},{"anchor":"7-Documentation-pipeline","text":"7. Documentation, pipeline","type":"heading","level":2},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet#Building-documentation","isActive":true,"overridingTitleInlineContent":[{"text":"Build documentation","type":"text"}],"type":"reference","overridingTitle":"Build documentation"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"overridingTitleInlineContent":[{"type":"text","text":"Preview documentation"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet#Previewing-documentation","type":"reference","isActive":true,"overridingTitle":"Preview documentation"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"There should be no warnings when previewing documentation","type":"text"}]}]}]}]},{"content":[{"inlineContent":[{"type":"reference","overridingTitleInlineContent":[{"text":"Publish documentation","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet#Publishing-documentation","isActive":true,"overridingTitle":"Publish documentation"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Review changes via ","type":"text"},{"code":"git status","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"git diff","type":"codeVoice"}]}]}]},{"anchor":"8-Final-steps","text":"8. Final steps","type":"heading","level":2},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Review changes to "},{"code":"SwiftUsdTests","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Review changes to ","type":"text"},{"code":"ast-answerer","type":"codeVoice"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Commit changes to "},{"type":"codeVoice","code":"SwiftUsd"},{"type":"text","text":", "},{"type":"codeVoice","code":"SwiftUsdTests"},{"type":"text","text":", "},{"type":"codeVoice","code":"ast-answerer"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Add git tag","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Push commit and tag to remote","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Push "},{"code":"SwiftUsdTests","type":"codeVoice"},{"type":"text","text":", "},{"code":"ast-answerer","type":"codeVoice"},{"type":"text","text":" to remote"}]}]}]}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangeLog","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UpgradeChecklist","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Miscellaneous"],"title":"About this repo","generated":true,"anchor":"About-this-repo"}],"variants":[{"paths":["\/documentation\/swiftusd\/releasechecklist"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/releasechecklist"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ReleaseChecklist"},"references":{"doc://SwiftUsd/documentation/SwiftUsd/OngoingWork":{"url":"\/documentation\/swiftusd\/ongoingwork","abstract":[{"type":"text","text":"In-progress and future tasks for improving OpenUSD in Swift"}],"kind":"article","role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork","type":"topic","title":"Ongoing Work"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","abstract":[],"type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/GettingStarted#Common-issues":{"title":"Common issues","kind":"section","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted#Common-issues","url":"\/documentation\/swiftusd\/gettingstarted#Common-issues","type":"topic","abstract":[]},"doc://SwiftUsd/documentation/SwiftUsd/CheatSheet#Previewing-documentation":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet#Previewing-documentation","title":"Previewing documentation","kind":"section","url":"\/documentation\/swiftusd\/cheatsheet#Previewing-documentation","abstract":[]},"doc://SwiftUsd/documentation/SwiftUsd/CheatSheet#Building-documentation":{"title":"Building documentation","kind":"section","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet#Building-documentation","url":"\/documentation\/swiftusd\/cheatsheet#Building-documentation","type":"topic","abstract":[]},"doc://SwiftUsd/documentation/SwiftUsd/BuildingLocally":{"kind":"article","title":"Building locally","url":"\/documentation\/swiftusd\/buildinglocally","type":"topic","abstract":[{"text":"Learn how to use SwiftUsd with local\/existing OpenUSD binaries","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/BuildingLocally","role":"article"},"doc://SwiftUsd/documentation/SwiftUsd/GettingStarted":{"abstract":[{"text":"Adding SwiftUsd to your project or package","type":"text"}],"url":"\/documentation\/swiftusd\/gettingstarted","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted","kind":"article","title":"Getting Started with OpenUSD","role":"article"},"doc://SwiftUsd/documentation/SwiftUsd/ChangesToOpenUSD":{"kind":"article","title":"Changes to OpenUSD","url":"\/documentation\/swiftusd\/changestoopenusd","type":"topic","abstract":[{"text":"Learn about the changes this Swift Package makes to OpenUSD","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangesToOpenUSD","role":"article"},"doc://SwiftUsd/documentation/SwiftUsd/Miscellaneous#Repo-structure":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Miscellaneous#Repo-structure","title":"Repo structure","kind":"section","url":"\/documentation\/swiftusd\/miscellaneous#Repo-structure","abstract":[]},"doc://SwiftUsd/documentation/SwiftUsd/ChangeLog":{"abstract":[{"text":"Changes to SwiftUsd","type":"text"}],"role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangeLog","type":"topic","kind":"article","title":"Change Log","url":"\/documentation\/swiftusd\/changelog"},"doc://SwiftUsd/documentation/SwiftUsd/CheatSheet":{"title":"Cheat sheet","abstract":[{"text":"Tips for advanced users modifying this repo","type":"text"}],"kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet","url":"\/documentation\/swiftusd\/cheatsheet","role":"article","type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/Miscellaneous":{"abstract":[{"type":"text","text":"Miscellaneous details about this repo"}],"role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Miscellaneous","type":"topic","kind":"article","title":"Miscellaneous","url":"\/documentation\/swiftusd\/miscellaneous"},"doc://SwiftUsd/documentation/SwiftUsd/CheatSheet#Generating-a-new-patch":{"title":"Generating a new patch","url":"\/documentation\/swiftusd\/cheatsheet#Generating-a-new-patch","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet#Generating-a-new-patch","abstract":[],"type":"topic","kind":"section"},"doc://SwiftUsd/documentation/SwiftUsd/CheatSheet#Comparing-the-differences-between-an-old-patch-and-a-new-patch":{"title":"Comparing the differences between an old patch and a new patch","kind":"section","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet#Comparing-the-differences-between-an-old-patch-and-a-new-patch","url":"\/documentation\/swiftusd\/cheatsheet#Comparing-the-differences-between-an-old-patch-and-a-new-patch","type":"topic","abstract":[]},"doc://SwiftUsd/documentation/SwiftUsd/GettingStarted#Swift-Package":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted#Swift-Package","title":"Swift Package","kind":"section","url":"\/documentation\/swiftusd\/gettingstarted#Swift-Package","abstract":[]},"doc://SwiftUsd/documentation/SwiftUsd/UpgradeChecklist":{"abstract":[{"text":"Checklist for upgrading SwiftUsd to be based on a new OpenUSD version","type":"text"}],"role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UpgradeChecklist","type":"topic","kind":"article","title":"Upgrade Checklist","url":"\/documentation\/swiftusd\/upgradechecklist"},"doc://SwiftUsd/documentation/SwiftUsd/GettingStarted#Using-SwiftUsd":{"url":"\/documentation\/swiftusd\/gettingstarted#Using-SwiftUsd","kind":"section","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted#Using-SwiftUsd","type":"topic","title":"Using SwiftUsd"},"doc://SwiftUsd/documentation/SwiftUsd/CheatSheet#Publishing-documentation":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet#Publishing-documentation","title":"Publishing documentation","kind":"section","url":"\/documentation\/swiftusd\/cheatsheet#Publishing-documentation","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangeLog","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UpgradeChecklist","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Miscellaneous"],"generated":true,"title":"About this repo","anchor":"About-this-repo"}],"op":"replace","path":"\/seeAlsoSections"}]}]}