{"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxMacros","interfaceLanguage":"swift"},"kind":"article","abstract":[{"text":"Learn about useful Swift-Cxx macros for writing C++ code used by Swift","type":"text"}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"text":"SwiftUsd provides the standard Swift-Cxx macros from the Swift compiler, which can be found ","type":"text"},{"identifier":"https:\/\/www.swift.org\/documentation\/cxx-interop\/#list-of-customization-macros-in-swiftbridging","isActive":true,"type":"reference"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"SwiftUsd also provides macros that can make a function unavailable in Swift:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SWIFT_UNAVAILABLE","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SWIFT_UNAVAILABLE_MESSAGE"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"variants":[{"paths":["\/documentation\/swiftusd\/swiftcxxmacros"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/swiftcxxmacros"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"anchor":"Using-SwiftUsd-from-C++","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStartedInCPlusPlus","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxInteropMemorySafety"],"generated":true,"title":"Using SwiftUsd from C++"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"metadata":{"roleHeading":"Article","role":"article","modules":[{"name":"OpenUSD"}],"title":"Swift-Cxx Macros"},"sections":[],"references":{"doc://SwiftUsd/documentation/OpenUSD/SWIFT_UNAVAILABLE":{"abstract":[],"url":"\/documentation\/openusd\/swift_unavailable","role":"symbol","fragments":[{"kind":"identifier","text":"SWIFT_UNAVAILABLE"}],"title":"SWIFT_UNAVAILABLE","kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SWIFT_UNAVAILABLE"},"https://www.swift.org/documentation/cxx-interop/#list-of-customization-macros-in-swiftbridging":{"identifier":"https:\/\/www.swift.org\/documentation\/cxx-interop\/#list-of-customization-macros-in-swiftbridging","title":"here","titleInlineContent":[{"text":"here","type":"text"}],"type":"link","url":"https:\/\/www.swift.org\/documentation\/cxx-interop\/#list-of-customization-macros-in-swiftbridging"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","abstract":[],"type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/GettingStartedInCPlusPlus":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStartedInCPlusPlus","abstract":[{"type":"text","text":"Using SwiftUsd from C++"}],"role":"article","title":"Getting Started In C++","type":"topic","url":"\/documentation\/swiftusd\/gettingstartedincplusplus","kind":"article"},"doc://SwiftUsd/documentation/SwiftUsd/SwiftCxxInteropMemorySafety":{"kind":"article","abstract":[{"type":"text","text":"Learn how to avoid unsafe memory management issues when using Swift-Cxx interop"}],"role":"article","title":"Swift-Cxx Interop and Memory Safety","type":"topic","url":"\/documentation\/swiftusd\/swiftcxxinteropmemorysafety","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxInteropMemorySafety"},"doc://SwiftUsd/documentation/OpenUSD/SWIFT_UNAVAILABLE_MESSAGE":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SWIFT_UNAVAILABLE_MESSAGE","abstract":[],"role":"symbol","title":"SWIFT_UNAVAILABLE_MESSAGE","type":"topic","fragments":[{"kind":"identifier","text":"SWIFT_UNAVAILABLE_MESSAGE"}],"url":"\/documentation\/openusd\/swift_unavailable_message","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"generated":true,"title":"Using SwiftUsd from C++","anchor":"Using-SwiftUsd-from-C++","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStartedInCPlusPlus","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxInteropMemorySafety"]}],"path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}