{"kind":"article","seeAlsoSections":[{"title":"Using SwiftUsd from C++","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStartedInCPlusPlus","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxMacros"],"generated":true,"anchor":"Using-SwiftUsd-from-C++"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"variants":[{"paths":["\/documentation\/swiftusd\/swiftcxxinteropmemorysafety"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/swiftcxxinteropmemorysafety"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"OpenUSD"}],"role":"article","roleHeading":"Article","title":"Swift-Cxx Interop and Memory Safety"},"abstract":[{"type":"text","text":"Learn how to avoid unsafe memory management issues when using Swift-Cxx interop"}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxInteropMemorySafety","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"When directly moving ","type":"text"},{"code":"pxr::TfRefBase","type":"codeVoice"},{"text":" subclasses, such as ","type":"text"},{"code":"pxr::UsdStage","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"pxr::SdfLayer","type":"codeVoice"},{"text":", back and forth between Swift and C++, it is very easy to create a memory safety issue if you’re not careful. This article explains how to avoid these issues, and why they occur in the first place.","type":"text"}]},{"type":"heading","text":"The safe cases","anchor":"The-safe-cases","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"Memory safety issues only arise when moving "},{"type":"codeVoice","code":"pxr::TfRefBase"},{"type":"text","text":" subclasses back and forth between Swift and C++. When working just in C++ or just in Swift, follow these best practices to guarantee that your code is memory safe:"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When working purely in C++, C++ lifetime rules and memory management apply. In particular, C++ code should use the "},{"type":"codeVoice","code":"pxr::TfRefPtr<T>"},{"type":"text","text":" and "},{"type":"codeVoice","code":"pxr::TfWeakPtr<T>"},{"type":"text","text":" smart pointers instead of handling raw pointers, because raw pointers in C++ do not do any reference counting or memory management. For example, use "},{"type":"codeVoice","code":"pxr::TfRefPtr<pxr::UsdStage>"},{"type":"text","text":" or the equivalent typealias "},{"type":"codeVoice","code":"pxr::UsdStageRefPtr"},{"type":"text","text":", instead of using "},{"type":"codeVoice","code":"pxr::UsdStage *"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When working purely in Swift, Swift lifetime rules and memory management apply. In particular, Swift may deallocate variables sooner than expected, especially temporary values. Swift code should directly use types that derive from "},{"type":"codeVoice","code":"pxr::TfRefBase"},{"type":"text","text":" instead of using the "},{"type":"codeVoice","code":"pxr::TfRefPtr<T>"},{"type":"text","text":" and "},{"type":"codeVoice","code":"pxr::TfWeakPtr<T>"},{"type":"text","text":" smart pointers, because Swift can provide better ergonomics with "},{"type":"codeVoice","code":"pxr::TfRefBase"},{"type":"text","text":" subclasses while doing reference counting and memory management. For example, use "},{"type":"codeVoice","code":"pxr.UsdStage"},{"type":"text","text":" instead of "},{"type":"codeVoice","code":"pxr.TfRefPtr<pxr.UsdStage>"},{"type":"text","text":" or "},{"type":"codeVoice","code":"pxr.UsdStageRefPtr"},{"type":"text","text":"."}]},{"type":"heading","text":"The unsafe cases","anchor":"The-unsafe-cases","level":3},{"type":"paragraph","inlineContent":[{"text":"When a Swift function takes or returns a ","type":"text"},{"code":"pxr::TfRefBase","type":"codeVoice"},{"text":" subclass, it is exposed to C++ as taking a raw pointer:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["\/\/ Swift source code","public func takeStage(_ stage: pxr.UsdStage) { ... }","public func returnStage() -> pxr.UsdStage { ... }"]},{"type":"codeListing","syntax":"c++","code":["\/\/ Generated C++ interface","void SwiftModule::takeStage(pxr::UsdStage* _Nonnull);","pxr::UsdStage* _Nonnull SwiftModule::returnStage();"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This violates the best practices for C++, because C++ code should work with the "},{"type":"codeVoice","code":"pxr::TfRefPtr<T>"},{"type":"text","text":" and "},{"type":"codeVoice","code":"pxr::TfWeakPtr<T>"},{"type":"text","text":" smart pointers instead of raw pointers."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Similarly, when a C++ function violates C++ best practices and takes or returns a raw pointer to a "},{"type":"codeVoice","code":"pxr::TfRefBase"},{"type":"text","text":", it is imported to Swift as taking the "},{"type":"codeVoice","code":"pxr::TfRefBase"},{"type":"text","text":" directly, which can improve ergonomics for Swift:"}]},{"type":"codeListing","syntax":"c++","code":["\/\/ C++ source code","void takeStageByRawPointer(pxr::UsdStage* _Nonnull);","void takeStageBySmartPointer(pxr::TfRefPtr<pxr::UsdStage>);","pxr::UsdStage* _Nonnull returnStageByRawPointer();","pxr::TfRefPtr<pxr::UsdStage> returnStageBySmartPointer();"]},{"type":"codeListing","syntax":"swift","code":["\/\/ Generated Swift interface","func takeStageByRawPointer(_: pxr.UsdStage);","func takeStageBySmartPointer(_: pxr.TfRefPtr<pxr.UsdStage>);","func returnStageByRawPointer() -> pxr.UsdStage;","func returnStageBySmartPointer() -> pxr.TfRefPtr<pxr.UsdStage>);"]},{"type":"paragraph","inlineContent":[{"text":"When working with raw pointers in any of these cases, the C++ code needs to take care to match Swift’s expectations for memory management. Think carefully about the raw pointer’s ","type":"text"},{"inlineContent":[{"text":"direction of movement","type":"text"}],"type":"emphasis"},{"text":" and its ","type":"text"},{"inlineContent":[{"type":"text","text":"method of movement"}],"type":"emphasis"},{"text":":","type":"text"}]},{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Direction of movement","type":"text"}],"type":"strong"},{"type":"text","text":": Is the raw pointer moving from C++ to Swift, or from Swift to C++?"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Moving from C++ to Swift: Use a "},{"type":"codeVoice","code":"PassToSwift"},{"type":"text","text":" function"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Moving from Swift to C++: Use a ","type":"text"},{"type":"codeVoice","code":"TakeFromSwift"},{"text":" function","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Method of movement"}],"type":"strong"},{"text":". Is the raw pointer being passed a parameter to a function call, or is it the value returned from a function call?","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Moving as a return value: Use a ","type":"text"},{"code":"AsReturnValue","type":"codeVoice"},{"text":" function","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Moving as a function parameter: Use a ","type":"text"},{"code":"AsFunctionParameter","type":"codeVoice"},{"text":" function","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Combine the direction of movement and the method of movement to determine which of the four following functions to use."}]},{"type":"heading","text":"SwiftUsd::PassToSwiftAsReturnValue","anchor":"SwiftUsdPassToSwiftAsReturnValue","level":3},{"type":"paragraph","inlineContent":[{"text":"When a ","type":"text"},{"type":"codeVoice","code":"pxr::TfRefBase"},{"text":" subclass in C++ is being moved to Swift by returning it from a C++ function, use the function ","type":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/PassToSwiftAsReturnValue","overridingTitle":"SwiftUsd::PassToSwiftAsReturnValue(SmartPointer&)","overridingTitleInlineContent":[{"type":"codeVoice","code":"SwiftUsd::PassToSwiftAsReturnValue(SmartPointer&)"}],"type":"reference","isActive":true},{"text":" in the return statement, and apply the ","type":"text"},{"type":"codeVoice","code":"SWIFT_RETURNS_RETAINED"},{"text":" macro to your function declaration:","type":"text"}]},{"type":"codeListing","syntax":"c++","code":["\/\/ foo.hpp","#include \"swiftUsd\/swiftUsd.h\"","#include \"pxr\/usd\/usd\/stage.h\"","","pxr::UsdStage* _Nonnull returnStageByRawPointer() SWIFT_RETURNS_RETAINED;"]},{"type":"codeListing","syntax":"c++","code":["\/\/ foo.mm","#include \"foo.hpp\"","","pxr::UsdStage* _Nonnull returnStageByRawPointer() SWIFT_RETURNS_RETAINED {","    pxr::UsdStageRefPtr stage = pxr::UsdStage::CreateInMemory();","    return SwiftUsd::PassToSwiftAsReturnValue(stage);","}"]},{"name":"Warning","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"type":"reference","overridingTitle":"SwiftUsd::PassToSwiftAsReturnValue(SmartPointer&)","overridingTitleInlineContent":[{"code":"SwiftUsd::PassToSwiftAsReturnValue(SmartPointer&)","type":"codeVoice"}],"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/PassToSwiftAsReturnValue"},{"type":"text","text":" is called earlier than the return statement, the resulting value may become a use-after-free memory safety issue."}]}],"style":"warning"},{"type":"heading","text":"SwiftUsd::PassToSwiftAsFunctionParameter","anchor":"SwiftUsdPassToSwiftAsFunctionParameter","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"When a "},{"type":"codeVoice","code":"pxr::TfRefBase"},{"type":"text","text":" subclass in C++ is being moved to Swift by passing it to a Swift function, use the function "},{"overridingTitleInlineContent":[{"code":"SwiftUsd::PassToSwiftAsFunctionParameter(SmartPointer&)","type":"codeVoice"}],"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/PassToSwiftAsFunctionParameter","overridingTitle":"SwiftUsd::PassToSwiftAsFunctionParameter(SmartPointer&)"},{"type":"text","text":" in the function call expression:"}]},{"type":"codeListing","syntax":"swift","code":["\/\/ foo.swift","public func takeStageByRawPointer(_ stage: pxr.UsdStage) { ... }"]},{"type":"codeListing","syntax":"c++","code":["\/\/ foo.mm","#include \"MyTarget-Swift.h\"","#include \"swiftUsd\/swiftUsd.h\"","#include \"pxr\/usd\/usd\/stage.h\"","","void callSwiftWithRawPointer() {","    pxr::UsdStageRefPtr stage = pxr::UsdStage::CreateInMemory();","    MyTarget::takeStageByRawPointer(SwiftUsd::PassToSwiftAsFunctionParameter(stage));","}"]},{"name":"Warning","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"overridingTitle":"SwiftUsd::PassToSwiftAsFunctionParameter(SmartPointer&)","overridingTitleInlineContent":[{"code":"SwiftUsd::PassToSwiftAsFunctionParameter(SmartPointer&)","type":"codeVoice"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/PassToSwiftAsFunctionParameter","isActive":true,"type":"reference"},{"type":"text","text":" is called earlier than the function call expression, the resulting value may become a use-after-free memory issue."}]}],"style":"warning"},{"type":"heading","text":"SwiftUsd:TakeReturnValueFromSwift","anchor":"SwiftUsdTakeReturnValueFromSwift","level":3},{"type":"paragraph","inlineContent":[{"text":"When a ","type":"text"},{"type":"codeVoice","code":"pxr::TfRefBase"},{"text":" subclass in Swift is being moved to C++ by returning it from a Swift function, use the function ","type":"text"},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"SwiftUsd::TakeReturnValueFromSwift(SmartPointer::DataType*)"}],"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/TakeReturnValueFromSwift","overridingTitle":"SwiftUsd::TakeReturnValueFromSwift(SmartPointer::DataType*)"},{"text":" on the return value of the function call expression:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["\/\/ foo.swift","public func returnStageByRawPointer() -> pxr.UsdStage { ... }"]},{"type":"codeListing","syntax":"c++","code":["\/\/ foo.mm","#include \"MyTarget-Swift.h\"","#include \"swiftUsd\/swiftUsd.h\"","#include \"pxr\/usd\/usd\/stage.h\"","","void takeRawPointerFromSwift() {","    pxr::UsdStageRefPtr stage = SwiftUsd::TakeReturnValueFromSwift<pxr::UsdStageRefPtr>(MyTarget::returnStageByRawPointer());","}"]},{"name":"Warning","type":"aside","content":[{"inlineContent":[{"type":"text","text":"If "},{"overridingTitle":"SwiftUsd::TakeReturnValueFromSwift(SmartPointer::DataType*)","overridingTitleInlineContent":[{"code":"SwiftUsd::TakeReturnValueFromSwift(SmartPointer::DataType*)","type":"codeVoice"}],"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/TakeReturnValueFromSwift","isActive":true},{"type":"text","text":" is not called on the return value of the function call expression, the resulting value will become a memory leak."}],"type":"paragraph"}],"style":"warning"},{"type":"heading","text":"SwiftUsd::TakeFunctionParameterFromSwift","anchor":"SwiftUsdTakeFunctionParameterFromSwift","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"When a "},{"code":"pxr::TfRefBase","type":"codeVoice"},{"type":"text","text":" subclass in Swift is being moved to C++ by passing it to a C++ function, use the function "},{"overridingTitleInlineContent":[{"code":"SwiftUsd::TakeFunctionParameterFromSwift(SmartPointer::DataType*)","type":"codeVoice"}],"isActive":true,"overridingTitle":"SwiftUsd::TakeFunctionParameterFromSwift(SmartPointer::DataType*)","type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/TakeFunctionParameterFromSwift"},{"type":"text","text":" at the start of the function body:"}]},{"type":"codeListing","syntax":"c++","code":["\/\/ foo.hpp","#include \"swiftUsd\/swiftUsd.h\"","#include \"pxr\/usd\/usd\/stage.h\"","","void useRawPointerPassedBySwift(pxr::UsdStage* _Nonnull _stage);"]},{"type":"codeListing","syntax":"c++","code":["\/\/ foo.mm","#include \"foo.mm\"","","void useRawPointerPassedBySwift(pxr::UsdStage* _Nonnull _stage) {","    pxr::UsdStageRefPtr stage = SwiftUsd::TakeFunctionParameterFromSwift<pxr::UsdStageRefPtr>(_stage);","}"]},{"name":"Warning","type":"aside","content":[{"inlineContent":[{"type":"text","text":"If "},{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/TakeFunctionParameterFromSwift","overridingTitleInlineContent":[{"type":"codeVoice","code":"SwiftUsd::TakeFunctionParameterFromSwift(SmartPointer::DataType*)"}],"overridingTitle":"SwiftUsd::TakeFunctionParameterFromSwift(SmartPointer::DataType*)","isActive":true},{"type":"text","text":" is not called on the function parameter, using the resulting value may result in a null pointer dereference memory issue."}],"type":"paragraph"}],"style":"warning"}]}],"references":{"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd/TakeReturnValueFromSwift":{"type":"topic","title":"TakeReturnValueFromSwift","abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/swiftusd\/takereturnvaluefromswift","role":"symbol","fragments":[{"text":"TakeReturnValueFromSwift","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/TakeReturnValueFromSwift"},"doc://SwiftUsd/documentation/SwiftUsd/GettingStartedInCPlusPlus":{"url":"\/documentation\/swiftusd\/gettingstartedincplusplus","title":"Getting Started In C++","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStartedInCPlusPlus","abstract":[{"type":"text","text":"Using SwiftUsd from C++"}],"role":"article","kind":"article","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD":{"type":"topic","url":"\/documentation\/openusd","title":"OpenUSD","role":"collection","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd/PassToSwiftAsFunctionParameter":{"type":"topic","title":"PassToSwiftAsFunctionParameter","abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/swiftusd\/passtoswiftasfunctionparameter","role":"symbol","fragments":[{"text":"PassToSwiftAsFunctionParameter","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/PassToSwiftAsFunctionParameter"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd/TakeFunctionParameterFromSwift":{"type":"topic","title":"TakeFunctionParameterFromSwift","abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/swiftusd\/takefunctionparameterfromswift","role":"symbol","fragments":[{"text":"TakeFunctionParameterFromSwift","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/TakeFunctionParameterFromSwift"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd/PassToSwiftAsReturnValue":{"type":"topic","title":"PassToSwiftAsReturnValue","abstract":[],"url":"\/documentation\/openusd\/swiftusd\/passtoswiftasreturnvalue","kind":"symbol","role":"symbol","fragments":[{"text":"PassToSwiftAsReturnValue","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd\/PassToSwiftAsReturnValue"},"doc://SwiftUsd/documentation/SwiftUsd/SwiftCxxMacros":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxMacros","abstract":[{"text":"Learn about useful Swift-Cxx macros for writing C++ code used by Swift","type":"text"}],"title":"Swift-Cxx Macros","url":"\/documentation\/swiftusd\/swiftcxxmacros","kind":"article","type":"topic","role":"article"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Using SwiftUsd from C++","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStartedInCPlusPlus","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/SwiftCxxMacros"],"generated":true,"anchor":"Using-SwiftUsd-from-C++"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}