{"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"seeAlsoSections":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingLibWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"],"anchor":"New-symbol-documentation","generated":true,"title":"New symbol documentation"}],"sections":[],"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"code":"pxr.UsdEditContext","type":"codeVoice"},{"text":" is a move-only type that can’t be imported into Swift. This Swift Package provides ","type":"text"},{"overridingTitleInlineContent":[{"code":"Overlay.withUsdEditContext(_:_:_:)","type":"codeVoice"}],"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/withUsdEditContext(_:_:_:)","overridingTitle":"Overlay.withUsdEditContext(_:_:_:)","isActive":true},{"text":" as a convenient way to access the RAII behavior of ","type":"text"},{"code":"pxr.UsdEditContext","type":"codeVoice"},{"text":" in C++.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In C++, we would use the following pattern:"}]},{"type":"codeListing","syntax":"c++","code":["{","    pxr::UsdEditContext ctxt(vset.GetVariantEditContext());","","    \/\/ All Usd mutation of the UsdStage on which vset sits will","    \/\/ now go \"inside\" the currently selected variant of vset","","    pxr::VtVec3fArray colorValue;","    colorValue.push_back(pxr::GfVec3f(1, 0, 0));","    colorAttr.Set(colorValue);","}","\/\/ Mutations no longer go inside the selected variant of vset"]},{"type":"paragraph","inlineContent":[{"text":"In Swift, the pattern is:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["Overlay.withUsdEditContext(vset.GetVariantEditContext(pxr.SdfLayerHandle())) {","    \/\/ Mutations go inside the selected variant of vset","    ","    let colorValue: pxr.VtVec3fArray = [pxr.GfVec3f(1, 0, 0)]","    colorAttr.Set(colorValue, pxr.UsdTimeCode.Default())","}","\/\/ Mutations no longer go inside the selected variant of vset"]}]}],"variants":[{"paths":["\/documentation\/swiftusd\/usingeditcontexts"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/usingeditcontexts"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"collectionGroup","title":"Using edit contexts","roleHeading":"API Collection","modules":[{"name":"OpenUSD"}]},"abstract":[{"text":"Using ","type":"text"},{"code":"pxr.UsdEditContext","type":"codeVoice"},{"text":" in Swift","type":"text"}],"topicSections":[{"abstract":[{"text":"In Swift, these functions live under ","type":"text"},{"type":"codeVoice","code":"Overlay"},{"text":".","type":"text"}],"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/withUsdEditContext(_:_:_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/withUsdEditContext(_:_:)"],"anchor":"Topics"}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"references":{"doc://SwiftUsd/documentation/SwiftUsd/ConvenientExtensions":{"url":"\/documentation\/swiftusd\/convenientextensions","kind":"article","title":"Convenient extensions","type":"topic","role":"collectionGroup","abstract":[{"type":"text","text":"Extensions that make OpenUSD nicer to use in Swift"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions"},"doc://SwiftUsd/documentation/SwiftUsd/TypeConversion":{"role":"collectionGroup","title":"Type conversion","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion","url":"\/documentation\/swiftusd\/typeconversion","abstract":[],"kind":"article"},"doc://SwiftUsd/documentation/SwiftUsd/CheckingForValidity":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","abstract":[{"type":"text","text":"Checking for "},{"type":"codeVoice","code":"IsValid()"},{"type":"text","text":" and null pointers in Swift"}],"role":"article","url":"\/documentation\/swiftusd\/checkingforvalidity","kind":"article","title":"Checking for validity"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/withUsdEditContext(_:_:_:)":{"abstract":[{"text":"Performs an edit using the edit target.","type":"text"}],"type":"topic","url":"\/documentation\/openusd\/c++\/overlay\/withusdeditcontext(_:_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withUsdEditContext","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"UsdStage","preciseIdentifier":"c:@N@pxr@S@UsdStage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"UsdEditTarget","preciseIdentifier":"c:@N@pxr@S@UsdEditTarget","kind":"typeIdentifier"},{"text":", () ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> (","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE18withUsdEditContextyxSo021pxrInternal_v0_25_8__H10Reserved__O0E5StageV_AF0eF6TargetVxyKXEtKlFZ1TL_xmfp","kind":"typeIdentifier"},{"text":")) ","kind":"text"},{"text":"rethrows","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE18withUsdEditContextyxSo021pxrInternal_v0_25_8__H10Reserved__O0E5StageV_AF0eF6TargetVxyKXEtKlFZ1TL_xmfp","kind":"typeIdentifier"}],"kind":"symbol","title":"withUsdEditContext(_:_:_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/withUsdEditContext(_:_:_:)","role":"symbol"},"doc://SwiftUsd/documentation/SwiftUsd/DereferencingPointers":{"title":"Dereferencing pointers","url":"\/documentation\/swiftusd\/dereferencingpointers","abstract":[{"type":"text","text":"Safely dereferencing "},{"type":"codeVoice","code":"pxr.TfRefPtr"},{"type":"text","text":" and "},{"type":"codeVoice","code":"pxr.TfWeakPtr"},{"type":"text","text":" in Swift"}],"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfNotice":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","url":"\/documentation\/swiftusd\/workingwithtfnotice","abstract":[{"text":"Learn how to use the TfNotice notification subsystem in Swift","type":"text"}],"title":"Working with TfNotice","kind":"article","type":"topic","role":"article"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfDiagnosticFacilities":{"abstract":[{"text":"Learn how to use the Tf diagnostic facilities in Swift","type":"text"}],"title":"Working with Tf Diagnostic Facilities","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","role":"collectionGroup","url":"\/documentation\/swiftusd\/workingwithtfdiagnosticfacilities","kind":"article","type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfErrorMark":{"role":"article","title":"Working with TfErrorMark","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","url":"\/documentation\/swiftusd\/workingwithtferrormark","abstract":[{"type":"text","text":"Learn how to use TfErrorMark in Swift"}],"kind":"article"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/withUsdEditContext(_:_:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withUsdEditContext","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Overlay","preciseIdentifier":"c:@N@Overlay","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"UsdStagePtr_UsdEditTarget_Pair","preciseIdentifier":"c:Typedefs.h@N@Overlay@T@UsdStagePtr_UsdEditTarget_Pair","kind":"typeIdentifier"},{"text":", () ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> (","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE18withUsdEditContextyxSo3stdO3__1O00161pairpxrTfWeakPtrpxrUsdStagepxrUsdEditTarget_eqHICdkpbqgrbGbFFljbGxvbV_xyKXEtKlFZ1TL_xmfp","kind":"typeIdentifier"},{"text":")) ","kind":"text"},{"text":"rethrows","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE18withUsdEditContextyxSo3stdO3__1O00161pairpxrTfWeakPtrpxrUsdStagepxrUsdEditTarget_eqHICdkpbqgrbGbFFljbGxvbV_xyKXEtKlFZ1TL_xmfp","kind":"typeIdentifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/withUsdEditContext(_:_:)","type":"topic","abstract":[{"text":"Performs an edit using the edit target","type":"text"}],"url":"\/documentation\/openusd\/c++\/overlay\/withusdeditcontext(_:_:)","title":"withUsdEditContext(_:_:)"},"doc://SwiftUsd/documentation/SwiftUsd/CreatingPointers":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","abstract":[{"type":"text","text":"Creating "},{"type":"codeVoice","code":"pxr.TfRefPtr"},{"type":"text","text":" and "},{"type":"codeVoice","code":"pxr.TfWeakPtr"},{"type":"text","text":" in Swift"}],"url":"\/documentation\/swiftusd\/creatingpointers","kind":"article","type":"topic","title":"Creating pointers","role":"collectionGroup"},"doc://SwiftUsd/documentation/SwiftUsd/UsingLibWork":{"url":"\/documentation\/swiftusd\/usinglibwork","abstract":[{"text":"Learn how to use the ","type":"text"},{"type":"codeVoice","code":"pxr::Work"},{"text":" library for multithreading in Swift","type":"text"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingLibWork","kind":"article","role":"article","title":"Using libWork"},"doc://SwiftUsd/documentation/OpenUSD":{"type":"topic","url":"\/documentation\/openusd","title":"OpenUSD","role":"collection","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingLibWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"],"anchor":"New-symbol-documentation","title":"New symbol documentation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}