{"abstract":[{"text":"Learn about foreign reference types and how to use them","type":"text"}],"primaryContentSections":[{"content":[{"level":2,"text":"Overview","anchor":"Overview","type":"heading"},{"inlineContent":[{"text":"In Swift, a foreign reference type (FRT) is a C++ type that is annotated with ","type":"text"},{"code":"SWIFT_SHARED_REFERENCE","type":"codeVoice"},{"text":", ","type":"text"},{"code":"SWIFT_IMMORTAL_REFERENCE","type":"codeVoice"},{"text":", or ","type":"text"},{"code":"SWIFT_UNSAFE_REFERENCE","type":"codeVoice"},{"text":". When Swift encounters C++ pointers or references to such a type, Swift imports the pointer\/reference as a class type with Swift reference semantics. These annotations can grant access in Swift to C++ types that are non-movable and non-copyable, which would otherwise not be directly usable in Swift.","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"SWIFT_SHARED_REFERENCE"},{"type":"text","text":" types participate in automatic reference counting (ARC), just like Swift classes and actors. They are guaranteed to stay alive as long as there is at least one strong reference to it, such as a Swift variable containing the reference type. (However, using the "},{"type":"codeVoice","code":"weak"},{"type":"text","text":" keyword in Swift with these types does not work: "},{"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/swiftlang\/swift\/issues\/83080"},{"type":"text","text":")"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"SWIFT_IMMORTAL_REFERENCE","type":"codeVoice"},{"type":"text","text":" types are immortal types that are allocated but never deallocated, like singletons."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"SWIFT_UNSAFE_REFERENCE"},{"type":"text","text":" types are types that have no lifetime guarantees and may be deallocated at some point."}]}]}],"type":"unorderedList"},{"inlineContent":[{"type":"text","text":"See "},{"type":"reference","identifier":"https:\/\/www.swift.org\/documentation\/cxx-interop\/#mapping-c-types-to-swift-reference-types","isActive":true},{"type":"text","text":" for more information about FRTs."}],"type":"paragraph"},{"level":3,"text":"OpenUSD and reference types","anchor":"OpenUSD-and-reference-types","type":"heading"},{"inlineContent":[{"type":"text","text":"In OpenUSD, there are several ways that types can indicate that they have reference semantics:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Inheriting from ","type":"text"},{"code":"pxr::TfRefBase","type":"codeVoice"},{"text":": For example, ","type":"text"},{"code":"pxr::UsdStage","type":"codeVoice"},{"text":" inherits from ","type":"text"},{"code":"pxr::TfRefBase","type":"codeVoice"},{"text":". For these types, SwiftUsd tries to mark all of them as ","type":"text"},{"code":"SWIFT_SHARED_REFERENCE","type":"codeVoice"},{"text":", because ","type":"text"},{"code":"pxr::TfRefBase","type":"codeVoice"},{"text":" provides intrusive reference counting semantics, which is a great match for ","type":"text"},{"code":"SWIFT_SHARED_REFERENCE","type":"codeVoice"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Inheriting from ","type":"text"},{"code":"pxr::TfWeakBase","type":"codeVoice"},{"text":": For example, ","type":"text"},{"code":"pxr::UsdImagingDelegate","type":"codeVoice"},{"text":" inherits from ","type":"text"},{"code":"pxr::TfWeakBase","type":"codeVoice"},{"text":". For these types, SwiftUsd currently doesn’t annotate them, so they may not be usable directly in Swift. (However, types like ","type":"text"},{"code":"pxr::SdfLayer","type":"codeVoice"},{"text":" which inherit from ","type":"text"},{"code":"pxr::TfRefBase","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"pxr::TfWeakBase","type":"codeVoice"},{"text":" are usable in Swift. Those types are marked ","type":"text"},{"code":"SWIFT_SHARED_REFERENCE","type":"codeVoice"},{"text":", and additionally can be used with ","type":"text"},{"overridingTitle":"Overlay.WeakReferenceHolder","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/WeakReferenceHolder","overridingTitleInlineContent":[{"type":"codeVoice","code":"Overlay.WeakReferenceHolder"}],"type":"reference","isActive":true},{"text":" to hold them weakly instead of strongly.)","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Integrating with "},{"type":"codeVoice","code":"pxr::TfStaticData<T>"},{"type":"text","text":". For example, "},{"type":"codeVoice","code":"pxr::UsdGeomTokens"},{"type":"text","text":" and "},{"type":"codeVoice","code":"extern pxr::TfStaticData<UsdGeomTokensType> UsdGeomTokens;"},{"type":"text","text":". For these types, the template argument may be imported into Swift, but the "},{"type":"codeVoice","code":"pxr::TfStaticData"},{"type":"text","text":" specialization is not, and SwiftUsd currently doesn’t annotate it. However, future versions of SwiftUsd might annotate "},{"type":"codeVoice","code":"pxr::TfStaticData"},{"type":"text","text":" specializations so that they are imported into Swift."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Deleting\/hiding copy and move constructors, but integrating with ","type":"text"},{"type":"codeVoice","code":"pxr::TfSingleton<T>"},{"text":". For example, ","type":"text"},{"type":"codeVoice","code":"pxr::PlugRegistry"},{"text":". For these types, SwiftUsd marks them as ","type":"text"},{"type":"codeVoice","code":"SWIFT_IMMORTAL_REFERENCE"},{"text":", so they should be usable directly in Swift.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Deleting\/hiding copy and move constructors, used via stl smart pointer. For example, "},{"code":"pxr::UsdImagingGLEngine","type":"codeVoice"},{"type":"text","text":". These types are expected to be used via "},{"code":"std::unique_ptr<T>","type":"codeVoice"},{"type":"text","text":" or "},{"code":"std::shared_ptr<T>","type":"codeVoice"},{"type":"text","text":". For these types, SwiftUsd currently doesn’t annotate them or their stl smart pointer specializations, and the stl smart pointer specializations may not be very useful in Swift."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Deleting\/hiding copy and move constructors, used by const-ref. For example, "},{"type":"codeVoice","code":"pxr::UsdPrimDefinition"},{"type":"text","text":". For these types, SwiftUsd currently doesn’t annotate them, so they may not be usable directly in Swift."}]}]}],"type":"unorderedList"},{"style":"note","type":"aside","name":"Note","content":[{"inlineContent":[{"type":"text","text":"Types like "},{"type":"codeVoice","code":"pxr::UsdEditContext"},{"type":"text","text":" and "},{"type":"codeVoice","code":"pxr::TfErrorMark"},{"type":"text","text":" are not directly imported into Swift because they are non-movable and non-copyable. However, they are intended to be used as automatic (local) variables for RAII, and do not have reference semantics. SwiftUsd provides "},{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/withUsdEditContext(_:_:_:)","overridingTitle":"Overlay.withUsdEditContext(_:_:_:)","isActive":true,"overridingTitleInlineContent":[{"type":"codeVoice","code":"Overlay.withUsdEditContext(_:_:_:)"}]},{"type":"text","text":", and future versions of SwiftUsd might provide an easy way to directly or indirectly use these types."}],"type":"paragraph"}]},{"style":"note","type":"aside","name":"Note","content":[{"inlineContent":[{"type":"text","text":"This list is non-exhaustive; there may be other patterns in OpenUSD of using non-movable non-copyable types."}],"type":"paragraph"}]},{"level":3,"text":"SwiftUsd APIs","anchor":"SwiftUsd-APIs","type":"heading"},{"inlineContent":[{"type":"text","text":"SwiftUsd conforms all imported FRTs to "},{"code":"Equatable","type":"codeVoice"},{"type":"text","text":", "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":", and "},{"code":"Comparable","type":"codeVoice"},{"type":"text","text":", and also provides static "},{"code":"===","type":"codeVoice"},{"type":"text","text":" and "},{"code":"!==","type":"codeVoice"},{"type":"text","text":" operators for comparing the identity of two FRTs of the same type."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"SwiftUsd also creates some underscored protocols to make FRTs easier to use in Swift, such as to provide default protocol conformances. Avoid using these protocols in your code, because they are not part of the stable API.","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_SwiftUsdReferenceTypeProtocol","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_SwiftUsdImmortalReferenceTypeProtocol","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfRefBaseProtocol","type":"reference"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfRefPtrProtocol","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfConstRefPtrProtocol","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfWeakBaseProtocol","type":"reference"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfWeakPtrProtocol","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfConstWeakPtrProtocol","isActive":true,"type":"reference"}],"type":"paragraph"}]}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WhatIsAForeignReferenceType","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"kind":"article","sections":[],"seeAlsoSections":[{"generated":true,"anchor":"Working-with-foreign-reference-types","title":"Working with foreign reference types","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ForeignReferenceTypesAndSmartPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CastingBetweenForeignReferenceTypes"]}],"metadata":{"roleHeading":"Article","role":"article","modules":[{"name":"OpenUSD"}],"title":"What is a Foreign Reference Type?"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftusd\/whatisaforeignreferencetype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/swiftusd\/whatisaforeignreferencetype"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/_SwiftUsdImmortalReferenceTypeProtocol":{"title":"Overlay._SwiftUsdImmortalReferenceTypeProtocol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_SwiftUsdImmortalReferenceTypeProtocol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_SwiftUsdImmortalReferenceTypeProtocol","kind":"identifier"}],"url":"\/documentation\/openusd\/c++\/overlay\/_swiftusdimmortalreferencetypeprotocol","role":"symbol","navigatorTitle":[{"text":"_SwiftUsdImmortalReferenceTypeProtocol","kind":"identifier"}],"abstract":[{"text":"Protocol representing immortal reference types in OpenUSD. Don’t use this unless you know what you’re doing","type":"text"}],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/_TfConstWeakPtrProtocol":{"kind":"symbol","abstract":[{"type":"text","text":"Protocol representing "},{"type":"codeVoice","code":"pxr::TfWeakPtr<const T>"},{"type":"text","text":" specializations. Don’t use this unless you know what you’re doing"}],"title":"Overlay._TfConstWeakPtrProtocol","navigatorTitle":[{"text":"_TfConstWeakPtrProtocol","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfConstWeakPtrProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_TfConstWeakPtrProtocol","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/openusd\/c++\/overlay\/_tfconstweakptrprotocol"},"https://github.com/swiftlang/swift/issues/83080":{"titleInlineContent":[{"text":"https:\/\/github.com\/swiftlang\/swift\/issues\/83080: Assigning a non-nil value to a weak SWIFT_SHARED_REFERENCE variable crashes at runtime","type":"text"}],"url":"https:\/\/github.com\/swiftlang\/swift\/issues\/83080","type":"link","identifier":"https:\/\/github.com\/swiftlang\/swift\/issues\/83080","title":"https:\/\/github.com\/swiftlang\/swift\/issues\/83080: Assigning a non-nil value to a weak SWIFT_SHARED_REFERENCE variable crashes at runtime"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/_TfWeakPtrProtocol":{"title":"Overlay._TfWeakPtrProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"_TfWeakPtrProtocol"}],"type":"topic","abstract":[{"type":"text","text":"Protocol representing "},{"type":"codeVoice","code":"pxr::TfWeakPtr<T>"},{"type":"text","text":" specializations. Don’t use this unless you know what you’re doing"}],"url":"\/documentation\/openusd\/c++\/overlay\/_tfweakptrprotocol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"_TfWeakPtrProtocol"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfWeakPtrProtocol","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/withUsdEditContext(_:_:_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withUsdEditContext","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@UsdStage","text":"UsdStage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@UsdEditTarget","text":"UsdEditTarget","kind":"typeIdentifier"},{"text":", () ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> (","kind":"text"},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE18withUsdEditContextyxSo021pxrInternal_v0_25_5__H10Reserved__O0E5StageV_AF0eF6TargetVxyKXEtKlFZ1TL_xmfp","text":"T","kind":"typeIdentifier"},{"text":")) ","kind":"text"},{"text":"rethrows","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:So7OverlayO7OpenUSDE18withUsdEditContextyxSo021pxrInternal_v0_25_5__H10Reserved__O0E5StageV_AF0eF6TargetVxyKXEtKlFZ1TL_xmfp","text":"T","kind":"typeIdentifier"}],"url":"\/documentation\/openusd\/c++\/overlay\/withusdeditcontext(_:_:_:)","abstract":[{"text":"Performs an edit using the edit target.","type":"text"}],"kind":"symbol","title":"withUsdEditContext(_:_:_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/withUsdEditContext(_:_:_:)","type":"topic","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/_SwiftUsdReferenceTypeProtocol":{"abstract":[{"text":"Protocol representing all foreign reference types in OpenUSD. Don’t use this unless you know what you’re doing","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_SwiftUsdReferenceTypeProtocol","url":"\/documentation\/openusd\/c++\/overlay\/_swiftusdreferencetypeprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_SwiftUsdReferenceTypeProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"_SwiftUsdReferenceTypeProtocol","kind":"identifier"}],"title":"Overlay._SwiftUsdReferenceTypeProtocol","kind":"symbol","role":"symbol","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/_TfRefPtrProtocol":{"type":"topic","abstract":[{"text":"Protocol representing ","type":"text"},{"code":"pxr::TfRefPtr<T>","type":"codeVoice"},{"text":" specializations. Don’t use this unless you know what you’re doing","type":"text"}],"navigatorTitle":[{"text":"_TfRefPtrProtocol","kind":"identifier"}],"title":"Overlay._TfRefPtrProtocol","kind":"symbol","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfRefPtrProtocol","url":"\/documentation\/openusd\/c++\/overlay\/_tfrefptrprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_TfRefPtrProtocol","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/WeakReferenceHolder":{"kind":"symbol","role":"symbol","title":"Overlay.WeakReferenceHolder","abstract":[{"type":"text","text":"Holds a "},{"type":"codeVoice","code":"pxr::TfWeakBase"},{"type":"text","text":" subclass weakly"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WeakReferenceHolder","kind":"identifier"}],"url":"\/documentation\/openusd\/c++\/overlay\/weakreferenceholder","navigatorTitle":[{"text":"WeakReferenceHolder","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/WeakReferenceHolder"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/_TfRefBaseProtocol":{"navigatorTitle":[{"text":"_TfRefBaseProtocol","kind":"identifier"}],"url":"\/documentation\/openusd\/c++\/overlay\/_tfrefbaseprotocol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfRefBaseProtocol","title":"Overlay._TfRefBaseProtocol","abstract":[{"text":"Protocol representing ","type":"text"},{"code":"pxr::TfRefBase","type":"codeVoice"},{"text":" subclasses. Don’t use this unless you know what you’re doing","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_TfRefBaseProtocol","kind":"identifier"}],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","kind":"symbol","abstract":[],"url":"\/documentation\/openusd","role":"collection","type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/ForeignReferenceTypesAndSmartPointers":{"type":"topic","role":"article","abstract":[{"type":"text","text":"Learn about "},{"code":"pxr::TfRefPtr","type":"codeVoice"},{"type":"text","text":" and "},{"code":"pxr::TfWeakPtr","type":"codeVoice"},{"type":"text","text":" in Swift"}],"title":"Foreign Reference Types and Smart Pointers","url":"\/documentation\/swiftusd\/foreignreferencetypesandsmartpointers","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ForeignReferenceTypesAndSmartPointers","kind":"article"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/_TfWeakBaseProtocol":{"abstract":[{"text":"Protocol representing ","type":"text"},{"code":"pxr::TfWeakBase","type":"codeVoice"},{"text":" subclasses. Don’t use this unless you know what you’re doing","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_TfWeakBaseProtocol","kind":"identifier"}],"title":"Overlay._TfWeakBaseProtocol","url":"\/documentation\/openusd\/c++\/overlay\/_tfweakbaseprotocol","kind":"symbol","navigatorTitle":[{"text":"_TfWeakBaseProtocol","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfWeakBaseProtocol","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/_TfConstRefPtrProtocol":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfConstRefPtrProtocol","type":"topic","url":"\/documentation\/openusd\/c++\/overlay\/_tfconstrefptrprotocol","abstract":[{"text":"Protocol representing ","type":"text"},{"type":"codeVoice","code":"pxr::TfRefPtr<const T>"},{"text":" specializations. Don’t use this unless you know what you’re doing","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"_TfConstRefPtrProtocol","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_TfConstRefPtrProtocol","kind":"identifier"}],"title":"Overlay._TfConstRefPtrProtocol"},"doc://SwiftUsd/documentation/SwiftUsd/CastingBetweenForeignReferenceTypes":{"url":"\/documentation\/swiftusd\/castingbetweenforeignreferencetypes","type":"topic","kind":"article","title":"Casting between Foreign Reference Types","abstract":[{"text":"Learn about casting with Foreign Reference Types","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CastingBetweenForeignReferenceTypes","role":"article"},"https://www.swift.org/documentation/cxx-interop/#mapping-c-types-to-swift-reference-types":{"titleInlineContent":[{"type":"text","text":"swift.org"}],"identifier":"https:\/\/www.swift.org\/documentation\/cxx-interop\/#mapping-c-types-to-swift-reference-types","type":"link","title":"swift.org","url":"https:\/\/www.swift.org\/documentation\/cxx-interop\/#mapping-c-types-to-swift-reference-types"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"anchor":"Working-with-foreign-reference-types","title":"Working with foreign reference types","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ForeignReferenceTypesAndSmartPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CastingBetweenForeignReferenceTypes"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"}]}]}