{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark"},"seeAlsoSections":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"],"anchor":"New-symbol-documentation","generated":true,"title":"New symbol documentation"}],"primaryContentSections":[{"content":[{"text":"Overview","type":"heading","anchor":"Overview","level":2},{"inlineContent":[{"type":"text","text":"OpenUSD includes a non-fatal error tracking system via "},{"type":"codeVoice","code":"pxr::TfErrorMark"},{"type":"text","text":". "},{"type":"codeVoice","code":"TfErrorMark"},{"type":"text","text":" can’t be directly used in Swift, so SwiftUsd provides the "},{"type":"reference","overridingTitleInlineContent":[{"type":"codeVoice","code":"Overlay.withTfErrorMark(_:)"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/withTfErrorMark(_:)","isActive":true,"overridingTitle":"Overlay.withTfErrorMark(_:)"},{"type":"text","text":" function and the wrapping type "},{"type":"reference","overridingTitleInlineContent":[{"code":"TfErrorMarkWrapper","type":"codeVoice"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfErrorMarkWrapper","isActive":true,"overridingTitle":"TfErrorMarkWrapper"},{"type":"text","text":" instead."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Example usage:"}],"type":"paragraph"},{"code":["Overlay.withTfErrorMark { mark in","    \/\/ do some work...","    let stage = Overlay.DereferenceOrNil(pxr.UsdStage.CreateNew(path, .LoadAll))","","    if !mark.IsClean() {","        \/\/ errors occurred during work","        for error in mark.errors {","            print(error.GetCommentary())","        }","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"aside","name":"Important","style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"pxr::TfErrorMark","type":"codeVoice"},{"type":"text","text":" uses thread-local storage, which is incompatible with Swift Concurrency’s task execution model. For this reason, the body of "},{"isActive":true,"type":"reference","overridingTitleInlineContent":[{"code":"Overlay.withTfErrorMark(_:)","type":"codeVoice"}],"overridingTitle":"Overlay.withTfErrorMark(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/withTfErrorMark(_:)"},{"type":"text","text":" is intentionally forced to be synchronous (i.e. cannot "},{"code":"await","type":"codeVoice"},{"type":"text","text":" calls to "},{"code":"async","type":"codeVoice"},{"type":"text","text":" functions.)"}]}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/swiftusd\/workingwithtferrormark"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/workingwithtferrormark"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Learn how to use TfErrorMark in Swift"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","metadata":{"role":"article","title":"Working with TfErrorMark","roleHeading":"Article","modules":[{"name":"OpenUSD"}]},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"references":{"doc://SwiftUsd/documentation/SwiftUsd/UsingEditContexts":{"abstract":[{"type":"text","text":"Using "},{"type":"codeVoice","code":"pxr.UsdEditContext"},{"type":"text","text":" in Swift"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","role":"collectionGroup","title":"Using edit contexts","url":"\/documentation\/swiftusd\/usingeditcontexts","kind":"article","type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfNotice":{"kind":"article","title":"Working with TfNotice","type":"topic","role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","abstract":[{"text":"Learn how to use the TfNotice notification subsystem in Swift","type":"text"}],"url":"\/documentation\/swiftusd\/workingwithtfnotice"},"doc://SwiftUsd/documentation/SwiftUsd/CreatingPointers":{"kind":"article","url":"\/documentation\/swiftusd\/creatingpointers","abstract":[{"text":"Creating ","type":"text"},{"code":"pxr.TfRefPtr","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"pxr.TfWeakPtr","type":"codeVoice"},{"text":" in Swift","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","type":"topic","title":"Creating pointers","role":"collectionGroup"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/TfErrorMarkWrapper":{"url":"\/documentation\/openusd\/overlay\/tferrormarkwrapper","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TfErrorMarkWrapper","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfErrorMarkWrapper","type":"topic","kind":"symbol","role":"symbol","title":"struct TfErrorMarkWrapper","abstract":[],"navigatorTitle":[{"text":"TfErrorMarkWrapper","kind":"identifier"}]},"doc://SwiftUsd/documentation/SwiftUsd/TypeConversion":{"kind":"article","type":"topic","url":"\/documentation\/swiftusd\/typeconversion","role":"collectionGroup","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion","title":"Type conversion","abstract":[]},"doc://SwiftUsd/documentation/SwiftUsd/ConvenientExtensions":{"role":"collectionGroup","kind":"article","abstract":[{"type":"text","text":"Extensions that make OpenUSD nicer to use in Swift"}],"title":"Convenient extensions","url":"\/documentation\/swiftusd\/convenientextensions","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/withTfErrorMark(_:)":{"role":"symbol","abstract":[{"text":"Performs work with a ","type":"text"},{"type":"codeVoice","code":"pxr::TfErrorMark"},{"text":" in scope","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withTfErrorMark","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"E","kind":"genericParameter"},{"text":">((","kind":"text"},{"text":"borrowing","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Overlay","preciseIdentifier":"c:@N@Overlay","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"TfErrorMarkWrapper","preciseIdentifier":"c:@N@Overlay@S@TfErrorMarkWrapper","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":"(","kind":"text"},{"text":"E","preciseIdentifier":"s:So7OverlayO7OpenUSDE15withTfErrorMarkyxxAB0efG7WrapperVq_YKXEq_YKs0F0R_r0_lFZ1EL_q_mfp","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE15withTfErrorMarkyxxAB0efG7WrapperVq_YKXEq_YKs0F0R_r0_lFZ1TL_xmfp","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":"(","kind":"text"},{"text":"E","preciseIdentifier":"s:So7OverlayO7OpenUSDE15withTfErrorMarkyxxAB0efG7WrapperVq_YKXEq_YKs0F0R_r0_lFZ1EL_q_mfp","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"T","preciseIdentifier":"s:So7OverlayO7OpenUSDE15withTfErrorMarkyxxAB0efG7WrapperVq_YKXEq_YKs0F0R_r0_lFZ1TL_xmfp","kind":"typeIdentifier"}],"url":"\/documentation\/openusd\/c++\/overlay\/withtferrormark(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/withTfErrorMark(_:)","type":"topic","kind":"symbol","title":"withTfErrorMark(_:)"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfDiagnosticFacilities":{"type":"topic","title":"Working with Tf Diagnostic Facilities","kind":"article","abstract":[{"text":"Learn how to use the Tf diagnostic facilities in Swift","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","url":"\/documentation\/swiftusd\/workingwithtfdiagnosticfacilities","role":"collectionGroup"},"doc://SwiftUsd/documentation/SwiftUsd/CheckingForValidity":{"role":"article","title":"Checking for validity","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","url":"\/documentation\/swiftusd\/checkingforvalidity","kind":"article","abstract":[{"text":"Checking for ","type":"text"},{"type":"codeVoice","code":"IsValid()"},{"text":" and null pointers in Swift","type":"text"}],"type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/DereferencingPointers":{"title":"Dereferencing pointers","url":"\/documentation\/swiftusd\/dereferencingpointers","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","abstract":[{"text":"Safely dereferencing ","type":"text"},{"type":"codeVoice","code":"pxr.TfRefPtr"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"pxr.TfWeakPtr"},{"text":" in Swift","type":"text"}],"type":"topic","kind":"article","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"],"generated":true,"anchor":"New-symbol-documentation","title":"New symbol documentation"}],"path":"\/seeAlsoSections"}]}]}