{"metadata":{"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"pxr::TfWeakPtr","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@ST>1#T@TfWeakPtr"},{"text":"<","kind":"text"},{"text":"__SwiftUsd","kind":"identifier","preciseIdentifier":"c:@N@__SwiftUsd"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"identifier","preciseIdentifier":"c:@N@__SwiftUsd@N@TfNotice"},{"text":".","kind":"text"},{"text":"ListenerBase","kind":"typeIdentifier","preciseIdentifier":"c:@N@__SwiftUsd@N@TfNotice@S@ListenerBase"},{"kind":"text","text":">"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","kind":"typeIdentifier","text":"TfNotice"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@TfNotice@S@Key","kind":"typeIdentifier","text":"Key"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SwiftKey"}],"title":"init(_:_:)","navigatorTitle":[{"kind":"identifier","text":"SwiftKey"}],"roleHeading":"Initializer","modules":[{"name":"OpenUSD"}],"externalID":"c:@N@pxr@S@TfNotice@S@SwiftKey@F@SwiftKey#$@N@pxr@S@TfWeakPtr>#$@N@__SwiftUsd@N@TfNotice@S@ListenerBase#$@N@pxr@S@TfNotice@S@Key#","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"listener","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"pxr::TfWeakPtr","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@ST>1#T@TfWeakPtr"},{"text":"<","kind":"text"},{"text":"__SwiftUsd","kind":"identifier","preciseIdentifier":"c:@N@__SwiftUsd"},{"kind":"text","text":"."},{"kind":"identifier","text":"TfNotice","preciseIdentifier":"c:@N@__SwiftUsd@N@TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ListenerBase","preciseIdentifier":"c:@N@__SwiftUsd@N@TfNotice@S@ListenerBase"},{"kind":"text","text":">"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"registrationKey"},{"kind":"text","text":": "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Key","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@Key"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SwiftKey"}],"platforms":["macOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/SwiftKey-2l2b4","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/openusd\/swiftkey\/swiftkey-2l2b4"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/swiftkey\/swiftkey-2l2b4"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","references":{"doc://SwiftUsd/documentation/OpenUSD/SwiftKey/SwiftKey-2l2b4":{"url":"\/documentation\/openusd\/swiftkey\/swiftkey-2l2b4","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"pxr::TfWeakPtr","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@ST>1#T@TfWeakPtr"},{"text":"<","kind":"text"},{"text":"__SwiftUsd","kind":"identifier","preciseIdentifier":"c:@N@__SwiftUsd"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"identifier","preciseIdentifier":"c:@N@__SwiftUsd@N@TfNotice"},{"text":".","kind":"text"},{"text":"ListenerBase","kind":"typeIdentifier","preciseIdentifier":"c:@N@__SwiftUsd@N@TfNotice@S@ListenerBase"},{"text":">","kind":"text"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice@S@Key","text":"Key","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/SwiftKey-2l2b4","navigatorTitle":[{"text":"SwiftKey","kind":"identifier"}],"type":"topic","abstract":[],"title":"init(_:_:)","role":"symbol","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD","kind":"symbol","abstract":[],"url":"\/documentation\/openusd","role":"collection","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/SwiftKey":{"title":"class SwiftKey","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","url":"\/documentation\/openusd\/swiftkey","role":"symbol","abstract":[{"type":"text","text":"A key representing a listener registered from either Swift or C++"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwiftKey"}],"navigatorTitle":[{"kind":"identifier","text":"SwiftKey"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Constructor","op":"replace"},{"path":"\/metadata\/title","value":"SwiftKey","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SwiftKey","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SwiftKey"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"identifier","text":"SwiftKey"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@ST>1#T@TfWeakPtr","text":"pxr::TfWeakPtr"},{"kind":"text","text":"<"},{"kind":"identifier","preciseIdentifier":"c:@N@__SwiftUsd","text":"__SwiftUsd"},{"kind":"text","text":"::"},{"kind":"identifier","preciseIdentifier":"c:@N@__SwiftUsd@N@TfNotice","text":"TfNotice"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@__SwiftUsd@N@TfNotice@S@ListenerBase","text":"ListenerBase"},{"kind":"text","text":"> "},{"kind":"internalParam","text":"listener"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"::"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","kind":"typeIdentifier","text":"TfNotice"},{"kind":"text","text":"::"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice@S@Key","kind":"typeIdentifier","text":"Key"},{"kind":"text","text":" "},{"kind":"internalParam","text":"registrationKey"},{"text":");","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1SwiftKey-2l2b4\/title","value":"SwiftKey","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1SwiftKey-2l2b4\/fragments","value":[{"text":"SwiftKey","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1SwiftKey-2l2b4\/navigatorTitle","value":[{"text":"SwiftKey","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/title","value":"SwiftKey","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/fragments","value":[{"kind":"identifier","text":"SwiftKey"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/navigatorTitle","value":[{"text":"SwiftKey","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}