{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/GetAssetInfo"},"kind":"symbol","variants":[{"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper\/getassetinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper\/getassetinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetAssetInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"assetPath"},{"kind":"text","text":": "},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"string","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"resolvedPath","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArResolvedPath","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArResolvedPath"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArAssetInfo","text":"ArAssetInfo"}],"platforms":["macOS"],"languages":["swift"]}]}],"metadata":{"externalID":"c:@N@Overlay@S@ArResolverWrapper@F@GetAssetInfo#&1$@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C#&1$@N@pxr@S@ArResolvedPath#1","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetAssetInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","kind":"identifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"text":", ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArResolvedPath","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArResolvedPath"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArAssetInfo","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArAssetInfo"}],"title":"GetAssetInfo(_:_:)","symbolKind":"method","modules":[{"name":"OpenUSD"}],"navigatorTitle":[{"text":"GetAssetInfo","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper"]]},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"title":"Overlay","type":"topic","fragments":[{"kind":"identifier","text":"Overlay"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection","abstract":[],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/GetAssetInfo":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/GetAssetInfo","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetAssetInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","kind":"identifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"text":", ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArResolvedPath","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArResolvedPath"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArAssetInfo","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArAssetInfo"}],"type":"topic","abstract":[],"title":"GetAssetInfo(_:_:)","navigatorTitle":[{"text":"GetAssetInfo","kind":"identifier"}],"role":"symbol","url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/getassetinfo"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper":{"title":"class ArResolverWrapper","navigatorTitle":[{"kind":"identifier","text":"ArResolverWrapper"}],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArResolverWrapper"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"GetAssetInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GetAssetInfo","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GetAssetInfo","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":"::","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@ArAssetInfo","text":"ArAssetInfo","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"GetAssetInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@std","text":"std","kind":"identifier"},{"text":"::","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C","text":"string","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"assetPath","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":"::","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@ArResolvedPath","text":"ArResolvedPath","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"resolvedPath","kind":"internalParam"},{"text":") ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}],"platforms":["macOS"]}]}},{"value":"Overlay","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"value":[{"text":"Overlay","kind":"identifier"}],"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1GetAssetInfo\/title","op":"replace","value":"GetAssetInfo"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1GetAssetInfo\/fragments","op":"replace","value":[{"text":"GetAssetInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1GetAssetInfo\/navigatorTitle","op":"replace","value":[{"text":"GetAssetInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/title","op":"replace","value":"ArResolverWrapper"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/fragments","op":"replace","value":[{"text":"ArResolverWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ArResolverWrapper"}]}]}]}