{"metadata":{"navigatorTitle":[{"text":"operator bool","kind":"identifier"}],"externalID":"c:@N@Overlay@S@ArResolverWrapper@F@operator bool#1","title":"operator bool","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"text":"_Bool","kind":"identifier"}],"modules":[{"name":"OpenUSD"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper\/operator_bool"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper\/operator_bool"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/operator_bool","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"explicit","kind":"keyword"},{"text":" ","kind":"text"},{"text":"operator","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_Bool","kind":"typeIdentifier"},{"text":"() ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}],"platforms":["macOS"]}]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper"]]},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArResolverWrapper","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","url":"\/documentation\/openusd\/overlay\/arresolverwrapper","title":"class ArResolverWrapper","abstract":[],"type":"topic","navigatorTitle":[{"text":"ArResolverWrapper","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/operator_bool":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/operator_bool","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"operator bool"}],"type":"topic","title":"operator bool","role":"symbol","abstract":[],"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/operator_bool","fragments":[{"kind":"identifier","text":"_Bool"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"fragments":[{"text":"Overlay","kind":"identifier"}],"role":"symbol","title":"Overlay","type":"topic","url":"\/documentation\/openusd\/overlay","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay"},"doc://SwiftUsd/documentation/OpenUSD":{"url":"\/documentation\/openusd","kind":"symbol","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"operator bool","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"_Bool"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"operator bool"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"explicit"},{"kind":"text","text":" "},{"kind":"keyword","text":"operator"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"_Bool"},{"kind":"text","text":"() "},{"kind":"keyword","text":"const"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/title","value":"ArResolverWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/fragments","value":[{"text":"ArResolverWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"ArResolverWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1operator_bool\/title","value":"operator bool","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1operator_bool\/fragments","value":[{"text":"_Bool","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1operator_bool\/navigatorTitle","value":[{"text":"operator bool","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"kind":"identifier","text":"Overlay"}],"op":"add"}],"traits":[{"interfaceLanguage":"occ"}]}]}