#===----------------------------------------------------------------------===#
# This source file is part of github.com/apple/SwiftUsd
#
# Copyright © 2025 Apple Inc. and the SwiftUsd project authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#===----------------------------------------------------------------------===#

name: Check that pull requests don't update automated files
run-name: Checking that pull request doesn't update automated files

on:
  pull_request:
    paths:
    - ./Package.swift
    - ./swift-package/**
    - ./SwiftUsd.doccarchive/**
    - ./SwiftUsd/docs/**

jobs:
  Fail:
    runs-on: self-hosted
    steps:
    - run: exit 1