{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArGetUnderlyingResolver","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","text":"ArResolverWrapper","preciseIdentifier":"c:@N@Overlay@S@ArResolverWrapper","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArGetUnderlyingResolver"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/argetunderlyingresolver"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/argetunderlyingresolver"]}],"sections":[],"metadata":{"roleHeading":"Function","modules":[{"name":"OpenUSD"}],"symbolKind":"func","role":"symbol","title":"ArGetUnderlyingResolver()","externalID":"c:@N@Overlay@F@ArGetUnderlyingResolver#","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArGetUnderlyingResolver"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@Overlay@S@ArResolverWrapper","kind":"typeIdentifier","text":"ArResolverWrapper"}],"navigatorTitle":[{"text":"ArGetUnderlyingResolver","kind":"identifier"}]},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"type":"topic","kind":"symbol","url":"\/documentation\/openusd\/overlay","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"fragments":[{"kind":"identifier","text":"Overlay"}],"title":"Overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArGetUnderlyingResolver":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArGetUnderlyingResolver","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@Overlay@S@ArResolverWrapper","text":"ArResolverWrapper","kind":"typeIdentifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArGetUnderlyingResolver","url":"\/documentation\/openusd\/overlay\/argetunderlyingresolver","kind":"symbol","navigatorTitle":[{"text":"ArGetUnderlyingResolver","kind":"identifier"}],"abstract":[],"title":"ArGetUnderlyingResolver()","type":"topic","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","title":"class ArResolverWrapper","navigatorTitle":[{"text":"ArResolverWrapper","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArResolverWrapper","kind":"identifier"}],"role":"symbol","url":"\/documentation\/openusd\/overlay\/arresolverwrapper","type":"topic","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/openusd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Function","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ArGetUnderlyingResolver","path":"\/metadata\/title"},{"op":"replace","value":"func","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ArGetUnderlyingResolver","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ArGetUnderlyingResolver"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","text":"ArResolverWrapper","preciseIdentifier":"c:@N@Overlay@S@ArResolverWrapper","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"ArGetUnderlyingResolver","kind":"identifier"},{"text":"();","kind":"text"}],"languages":["occ"],"platforms":["macOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"Overlay","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"value":[{"kind":"identifier","text":"Overlay"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"value":[{"kind":"identifier","text":"Overlay"}],"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"value":"ArGetUnderlyingResolver","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArGetUnderlyingResolver\/title"},{"value":[{"kind":"identifier","text":"ArGetUnderlyingResolver"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArGetUnderlyingResolver\/fragments"},{"value":[{"kind":"identifier","text":"ArGetUnderlyingResolver"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArGetUnderlyingResolver\/navigatorTitle"},{"value":"ArResolverWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/title"},{"value":[{"text":"ArResolverWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/fragments"},{"value":[{"kind":"identifier","text":"ArResolverWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}