{"seeAlsoSections":[{"title":"Namespace Overlay","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfErrorMarkWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper"],"generated":true,"anchor":"Namespace-Overlay"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiWrapper","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/HgiWrapper"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateBlitCmds","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateBuffer","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateComputeCmds","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateComputePipeline","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateGraphicsCmds","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateGraphicsPipeline","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateResourceBindings","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateSampler","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateShaderFunction","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateShaderProgram","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateTexture","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateTextureView","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyBuffer","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyComputePipeline","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyGraphicsPipeline","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyResourceBindings","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroySampler","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyShaderFunction","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyShaderProgram","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyTexture","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyTextureView","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/EndFrame","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/GarbageCollect","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/GetAPIName","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/GetCapabilities","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/GetIndirectCommandEncoder","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/IsBackendSupported","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/StartFrame","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/SubmitCmds","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/VtValueWrappingHgiRawPtr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/get","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/get_shared","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/operator_bool"],"generated":true},{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateNamedHgi","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreatePlatformDefaultHgi","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/IsSupported"],"generated":true}],"sections":[],"metadata":{"externalID":"c:@N@Overlay@S@HgiWrapper","role":"symbol","symbolKind":"class","modules":[{"name":"OpenUSD"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HgiWrapper"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"HgiWrapper"}],"title":"class HgiWrapper"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay"]]},"kind":"symbol","relationshipsSections":[{"title":"Inherited By","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper"],"type":"inheritedBy","kind":"relationships"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/openusd\/overlay\/hgiwrapper"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/hgiwrapper"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper"},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"HioImageWrapper","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HioImageWrapper","kind":"identifier"}],"kind":"symbol","title":"class HioImageWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","url":"\/documentation\/openusd\/overlay\/hioimagewrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/GarbageCollect":{"fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GarbageCollect"},{"kind":"text","text":"()"}],"title":"GarbageCollect()","navigatorTitle":[{"kind":"identifier","text":"GarbageCollect"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/garbagecollect","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/GarbageCollect","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/operator_bool":{"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/operator_bool","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"_Bool"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"operator bool"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/operator_bool","title":"operator bool","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreateGraphicsCmds":{"fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateGraphicsCmds"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiGraphicsCmdsDesc","text":"HgiGraphicsCmdsDesc"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HgiGraphicsCmdsUniquePtr","preciseIdentifier":"c:@N@std@N@__1@S@unique_ptr>#$@N@pxr@S@HgiGraphicsCmds#$@N@std@N@__1@S@default_delete>#S0_"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/creategraphicscmds","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CreateGraphicsCmds"}],"abstract":[],"type":"topic","kind":"symbol","title":"CreateGraphicsCmds(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateGraphicsCmds"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/SubmitCmds":{"title":"SubmitCmds(_:_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/SubmitCmds","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubmitCmds"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@HgiCmds","kind":"typeIdentifier","text":"HgiCmds"},{"kind":"text","text":">"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@E@HgiSubmitWaitType","kind":"typeIdentifier","text":"HgiSubmitWaitType"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"SubmitCmds"}],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/submitcmds","type":"topic","role":"symbol","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/get_shared":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/get_shared","kind":"symbol","title":"get_shared()","type":"topic","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/get_shared","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get_shared","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"std","kind":"identifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"std::shared_ptr","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr"},{"text":"<","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"Hgi","preciseIdentifier":"c:@N@pxr@S@Hgi","kind":"typeIdentifier"},{"text":">","kind":"text"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"get_shared","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/DestroyComputePipeline":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"DestroyComputePipeline"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiComputePipeline","kind":"typeIdentifier","text":"HgiComputePipelineHandle"},{"text":">","kind":"text"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyComputePipeline","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/destroycomputepipeline","title":"DestroyComputePipeline(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DestroyComputePipeline"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/HgiWrapper":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","preciseIdentifier":"c:@N@std","kind":"identifier"},{"text":".","kind":"text"},{"text":"std::shared_ptr","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"Hgi","preciseIdentifier":"c:@N@pxr@S@Hgi","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"HgiWrapper","kind":"typeIdentifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/HgiWrapper","type":"topic","abstract":[],"navigatorTitle":[{"text":"HgiWrapper","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"init(_:)","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/hgiwrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/get":{"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/get","navigatorTitle":[{"text":"get","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"Hgi","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@Hgi"},{"text":">","kind":"text"}],"kind":"symbol","title":"get()","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/get","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreateComputeCmds":{"abstract":[],"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/createcomputecmds","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateComputeCmds"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@HgiComputeCmdsDesc","kind":"typeIdentifier","text":"HgiComputeCmdsDesc"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@S@unique_ptr>#$@N@pxr@S@HgiComputeCmds#$@N@std@N@__1@S@default_delete>#S0_","text":"HgiComputeCmdsUniquePtr","kind":"typeIdentifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateComputeCmds","title":"CreateComputeCmds(_:)","type":"topic","navigatorTitle":[{"text":"CreateComputeCmds","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/VtValueWrappingHgiRawPtr":{"abstract":[],"role":"symbol","type":"topic","title":"VtValueWrappingHgiRawPtr()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VtValueWrappingHgiRawPtr","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"VtValue","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@VtValue"}],"navigatorTitle":[{"text":"VtValueWrappingHgiRawPtr","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/vtvaluewrappinghgirawptr","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/VtValueWrappingHgiRawPtr"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/DestroyResourceBindings":{"role":"symbol","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"DestroyResourceBindings"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HgiResourceBindingsHandle","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiResourceBindings"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyResourceBindings","navigatorTitle":[{"kind":"identifier","text":"DestroyResourceBindings"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/destroyresourcebindings","title":"DestroyResourceBindings(_:)","abstract":[],"type":"topic","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreateTextureView":{"kind":"symbol","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/createtextureview","type":"topic","abstract":[],"title":"CreateTextureView(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateTextureView","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateTextureView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"HgiTextureViewDesc","preciseIdentifier":"c:@N@pxr@S@HgiTextureViewDesc","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"HgiTextureViewHandle","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiTextureView","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"CreateTextureView"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreateShaderFunction":{"navigatorTitle":[{"kind":"identifier","text":"CreateShaderFunction"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/createshaderfunction","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateShaderFunction","type":"topic","abstract":[],"kind":"symbol","title":"CreateShaderFunction(_:)","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateShaderFunction"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HgiShaderFunctionDesc","preciseIdentifier":"c:@N@pxr@S@HgiShaderFunctionDesc"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiShaderFunction","text":"HgiShaderFunctionHandle"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/GetCapabilities":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetCapabilities","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@HgiCapabilities","text":"HgiCapabilities","kind":"typeIdentifier"},{"text":">","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GetCapabilities"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/GetCapabilities","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/getcapabilities","title":"GetCapabilities()"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/StartFrame":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"StartFrame","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/StartFrame","title":"StartFrame()","kind":"symbol","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"StartFrame"},{"kind":"text","text":"()"}],"type":"topic","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/startframe"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/DestroyGraphicsPipeline":{"navigatorTitle":[{"text":"DestroyGraphicsPipeline","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyGraphicsPipeline","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/destroygraphicspipeline","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"DestroyGraphicsPipeline"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HgiGraphicsPipelineHandle","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiGraphicsPipeline"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"title":"DestroyGraphicsPipeline(_:)"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/DestroyBuffer":{"type":"topic","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"DestroyBuffer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiBuffer","text":"HgiBufferHandle","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"DestroyBuffer","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyBuffer","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/destroybuffer","title":"DestroyBuffer(_:)"},"doc://SwiftUsd/documentation/OpenUSD":{"url":"\/documentation\/openusd","kind":"symbol","type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","title":"OpenUSD"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"kind":"symbol","title":"struct UsdPrimTypeInfoWrapper","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreateComputePipeline":{"title":"CreateComputePipeline(_:)","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/createcomputepipeline","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateComputePipeline","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateComputePipeline","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"HgiComputePipelineDesc","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiComputePipelineDesc"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HgiComputePipelineHandle","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiComputePipeline"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CreateComputePipeline"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreateGraphicsPipeline":{"abstract":[],"role":"symbol","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/creategraphicspipeline","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateGraphicsPipeline","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateGraphicsPipeline","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@HgiGraphicsPipelineDesc","text":"HgiGraphicsPipelineDesc","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiGraphicsPipeline","text":"HgiGraphicsPipelineHandle","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"CreateGraphicsPipeline","kind":"identifier"}],"title":"CreateGraphicsPipeline(_:)","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/DestroyShaderFunction":{"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/destroyshaderfunction","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"DestroyShaderFunction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiShaderFunction","kind":"typeIdentifier","text":"HgiShaderFunctionHandle"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyShaderFunction","navigatorTitle":[{"kind":"identifier","text":"DestroyShaderFunction"}],"kind":"symbol","type":"topic","abstract":[],"title":"DestroyShaderFunction(_:)","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreatePlatformDefaultHgi":{"navigatorTitle":[{"kind":"identifier","text":"CreatePlatformDefaultHgi"}],"kind":"symbol","title":"CreatePlatformDefaultHgi()","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreatePlatformDefaultHgi","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreatePlatformDefaultHgi"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"HgiWrapper","preciseIdentifier":"c:@N@Overlay@S@HgiWrapper"}],"abstract":[],"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/createplatformdefaulthgi","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/DestroySampler":{"role":"symbol","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"DestroySampler"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HgiSamplerHandle","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiSampler"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"title":"DestroySampler(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroySampler","navigatorTitle":[{"kind":"identifier","text":"DestroySampler"}],"type":"topic","kind":"symbol","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/destroysampler","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HgiWrapper"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HgiWrapper"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper","title":"class HgiWrapper","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","type":"topic","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreateShaderProgram":{"fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateShaderProgram","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@HgiShaderProgramDesc","text":"HgiShaderProgramDesc","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiShaderProgram","text":"HgiShaderProgramHandle","kind":"typeIdentifier"}],"type":"topic","title":"CreateShaderProgram(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateShaderProgram","kind":"symbol","abstract":[],"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/createshaderprogram","navigatorTitle":[{"text":"CreateShaderProgram","kind":"identifier"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/EndFrame":{"type":"topic","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EndFrame","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"role":"symbol","title":"EndFrame()","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/EndFrame","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/endframe","kind":"symbol","navigatorTitle":[{"text":"EndFrame","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/GetIndirectCommandEncoder":{"navigatorTitle":[{"text":"GetIndirectCommandEncoder","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/GetIndirectCommandEncoder","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetIndirectCommandEncoder"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HgiIndirectCommandEncoder","preciseIdentifier":"c:@N@pxr@S@HgiIndirectCommandEncoder"},{"kind":"text","text":">"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/getindirectcommandencoder","title":"GetIndirectCommandEncoder()","abstract":[],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/DestroyShaderProgram":{"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/destroyshaderprogram","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyShaderProgram","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DestroyShaderProgram","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiShaderProgram","text":"HgiShaderProgramHandle","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"}],"title":"DestroyShaderProgram(_:)","navigatorTitle":[{"text":"DestroyShaderProgram","kind":"identifier"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/DestroyTexture":{"type":"topic","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"DestroyTexture"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HgiTextureHandle","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiTexture"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DestroyTexture"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/destroytexture","title":"DestroyTexture(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyTexture","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreateSampler":{"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/createsampler","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateSampler","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateSampler"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiSamplerDesc","text":"HgiSamplerDesc"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiSampler","text":"HgiSamplerHandle"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CreateSampler"}],"abstract":[],"title":"CreateSampler(_:)","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreateNamedHgi":{"type":"topic","role":"symbol","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/createnamedhgi","kind":"symbol","navigatorTitle":[{"text":"CreateNamedHgi","kind":"identifier"}],"title":"CreateNamedHgi(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateNamedHgi"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfToken","text":"TfToken"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@S@HgiWrapper","text":"HgiWrapper"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateNamedHgi"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/IsSupported":{"kind":"symbol","role":"symbol","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/issupported","title":"IsSupported(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/IsSupported","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"IsSupported"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsSupported","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfToken","text":"TfToken","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:b","text":"Bool","kind":"typeIdentifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"fragments":[{"text":"Overlay","kind":"identifier"}],"role":"symbol","title":"Overlay","type":"topic","url":"\/documentation\/openusd\/overlay","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreateTexture":{"type":"topic","role":"symbol","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateTexture","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@HgiTextureDesc","text":"HgiTextureDesc","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiTexture","kind":"typeIdentifier","text":"HgiTextureHandle"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateTexture","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CreateTexture"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/createtexture","title":"CreateTexture(_:)","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/GetAPIName":{"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/getapiname","title":"GetAPIName()","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/GetAPIName","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetAPIName","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfToken","text":"TfToken","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"GetAPIName","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiMetalWrapper","kind":"identifier"}],"title":"class HgiMetalWrapper","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper","navigatorTitle":[{"text":"HgiMetalWrapper","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreateBlitCmds":{"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/createblitcmds","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateBlitCmds","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateBlitCmds","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Overlay","kind":"identifier","preciseIdentifier":"c:@N@Overlay"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@shared_ptr>#$@N@pxr@S@HgiBlitCmds","text":"HgiBlitCmds_SharedPtr"}],"title":"CreateBlitCmds()","navigatorTitle":[{"kind":"identifier","text":"CreateBlitCmds"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/DestroyTextureView":{"navigatorTitle":[{"text":"DestroyTextureView","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyTextureView","kind":"symbol","title":"DestroyTextureView(_:)","role":"symbol","type":"topic","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/destroytextureview","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DestroyTextureView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"HgiTextureViewHandle","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiTextureView"},{"kind":"text","text":">"},{"kind":"text","text":")"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/IsBackendSupported":{"abstract":[],"navigatorTitle":[{"text":"IsBackendSupported","kind":"identifier"}],"kind":"symbol","type":"topic","title":"IsBackendSupported()","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/IsBackendSupported","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsBackendSupported","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/isbackendsupported"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"navigatorTitle":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"role":"symbol","title":"class UsdImagingGLEngineWrapper","type":"topic","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreateBuffer":{"navigatorTitle":[{"kind":"identifier","text":"CreateBuffer"}],"abstract":[],"fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateBuffer"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiBufferDesc","text":"HgiBufferDesc"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiBuffer","text":"HgiBufferHandle"}],"role":"symbol","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/createbuffer","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateBuffer","title":"CreateBuffer(_:)","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/TfErrorMarkWrapper":{"role":"symbol","abstract":[],"type":"topic","title":"struct TfErrorMarkWrapper","url":"\/documentation\/openusd\/overlay\/tferrormarkwrapper","navigatorTitle":[{"text":"TfErrorMarkWrapper","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TfErrorMarkWrapper","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/TfErrorMarkWrapper","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdAppUtilsFrameRecorderWrapper":{"url":"\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"title":"class UsdAppUtilsFrameRecorderWrapper","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArResolverWrapper","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","url":"\/documentation\/openusd\/overlay\/arresolverwrapper","title":"class ArResolverWrapper","abstract":[],"type":"topic","navigatorTitle":[{"text":"ArResolverWrapper","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreateResourceBindings":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CreateResourceBindings"}],"kind":"symbol","type":"topic","title":"CreateResourceBindings(_:)","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateResourceBindings","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateResourceBindings","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"HgiResourceBindingsDesc","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiResourceBindingsDesc"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiResourceBindings","text":"HgiResourceBindingsHandle"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/createresourcebindings"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"HgiWrapper","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HgiWrapper"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HgiWrapper"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateBlitCmds","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateBuffer","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateComputeCmds","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateComputePipeline","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateGraphicsCmds","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateGraphicsPipeline","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateResourceBindings","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateSampler","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateShaderFunction","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateShaderProgram","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateTexture","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateTextureView","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyBuffer","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyComputePipeline","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyGraphicsPipeline","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyResourceBindings","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroySampler","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyShaderFunction","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyShaderProgram","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyTexture","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyTextureView","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/EndFrame","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/GarbageCollect","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/GetAPIName","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/GetCapabilities","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/GetIndirectCommandEncoder","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/HgiWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/IsBackendSupported","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/StartFrame","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/SubmitCmds","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/VtValueWrappingHgiRawPtr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/get","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/get_shared","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/operator_bool"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreateNamedHgi","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreatePlatformDefaultHgi","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/IsSupported"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper"],"kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"title":"Namespace Overlay","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper"],"generated":true,"anchor":"Namespace-Overlay"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiWrapper","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title","value":"HioImageWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments","value":[{"text":"HioImageWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"HioImageWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1GarbageCollect\/title","value":"GarbageCollect","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1GarbageCollect\/fragments","value":[{"kind":"identifier","text":"GarbageCollect"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1GarbageCollect\/navigatorTitle","value":[{"kind":"identifier","text":"GarbageCollect"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1operator_bool\/title","value":"operator bool","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1operator_bool\/fragments","value":[{"text":"_Bool","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1operator_bool\/navigatorTitle","value":[{"kind":"identifier","text":"operator bool"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateGraphicsCmds\/title","value":"CreateGraphicsCmds","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateGraphicsCmds\/fragments","value":[{"kind":"identifier","text":"CreateGraphicsCmds"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateGraphicsCmds\/navigatorTitle","value":[{"kind":"identifier","text":"CreateGraphicsCmds"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1SubmitCmds\/title","value":"SubmitCmds","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1SubmitCmds\/fragments","value":[{"text":"SubmitCmds","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1SubmitCmds\/navigatorTitle","value":[{"text":"SubmitCmds","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1get_shared\/title","value":"get_shared","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1get_shared\/fragments","value":[{"text":"get_shared","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1get_shared\/navigatorTitle","value":[{"kind":"identifier","text":"get_shared"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyComputePipeline\/title","value":"DestroyComputePipeline","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyComputePipeline\/fragments","value":[{"text":"DestroyComputePipeline","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyComputePipeline\/navigatorTitle","value":[{"text":"DestroyComputePipeline","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1HgiWrapper\/title","value":"HgiWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1HgiWrapper\/fragments","value":[{"kind":"identifier","text":"HgiWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1HgiWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"HgiWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1get\/title","value":"get","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1get\/fragments","value":[{"text":"get","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1get\/navigatorTitle","value":[{"kind":"identifier","text":"get"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateComputeCmds\/title","value":"CreateComputeCmds","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateComputeCmds\/fragments","value":[{"text":"CreateComputeCmds","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateComputeCmds\/navigatorTitle","value":[{"kind":"identifier","text":"CreateComputeCmds"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1VtValueWrappingHgiRawPtr\/title","value":"VtValueWrappingHgiRawPtr","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1VtValueWrappingHgiRawPtr\/fragments","value":[{"text":"VtValueWrappingHgiRawPtr","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1VtValueWrappingHgiRawPtr\/navigatorTitle","value":[{"kind":"identifier","text":"VtValueWrappingHgiRawPtr"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyResourceBindings\/title","value":"DestroyResourceBindings","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyResourceBindings\/fragments","value":[{"kind":"identifier","text":"DestroyResourceBindings"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyResourceBindings\/navigatorTitle","value":[{"text":"DestroyResourceBindings","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateTextureView\/title","value":"CreateTextureView","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateTextureView\/fragments","value":[{"kind":"identifier","text":"CreateTextureView"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateTextureView\/navigatorTitle","value":[{"text":"CreateTextureView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateShaderFunction\/title","value":"CreateShaderFunction","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateShaderFunction\/fragments","value":[{"kind":"identifier","text":"CreateShaderFunction"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateShaderFunction\/navigatorTitle","value":[{"text":"CreateShaderFunction","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1GetCapabilities\/title","value":"GetCapabilities","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1GetCapabilities\/fragments","value":[{"text":"GetCapabilities","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1GetCapabilities\/navigatorTitle","value":[{"text":"GetCapabilities","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1StartFrame\/title","value":"StartFrame","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1StartFrame\/fragments","value":[{"text":"StartFrame","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1StartFrame\/navigatorTitle","value":[{"kind":"identifier","text":"StartFrame"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyGraphicsPipeline\/title","value":"DestroyGraphicsPipeline","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyGraphicsPipeline\/fragments","value":[{"text":"DestroyGraphicsPipeline","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyGraphicsPipeline\/navigatorTitle","value":[{"text":"DestroyGraphicsPipeline","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyBuffer\/title","value":"DestroyBuffer","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyBuffer\/fragments","value":[{"text":"DestroyBuffer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyBuffer\/navigatorTitle","value":[{"text":"DestroyBuffer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/title","value":"UsdPrimTypeInfoWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/fragments","value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateComputePipeline\/title","value":"CreateComputePipeline","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateComputePipeline\/fragments","value":[{"kind":"identifier","text":"CreateComputePipeline"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateComputePipeline\/navigatorTitle","value":[{"text":"CreateComputePipeline","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateGraphicsPipeline\/title","value":"CreateGraphicsPipeline","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateGraphicsPipeline\/fragments","value":[{"kind":"identifier","text":"CreateGraphicsPipeline"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateGraphicsPipeline\/navigatorTitle","value":[{"text":"CreateGraphicsPipeline","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyShaderFunction\/title","value":"DestroyShaderFunction","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyShaderFunction\/fragments","value":[{"text":"DestroyShaderFunction","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyShaderFunction\/navigatorTitle","value":[{"kind":"identifier","text":"DestroyShaderFunction"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreatePlatformDefaultHgi\/title","value":"CreatePlatformDefaultHgi","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreatePlatformDefaultHgi\/fragments","value":[{"text":"CreatePlatformDefaultHgi","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreatePlatformDefaultHgi\/navigatorTitle","value":[{"kind":"identifier","text":"CreatePlatformDefaultHgi"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroySampler\/title","value":"DestroySampler","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroySampler\/fragments","value":[{"text":"DestroySampler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroySampler\/navigatorTitle","value":[{"kind":"identifier","text":"DestroySampler"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/title","value":"HgiWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/fragments","value":[{"kind":"identifier","text":"HgiWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"HgiWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateShaderProgram\/title","value":"CreateShaderProgram","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateShaderProgram\/fragments","value":[{"text":"CreateShaderProgram","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateShaderProgram\/navigatorTitle","value":[{"text":"CreateShaderProgram","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1EndFrame\/title","value":"EndFrame","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1EndFrame\/fragments","value":[{"kind":"identifier","text":"EndFrame"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1EndFrame\/navigatorTitle","value":[{"kind":"identifier","text":"EndFrame"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1GetIndirectCommandEncoder\/title","value":"GetIndirectCommandEncoder","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1GetIndirectCommandEncoder\/fragments","value":[{"text":"GetIndirectCommandEncoder","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1GetIndirectCommandEncoder\/navigatorTitle","value":[{"kind":"identifier","text":"GetIndirectCommandEncoder"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyShaderProgram\/title","value":"DestroyShaderProgram","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyShaderProgram\/fragments","value":[{"kind":"identifier","text":"DestroyShaderProgram"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyShaderProgram\/navigatorTitle","value":[{"kind":"identifier","text":"DestroyShaderProgram"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyTexture\/title","value":"DestroyTexture","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyTexture\/fragments","value":[{"kind":"identifier","text":"DestroyTexture"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyTexture\/navigatorTitle","value":[{"text":"DestroyTexture","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateSampler\/title","value":"CreateSampler","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateSampler\/fragments","value":[{"text":"CreateSampler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateSampler\/navigatorTitle","value":[{"text":"CreateSampler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateNamedHgi\/title","value":"CreateNamedHgi","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateNamedHgi\/fragments","value":[{"text":"CreateNamedHgi","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateNamedHgi\/navigatorTitle","value":[{"kind":"identifier","text":"CreateNamedHgi"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1IsSupported\/title","value":"IsSupported","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1IsSupported\/fragments","value":[{"text":"IsSupported","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1IsSupported\/navigatorTitle","value":[{"text":"IsSupported","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"kind":"identifier","text":"Overlay"}],"op":"add"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateTexture\/title","value":"CreateTexture","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateTexture\/fragments","value":[{"text":"CreateTexture","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateTexture\/navigatorTitle","value":[{"kind":"identifier","text":"CreateTexture"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1GetAPIName\/title","value":"GetAPIName","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1GetAPIName\/fragments","value":[{"kind":"identifier","text":"GetAPIName"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1GetAPIName\/navigatorTitle","value":[{"text":"GetAPIName","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/title","value":"HgiMetalWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/fragments","value":[{"text":"HgiMetalWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"HgiMetalWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateBlitCmds\/title","value":"CreateBlitCmds","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateBlitCmds\/fragments","value":[{"kind":"identifier","text":"CreateBlitCmds"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateBlitCmds\/navigatorTitle","value":[{"kind":"identifier","text":"CreateBlitCmds"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyTextureView\/title","value":"DestroyTextureView","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyTextureView\/fragments","value":[{"text":"DestroyTextureView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyTextureView\/navigatorTitle","value":[{"text":"DestroyTextureView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1IsBackendSupported\/title","value":"IsBackendSupported","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1IsBackendSupported\/fragments","value":[{"kind":"identifier","text":"IsBackendSupported"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1IsBackendSupported\/navigatorTitle","value":[{"kind":"identifier","text":"IsBackendSupported"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title","value":"UsdImagingGLEngineWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateBuffer\/title","value":"CreateBuffer","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateBuffer\/fragments","value":[{"text":"CreateBuffer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateBuffer\/navigatorTitle","value":[{"kind":"identifier","text":"CreateBuffer"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/title","value":"UsdAppUtilsFrameRecorderWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/fragments","value":[{"text":"UsdAppUtilsFrameRecorderWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"UsdAppUtilsFrameRecorderWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/title","value":"ArResolverWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/fragments","value":[{"kind":"identifier","text":"ArResolverWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"ArResolverWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateResourceBindings\/title","value":"CreateResourceBindings","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateResourceBindings\/fragments","value":[{"text":"CreateResourceBindings","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreateResourceBindings\/navigatorTitle","value":[{"text":"CreateResourceBindings","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}